/* ========================================================
   Theme data for all 26 subjects.
   Each theme's signature hue is applied to its section via --accent.
======================================================== */

const THEMES = [
  {
    id: 'cs', num: '01', accent: 'var(--cs)', nav: 'oklch(0.75 0.17 200)',
    title: 'Data Cathedral', code: 'CS-01',
    chinese: '数据大教堂',
    tagline: 'Computer Science & Coding — a sacred geometry of logic, where towers of code rise from an infinite grid of memory.',
    palette: [
      {hex:'oklch(0.75 0.17 200)', name:'SIGNAL'},
      {hex:'oklch(0.55 0.16 200)', name:'CORE'},
      {hex:'oklch(0.35 0.10 210)', name:'DEPTH'},
      {hex:'oklch(0.92 0.08 190)', name:'FLASH'},
      {hex:'oklch(0.85 0.14 85)',  name:'QUERY'},
    ],
    mascot: 'Bit — a levitating cubic sprite that rearranges its pixels when you solve a problem.',
    props: ['TERMINAL','KEY','PACKET'],
    typeSample: 'function build() { return future; }',
    typeDescTitle: 'hello, world();',
  },
  {
    id: 'bio', num: '02', accent: 'var(--bio)', nav: 'oklch(0.75 0.17 155)',
    title: 'Helix Garden', code: 'BIO-02',
    chinese: '螺旋花园',
    tagline: 'Biotechnology & Genetics — a greenhouse of living code. DNA spirals bloom like flowers under ultraviolet light.',
    palette: [
      {hex:'oklch(0.75 0.17 155)', name:'LIFE'},
      {hex:'oklch(0.55 0.16 155)', name:'MOSS'},
      {hex:'oklch(0.35 0.10 160)', name:'SHADOW'},
      {hex:'oklch(0.92 0.08 150)', name:'BLOOM'},
      {hex:'oklch(0.85 0.14 85)',  name:'MUTATE'},
    ],
    mascot: 'Sprout — a translucent tadpole-shape with a glowing helix core, pulses when a sequence aligns.',
    props: ['HELIX','FLASK','CELL'],
    typeSample: 'sequence AAGT-CTGA-helix',
    typeDescTitle: 'life, encoded.',
  },
  {
    id: 'space', num: '03', accent: 'var(--space)', nav: 'oklch(0.72 0.17 295)',
    title: 'Starfield Port', code: 'SPC-03',
    chinese: '星港',
    tagline: 'Rocket & Space Technology — a launch gantry perched on the edge of night. Trajectories are stitched from constellations.',
    palette: [
      {hex:'oklch(0.72 0.17 295)', name:'ORBIT'},
      {hex:'oklch(0.52 0.16 295)', name:'VOID'},
      {hex:'oklch(0.35 0.10 290)', name:'ECLIPSE'},
      {hex:'oklch(0.92 0.08 295)', name:'IGNITION'},
      {hex:'oklch(0.85 0.14 85)',  name:'APOGEE'},
    ],
    mascot: 'Pilot — a chevron-shaped drone that trails a comet tail when accelerating.',
    props: ['ROCKET','SATELLITE','PLANET'],
    typeSample: 'Δv = 9.4 km/s',
    typeDescTitle: 'to the apogee.',
  },
  {
    id: 'mech', num: '04', accent: 'var(--mech)', nav: 'oklch(0.75 0.17 55)',
    title: 'Gear Foundry', code: 'MEC-04',
    chinese: '齿轮铸造厂',
    tagline: 'Mechanical Engineering — a workshop of torque and tolerance. Gears breathe steam, blueprints unroll from the ceiling.',
    palette: [
      {hex:'oklch(0.75 0.17 55)',  name:'BRASS'},
      {hex:'oklch(0.55 0.16 50)',  name:'FORGE'},
      {hex:'oklch(0.35 0.10 60)',  name:'IRON'},
      {hex:'oklch(0.92 0.08 60)',  name:'EMBER'},
      {hex:'oklch(0.85 0.14 85)',  name:'SPARK'},
    ],
    mascot: 'Cog — a small winged gear that hovers and whirrs, shedding sparks when torque is right.',
    props: ['GEAR','WRENCH','PISTON'],
    typeSample: 'torque = F · r',
    typeDescTitle: 'build the machine.',
  },
  {
    id: 'ai', num: '05', accent: 'var(--ai)', nav: 'oklch(0.72 0.17 335)',
    title: 'Neural Aurora', code: 'AI-05',
    chinese: '神经极光',
    tagline: 'Artificial Intelligence — a sky of synapses. Weights ripple like northern lights across a lattice of thought.',
    palette: [
      {hex:'oklch(0.72 0.17 335)', name:'SYNAPSE'},
      {hex:'oklch(0.52 0.16 335)', name:'CORTEX'},
      {hex:'oklch(0.35 0.10 330)', name:'DEEP'},
      {hex:'oklch(0.92 0.08 335)', name:'SPARK'},
      {hex:'oklch(0.85 0.14 85)',  name:'INSIGHT'},
    ],
    mascot: 'Nova — a soft polygonal orb with shifting internal nodes, blooms brighter as it learns.',
    props: ['NEURON','CHIP','GRAPH'],
    typeSample: 'loss → 0.0042',
    typeDescTitle: 'a mind, unfolding.',
  },
  {
    id: 'math', num: '06', accent: 'var(--math)', nav: 'oklch(0.72 0.17 245)',
    title: 'Geometry Void', code: 'MTH-06',
    chinese: '几何之境',
    tagline: 'Mathematics — an empty theatre where axes unfold into theorems. Proofs assemble themselves mid-air.',
    palette: [
      {hex:'oklch(0.72 0.17 245)', name:'AXIS'},
      {hex:'oklch(0.52 0.16 245)', name:'PROOF'},
      {hex:'oklch(0.35 0.10 245)', name:'SHADOW'},
      {hex:'oklch(0.92 0.08 240)', name:'SOLUTION'},
      {hex:'oklch(0.85 0.14 85)',  name:'QED'},
    ],
    mascot: 'Pi — a rotating tetrahedron whose faces flash equations when asked a question.',
    props: ['COMPASS','POLYHEDRON','FORMULA'],
    typeSample: '∫ e^(-x²) dx = √π',
    typeDescTitle: 'the proof is elegant.',
  },
  {
    id: 'med', num: '07', accent: 'var(--med)', nav: 'oklch(0.75 0.16 15)',
    title: 'Vital Chamber', code: 'MED-07',
    chinese: '生命之室',
    tagline: 'Medical Science — a soft-lit observation ward. Vitals breathe in slow rhythm; organs glow from within.',
    palette: [
      {hex:'oklch(0.75 0.16 15)',  name:'PULSE'},
      {hex:'oklch(0.55 0.15 15)',  name:'VEIN'},
      {hex:'oklch(0.35 0.10 15)',  name:'TISSUE'},
      {hex:'oklch(0.92 0.08 15)',  name:'VITAL'},
      {hex:'oklch(0.85 0.14 85)',  name:'CARE'},
    ],
    mascot: 'Cura — a pill-shaped companion with a soft heartbeat light, floats beside the patient.',
    props: ['HEART','SYRINGE','SCAN'],
    typeSample: 'BPM 72 · O₂ 98%',
    typeDescTitle: 'healing, measured.',
  },
  {
    id: 'chem', num: '08', accent: 'var(--chem)', nav: 'oklch(0.82 0.17 125)',
    title: 'Reaction Atrium', code: 'CHM-08',
    chinese: '反应穹厅',
    tagline: 'Chemistry — a glass atrium of bubbling catalysts. Molecules tumble in zero-G like constellations of atoms.',
    palette: [
      {hex:'oklch(0.82 0.17 125)', name:'CATALYST'},
      {hex:'oklch(0.62 0.16 125)', name:'BOND'},
      {hex:'oklch(0.35 0.10 130)', name:'DEEP'},
      {hex:'oklch(0.95 0.08 120)', name:'REACTION'},
      {hex:'oklch(0.85 0.14 85)',  name:'YIELD'},
    ],
    mascot: 'Ion — a small atom-cluster creature, gains and loses rings with each bond it makes.',
    props: ['MOLECULE','BEAKER','CRYSTAL'],
    typeSample: 'H₂O + NaCl → brine',
    typeDescTitle: 'elements recombine.',
  },
  {
    id: 'phys', num: '09', accent: 'var(--phys)', nav: 'oklch(0.78 0.13 215)',
    title: 'Force Observatory', code: 'PHY-09',
    chinese: '力之观测台',
    tagline: 'Physics — a cliff-side deck of pendulums and light cones. Gravity is visible as glowing field lines on glass.',
    palette: [
      {hex:'oklch(0.78 0.13 215)', name:'FIELD'},
      {hex:'oklch(0.55 0.13 215)', name:'WAVE'},
      {hex:'oklch(0.35 0.10 215)', name:'MASS'},
      {hex:'oklch(0.92 0.08 215)', name:'PHOTON'},
      {hex:'oklch(0.85 0.14 85)',  name:'CONSTANT'},
    ],
    mascot: 'Echo — a tuning-fork shape with a halo of waveforms; pings and ripples through the scene.',
    props: ['PENDULUM','PRISM','MAGNET'],
    typeSample: 'F = m·a · c = 3×10⁸',
    typeDescTitle: 'laws, everywhere.',
  },
  {
    id: 'env', num: '10', accent: 'var(--env)', nav: 'oklch(0.72 0.15 140)',
    title: 'Biosphere Dome', code: 'ENV-10',
    chinese: '生态穹顶',
    tagline: 'Environmental Science — a terrarium under stars. Rivers, forests and clouds layered like a cross-sectioned snow globe.',
    palette: [
      {hex:'oklch(0.72 0.15 140)', name:'CANOPY'},
      {hex:'oklch(0.52 0.13 140)', name:'LOAM'},
      {hex:'oklch(0.35 0.10 140)', name:'ABYSS'},
      {hex:'oklch(0.92 0.08 140)', name:'DAWN'},
      {hex:'oklch(0.85 0.14 85)',  name:'SUN'},
    ],
    mascot: 'Fern — a leaf-shaped drone that trails pollen particles, unfolds when air is clean.',
    props: ['TREE','DROPLET','LEAF'],
    typeSample: 'CO₂ 412 ppm ↓',
    typeDescTitle: 'one world, one lab.',
  },
  {
    id: 'robo', num: '11', accent: 'var(--robo)', nav: 'oklch(0.82 0.15 95)',
    title: 'Assembly Hangar', code: 'RBT-11',
    chinese: '装配机库',
    tagline: 'Robotics — a luminous hangar of arms and actuators. Machines rehearse motion paths on hex-grid floors.',
    palette: [
      {hex:'oklch(0.82 0.15 95)',  name:'ACTUATOR'},
      {hex:'oklch(0.55 0.14 95)',  name:'CHASSIS'},
      {hex:'oklch(0.35 0.10 95)',  name:'BASE'},
      {hex:'oklch(0.95 0.08 95)',  name:'SENSOR'},
      {hex:'oklch(0.85 0.14 85)',  name:'BEACON'},
    ],
    mascot: 'Widget — a tiny tracked bot with one expressive camera eye, tilts in curiosity.',
    props: ['ARM','SENSOR','TRACK'],
    typeSample: 'servo.setAngle(135°)',
    typeDescTitle: 'motion, programmed.',
  },
  {
    id: 'elec', num: '12', accent: 'var(--elec)', nav: 'oklch(0.72 0.17 275)',
    title: 'Circuit Grid', code: 'ELC-12',
    chinese: '电路之网',
    tagline: 'Electrical Engineering — a city of circuits on a black silicon plain. Currents run like midnight subway lines.',
    palette: [
      {hex:'oklch(0.72 0.17 275)', name:'CURRENT'},
      {hex:'oklch(0.52 0.16 275)', name:'TRACE'},
      {hex:'oklch(0.35 0.10 275)', name:'BOARD'},
      {hex:'oklch(0.92 0.08 275)', name:'PULSE'},
      {hex:'oklch(0.85 0.14 85)',  name:'RELAY'},
    ],
    mascot: 'Volt — a lightning-shard with soft rounded edges, hums and sparks at junctions.',
    props: ['RESISTOR','BATTERY','NODE'],
    typeSample: 'V = I · R · P = V·I',
    typeDescTitle: 'current flows here.',
  },

  {
    id: 'astro', num: '13', accent: 'var(--astro)', nav: 'oklch(0.78 0.13 260)',
    title: 'Deep-Sky Observatory', code: 'AST-13',
    chinese: '深空观测台',
    tagline: 'Astronomy & Astrophysics — a silent observatory above the cloud line. Galaxies drift like jellyfish; each pixel is a star system.',
    palette: [
      {hex:'oklch(0.78 0.13 260)', name:'GALAXY'},
      {hex:'oklch(0.52 0.14 260)', name:'NEBULA'},
      {hex:'oklch(0.30 0.08 260)', name:'VACUUM'},
      {hex:'oklch(0.92 0.08 260)', name:'PHOTON'},
      {hex:'oklch(0.85 0.14 85)',  name:'SUPERNOVA'},
    ],
    mascot: 'Nova — a small floating telescope drone with a ringed lens that blinks starlight on discovery.',
    props: ['TELESCOPE','GALAXY','COMET'],
    typeSample: 'z = 1.42 · M☉ = 4×10³⁰',
    typeDescTitle: 'through the lens.',
  },
  {
    id: 'geo', num: '14', accent: 'var(--geo)', nav: 'oklch(0.72 0.15 40)',
    title: 'Strata Vault', code: 'GEO-14',
    chinese: '地层秘境',
    tagline: 'Geology & Earth Science — a cross-section of the planet, layer by layer. Tectonic plates shift beneath a moon-lit canyon.',
    palette: [
      {hex:'oklch(0.72 0.15 40)',  name:'CLAY'},
      {hex:'oklch(0.55 0.14 40)',  name:'RUST'},
      {hex:'oklch(0.32 0.10 40)',  name:'BASALT'},
      {hex:'oklch(0.90 0.08 50)',  name:'CHALK'},
      {hex:'oklch(0.85 0.14 85)',  name:'MAGMA'},
    ],
    mascot: 'Stone — a round pebble with glowing vein-cracks that light up when a rock is identified.',
    props: ['CRYSTAL','COMPASS','CORE'],
    typeSample: 'depth 4.2km · age 1.8Gyr',
    typeDescTitle: 'dig deeper.',
  },
  {
    id: 'ocean', num: '15', accent: 'var(--ocean)', nav: 'oklch(0.72 0.15 230)',
    title: 'Abyssal Reef', code: 'OCN-15',
    chinese: '深海秘境',
    tagline: 'Oceanography & Marine Biology — bioluminescent depths where currents sing and creatures glow with their own constellations.',
    palette: [
      {hex:'oklch(0.72 0.15 230)', name:'TIDE'},
      {hex:'oklch(0.45 0.13 230)', name:'TRENCH'},
      {hex:'oklch(0.22 0.08 250)', name:'DEEP'},
      {hex:'oklch(0.92 0.08 220)', name:'FOAM'},
      {hex:'oklch(0.85 0.14 85)',  name:'LURE'},
    ],
    mascot: 'Finn — a jellyfish-drone with a translucent bell that pulses light when it finds rare species.',
    props: ['ANGLER','KELP','CORAL'],
    typeSample: 'depth -3,280m · salinity 35‰',
    typeDescTitle: 'listen to the deep.',
  },
  {
    id: 'meteo', num: '16', accent: 'var(--meteo)', nav: 'oklch(0.82 0.10 245)',
    title: 'Sky Tower', code: 'MET-16',
    chinese: '风云之塔',
    tagline: 'Meteorology & Climate — a layered atmosphere rendered as vertical strata. Weather fronts sweep past an instrumented balloon.',
    palette: [
      {hex:'oklch(0.82 0.10 245)', name:'CIRRUS'},
      {hex:'oklch(0.62 0.13 245)', name:'FRONT'},
      {hex:'oklch(0.38 0.10 245)', name:'STORM'},
      {hex:'oklch(0.95 0.05 245)', name:'MIST'},
      {hex:'oklch(0.85 0.14 85)',  name:'SUNLIGHT'},
    ],
    mascot: 'Cloud — a small rounded nimbus with animated lightning eyes, drizzles gold sparkles when calm.',
    props: ['BALLOON','CLOUD','VANE'],
    typeSample: '1013 hPa · RH 74% · 18°C',
    typeDescTitle: 'reading the sky.',
  },
  {
    id: 'paleo', num: '17', accent: 'var(--paleo)', nav: 'oklch(0.72 0.13 70)',
    title: 'Fossil Archive', code: 'PAL-17',
    chinese: '化石档案',
    tagline: 'Paleontology & Evolution — stone rooms where extinct creatures line up in geological time. Footprints glow gold under UV.',
    palette: [
      {hex:'oklch(0.72 0.13 70)',  name:'AMBER'},
      {hex:'oklch(0.55 0.12 70)',  name:'SANDSTONE'},
      {hex:'oklch(0.32 0.08 70)',  name:'SHALE'},
      {hex:'oklch(0.92 0.06 75)',  name:'BONE'},
      {hex:'oklch(0.85 0.14 85)',  name:'DISCOVERY'},
    ],
    mascot: 'Rex — a tiny friendly theropod silhouette with glowing eye-spot, tilts head at new fossils.',
    props: ['SKULL','AMMONITE','BRUSH'],
    typeSample: 'era Mesozoic · Cretaceous',
    typeDescTitle: 'the deep past speaks.',
  },
  {
    id: 'quant', num: '18', accent: 'var(--quant)', nav: 'oklch(0.72 0.17 310)',
    title: 'Probability Chamber', code: 'QNT-18',
    chinese: '概率之室',
    tagline: 'Quantum Physics — a room where particles exist everywhere at once. Wavefunctions shimmer like heat haze on glass.',
    palette: [
      {hex:'oklch(0.72 0.17 310)', name:'SUPERPOS'},
      {hex:'oklch(0.52 0.16 310)', name:'ENTANGLE'},
      {hex:'oklch(0.30 0.10 310)', name:'COLLAPSE'},
      {hex:'oklch(0.92 0.08 310)', name:'QUANTA'},
      {hex:'oklch(0.85 0.14 85)',  name:'OBSERVE'},
    ],
    mascot: 'Qubit — a small shimmering orb that flickers between two positions depending on if you look.',
    props: ['WAVE','SLIT','QUBIT'],
    typeSample: '|ψ⟩ = α|0⟩ + β|1⟩',
    typeDescTitle: 'both, until observed.',
  },
  {
    id: 'nuke', num: '19', accent: 'var(--nuke)', nav: 'oklch(0.82 0.17 135)',
    title: 'Reactor Core', code: 'NCL-19',
    chinese: '反应堆核心',
    tagline: 'Nuclear Science — a containment ring glowing cherenkov-blue beneath a lattice ceiling. Fission visible as slow-moving light rods.',
    palette: [
      {hex:'oklch(0.82 0.17 135)', name:'CHERENKOV'},
      {hex:'oklch(0.62 0.16 135)', name:'ISOTOPE'},
      {hex:'oklch(0.32 0.10 135)', name:'SHIELD'},
      {hex:'oklch(0.95 0.08 130)', name:'FUSION'},
      {hex:'oklch(0.85 0.14 85)',  name:'DECAY'},
    ],
    mascot: 'Halo — a ringed ion with an inner glow that pulses every half-life.',
    props: ['ATOM','ROD','SHIELD'],
    typeSample: 't½ = 5,730yr · ²³⁵U',
    typeDescTitle: 'energy, contained.',
  },
  {
    id: 'neuro', num: '20', accent: 'var(--neuro)', nav: 'oklch(0.75 0.17 25)',
    title: 'Cortex Map', code: 'NRO-20',
    chinese: '神经地图',
    tagline: 'Neuroscience — a cartography of thought. Neurons fire like city lights across a hemisphere at dusk.',
    palette: [
      {hex:'oklch(0.75 0.17 25)',  name:'SYNAPTIC'},
      {hex:'oklch(0.55 0.15 25)',  name:'DENDRITE'},
      {hex:'oklch(0.32 0.10 25)',  name:'AXON'},
      {hex:'oklch(0.92 0.08 25)',  name:'FIRING'},
      {hex:'oklch(0.85 0.14 85)',  name:'MEMORY'},
    ],
    mascot: 'Spark — a small branching dendrite creature that lights up in waves when ideas connect.',
    props: ['BRAIN','SYNAPSE','EEG'],
    typeSample: 'alpha 8–12Hz · beta 13–30Hz',
    typeDescTitle: 'thought, mapped.',
  },
  {
    id: 'mat', num: '21', accent: 'var(--mat)', nav: 'oklch(0.78 0.12 190)',
    title: 'Lattice Forge', code: 'MAT-21',
    chinese: '晶格锻造坊',
    tagline: 'Materials Science — a studio of crystals and alloys. Atoms arrange themselves on a holographic lattice that grows in real time.',
    palette: [
      {hex:'oklch(0.78 0.12 190)', name:'CRYSTAL'},
      {hex:'oklch(0.55 0.12 190)', name:'ALLOY'},
      {hex:'oklch(0.32 0.08 190)', name:'BOND'},
      {hex:'oklch(0.92 0.06 190)', name:'POLISH'},
      {hex:'oklch(0.85 0.14 85)',  name:'YIELD'},
    ],
    mascot: 'Prism — a small crystalline polyhedron whose facets refract the scene around it.',
    props: ['LATTICE','SHEET','BOND'],
    typeSample: 'Fe-C · 1200°C · BCC',
    typeDescTitle: 'matter, designed.',
  },
  {
    id: 'micro', num: '22', accent: 'var(--micro)', nav: 'oklch(0.82 0.17 110)',
    title: 'Petri World', code: 'MIC-22',
    chinese: '微观之境',
    tagline: 'Microbiology & Virology — a microscope-view world where bacteria colonies form continents and viruses float like star-ships.',
    palette: [
      {hex:'oklch(0.82 0.17 110)', name:'CULTURE'},
      {hex:'oklch(0.62 0.16 110)', name:'AGAR'},
      {hex:'oklch(0.32 0.10 120)', name:'SUBSTRATE'},
      {hex:'oklch(0.95 0.08 110)', name:'COLONY'},
      {hex:'oklch(0.85 0.14 85)',  name:'SAMPLE'},
    ],
    mascot: 'Bloom — a small round microbe with cilia that ripple outward when it splits.',
    props: ['MICROSCOPE','PETRI','VIRUS'],
    typeSample: '40× · 100× · 1000×',
    typeDescTitle: 'the invisible world.',
  },
  {
    id: 'zoo', num: '23', accent: 'var(--zoo)', nav: 'oklch(0.75 0.15 75)',
    title: 'Wildlife Reserve', code: 'ZOO-23',
    chinese: '生灵保护区',
    tagline: 'Zoology & Ecology — a savanna at golden hour. Animal silhouettes move across a stylized plain under acacia trees.',
    palette: [
      {hex:'oklch(0.75 0.15 75)',  name:'SAVANNA'},
      {hex:'oklch(0.55 0.13 75)',  name:'PELT'},
      {hex:'oklch(0.32 0.08 75)',  name:'TRACK'},
      {hex:'oklch(0.92 0.08 80)',  name:'HORIZON'},
      {hex:'oklch(0.85 0.14 85)',  name:'SUN'},
    ],
    mascot: 'Paw — a small fox silhouette with glowing ears that twitch when wildlife is near.',
    props: ['TRACK','FEATHER','SCOPE'],
    typeSample: 'species 487 · biome 12',
    typeDescTitle: 'observe, don\'t disturb.',
  },
  {
    id: 'bot', num: '24', accent: 'var(--bot)', nav: 'oklch(0.78 0.15 120)',
    title: 'Flora Atrium', code: 'BOT-24',
    chinese: '植物之园',
    tagline: 'Botany — a glass conservatory of every leaf shape and growth pattern. Photosynthesis rendered as rising green particles.',
    palette: [
      {hex:'oklch(0.78 0.15 120)', name:'CHLOROPHYLL'},
      {hex:'oklch(0.55 0.13 120)', name:'STEM'},
      {hex:'oklch(0.32 0.08 120)', name:'ROOT'},
      {hex:'oklch(0.92 0.08 120)', name:'PETAL'},
      {hex:'oklch(0.85 0.14 85)',  name:'POLLEN'},
    ],
    mascot: 'Petal — a small sprout with two rounded leaves, tilts toward the sun.',
    props: ['LEAF','SEED','BLOOM'],
    typeSample: 'C₆H₁₂O₆ · chlorophyll a',
    typeDescTitle: 'grow quietly.',
  },
  {
    id: 'arch', num: '25', accent: 'var(--arch)', nav: 'oklch(0.75 0.13 55)',
    title: 'Lost City Dig', code: 'ARC-25',
    chinese: '失落之城',
    tagline: 'Archaeology — a moonlit excavation. Grid strings criss-cross over a half-buried courtyard; pottery shards wait to be pieced together.',
    palette: [
      {hex:'oklch(0.75 0.13 55)',  name:'SANDSTONE'},
      {hex:'oklch(0.55 0.12 55)',  name:'DUSK'},
      {hex:'oklch(0.32 0.08 55)',  name:'EARTH'},
      {hex:'oklch(0.92 0.06 60)',  name:'IVORY'},
      {hex:'oklch(0.85 0.14 85)',  name:'ARTIFACT'},
    ],
    mascot: 'Shard — a small triangular pottery fragment with a glyph that glows when it fits a pattern.',
    props: ['AMPHORA','GLYPH','BRUSH'],
    typeSample: 'era -2400 BCE · grid E4',
    typeDescTitle: 'uncover gently.',
  },
  {
    id: 'agri', num: '26', accent: 'var(--agri)', nav: 'oklch(0.82 0.14 100)',
    title: 'Smart Fields', code: 'AGR-26',
    chinese: '智慧农场',
    tagline: 'Agricultural Science — an iso-view of a networked farm. Rows of crops pulse with moisture data; drones patrol the rows.',
    palette: [
      {hex:'oklch(0.82 0.14 100)', name:'WHEAT'},
      {hex:'oklch(0.62 0.13 100)', name:'LOAM'},
      {hex:'oklch(0.32 0.08 100)', name:'FURROW'},
      {hex:'oklch(0.92 0.08 100)', name:'DEW'},
      {hex:'oklch(0.85 0.14 85)',  name:'HARVEST'},
    ],
    mascot: 'Husk — a small wheat-bundle shape with two glowing grains for eyes.',
    props: ['WHEAT','DRONE','SENSOR'],
    typeSample: 'soil pH 6.5 · H₂O 42%',
    typeDescTitle: 'feed the future.',
  },
];

window.THEMES = THEMES;
