# Generated by Django 6.0.3 on 2026-03-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationtask",
            name="knodes_created",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generationtask",
            name="milestones_created",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
