# Generated by Django 6.0.3 on 2026-03-12 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField()),
                ("cover_image", models.URLField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai", "AI & Machine Learning"),
                            ("biotech", "Biotechnology"),
                            ("aerospace", "Aerospace"),
                            ("music", "Music & Audio"),
                            ("climate", "Climate & Environment"),
                            ("robotics", "Robotics"),
                            ("chemistry", "Chemistry"),
                            ("math", "Mathematics"),
                            ("cs", "Computer Science"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("min_age", models.PositiveSmallIntegerField(default=6)),
                ("max_age", models.PositiveSmallIntegerField(default=18)),
                ("estimated_hours", models.PositiveSmallIntegerField(default=10)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("acceptance_criteria", models.TextField(blank=True)),
                ("xp_reward", models.PositiveIntegerField(default=100)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "milestones",
                "ordering": ["project", "order"],
                "unique_together": {("project", "order")},
            },
        ),
        migrations.CreateModel(
            name="KnowledgeNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("difficulty_level", models.PositiveSmallIntegerField(default=1)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Text / Reading"),
                            ("interactive", "Interactive Exercise"),
                            ("code", "Coding Task"),
                            ("experiment", "Experiment / Hands-on"),
                            ("quiz", "Quiz"),
                            ("video", "Video"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "acceptance_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("code_submit", "Code Submission"),
                            ("essay", "Essay / Written Response"),
                            ("demo", "Demo / Presentation"),
                            ("peer_review", "Peer Review"),
                            ("auto", "Auto-verified (read-through)"),
                        ],
                        default="quiz",
                        max_length=20,
                    ),
                ),
                ("estimated_minutes", models.PositiveSmallIntegerField(default=15)),
                ("xp_reward", models.PositiveIntegerField(default=20)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True, related_name="unlocks", to="projects.knowledgenode"
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knodes",
                        to="projects.milestone",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knodes",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_nodes",
                "ordering": ["milestone", "order"],
            },
        ),
    ]
