# Generated by Django 6.0.3 on 2026-03-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_add_is_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="forked_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="projects.project",
            ),
        ),
    ]
