import {chromium,expect} from '@playwright/test';
import fs from 'node:fs/promises';
const dir=new URL('./',import.meta.url).pathname,origin='http://localhost:4000',hub=origin+'/mission/space';
const seenKey='systemedu:mission:space:intro:v1';
const browser=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const report={passed:false,checks:[],errors:[]};
const watch=p=>p.on('pageerror',e=>report.errors.push(e.message));
const film=p=>p.getByRole('dialog',{name:'前导任务短片'});
const playing=async p=>{await expect.poll(()=>p.locator('video').evaluate(v=>!v.paused&&v.currentTime>0),{timeout:20000}).toBe(true)};
try {
 const c=await browser.newContext({viewport:{width:1440,height:1050}}),p=await c.newPage();watch(p);let writes=0;
 p.on('request',r=>{if(r.url().includes('/api/learning/')&&!['GET','OPTIONS'].includes(r.method()))writes++});
 await p.goto(origin+'/library?view=lines');
 const card=p.locator('[data-line-card="space-exploration"]');await expect(card).toHaveAttribute('href','/mission/space');
 await card.click();await expect(p).toHaveURL(hub);await expect(film(p)).toBeVisible();await playing(p);
 expect(await p.evaluate(key=>localStorage.getItem(key),seenKey)).toBe('1');
 await p.screenshot({path:dir+'first-entry-desktop.png'});
 await p.getByRole('button',{name:'跳过序章，进入任务中心'}).click();await expect(film(p)).toHaveCount(0);
 await expect(p.locator('[data-journey-start]')).toBeFocused();
 await p.reload();await expect(p.locator('[data-space-journey]')).toBeVisible();await expect(p.locator('video')).toHaveCount(0);
 await p.getByRole('button',{name:'火星探索序章 · 29 秒'}).click();await expect(film(p)).toBeVisible();await playing(p);
 // Replay completion returns to the hub, not a new task or a completion write.
 await p.locator('video').evaluate(v=>v.currentTime=v.duration-.25);await expect(film(p)).toHaveCount(0,{timeout:10000});
 await p.locator('[data-journey-start]').click();await expect(p.locator('iframe')).toBeVisible();await p.locator('[data-journey-return] a').click();
 await expect(p).toHaveURL(/\/mission\/space\?station=first-contact#journey-map$/);await expect(p.locator('video')).toHaveCount(0);
 await p.getByRole('link',{name:'所有项目线',exact:true}).click();await expect(p).toHaveURL(origin+'/library?view=lines');
 await expect(p.locator('[data-line-card="biomedicine"]')).toHaveAttribute('href','/library?view=lines&line=biomedicine');
 await p.locator('[data-line-card="biomedicine"]').click();await expect(p.locator('[data-line-detail="biomedicine"]')).toBeVisible();
 await p.goto(origin+'/library');await expect(p.locator('[data-project-card="spot-a-world"] a[href="/mission/space"]')).toHaveCount(1);
 expect(writes).toBe(0);
 report.checks.push('Line card and project association enter mission directly; real audible autoplay succeeds when allowed; skip, reload, replay, real ended event, course-return and all-lines return work without looping; other lines retain their detail page; no learning record writes');
 await c.close();
 const legacy=await browser.newContext(),q=await legacy.newPage();watch(q);let listRequests=0;
 q.on('request',r=>{if(/\/api\/library\/projects$/.test(r.url()))listRequests++});
 await q.goto(origin+'/library?view=lines&line=space-exploration');await expect(q).toHaveURL(hub);await expect(film(q)).toBeVisible();await playing(q);
 expect(listRequests).toBe(0);
 await q.locator('video').evaluate(v=>v.currentTime=v.duration-.25);await expect(film(q)).toHaveCount(0,{timeout:10000});await expect(q.locator('[data-journey-start]')).toBeFocused();
 await legacy.close();report.checks.push('Old bookmarked line URL redirects via replace without fetching the old catalogue; first automatic film ends into a focused first-task button');
 const blocked=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),b=await blocked.newPage();watch(b);
 await blocked.addInitScript(()=>{const original=HTMLMediaElement.prototype.play;let activated=false;window.addEventListener('click',event=>{if(event.isTrusted)activated=true},{capture:true});HTMLMediaElement.prototype.play=function(){if(!activated)return Promise.reject(new DOMException('Test autoplay policy','NotAllowedError'));return original.call(this)}});
 await b.goto(hub);await expect(film(b)).toBeVisible();await expect(b.getByRole('button',{name:'播放任务序章',exact:true})).toBeVisible();
 expect(await b.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await b.screenshot({path:dir+'autoplay-fallback-mobile.png'});
 await b.getByRole('button',{name:'播放任务序章',exact:true}).click();await playing(b);await expect(b.getByRole('button',{name:'播放任务序章',exact:true})).toHaveCount(0);
 // Account hydration and changes must not replace the film or reset its position.
 const handle=await b.locator('video').elementHandle();
 await blocked.route('**/api/learning/records?**',r=>r.fulfill({contentType:'application/json',body:'{"draft":null,"submissions":[]}'}));
 await blocked.route('**/api/library/projects/*/tree',r=>r.fulfill({contentType:'application/json',body:'{"modules":[{"module_id":"M01"}]}'}));
 await blocked.route('**/api/my/knodes/*/complete-status',r=>r.fulfill({contentType:'application/json',body:'{"completed_knode_ids":[]}'}));
 await b.evaluate(t=>{localStorage.setItem('systemedu_token',t);window.dispatchEvent(new Event('focus'))},`test.${Buffer.from('{"sub":"intro-review"}').toString('base64url')}.test`);
 await expect(b.locator('[data-journey-start]')).toBeAttached();expect(await handle.evaluate(v=>v===document.querySelector('video'))).toBe(true);
 await b.keyboard.press('Escape');await expect(film(b)).toHaveCount(0);await blocked.close();
 report.checks.push('Blocked autoplay shows one clear play action; 390px layout has no overflow; click starts real playback; account change preserves video element; Escape exits');
 const offline=await browser.newContext(),o=await offline.newPage();watch(o);
 await offline.route('**/rover-briefing-v1.mp4',r=>r.abort());await o.goto(hub);await expect(film(o).getByRole('alert')).toContainText('短片未加载成功');await o.getByRole('button',{name:'跳过序章，进入任务中心'}).click();await expect(film(o)).toHaveCount(0);await expect(o.locator('[data-journey-start]')).toBeVisible();await offline.close();
 const denied=await browser.newContext(),d=await denied.newPage();watch(d);
 await denied.addInitScript(()=>{const get=Storage.prototype.getItem,set=Storage.prototype.setItem;Storage.prototype.getItem=function(key){if(key==='systemedu:mission:space:intro:v1')throw new DOMException('Disabled','SecurityError');return get.call(this,key)};Storage.prototype.setItem=function(key,value){if(key==='systemedu:mission:space:intro:v1')throw new DOMException('Disabled','SecurityError');return set.call(this,key,value)}});
 await d.goto(hub);await expect(film(d)).toBeVisible();await d.getByRole('button',{name:'关闭任务短片',exact:true}).click();await expect(film(d)).toHaveCount(0);await d.getByRole('link',{name:'所有项目线',exact:true}).click();await d.locator('[data-line-card="space-exploration"]').click();await expect(d.locator('[data-space-journey]')).toBeVisible();await expect(film(d)).toHaveCount(0);await denied.close();
 report.checks.push('Missing video never blocks entering tasks; storage denial is handled without errors and avoids repeated intro in the same client session');
 const background=await browser.newContext(),hidden=await background.newPage();watch(hidden);
 await background.addInitScript(()=>{window.__introHidden=true;Object.defineProperty(document,'hidden',{get:()=>window.__introHidden,configurable:true})});
 await hidden.goto(hub);await expect(hidden.locator('[data-space-journey]')).toBeVisible();await expect(hidden.getByRole('button',{name:'刷新进展'})).toBeEnabled();
 await expect(film(hidden)).toHaveCount(0);expect(await hidden.evaluate(key=>localStorage.getItem(key),seenKey)).toBeNull();
 await hidden.evaluate(()=>{window.__introHidden=false;document.dispatchEvent(new Event('visibilitychange'))});await expect(film(hidden)).toBeVisible();await playing(hidden);await background.close();
 report.checks.push('Background entry does not consume first-visit preference or start video; foreground visibility starts the intro');
 expect(report.errors).toEqual([]);report.passed=true;
} catch(e){report.failure=String(e);throw e}finally{await fs.writeFile(dir+'verification.json',JSON.stringify(report,null,2));await browser.close()}
