"""033 add user_project clone fields

Revision ID: 000777b126df
Revises: 20bc27e4d597
Create Date: 2026-05-19 20:01:52.916205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000777b126df'
down_revision: Union[str, Sequence[str], None] = '20bc27e4d597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_projects', sa.Column('cloned_version', sa.String(length=64), nullable=True))
    op.add_column('user_projects', sa.Column('local_path', sa.String(length=512), nullable=True))
    op.add_column('user_projects', sa.Column('cloned_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_projects', 'cloned_at')
    op.drop_column('user_projects', 'local_path')
    op.drop_column('user_projects', 'cloned_version')
    # ### end Alembic commands ###
