"""031 baseline student-app schema

Revision ID: 20bc27e4d597
Revises: 
Create Date: 2026-05-18 16:16:51.053486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bc27e4d597'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('assignment_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('library_slug', sa.String(length=128), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_paths', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_submissions_library_slug'), 'assignment_submissions', ['library_slug'], unique=False)
    op.create_index(op.f('ix_assignment_submissions_module_id'), 'assignment_submissions', ['module_id'], unique=False)
    op.create_index(op.f('ix_assignment_submissions_user_id'), 'assignment_submissions', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('library_slug', sa.String(length=128), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('active_skill', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'library_slug', 'module_id', 'title', name='uq_chat_session')
    )
    op.create_index(op.f('ix_chat_sessions_library_slug'), 'chat_sessions', ['library_slug'], unique=False)
    op.create_index(op.f('ix_chat_sessions_module_id'), 'chat_sessions', ['module_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('exercise_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('library_slug', sa.String(length=128), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('idea_id', sa.String(length=128), nullable=True),
    sa.Column('exercise_index', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('explanation_shown', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ea_user_created', 'exercise_attempts', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_ea_user_slug_module', 'exercise_attempts', ['user_id', 'library_slug', 'module_id'], unique=False)
    op.create_index(op.f('ix_exercise_attempts_user_id'), 'exercise_attempts', ['user_id'], unique=False)
    op.create_table('last_visited',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('library_slug', sa.String(length=128), nullable=False),
    sa.Column('last_module_id', sa.String(length=64), nullable=False),
    sa.Column('last_visited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'library_slug', name='uq_last_visited')
    )
    op.create_index(op.f('ix_last_visited_library_slug'), 'last_visited', ['library_slug'], unique=False)
    op.create_index(op.f('ix_last_visited_user_id'), 'last_visited', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('library_slug', sa.String(length=128), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_library_slug'), 'notes', ['library_slug'], unique=False)
    op.create_index(op.f('ix_notes_module_id'), 'notes', ['module_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('student_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('library_slug', sa.String(length=128), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source_session', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sf_user_scope_current', 'student_facts', ['user_id', 'scope'], unique=False, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_index('idx_sf_user_slug_current', 'student_facts', ['user_id', 'library_slug'], unique=False, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_index(op.f('ix_student_facts_user_id'), 'student_facts', ['user_id'], unique=False)
    op.create_table('user_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('library_slug', sa.String(length=128), nullable=False),
    sa.Column('library_version', sa.String(length=64), nullable=True),
    sa.Column('pulled_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'library_slug', name='uq_user_project')
    )
    op.create_index(op.f('ix_user_projects_library_slug'), 'user_projects', ['library_slug'], unique=False)
    op.create_index(op.f('ix_user_projects_user_id'), 'user_projects', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('library_slug', sa.String(length=128), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.Text(), nullable=True),
    sa.Column('skill', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_library_slug'), 'chat_messages', ['library_slug'], unique=False)
    op.create_index(op.f('ix_chat_messages_module_id'), 'chat_messages', ['module_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('pending_extractions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('enqueued_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_pending_extraction_session')
    )
    op.create_index('idx_pe_status_enqueued', 'pending_extractions', ['status', 'enqueued_at'], unique=False, postgresql_where=sa.text("status IN ('pending','failed')"))
    op.create_index(op.f('ix_pending_extractions_session_id'), 'pending_extractions', ['session_id'], unique=False)
    op.create_index(op.f('ix_pending_extractions_user_id'), 'pending_extractions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_extractions_user_id'), table_name='pending_extractions')
    op.drop_index(op.f('ix_pending_extractions_session_id'), table_name='pending_extractions')
    op.drop_index('idx_pe_status_enqueued', table_name='pending_extractions', postgresql_where=sa.text("status IN ('pending','failed')"))
    op.drop_table('pending_extractions')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_module_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_library_slug'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_user_projects_user_id'), table_name='user_projects')
    op.drop_index(op.f('ix_user_projects_library_slug'), table_name='user_projects')
    op.drop_table('user_projects')
    op.drop_index(op.f('ix_student_facts_user_id'), table_name='student_facts')
    op.drop_index('idx_sf_user_slug_current', table_name='student_facts', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_index('idx_sf_user_scope_current', table_name='student_facts', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_table('student_facts')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_module_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_library_slug'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_last_visited_user_id'), table_name='last_visited')
    op.drop_index(op.f('ix_last_visited_library_slug'), table_name='last_visited')
    op.drop_table('last_visited')
    op.drop_index(op.f('ix_exercise_attempts_user_id'), table_name='exercise_attempts')
    op.drop_index('idx_ea_user_slug_module', table_name='exercise_attempts')
    op.drop_index('idx_ea_user_created', table_name='exercise_attempts')
    op.drop_table('exercise_attempts')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_module_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_library_slug'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_assignment_submissions_user_id'), table_name='assignment_submissions')
    op.drop_index(op.f('ix_assignment_submissions_module_id'), table_name='assignment_submissions')
    op.drop_index(op.f('ix_assignment_submissions_library_slug'), table_name='assignment_submissions')
    op.drop_table('assignment_submissions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
