const fs=require('node:fs'),assert=require('node:assert/strict');
const ts=require('../../packages/student-web/node_modules/typescript');
require.extensions['.ts']=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);
const m=require('../../packages/student-web/src/lib/project-lines/rover-mission.ts');
const r=require('../../packages/student-web/src/lib/project-lines/rover-system.ts');
assert.equal(m.missionNodeStatus(undefined,false,false),'loading');
assert.equal(m.missionNodeStatus(undefined,true,true),'unknown');
assert.equal(m.missionNodeStatus(undefined,true,false),'new');
assert.equal(m.missionNodeStatus({answers:['我的判断']},true,false),'draft');
assert.equal(m.missionNodeStatus({answers:['我的判断'],submitted_at:'2026-10-09'},true,false),'submitted');
let a=r.newRoverSystem();a=r.runSystem(a,'training');
a.design={...a.design,actuator:'action',battery:'extended',deck:'reinforced',pace:'slow',sand:'slow',unknown:'stop'};
a=r.runSystem(a,'training');a=r.runSystem(a,'diagnostic');
a.diagnosis={caseId:'A7',probes:['camera','decision'],hypothesis:'camera',repair:'reconnect'};
a=r.runSystem(a,'diagnostic');a=r.runSystem(a,'transfer');
const body={answers:[1,2,3].map(i=>({question_id:'e'+i,question:'测试问题',answer:'测试证据'})),artifact:a};
assert(r.prototypeChecks(a).every(c=>c.passed));
assert.equal(m.roverEvidenceSummary(body,body,'2026-10-09').digital,5);
assert.equal(m.roverEvidenceSummary(body,body,'2026-10-09').submitted,false,'Digital success must not stand in for physical delivery');
assert.equal(m.roverEvidenceSummary({answers:[],artifact:{schema_version:'wrong'}},null).invalid,true);
fs.writeFileSync(__dirname+'/digital-fixture.json',JSON.stringify(body,null,2));
assert.equal(m.hasRoverMission({id:'assemble-a-rover',version:'1.0'}),false);
assert.equal(m.hasRoverMission({id:'assemble-a-rover',version:'2.0',legacy_edition:true}),false);
assert.equal(m.hasRoverMission({id:'write-driving-rules',version:'1.0'}),false);
console.log('PASS: record states, version boundaries, real digital checks and no false physical delivery');
