import * as THREE from 'three'
import type {Config} from './bionics-model'
type Profile={name:string;points:number[][];holes:number[][];thickness:number;quantity:number;note:string}
const rect=(w:number,h:number)=>[[-w/2,0],[w/2,0],[w/2,h],[-w/2,h]]
export function profiles(c:Config):Profile[]{return[
 {name:'base',points:rect(110,105),holes:[[-43,10,1.7],[43,10,1.7],[-43,95,1.7],[43,95,1.7],[-15,20,1.7],[15,20,1.7]],thickness:5,quantity:1,note:'平面朝下；底座接口由实购物品位置复核。'},
 {name:'moving-finger',points:[[-8,-9],[8,-9],[8,c.finger-12],[6,c.finger+5],[-6,c.finger+5],[-8,c.finger-12]],holes:[[0,0,c.bore/2],[0,9,1.2],[0,18,1.2],[0,c.finger-5,1.7]],thickness:5,quantity:1,note:'保留原配摇臂，打印件的孔与摇臂孔实测对齐；不打印舵机花键。'},
 {name:'servo-cheek',points:[[-22,0],[22,0],[16,c.gap+28],[-16,c.gap+28]],holes:[[-13,7,1.7],[13,7,1.7],[-10,c.gap+8,1.2],[10,c.gap+8,1.2]],thickness:5,quantity:2,note:'侧板平放；舵机夹座与孔距按型号适配，轴心到承接面为设计间隙。'},
 {name:'anvil',points:rect(36,48),holes:[[-12,8,1.7],[12,8,1.7],[-12,40,1.7],[12,40,1.7]],thickness:6,quantity:1,note:'固定承接垫，安装在底座；用打印垫片调高并实测零位。'},
 {name:'contact-pad',points:rect(20,16),holes:[[0,8,1.7]],thickness:3,quantity:1,note:'可换接触片；PLA 起点，若改 TPU 须重新试配。'},
 {name:'fit-coupon',points:rect(44,20),holes:[[-13,10,(c.bore-.1)/2],[0,10,c.bore/2],[13,10,(c.bore+.1)/2]],thickness:4,quantity:1,note:'三个孔依次为名义孔径 −0.1 / 原值 / +0.1 mm。'},
 {name:'angle-bracket',points:[[0,0],[24,0],[24,5],[5,5],[5,24],[0,24]],holes:[],thickness:18,quantity:4,note:'直角连接起点；按底座及侧板孔位在 CAD 中补通孔后导出，禁止把无孔模板冒充装好。'}
]}
export function parts(c:Config){return profiles(c).map(p=>{const s=new THREE.Shape();p.points.forEach(([x,y],i)=>i?s.lineTo(x,y):s.moveTo(x,y));s.closePath();for(const [x,y,r] of p.holes){const h=new THREE.Path();h.absarc(x,y,r,0,Math.PI*2,true);s.holes.push(h)}return{...p,geometry:new THREE.ExtrudeGeometry(s,{depth:p.thickness,bevelEnabled:false,curveSegments:32})}})}
export function cad(c:Config){const data=profiles(c).map(p=>{const points=p.name==='moving-finger'?'[[-8,-9],[8,-9],[8,finger-12],[6,finger+5],[-6,finger+5],[-8,finger-12]]':p.name==='servo-cheek'?'[[-22,0],[22,0],[16,gap+28],[-16,gap+28]]':JSON.stringify(p.points);const holes=p.name==='moving-finger'?'[[0,0,bore/2],[0,9,1.2],[0,18,1.2],[0,finger-5,1.7]]':p.name==='servo-cheek'?'[[-13,7,1.7],[13,7,1.7],[-10,gap+8,1.2],[10,gap+8,1.2]]':p.name==='fit-coupon'?'[[-13,10,(bore-.1)/2],[0,10,bore/2],[13,10,(bore+.1)/2]]':JSON.stringify(p.holes);return `if(part=="${p.name}") profile(${points},${holes},${p.thickness}); // qty ${p.quantity}`});return `// SystemEdu 参数化夹爪起点，单位 mm；尚未实物打样。\n// 全部自制结构 FDM 打印。保留原配摇臂，按实测尺寸修改安装孔。\n$fn=64; finger=${c.finger}; gap=${c.gap}; bore=${c.bore};\n// 可选：base / moving-finger / servo-cheek / anvil / contact-pad / fit-coupon / angle-bracket\npart="moving-finger";\nmodule profile(points,holes,t){difference(){linear_extrude(t)polygon(points);for(h=holes)translate([h[0],h[1],-1])cylinder(h=t+2,r=h[2]);}}\n${data.join('\n')}\n// finger、gap、bore 直接驱动相关零件。修改后 F6 渲染并重新导出 STL。\n// 直角座需增加穿过两侧面的安装孔；坐标按本人底座/支架匹配。参见制作指南。\n`}
export function firmware(c:Config){return `// SystemEdu rotary-input gripper STARTER; not a medical device.\n// Uno A0: 10k pot wiper; ends 5V/GND. D9: servo signal. D2: stop to GND (INPUT_PULLUP).\n// Servo: separate regulated 5V supply with physical switch; grounds common, positives NOT tied to USB 5V.\n// Calibrate with horn unloaded first. Physical power switch is the stop, not software alone.\n#include <Servo.h>\nServo finger;\nconst int N=${c.window}, CONFIRM=${c.confirm};\nconst float CLOSE=${c.on.toFixed(2)}, OPEN=${c.off.toFixed(2)};\nconst int OPEN_ANGLE=90, CLOSE_ANGLE=${90+Math.round(c.angle)}; // replace with YOUR measured non-binding endpoints\nfloat history[N]; int used=0,index=0,highCount=0,lowCount=0; bool closed=false; unsigned long last=0;\nvoid setup(){pinMode(2,INPUT_PULLUP);Serial.begin(115200);finger.attach(9);finger.write(OPEN_ANGLE);}\nvoid loop(){\n if(digitalRead(2)==LOW){closed=false;finger.write(OPEN_ANGLE);highCount=lowCount=used=index=0;return;}\n if(millis()-last<200)return;last=millis();\n const int adc=analogRead(A0); history[index]=adc/1023.0;index=(index+1)%N;if(used<N)used++;\n float value=0;for(int i=0;i<used;i++)value+=history[i];value/=used;\n if(value>=CLOSE){highCount++;lowCount=0;}else if(value<=OPEN){lowCount++;highCount=0;}else{highCount=lowCount=0;}\n if(highCount>=CONFIRM)closed=true;if(lowCount>=CONFIRM)closed=false;\n finger.write(closed?CLOSE_ANGLE:OPEN_ANGLE);\n Serial.print(millis());Serial.print(',');Serial.print(adc);Serial.print(',');Serial.print(value,3);Serial.print(',');Serial.println(closed);\n}\n// ADC has no built-in disconnect flag. A loose pot lead may float: physical stop first.\n// Browser null-sample tests do NOT prove this board can detect unplugged wires.\n`}
