/** 信号均为可复现的教学合成数据；几何接触不表示真实夹持力。 */
export const VERSION = 'bionics/1' as const
export type Mode = 'gate'|'grasp'|'filter'|'rules'|'mechanics'|'system'|'challenge'
export const MODES: Record<string,Mode> = {'open-a-signal-gate':'gate','grasp-a-virtual-block':'grasp','clean-a-signal':'filter','write-a-grasp-rule':'rules','design-a-printed-gripper':'mechanics','assemble-a-signal-controller':'system','test-an-unseen-object':'challenge'}
export const FINAL: Record<string,string> = {'clean-a-signal':'M04','write-a-grasp-rule':'M04','design-a-printed-gripper':'M05','assemble-a-signal-controller':'M06','test-an-unseen-object':'M05'}
export const CASES = {steady:'平稳握松',noise:'阈值附近有干扰',brief:'短促信号',missing:'读数突然中断',units:'接口故障复测',unseen:'首次陌生物体任务'} as const
export type Case = keyof typeof CASES
export type Config = {window:number;on:number;off:number;confirm:number;missing:'release'|'hold';unit:'normalized'|'adc';finger:number;gap:number;angle:number;bore:number}
export const DEFAULT:Config={window:1,on:.6,off:.45,confirm:1,missing:'release',unit:'adc',finger:55,gap:55,angle:30,bore:3.3}
export const LIMITS={window:[1,11,2],on:[.35,.9,.05],off:[.1,.7,.05],confirm:[1,5,1],finger:[40,65,1],gap:[45,65,1],angle:[10,50,1],bore:[3.1,3.6,.05]} as const
export const canonical=(x:unknown):string=>JSON.stringify(x,(_,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b))):v)
export const key=(c:Config)=>canonical(c)
export function validConfig(x:unknown):x is Config{if(!x||typeof x!=='object')return false;const c=x as Config;return Object.entries(LIMITS).every(([k,[lo,hi]])=>Number.isFinite(c[k as keyof Config])&&Number(c[k as keyof Config])>=lo&&Number(c[k as keyof Config])<=hi)&&Number.isInteger(c.window)&&Number.isInteger(c.confirm)&&c.off<c.on&&['release','hold'].includes(c.missing)&&['normalized','adc'].includes(c.unit)}
export function effective(c:Config,mode:Mode){return canonical(mode==='filter'||mode==='gate'||mode==='rules'?{window:c.window,on:c.on,off:c.off,confirm:c.confirm,missing:c.missing,unit:c.unit}:mode==='mechanics'||mode==='grasp'?{finger:c.finger,gap:c.gap,angle:c.angle}:c)}
export const clamp=(v:number,lo:number,hi:number)=>Math.max(lo,Math.min(hi,v))
export function aperture(c:Config,angle=c.angle){return c.gap-c.finger*Math.sin(angle*Math.PI/180)}
export function contact(c:Config,width:number){const gap=aperture(c),clearance=gap-width;return{gap,clearance,state:clearance>1?'miss':clearance< -1?'overtravel':'contact'} as const}
export type Sample={t:number;ideal:number;raw:number|null;intent:boolean}
export function samples(which:Case):Sample[]{return Array.from({length:61},(_,i)=>{const t=i*.2,intent=which==='brief'?(t>=3&&t<3.8||t>=7&&t<7.8):(t>=2&&t<5||t>=7&&t<10);const ideal=intent?.78:.22;let raw=ideal+.025*Math.sin(i*2.1);if(which==='noise')raw+=(t>=4.4&&t<6.8?.37:.1)*Math.sin(i*1.7);if(which==='unseen')raw=ideal+(t>=4&&t<7?.32:.08)*Math.sin(i*2.2);return{t,ideal,intent,raw:which==='missing'&&t>=3&&t<4.4?null:clamp(raw,0,1)}})}
/** 仅用当前及过去样本；断流清空窗口，恢复后不混入旧样本。 */
export function processSignal(input:Sample[],c:Config,which:Case){let closed=false,above=0,below=0;const history:number[]=[];return input.map(s=>{const received=s.raw===null?null:which==='units'?Math.round(s.raw*1023):s.raw;const normalized=received===null?null:which==='units'&&c.unit==='adc'?received/1023:received;if(normalized===null){history.length=0;above=below=0;if(c.missing==='release')closed=false;return{...s,received,filtered:null,closed,valid:false}}
 history.push(normalized);if(history.length>c.window)history.shift();const filtered=history.reduce((a,b)=>a+b,0)/history.length;
 if(filtered>=c.on){above++;below=0}else if(filtered<=c.off){below++;above=0}else{above=below=0}if(above>=c.confirm)closed=true;if(below>=c.confirm)closed=false;
 return{...s,received,filtered,closed,valid:true}
})}
export type Point=ReturnType<typeof processSignal>[number]
export type Run={id:string;at:string;config:Config;mode:Mode;scenario:Case;points:Point[];error:number;falseSeconds:number;missSeconds:number;switches:number;latency:number|null;width:number;gap:number;contact:'miss'|'overtravel'|'contact'}
export function simulate(c:Config,mode:Mode,scenario:Case,id='preview',at=''):Run{if(!validConfig(c))throw Error('参数无效：松开阈值应低于闭合阈值。');const points=processSignal(samples(scenario),c,scenario),observed=points.filter(p=>p.filtered!==null),evaluated=points.slice(0,-1);const width=scenario==='unseen'?33:28,grip=contact(c,width);let switches=0;points.forEach((p,i)=>{if(i>0&&p.closed!==points[i-1].closed)switches++});const start=points.find(p=>p.intent)?.t??0,response=points.find(p=>p.t>=start&&p.intent&&p.closed)?.t;
 return{id,at,config:{...c},mode,scenario,points,error:observed.reduce((s,p)=>s+Math.abs(p.filtered!-p.ideal),0)/Math.max(1,observed.length),falseSeconds:evaluated.filter(p=>!p.intent&&p.closed).length*.2,missSeconds:evaluated.filter(p=>p.intent&&!p.closed).length*.2,switches,latency:response===undefined?null:response-start,width,gap:grip.gap,contact:grip.state}}
export function rule(c:Config){return `close = ${c.on.toFixed(2)}\nopen = ${c.off.toFixed(2)}\nconfirm = ${c.confirm}\nmissing = ${c.missing}`}
export function parseRule(code:string,c:Config):Config{const data:Record<string,string>={};for(const line of code.trim().split('\n')){const m=line.trim().match(/^(close|open|confirm|missing)\s*=\s*([\w.]+)$/);if(!m||data[m[1]])throw Error('只允许 close、open、confirm、missing 各一行。');data[m[1]]=m[2]}if(Object.keys(data).length!==4)throw Error('请写完整四行。');const next={...c,on:Number(data.close),off:Number(data.open),confirm:Number(data.confirm),missing:data.missing} as Config;if(!validConfig(next))throw Error('检查阈值顺序、确认次数 1–5，以及 release / hold。');return next}
export type Physical={revision:string;material:string;dimensions:string;before:string;change:string;after:string;wiring:string;source:string;csv:string;photos:{id:string;data:string;caption:string;revision:string}[]}
export type Frozen={at:string;config:Config;question:string;limit:number;first:Run|null;physical:Physical|null}
export type Workspace={schema:typeof VERSION;config:Config;runs:Run[];decision:string;boundary:string;hypothesis:string;probes:string[];repair:string;physical:Physical;frozen:Frozen|null;question:string;limit:number;sources:{project:string;submission:string}[]}
export const emptyPhysical=():Physical=>({revision:'',material:'',dimensions:'',before:'',change:'',after:'',wiring:'',source:'',csv:'',photos:[]})
export function fresh(mode:Mode='gate'):Workspace{return{schema:VERSION,config:{...DEFAULT,...(mode==='system'||mode==='challenge'?{unit:'normalized' as const}:{})},runs:[],decision:'',boundary:'',hypothesis:'',probes:[],repair:'',physical:emptyPhysical(),frozen:null,question:'',limit:.4,sources:[]}}
export function measurementRows(csv:string){const rows=csv.trim().split(/\r?\n/);if(rows.shift()!=='angle_deg,gap_mm,target_mm,held_5s')throw Error('表头应为 angle_deg,gap_mm,target_mm,held_5s');if(rows.length<3||rows.length>30)throw Error('保留 3–30 次本人测量。');return rows.map((s,i)=>{const p=s.split(',');if(p.length!==4||p.some(x=>x.trim()===''))throw Error(`第 ${i+1} 行缺字段。`);const [angle,gap,target,held]=p.map(Number);if(![angle,gap,target,held].every(Number.isFinite)||angle<0||angle>90||gap<0||gap>100||target<=0||target>70||![0,1].includes(held))throw Error(`第 ${i+1} 行超出范围或保持结果不是 0/1。`);return{angle,gap,target,held}})}
function physicalOK(p:unknown):p is Physical{if(!p||typeof p!=='object')return false;const x=p as Physical;return ['revision','material','dimensions','before','change','after','wiring','source','csv'].every(k=>typeof x[k as keyof Physical]==='string')&&x.source.length<=16000&&x.csv.length<=6000&&Array.isArray(x.photos)&&x.photos.length<=2&&x.photos.every(f=>f&&typeof f.id==='string'&&typeof f.revision==='string'&&typeof f.caption==='string'&&typeof f.data==='string'&&f.data.startsWith('data:image/jpeg;base64,')&&f.data.length<=52000)}
function runOK(r:unknown):r is Run{if(!r||typeof r!=='object')return false;const x=r as Run;return validConfig(x.config)&&Object.values(MODES).includes(x.mode)&&Object.keys(CASES).includes(x.scenario)&&typeof x.id==='string'&&typeof x.at==='string'&&Array.isArray(x.points)&&x.points.length===61&&x.points.every(p=>p&&Number.isFinite(p.t)&&Number.isFinite(p.ideal)&&(p.raw===null||Number.isFinite(p.raw))&&(p.filtered===null||Number.isFinite(p.filtered))&&(p.received===null||Number.isFinite(p.received))&&typeof p.closed==='boolean'&&typeof p.intent==='boolean'&&typeof p.valid==='boolean')&&[x.error,x.falseSeconds,x.missSeconds,x.switches,x.width,x.gap].every(Number.isFinite)&&(x.latency===null||Number.isFinite(x.latency))&&['contact','miss','overtravel'].includes(x.contact)}
export function validWorkspace(value:unknown):value is Workspace{try{if(!value||typeof value!=='object')return false;const a=value as Workspace,f=a.frozen;return a.schema===VERSION&&validConfig(a.config)&&Array.isArray(a.runs)&&a.runs.length<=8&&a.runs.every(runOK)&&['decision','boundary','hypothesis','repair','question'].every(k=>typeof a[k as keyof Workspace]==='string')&&Number.isFinite(a.limit)&&a.limit>=0&&a.limit<=3&&Array.isArray(a.probes)&&a.probes.length<=3&&a.probes.every(p=>['signal','interface','mechanism'].includes(p))&&physicalOK(a.physical)&&Array.isArray(a.sources)&&a.sources.length<=3&&a.sources.every(s=>typeof s.project==='string'&&typeof s.submission==='string')&&(f===null||f&&typeof f.at==='string'&&typeof f.question==='string'&&Number.isFinite(f.limit)&&f.limit>=0&&f.limit<=3&&validConfig(f.config)&&(f.first===null||runOK(f.first))&&(f.physical===null||physicalOK(f.physical)))}catch{return false}}
export function remember(a:Workspace,r:Run):Workspace{const candidates=[...a.runs,r],first=candidates[0],fault=candidates.find(r=>r.scenario==='units'),keep=[first,...(fault&&fault!==first?[fault]:[])];return{...a,runs:[...keep,...candidates.filter(r=>!keep.includes(r)).slice(-(8-keep.length))]}}
export function physicalChecks(a:Workspace){const p=a.physical;let rows=false;try{rows=measurementRows(p.csv).length>=3}catch{}return[{title:'当前设计的本人打印与试配记录',passed:p.revision===key(a.config)&&[p.material,p.dimensions,p.before,p.change,p.after,p.wiring].every(s=>s.trim().length>=5)},{title:'本人修改的 CAD / 程序源',passed:p.source.trim().length>=60},{title:'至少三次原始测量，成功或失败都保留',passed:rows},{title:'两张本人照片及其证据说明',passed:p.photos.length===2&&p.photos.every(p=>p.revision===key(a.config)&&p.caption.trim().length>=5)}]}
export function checks(id:string,a:Workspace,prototype=false){const mode=MODES[id],micro=mode==='gate'||mode==='grasp',current=a.runs.filter(r=>key(r.config)===key(a.config)),pairs=a.runs.some((r,i)=>a.runs.slice(i+1).some(s=>s.scenario===r.scenario&&effective(s.config,mode)!==effective(r.config,mode)));const out=[{title:'同一工况下改变相关参数，保留两版比较',passed:pairs},{title:'当前配置有对应实验，旧结果不代替新版本',passed:current.length>0}];if(!micro)out.push({title:'自己的选择理由和模型边界',passed:a.decision.trim().length>=10&&a.boundary.trim().length>=10});if(mode==='rules'||mode==='system'||mode==='challenge')out.push({title:'当前规则在干扰与断流工况分别测试',passed:['noise','missing'].every(s=>current.some(r=>r.scenario===s))});if(mode==='system'||mode==='challenge')out.push({title:'先提假设、检查接口，保留修复前后证据',passed:a.hypothesis.trim().length>=10&&a.probes.includes('interface')&&a.repair.trim().length>=10&&a.runs.some(r=>r.scenario==='units'&&r.config.unit==='normalized')&&current.some(r=>r.scenario==='units'&&r.config.unit==='adc')});if(mode==='challenge')out.push({title:'事前声明与不可覆盖的第一次结果',passed:!!a.frozen?.first&&a.frozen.question.trim().length>=15});if(!prototype&&['mechanics','system','challenge'].includes(mode))out.push(...physicalChecks(a));if(!prototype&&mode==='challenge')out.push({title:'冻结版本的首轮实物记录已固定',passed:!!a.frozen?.physical&&a.frozen.physical.revision===key(a.frozen.config)});return out}
