const fs=require('fs'),assert=require('assert'),{chromium}=require('/Users/xinghan/Dev/systemedu/node_modules/playwright');
const [a,b]=JSON.parse(fs.readFileSync('/private/tmp/pvlib-preview/test-credentials.json')).users,out='/private/tmp/pvlib-authoring/audit/browser/restore-bridge';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({args:['--no-proxy-server']}),checks=[];
async function open(user){const ctx=await browser.newContext();await ctx.addInitScript(t=>{if(window===window.top)localStorage.setItem('systemedu_token',t)},user.token);await ctx.route(/http:\/\/(localhost|127\.0\.0\.1):18820\/api\/(learning\/|auth\/me)/,r=>r.continue({url:r.request().url().replace(/http:\/\/(localhost|127\.0\.0\.1):18820/,'http://127.0.0.1:18928')}));const p=await ctx.newPage();p.on('pageerror',e=>console.log('PAGE ERROR',e.message));p.on('response',async r=>{if(r.url().includes('/api/learning/records?')&&r.url().includes('kind=assignment')){let d=await r.json();console.log('ASSIGNMENT',r.status(),new URL(r.url()).searchParams.get('content_version'),!!d.draft?.body?.artifact, d.draft?.body?.artifact?Object.keys(d.draft.body.artifact):[]);}});await p.goto('http://127.0.0.1:4000/preview/pvlib/M21?view=lab&mode=game');const loc=p.locator('[data-preview-lab] iframe');await loc.waitFor();const f=await(await loc.elementHandle()).contentFrame();await f.evaluate(()=>{window.restoredForTest=[];window.addEventListener('message',e=>{if(e.source===parent&&e.data?.type==='systemedu-pvlib-artifact-restore')window.restoredForTest.push(e.data)})});return {ctx,p,f}}
const x=await open(a);
// Make a real fresh operation in the current course version before restoring it.
await x.f.locator('#prediction').fill('QA：比较两种间距的遮挡。');await x.f.locator('#variable').selectOption('spacing');await x.f.locator('#spacing').selectOption('5');await x.f.locator('#measure').click();await x.f.locator('#spacing').selectOption('1');await x.f.locator('#measure').click();await x.f.locator('#unmodeled').fill('QA：这是数字实验，不是实物测量。');await x.f.locator('#explanation').fill('QA：相同太阳高度，两次间距观察保留在实验历史。');await x.f.locator('#save').click();await x.p.getByRole('button',{name:'关联到本节作业',exact:true}).click();let delivery=x.p.locator('[data-pvlib-delivery]');for(const input of await delivery.locator('input[type=text],textarea').all())await input.fill('QA restore bridge '+Date.now());await delivery.locator('[data-learning-status]').filter({hasText:'已保存到账号'}).waitFor();await delivery.getByRole('button',{name:'提交本节作业',exact:true}).click();await delivery.locator('[data-learning-status]').filter({hasText:'已提交到账号'}).waitFor();await x.ctx.close();Object.assign(x,await open(a));
await x.p.evaluate(()=>window.postMessage({type:'systemedu-pvlib-artifact-ready',module_id:'M21',idea_id:'M21-game'},'*'));await x.f.evaluate(()=>parent.postMessage({type:'systemedu-pvlib-artifact-ready',module_id:'M33',idea_id:'M21-game'},'*'));await x.p.waitForTimeout(250);assert.equal(await x.f.evaluate(()=>window.restoredForTest.length),0);checks.push('forged parent source and wrong lesson ignored');
await x.f.evaluate(()=>parent.postMessage({type:'systemedu-pvlib-artifact-ready',module_id:'M21',idea_id:'M21-game'},'*'));await x.f.waitForFunction(()=>window.restoredForTest.length>0);const msg=await x.f.evaluate(()=>({keys:Object.keys(window.restoredForTest[0]).sort(),module:window.restoredForTest[0].module_id,idea:window.restoredForTest[0].idea_id,payloadKeys:Object.keys(window.restoredForTest[0].artifact)}));assert.deepEqual(msg.keys,['artifact','idea_id','module_id','type']);assert.equal(msg.module,'M21');assert.equal(msg.idea,'M21-game');assert(msg.payloadKeys.length);checks.push('saved account assignment payload restored through exact opaque frame; no token or classroom answers');
const y=await open(b);await y.f.evaluate(()=>parent.postMessage({type:'systemedu-pvlib-artifact-ready',module_id:'M21',idea_id:'M21-game'},'*'));await y.p.waitForTimeout(1000);assert.equal(await y.f.evaluate(()=>window.restoredForTest.length),0);checks.push('second isolated account receives no first account artifact');
await x.ctx.close();await y.ctx.close();await browser.close();fs.writeFileSync(out+'/report.json',JSON.stringify({status:'pass',checks,scope:'read-only isolated test account bridge check; M33 thermal end-to-end still pending'},null,2));console.log('PASS',checks.length,'browser bridge checks')})().catch(e=>{console.error(e);process.exit(1)});
