'use client'
import Link from 'next/link'
import {useEffect,useRef,useState} from 'react'
import {useLearningIdentity,useLearningRecord} from '@/lib/hooks/use-learning-record'
import {learningRecords} from '@/lib/api/learning-records'
import {learningCacheKey} from '@/lib/learning-record-session'
import type {GuidedCourse,GuidedModule} from '@/lib/project-lines/guided-course'
import {CASES,MODES,FINAL,LIMITS,fresh,validWorkspace,validConfig,simulate,remember,rule,parseRule,key,canonical,contact,type Config,type Workspace,type Case} from '@/lib/project-lines/bionics-model'
import {cad,firmware} from '@/lib/project-lines/bionics-geometry'
import {BionicsScene} from './bionics-scene'
import {BionicsPlot,BionicsDelivery,BionicsPhysical,BionicsChallenge,bionicsBody,bionicsScope,download} from './bionics-evidence'
import {LearningRecordStatus} from './learning-record-status'
import s from './bionics-workspace.module.css'
const labels={window:['平均窗口','点','越长可能越平滑，也可能拖慢响应。'],on:['闭合阈值','','达到此值才累计闭合确认。'],off:['松开阈值','','必须低于闭合阈值，中间区域保持状态。'],confirm:['连续确认','次','每 0.2 秒取一次样本。'],finger:['转轴到接触点','mm','打印夹指的有效长度。'],gap:['零位间隙','mm','水平夹指的接触点到固定承接面的距离。'],angle:['向下转角','°','理想点接触几何，不表示真实夹持力。'],bore:['名义配合孔径','mm','先打印试配片，再按实物调整。']} as const
export function BionicsMicroProject({id,title}:{id:string;title:string}){return <main className={s.micro}><Link href="/library?view=lines&line=neuro-bionics">← 超能机械师</Link><p>01 / 约三分钟 · 先让一个想法动起来</p><h1>{title}</h1><p>{id==='open-a-signal-gate'?'先运行一次，让信号控制门；改一个阈值再试，找到误开和迟开的区别。':'转动夹指，比较碰不到、接近和过行程。留下自己的两版设计。'}</p><BionicsWorkspace id={id} node="M01"/></main>}
export function BionicsCourseWorkspace({course,node}:{course:GuidedCourse;node:GuidedModule}){return <BionicsWorkspace id={course.id} node={node.module_id}/>}
function BionicsWorkspace({id,node}:{id:string;node:string}){const identity=useLearningIdentity();return <Session key={`${id}:${identity.owner}`} id={id} node={node}/>}
function Session({id,node}:{id:string;node:string}){
 const mode=MODES[id],geometryOnly=mode==='grasp'||mode==='mechanics',micro=['gate','grasp'].includes(mode),physical=['mechanics','system','challenge'].includes(mode),system=['system','challenge'].includes(mode),identity=useLearningIdentity(),record=useLearningRecord(bionicsScope(id),bionicsBody(fresh(mode))),a=validWorkspace(record.body.artifact)?record.body.artifact:fresh(mode),c=a.config,disabled=!record.ready||record.busy||!!record.conflict||record.pending||!validWorkspace(record.body.artifact),live=useRef({disabled,a,owner:identity.owner})
 const [scenario,setScenario]=useState<Case>(system?'units':'noise'),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[editor,setEditor]=useState<{basis:string;value:string}|null>(null),[message,setMessage]=useState(''),[importing,setImporting]=useState(false)
 useEffect(()=>{live.current={disabled,a,owner:identity.owner}},[disabled,a,identity.owner]);useEffect(()=>()=>{live.current.disabled=true},[])
 const code=editor?.basis===rule(c)?editor.value:rule(c),playhead=useRef(0);useEffect(()=>{playhead.current=time},[time])
 useEffect(()=>{if(!playing)return;let frame=0;const start=performance.now()-playhead.current*1000;const tick=()=>{const next=Math.min(12,(performance.now()-start)/1000);setTime(next);if(next<12)frame=requestAnimationFrame(tick);else setPlaying(false)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[playing])
 const preview=simulate(c,mode,scenario),point=preview.points[Math.min(60,Math.floor(time/.2))],grip=contact(c,preview.width),final=micro||node===FINAL[id]
 function update(next:Workspace){if(disabled)return;if(!validWorkspace(next)){setMessage('记录格式不合法，请检查参数或文件。');return}const payload=bionicsBody(next);if(new TextEncoder().encode(JSON.stringify(payload)).length>235000){setMessage('记录容量不足，请缩短说明或源文件、裁剪照片。');return}record.session.update(payload)}
 async function flush(){await record.session.save();const state=record.session.snapshot();if(identity.token&&state.dirty){setMessage("实验草稿尚未同步，请先重试同步，再提交作品。");return false}return true}
 function change(patch:Partial<Config>){const next={...c,...patch};if(!validConfig(next)){setMessage('松开阈值必须低于闭合阈值。');return}update({...a,config:next});setMessage('参数已改变；运行一次，保存这一版的对应结果。')}
 function run(){const r=simulate(c,mode,scenario,crypto.randomUUID(),new Date().toISOString());update(remember(a,r));setTime(0);setPlaying(!matchMedia('(prefers-reduced-motion: reduce)').matches);setMessage('本次参数与实验已记录。改变一个参数，在相同工况再比较。')}
 async function importOwn(){setImporting(true);const owner=identity.owner;try{const next=structuredClone(a);let found=0;for(const project of ['clean-a-signal','write-a-grasp-rule','design-a-printed-gripper']){const scope=bionicsScope(project,'final');let saved:Workspace|null=null,submission='';if(identity.token){const data=await learningRecords.read(identity.token,scope);const latest=data.submissions.find(x=>validWorkspace(x.body.artifact));if(latest){saved=latest.body.artifact as Workspace;submission=latest.id}}else{const raw=localStorage.getItem(learningCacheKey(owner,scope));if(raw){const cache=JSON.parse(raw);if(cache.submittedAt&&validWorkspace(cache.body?.artifact)){saved=cache.body.artifact;submission='本机提交 '+cache.submittedAt}}}if(saved){found++;const source=saved.config;next.config={...next.config,...(project==='clean-a-signal'?{window:source.window}:project==='write-a-grasp-rule'?{on:source.on,off:source.off,confirm:source.confirm,missing:source.missing}:{finger:source.finger,gap:source.gap,angle:source.angle,bore:source.bore})};next.sources=[...next.sources.filter(s=>s.project!==project),{project,submission}]}}if(live.current.disabled||live.current.owner!==owner)return;if(canonical(live.current.a)!==canonical(a)){setMessage("读取期间草稿已改变，未覆盖新输入，请重新读取前作。");return}update(next);setMessage(found?`已接入 ${found} 份本人前作参数；请重新验证系统接口及当前配置。`:'尚未找到本人提交的前作，当前使用示例参数；可以先完成前面的课程。')}catch{setMessage('前作读取失败，请稍后重试；现有参数未改变。')}finally{setImporting(false)}}
 const controls:(keyof typeof labels)[]=mode==='grasp'?['angle','finger','gap']:mode==='gate'?['on','off']:mode==='filter'?['window','on']:mode==='rules'?['window','on','off','confirm']:mode==='mechanics'?['finger','gap','angle','bore']:['window','on','off','confirm','finger','gap','angle','bore']
 return <section className={s.work} data-bionics-workspace={id}><p className={s.eyebrow}>SIGNAL → RULE → MOTION</p><h3>{micro?'先运行，再改一次':'信号与机械实验台'}</h3><p className={s.step}>{micro?'① 运行并保留基线　② 改一个参数、同工况重试　③ 保存两版发现':'本项目各节点共用一份实验草稿；课程学习记录在下方分别保存。'}</p>{!record.ready&&<p>正在读取你的实验记录…</p>}<div className={s.layout}><BionicsScene config={c} mode={mode} closed={mode==='grasp'||mode==='mechanics'?true:point.closed} time={time}/><fieldset className={s.fieldset} disabled={disabled||importing}><div className={s.controls}>{controls.map(field=><label className={s.control} key={field}>{labels[field][0]}<output>{Number(c[field].toFixed(2))} {labels[field][1]}</output><input aria-label={labels[field][0]} type="range" min={LIMITS[field][0]} max={LIMITS[field][1]} step={LIMITS[field][2]} value={c[field]} onChange={e=>change({[field]:Number(e.target.value)})}/><small>{labels[field][2]}</small></label>)}{!['grasp','mechanics','gate','filter'].includes(mode)&&<label>读数缺失时<select value={c.missing} onChange={e=>change({missing:e.target.value as Config['missing']})}><option value="release">松开 release</option><option value="hold">保持 hold</option></select></label>}{!geometryOnly&&<label>测试工况<select value={scenario} onChange={e=>{setScenario(e.target.value as Case);setTime(0);setPlaying(false)}}>{Object.entries(CASES).filter(([k])=>k!=='unseen'&&(system||k!=='units')).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>}<button className={s.primary} onClick={run}>运行并保留本次实验</button></div></fieldset></div>{!geometryOnly&&<><div className={s.row}><button disabled={disabled} onClick={()=>{if(time>=12)setTime(0);setPlaying(!playing)}}>{playing?'暂停回放':'播放当前配置'}</button><label>回放时间 {time.toFixed(1)} s <input aria-label="回放时间" type="range" min="0" max="12" step=".2" value={time} onChange={e=>{setPlaying(false);setTime(Number(e.target.value))}}/></label><span>状态：{point.closed?'闭合':'松开'} · {point.valid?'有效读数':'缺测'}</span></div><BionicsPlot run={preview} cursor={time}/></>}{geometryOnly&&<div className={s.stats}><div><strong>{c.angle}°</strong><span>夹指向下转角</span></div><div><strong>{grip.gap.toFixed(1)} mm</strong><span>预测剩余开口</span></div><div><strong>{grip.clearance.toFixed(1)} mm</strong><span>开口减目标高度</span></div></div>}{physical||mode==='grasp'?<p className={s.notice}>目标高 {preview.width} mm，闭合时预测开口 {grip.gap.toFixed(1)} mm：{grip.state==='miss'?'尚未碰到':grip.state==='overtravel'?'预测过行程，需要减小闭合量':'接近几何接触'}。这不是力学计算；真实夹持与保持需要测量。</p>:null}
 {mode==='rules'||system?<section className={s.section}><h4>写进机器真正执行的规则</h4><p>四行各控制一件事。修改后点击应用，再运行实验；中间阈值区域保持原状态。</p><fieldset disabled={disabled} className={s.fieldset}><label>控制规则<textarea className={s.rule} aria-label="控制规则" value={code} maxLength={300} onChange={e=>setEditor({basis:rule(c),value:e.target.value})}/></label><button onClick={()=>{try{const next=parseRule(code,c);update({...a,config:next});setMessage('规则已应用，实验将使用这些条件。')}catch(e){setMessage(String(e))}}}>应用规则</button></fieldset></section>:null}
 {system&&<section className={s.section}><h4>连接与诊断自己的系统</h4><button disabled={disabled||importing} onClick={importOwn}>{importing?'读取中…':'读取本人已提交的前作参数'}</button><p className={s.caption}>{a.sources.length?`已接入 ${a.sources.length} 份作品；旧照片不会作为当前设计的实测。`:'没有前作时从示例开始，后续仍要独立验证。'}</p><fieldset disabled={disabled||importing} className={s.fieldset}><label>先写诊断假设<input maxLength={500} value={a.hypothesis} placeholder="例如：低读数仍触发闭合，可能是输入范围与阈值单位不同。" onChange={e=>update({...a,hypothesis:e.target.value})}/></label><div className={s.row}>{(['signal','interface','mechanism'] as const).map((probe,i)=><button key={probe} onClick={()=>{if(a.hypothesis.trim().length<10){setMessage('先留下一个可以被读数检验的假设，再探查。');return}update({...a,probes:Array.from(new Set([...a.probes,probe]))});setMessage(probe==='interface'?'接口工况收到约 225，控制器阈值只有 0.60。检查两者是否采用相同单位。':probe==='signal'?'合成意图在 0.22 / 0.78 间变化；输入接收端在接口工况给出 0–1023 的数值。':'夹指开口取决于长度、零位和角度；改几何不会修复输入单位。')}}>探查{['信号','接口','机构'][i]}</button>)}</div><label>接口输入约定<select aria-label="接口输入约定" value={c.unit} onChange={e=>change({unit:e.target.value as Config['unit']})}><option value="normalized">直接当作 0–1</option><option value="adc">ADC 0–1023 转为 0–1</option></select></label><label>我的修复依据<input maxLength={500} value={a.repair} placeholder="写探查读数、最小修改，以及相同工况的复测变化。" onChange={e=>update({...a,repair:e.target.value})}/></label></fieldset></section>}
 <section className={s.section}><h4>保留的实验 · {a.runs.length} / 8</h4><p className={s.caption}>保留第一版、首次接口故障及最近实验。参数改变后要重新运行；预览曲线不自动算作已记录试验。</p><div className={s.tableScroll}><table><thead><tr><th>版本 / 工况</th><th>窗口 / 确认</th><th>开 / 合阈值</th><th>角度 / 间隙</th><th>误闭合</th><th>配置</th></tr></thead><tbody>{a.runs.map((r,i)=><tr key={r.id}><td>{i+1} / {CASES[r.scenario]}</td><td>{r.config.window} / {r.config.confirm}</td><td>{r.config.off} / {r.config.on}</td><td>{r.config.angle}° / {r.gap.toFixed(1)} mm</td><td>{r.falseSeconds.toFixed(1)} s</td><td>{key(r.config)===key(c)?'当前':'旧版'}</td></tr>)}</tbody></table></div></section>
 {!micro&&<fieldset className={s.fields} disabled={disabled}><label>我的选择与证据<input maxLength={1000} value={a.decision} placeholder="例如：同工况窗口从 1 改到 3 后，… 减少，但 … 增加，所以我选择 …。" onChange={e=>update({...a,decision:e.target.value})}/></label><label>当前证据还不能证明什么<input maxLength={1000} value={a.boundary} placeholder="例如：合成信号结果不能证明真实肌电有效；几何接触还没有力学验证。" onChange={e=>update({...a,boundary:e.target.value})}/></label></fieldset>}
 {physical&&<section className={s.section}><h4>把自己的设计带到桌面</h4><p>参数化 CAD 与控制程序会使用当前配置。先打印试配片，实测舵机与摇臂孔位，再修改安装座。模板尚未实物打样，不能直接当作已验证套件。</p><div className={s.row}><button onClick={()=>download('my-gripper.scad',cad(c))}>下载当前参数 CAD</button><button onClick={()=>download('my-gripper.ino',firmware(c))}>下载当前控制程序</button><a href="/project-lines/neuro-bionics/hardware/making-guide.html" target="_blank" rel="noreferrer">器材、接线与打印步骤 ↗</a><a href="/project-lines/neuro-bionics/hardware/bionics-starter.zip" download>默认 STL 与完整起点包</a></div></section>}
 {mode==='challenge'&&<BionicsChallenge a={a} update={update} disabled={disabled}/>}{physical&&<BionicsPhysical a={a} update={update} disabled={disabled}/>}{message&&<p role="status" className={s.notice}>{message}</p>}<LearningRecordStatus record={record}/>{final&&<>{physical&&<BionicsDelivery id={id} a={a} ready={!disabled} flush={flush} prototype/>}<BionicsDelivery id={id} a={a} ready={!disabled} flush={flush}/></>}{!final&&<p className={s.caption}>最终交付位于 {FINAL[id]}；当前实验草稿会随节点继续保留。</p>}</section>
}
