'use client'
import {useEffect,useRef,useState} from 'react'
import {useLearningRecord} from '@/lib/hooks/use-learning-record'
import type {LearningBody,LearningScope} from '@/lib/api/learning-records'
import {CASES,FINAL,checks,canonical,key,physicalChecks,validWorkspace,measurementRows,emptyPhysical,simulate,type Workspace,type Run,type Physical} from '@/lib/project-lines/bionics-model'
import {LearningRecordStatus} from './learning-record-status'
import s from './bionics-workspace.module.css'
export const bionicsScope=(id:string,phase='work'):LearningScope=>({library_slug:id,module_id:phase==='work'?'WORK':FINAL[id]||'M01',activity_id:`bionics-${phase}`,kind:phase==='work'?'classroom':'assignment',content_version:'1.0'})
export const bionicsBody=(a:Workspace):LearningBody=>({answers:[{question_id:'decision',question:'我的参数、证据与解释',answer:a.decision||`保留 ${a.runs.length} 次教学实验，详见作品档案。`}],artifact:structuredClone(a) as unknown as Record<string,unknown>,client_context:{schema:'bionics/1',data_origin:'simulated-and-learner-evidence'}})
export function download(name:string,text:string){const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
export function BionicsPlot({run:r,cursor}:{run:Run;cursor?:number}){
 const path=(field:'raw'|'filtered'|'ideal')=>{let pen=false;return r.points.map(p=>{const v=p[field];if(v===null){pen=false;return ''}const start=pen?'L':'M';pen=true;return `${start}${40+p.t*45},${172-Math.max(0,Math.min(1,v))*120}`}).join(' ')}
 return <><div className={s.stats}><div><strong>{r.error.toFixed(3)}</strong><span>与合成意图的平均误差</span></div><div><strong>{r.falseSeconds.toFixed(1)} s</strong><span>误闭合累计时间</span></div><div><strong>{r.latency===null?'未响应':r.latency.toFixed(1)+' s'}</strong><span>第一次动作响应延迟</span></div></div><svg className={s.plot} viewBox="0 0 620 235" role="img" aria-label="原始输入、因果平均和合成意图随时间变化，缺测处断开"><title>{`${CASES[r.scenario]} · 每 0.2 秒采样`}</title>{[0,.5,1].map(v=><g key={v}><path d={`M40 ${172-v*120}H580`} stroke="#d8ddce"/><text x="32" y={176-v*120} textAnchor="end" fontSize="11" fill="#697566">{v}</text></g>)}<path d={path('ideal')} stroke="#7d8580" strokeDasharray="5 4" fill="none"/><path d={path('raw')} stroke="#bb704b" strokeWidth="1.5" fill="none"/><path d={path('filtered')} stroke="#347159" strokeWidth="2.5" fill="none"/>{r.points.slice(0,-1).map(p=><rect key={p.t} x={40+p.t*45} y="192" width="9.2" height="9" fill={!p.valid?'#d6b497':p.closed?'#3f6654':'#dce1d2'}/>)}{[0,3,6,9,12].map(t=><text key={t} x={40+t*45} y="222" textAnchor="middle" fontSize="11" fill="#697566">{t}s</text>)}{cursor!==undefined&&<path d={`M${40+cursor*45} 32V205`} stroke="#3a443a" strokeWidth="1"/>}<text x="40" y="24" fill="#637064" fontSize="11">归一化幅值（越界被截在图顶，原始表保留数值）</text></svg><div className={s.traceLegend}><span>原始</span><span>处理后</span><span>虚线：合成意图</span></div><p className={s.caption}>下方色带：深绿闭合，浅绿松开，棕色缺测。切换 {r.switches} 次；遗漏 {r.missSeconds.toFixed(1)} s。这里的“意图”是出题时设定的已知信号，不是真实人体测量。</p><details><summary>原始采样、接口与状态表</summary><div className={s.tableScroll}><table><thead><tr><th>秒</th><th>意图值</th><th>原始收到</th><th>处理后</th><th>状态</th></tr></thead><tbody>{r.points.map(p=><tr key={p.t}><td>{p.t.toFixed(1)}</td><td>{p.ideal.toFixed(2)}</td><td>{p.received===null?'缺测':p.received.toFixed(3)}</td><td>{p.filtered===null?'缺测':p.filtered.toFixed(3)}</td><td>{p.closed?'闭合':'松开'}</td></tr>)}</tbody></table></div></details></>
}
function Report({a}:{a:Workspace}){return <article className={s.report} data-bionics-report><h4>我的信号与机械作品</h4><p>{a.decision||'短体验：两版操作与结果见下方。'}</p><p>边界：{a.boundary||'教学合成信号与理想几何，尚无真实夹持力验证。'}</p><details><summary>固定的配置</summary><pre>{JSON.stringify(a.config,null,2)}</pre></details>{a.sources.length>0&&<p>本人前作来源：{a.sources.map(x=>`${x.project} / ${x.submission}`).join('；')}</p>}{a.runs.map((r,i)=><details key={r.id}><summary>实验 {i+1} · {CASES[r.scenario]} · 窗口 {r.config.window} / 角度 {r.config.angle}°</summary><BionicsPlot run={r}/><p>目标高 {r.width} mm，预测开口 {r.gap.toFixed(1)} mm，几何判断 {r.contact}。</p></details>)}{a.hypothesis&&<p>假设：{a.hypothesis}；探查 {a.probes.join('、')}；修复依据：{a.repair}</p>}{a.frozen&&<div className={s.notice}><h4>事前声明与第一次结果</h4><p>{a.frozen.question}；误闭合上限 {a.frozen.limit} s；冻结于 {a.frozen.at}。</p>{a.frozen.first&&<><p>第一次误闭合 {a.frozen.first.falseSeconds.toFixed(1)} s，{a.frozen.first.falseSeconds<=a.frozen.limit?'达到':'未达到'}原标准。</p><BionicsPlot run={a.frozen.first}/></>}{a.frozen.physical&&<details><summary>固定的第一次实物原始记录</summary><pre>{a.frozen.physical.csv}</pre>{a.frozen.physical.photos.map(p=><figure key={p.id}><img className={s.photo} src={p.data} alt={p.caption}/><figcaption>{p.caption}</figcaption></figure>)}</details>}</div>}{a.physical.revision&&<><h4>本人实物证据</h4><p>{a.physical.material}；{a.physical.dimensions}；接线：{a.physical.wiring}</p><p>试配：{a.physical.before} → 修改：{a.physical.change} → 复测：{a.physical.after}</p><details><summary>本人源文件与测量</summary><pre>{a.physical.source}</pre><pre>{a.physical.csv}</pre></details>{a.physical.photos.map(p=><figure key={p.id}><img className={s.photo} src={p.data} alt={p.caption}/><figcaption>{p.caption}</figcaption></figure>)}<p className={s.caption}>材料由学习者提供；完整性检查不替代真实性与性能的人工评阅。</p></>}</article>}
export function BionicsDelivery({id,a,ready,flush,prototype=false}:{id:string;a:Workspace;ready:boolean;flush:()=>Promise<boolean>;prototype?:boolean}){
 const record=useLearningRecord(bionicsScope(id,prototype?'prototype':'final'),{answers:[]}),items=checks(id,a,prototype),payload=bionicsBody(a),size=new TextEncoder().encode(JSON.stringify(payload)).length,complete=ready&&size<235000&&items.every(x=>x.passed),same=!!record.submittedAt&&canonical(record.body)===canonical(payload),snapshots=record.history.length?record.history:record.submittedAt?[{id:'local',created_at:record.submittedAt,body:record.body}]:[]
 async function submit(){if(record.pending){await record.session.submit();return}if(!complete||!await flush())return;record.session.update(payload);await record.session.submit()}
 return <section className={s.delivery} id={prototype?'digital-prototype':'project-delivery'}><p className={s.eyebrow}>{prototype?'阶段作品':'最终作品'}</p><h3>{prototype?'先保存数字原型':'把作品与证据一起留下'}</h3><ul className={s.checks}>{items.map(x=><li key={x.title} data-pass={x.passed}><span>{x.passed?'已具备':'待补充'}</span>{x.title}</li>)}</ul>{prototype&&<p>数字原型独立保存；正式实物交付仍需要本人制作与测量。</p>}{size>=235000&&<p role="alert">证据超出保存容量，请缩短说明、源文件或降低照片大小后重试。</p>}<button className={s.primary} disabled={!record.ready||record.busy||record.conflict||(!record.pending&&(!complete||same))} onClick={submit}>{record.pending?'重试提交':same?'此版已保存':prototype?'保存数字原型':'提交我的作品'}</button><LearningRecordStatus record={record}/>{snapshots.map(x=><details key={x.id}><summary>已交付版本 · {new Date(x.created_at).toLocaleString()}</summary>{validWorkspace(x.body.artifact)?<Report a={x.body.artifact}/>:<p>此记录格式无法在当前实验台打开。</p>}</details>)}</section>
}
async function photoData(file:File){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>12000000)throw Error('请选择 12 MB 内的 JPG、PNG 或 WebP。');const bmp=await createImageBitmap(file);try{const k=Math.min(1,480/Math.max(bmp.width,bmp.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bmp.width*k);canvas.height=Math.round(bmp.height*k);const ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bmp,0,0,canvas.width,canvas.height);for(const q of [.65,.45,.28,.16]){const data=canvas.toDataURL('image/jpeg',q);if(data.length<=22000)return data}throw Error('请裁剪照片，突出需要说明的装配或测量区域。')}finally{bmp.close()}}
export function BionicsPhysical({a,update,disabled}:{a:Workspace;update:(a:Workspace)=>void;disabled:boolean}){
 const p=a.physical,[busy,setBusy]=useState(false),[message,setMessage]=useState(''),live=useRef({a,disabled});useEffect(()=>{live.current={a,disabled}},[a,disabled]);useEffect(()=>()=>{live.current.disabled=true},[])
 const edit=(patch:Partial<Physical>)=>update({...a,physical:{...p,...patch}}),registered=p.revision===key(a.config)
 async function upload(file:File,kind:'source'|'photo'){setBusy(true);const revision=p.revision;try{if(kind==='source'&&file.size>16000)throw Error('源文件限 16 KB。');const data=kind==='photo'?await photoData(file):await file.text(),current=live.current;if(current.disabled||current.a.physical.revision!==revision||key(current.a.config)!==revision)return;const cp=current.a.physical;update({...current.a,physical:kind==='source'?{...cp,source:data}:{...cp,photos:[...cp.photos,{id:crypto.randomUUID(),data,caption:'',revision}].slice(0,2)}});setMessage('已读入，请补充说明。')}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 return <section className={s.section}><h4>自己的打印与实测</h4><p>先保存旧版，再为当前设计登记一组证据。换参数后需要重新验证；课程封面与示例不能作为本人制作。</p><button disabled={disabled||registered} onClick={()=>update({...a,physical:{...emptyPhysical(),revision:key(a.config)}})}>{registered?'已登记当前设计':'登记当前版本并开始新证据组'}</button><fieldset className={s.fieldset} disabled={disabled||busy||!registered}><div className={s.fields}>{([['material','打印材料与设置','例如：PLA，实际层高、壁数和打印方向'],['dimensions','本人实购与测量尺寸','位置舵机型号、孔距、摇臂及目标尺寸'],['before','试配前现象','哪一处间隙、固定或开口不符合预期？'],['change','本人设计改动','修改了哪个孔、支撑或接触片？'],['after','修改后复测','保持哪些条件不变，观察到什么？'],['wiring','真实接线与停止方法','旋钮、控制板、舵机外部供电和共地']] as const).map(([field,label,hint])=><label key={field}>{label}<input maxLength={500} value={p[field]} placeholder={hint} onChange={e=>edit({[field]:e.target.value})}/></label>)}</div><label>本人修改的 CAD / 程序源 · SCAD、INO、TXT，16 KB 内<input type="file" accept=".scad,.ino,.txt" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void upload(file,'source')}}/></label>{p.source&&<details><summary>已保存的源文件</summary><pre>{p.source}</pre></details>}<label>本人原始测量 CSV · 至少三次<textarea rows={5} maxLength={6000} value={p.csv} placeholder={'angle_deg,gap_mm,target_mm,held_5s\n填写自己的实际角度、开口、目标高度、五秒保持结果 0 或 1'} onChange={e=>edit({csv:e.target.value})}/></label><details><summary>格式例子（不是本人实测）</summary><pre>{'angle_deg,gap_mm,target_mm,held_5s\n20,36,28,0\n28,29,28,0\n30,28,28,1'}</pre><p className={s.caption}>角度是夹指相对水平线向下的实际角；单位 °、mm、mm。保留失败，避免以持续堵转强行夹紧。</p></details>{p.csv&&<p role="status">{(()=>{try{return `格式已识别 ${measurementRows(p.csv).length} 次记录；真实性与性能待人工评阅。`}catch(e){return String(e)}})()}</p>}<label>本人装配与测量照片 · 两张<input type="file" accept="image/png,image/jpeg,image/webp" disabled={p.photos.length>=2} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void upload(f,'photo')}}/></label><div className={s.photoGrid}>{p.photos.map(f=><figure key={f.id}><img className={s.photo} src={f.data} alt={f.caption||'待说明的本人照片'}/><label>这张照片证明什么<input maxLength={240} value={f.caption} placeholder="指出打印改动或测量位置和读数" onChange={e=>edit({photos:p.photos.map(x=>x.id===f.id?{...x,caption:e.target.value}:x)})}/></label><button onClick={()=>edit({photos:p.photos.filter(x=>x.id!==f.id)})}>移除</button></figure>)}</div></fieldset>{message&&<p role="status">{message}</p>}</section>
}
export function BionicsChallenge({a,update,disabled}:{a:Workspace;update:(a:Workspace)=>void;disabled:boolean}){
 const frozen=a.frozen,canFreezePhysical=!!frozen?.first&&!frozen.physical&&key(a.config)===key(frozen.config)&&physicalChecks(a).every(x=>x.passed)
 return <section className={s.section}><h4>先定标准，再见第一次结果</h4><fieldset className={s.fields} disabled={disabled||!!frozen}><label>我的问题、实际物体与停止条件<input maxLength={500} value={a.question} placeholder="固定什么、改变什么、测什么？真实任务何时停止？" onChange={e=>update({...a,question:e.target.value})}/></label><label>事前允许误闭合上限 / 秒<input type="number" min={0} max={3} step={.2} value={a.limit} onChange={e=>update({...a,limit:Math.max(0,Math.min(3,Number(e.target.value)||0))})}/></label><button disabled={a.question.trim().length<15} onClick={()=>update({...a,frozen:{at:new Date().toISOString(),config:{...a.config},question:a.question,limit:a.limit,first:null,physical:null}})}>冻结事前方案</button></fieldset>{frozen&&<><p>事前声明：{frozen.question}；误闭合上限 {frozen.limit} 秒。冻结版本保留，后续为修订。</p><button disabled={disabled||!!frozen.first} onClick={()=>update({...a,frozen:{...frozen,first:simulate(frozen.config,'challenge','unseen',crypto.randomUUID(),new Date().toISOString())}})}>{frozen.first?'第一次数字结果已固定':'打开新工况并固定第一次数字结果'}</button>{frozen.first&&<><p>第一次误闭合 {frozen.first.falseSeconds.toFixed(1)} 秒，{frozen.first.falseSeconds<=frozen.limit?'达到':'未达到'}原标准；目标高 {frozen.first.width} mm，预测开口 {frozen.first.gap.toFixed(1)} mm。</p><BionicsPlot run={frozen.first}/></>}<div className={s.row}><button disabled={disabled||key(a.config)===key(frozen.config)} onClick={()=>update({...a,config:{...frozen.config}})}>恢复冻结配置以完成实物首轮</button><button disabled={disabled||!canFreezePhysical} onClick={()=>update({...a,frozen:{...frozen,physical:structuredClone(a.physical)}})}>{frozen.physical?'首次实物证据已固定':'固定下方本人实物证据为首轮'}</button></div><p className={s.caption}>首轮实物需要在冻结参数下填写完整制作、测量和照片。固定后才开始改进。平台保留记录顺序，不代替独立监考。</p></>}</section>
}
