'use client'
import {useEffect,useMemo,useRef,useState} from 'react'
import * as THREE from 'three'
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js'
import {parts} from '@/lib/project-lines/bionics-geometry'
import {aperture,DEFAULT,type Config,type Mode} from '@/lib/project-lines/bionics-model'
import s from './bionics-workspace.module.css'
const pivotHeight=(c:Config)=>c.gap+8

export function BionicsScene({config:c,mode,closed,time}:{config:Config;mode:Mode;closed:boolean;time:number}){
 const host=useRef<HTMLDivElement>(null),live=useRef({closed,time}),reset=useRef<()=>void>(()=>{}),closeUp=useRef<()=>void>(()=>{}),[fallback,setFallback]=useState(false)
 useEffect(()=>{live.current={closed,time}},[closed,time])
 const geometry=useMemo(()=>({...DEFAULT,finger:c.finger,gap:c.gap,angle:c.angle,bore:c.bore}),[c.finger,c.gap,c.angle,c.bore])
 useEffect(()=>{const c=geometry;if(!host.current)return;const container=host.current;let renderer:THREE.WebGLRenderer;try{if(new URLSearchParams(location.search).get('webgl')==='off')throw Error();renderer=new THREE.WebGLRenderer({antialias:true,alpha:false})}catch{const failed=requestAnimationFrame(()=>setFallback(true));return()=>cancelAnimationFrame(failed)}
  const readyFrame=requestAnimationFrame(()=>setFallback(false));renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;container.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','可旋转、缩放的打印机构三维模型');renderer.domElement.setAttribute('tabindex','0')
  const scene=new THREE.Scene();scene.background=new THREE.Color('#e8e1d3');scene.fog=new THREE.Fog('#e8e1d3',350,720);const camera=new THREE.PerspectiveCamera(38,1,.1,1500);camera.position.set(145,105,150);const control=new OrbitControls(camera,renderer.domElement);control.target.set(0,36,0);control.minDistance=130;control.maxDistance=400;control.maxPolarAngle=Math.PI*.48;control.enablePan=false;control.update();reset.current=()=>{camera.position.set(145,105,150);control.target.set(0,36,0);control.update()};closeUp.current=()=>{camera.position.set(75,105,110);control.target.set(-12,pivotHeight(c),15);control.update()}
  scene.add(new THREE.HemisphereLight(0xfff5df,0x8f9aab,2.8));const sun=new THREE.DirectionalLight(0xffe7c4,3);sun.position.set(-110,190,100);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-150,right:150,top:150,bottom:-150,near:1,far:550});sun.shadow.bias=-.00015;scene.add(sun);const rim=new THREE.DirectionalLight(0xabcce9,1.6);rim.position.set(100,70,-130);scene.add(rim)
  const textureCanvas=document.createElement('canvas');textureCanvas.width=64;textureCanvas.height=64;const ctx=textureCanvas.getContext('2d')!;ctx.fillStyle='#a0a0a0';ctx.fillRect(0,0,64,64);for(let y=0;y<64;y+=4){ctx.fillStyle=y%8?'#888':'#c5c5c5';ctx.fillRect(0,y,64,1)}const texture=new THREE.CanvasTexture(textureCanvas);texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(4,12)
  const printed=new THREE.MeshStandardMaterial({color:'#455059',roughness:.74,bumpMap:texture,bumpScale:.15}),ivory=new THREE.MeshStandardMaterial({color:'#dfdacc',roughness:.72,bumpMap:texture,bumpScale:.12}),copper=new THREE.MeshStandardMaterial({color:'#b55e3c',roughness:.5}),steel=new THREE.MeshStandardMaterial({color:'#7e8991',metalness:.82,roughness:.26}),blue=new THREE.MeshPhysicalMaterial({color:'#214568',roughness:.28,metalness:.12,clearcoat:.5}),pcb=new THREE.MeshStandardMaterial({color:'#315c4c',roughness:.63}),black=new THREE.MeshStandardMaterial({color:'#292b2b',roughness:.63})
  function mesh(g:THREE.BufferGeometry,m:THREE.Material,x=0,y=0,z=0,parent:THREE.Object3D=scene){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
  const box=(x:number,y:number,z:number,w:number,h:number,d:number,m:THREE.Material,parent?:THREE.Object3D)=>mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z,parent)
  function bolt(x:number,y:number,z:number,parent:THREE.Object3D=scene){const o=mesh(new THREE.CylinderGeometry(2.7,2.7,1.8,6),steel,x,y,z,parent);o.rotation.x=Math.PI/2;const slot=box(x,y,z+1,2.3,.45,.2,black,parent);return{o,slot}}
  const floor=mesh(new THREE.PlaneGeometry(1500,1500),new THREE.MeshStandardMaterial({color:'#c9b899',roughness:.96}),0,-1,0);floor.rotation.x=-Math.PI/2
  box(0,3,0,118,6,110,printed);for(const x of [-48,48])for(const z of [-44,44]){mesh(new THREE.CylinderGeometry(4,4,2,24),black,x,0,z);const b=mesh(new THREE.CylinderGeometry(3,3,1.5,6),steel,x,6.5,z);b.rotation.y=.5}
  // 输出轴水平，夹指在竖直面转动；固定承接面位于 y=12。
  const pivotY=12+c.gap,profile=parts(c);for(const z of [-10,10]){const support=profile.find(p=>p.name==='servo-cheek')!.geometry.clone();mesh(support,printed,-25,6,z);box(-25,10,z,36,8,14,ivory);for(const x of [-38,-12])bolt(x,13,z+3)}
  box(-25,pivotY-9,0,24,24,17,blue);box(-25,pivotY-21,0,28,3,22,blue);for(const x of [-35,-15])bolt(x,pivotY-20,13)
  const shaft=mesh(new THREE.CylinderGeometry(5,5,10,40),steel,-25,pivotY,14);shaft.rotation.x=Math.PI/2;const horn=mesh(new THREE.CylinderGeometry(8,8,3,48),ivory,-25,pivotY,20);horn.rotation.x=Math.PI/2
  const moving=new THREE.Group();moving.position.set(-25,pivotY,20);scene.add(moving);const finger=mesh(profile.find(p=>p.name==='moving-finger')!.geometry.clone(),printed,0,0,0,moving);finger.rotation.z=-Math.PI/2;bolt(0,0,6,moving);for(const x of [9,18])bolt(x,0,6,moving);box(c.finger,3.5,2.5,4,7,14,copper,moving)
  // 目标横向范围覆盖该教学模型允许的端点轨迹；公式只估计竖直开口。
  box(21,9,20,50,6,30,ivory);box(21,12+14,20,44,28,24,new THREE.MeshStandardMaterial({color:'#b5a17e',roughness:.98}));for(const x of [0,42])bolt(x,9,36)
  box(-7,10,-32,65,2,30,pcb);for(const x of [-33,18])for(const z of [-43,-21])mesh(new THREE.CylinderGeometry(1.5,1.5,2,16),steel,x,12,z);box(-4,12,-31,14,3,11,black);for(let i=0;i<14;i++){box(-32+i*3.5,13,-45,1,3,2,steel);box(-32+i*3.5,13,-18,1,3,2,steel)}box(-39,12,-33,12,8,10,steel)
  mesh(new THREE.CylinderGeometry(10,10,14,40),black,41,15,-29);mesh(new THREE.CylinderGeometry(8,8,1,40),copper,41,22.5,-29);box(41,23,-33,1,1,6,ivory)
  const ledMat=new THREE.MeshStandardMaterial({color:'#b5cc71',emissive:'#76953a',emissiveIntensity:.7});mesh(new THREE.SphereGeometry(1.7,16,12),ledMat,15,14,-33)
  for(const [i,color] of ['#c06839','#362f2a','#cba856'].entries()){const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(-26+i*2,pivotY-18,-8),new THREE.Vector3(-40-i*2,22,-12),new THREE.Vector3(-22+i*2,15,-24)]);mesh(new THREE.TubeGeometry(curve,30,.65,8,false),new THREE.MeshStandardMaterial({color,roughness:.5}))}
  for(const z of [-10,-4])box(-42,9,z,9,6,3,ivory)
  const gate=new THREE.Group();gate.position.set(-25,12,28);if(mode==='gate'){scene.add(gate);box(25,25,0,50,48,3,ivory,gate);for(const y of [12,30])box(25,y,2,44,2,1,copper,gate);box(50,25,5,4,5,3,steel,gate);moving.visible=false;box(-25,40,28,7,60,9,printed)}
  let frame=0,lost=false;const resize=new ResizeObserver(()=>{const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix()});resize.observe(container)
  const render=()=>{if(lost)return;const goal=live.current.closed?c.angle:0;moving.rotation.z=-goal*Math.PI/180;gate.rotation.y=live.current.closed?-1.25:0;ledMat.emissiveIntensity=live.current.closed?1.7:.15;control.update();renderer.render(scene,camera);frame=requestAnimationFrame(render)};render();const contextLost=(e:Event)=>{e.preventDefault();lost=true;setFallback(true)};renderer.domElement.addEventListener('webglcontextlost',contextLost)
  return()=>{cancelAnimationFrame(readyFrame);cancelAnimationFrame(frame);resize.disconnect();control.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose())}});texture.dispose();profile.forEach(p=>p.geometry.dispose());renderer.dispose();renderer.domElement.remove();reset.current=()=>{}}
 },[geometry,mode])
 return <div className={s.sceneWrap}><div ref={host} className={s.scene} aria-hidden={fallback}/>{fallback&&<div className={s.fallback}><svg viewBox="0 0 480 260" role="img" aria-label="同参数二维机构剖面"><rect width="480" height="260" fill="#e8e1d3"/><path d="M40 220H440M105 218V55" stroke="#535f60" strokeWidth="12"/><rect x="248" y={220-28*3} width="100" height={28*3} fill="#b5a17e"/><path d={`M105 ${220-c.gap*3}L${105+c.finger*3*Math.cos((closed?c.angle:0)*Math.PI/180)} ${220-c.gap*3+c.finger*3*Math.sin((closed?c.angle:0)*Math.PI/180)}`} stroke="#ab593a" strokeWidth="14"/><circle cx="105" cy={220-c.gap*3} r="15" fill="#6a808d"/><text x="30" y="30" fill="#33433f">几何剖面 · {closed?'闭合指令':'松开指令'}</text></svg><p>当前使用二维视图，参数、实验和保存仍可用。</p></div>}<div className={s.sceneBar}><span>{mode==='gate'?'信号门 · 教学模型':'打印夹爪 · 几何示意'} / {closed?'动作已触发':'等待信号'}</span><div className={s.row}><button onClick={()=>closeUp.current()}>近看关节</button><button onClick={()=>reset.current()}>复位视角</button></div></div><p className={s.caption}>拖动旋转，滚轮或双指缩放。目标高 28 mm；闭合开口约 {aperture(c).toFixed(1)} mm。接触片厚度、力与变形需实物验证。</p></div>
}
