"use client"
import {useEffect,useState,useSyncExternalStore} from 'react'
import Image from 'next/image'
import type {SlideTechnicalVisual} from '@/lib/types/api'
import {drawSmilesSvg} from '@/lib/rdkit'
import {BRIEF_KEY,BRIEF_PROPERTIES,DISCOVERY_MILESTONES,DISCOVERY_NOTE,DISCOVERY_ROWS,EMPTY_BRIEF,briefArtifact,briefProblems,discoveryEvidence,discoveryStages,parseBrief,selection,testCandidate,type DiscoveryId,type ProjectBrief} from '@/lib/discovery-brief'
import {ExactEquation,StepControls,useTeachingSteps,downloadEvidence} from './screening-common'
import './discovery-brief.css'

export const DISCOVERY_IMAGE='/slide-assets/molecule-monster-hunter/M01/virtual-to-experiment-v1.webp'
function readSaved(){try{return window.localStorage.getItem(BRIEF_KEY)}catch{return null}}
function subscribeSaved(callback:()=>void){window.addEventListener('storage',callback);window.addEventListener('m01-brief-saved',callback);return()=>{window.removeEventListener('storage',callback);window.removeEventListener('m01-brief-saved',callback)}}
function useSavedBrief(){return parseBrief(useSyncExternalStore(subscribeSaved,readSaved,()=>null))}
function Structure(){
  const [svg,setSvg]=useState('')
  useEffect(()=>{let active=true;drawSmilesSvg('CCO',{width:440,height:160}).then(s=>{if(active)setSvg(s)}).catch(()=>{});return()=>{active=false}},[])
  return <figure className="db-structure">{svg?<div dangerouslySetInnerHTML={{__html:svg}}/>:<code>结构写法：CCO</code>}<figcaption>乙醇 · 仅演示“结构怎样表示”<code>SMILES: CCO · RDKit 二维结构，不是预测结果</code></figcaption></figure>
}
function CandidateGrid({visible,reveal=false}:{visible:readonly {id:DiscoveryId;score:number;hit:boolean}[];reveal?:boolean}){
  return <ol className="db-grid" aria-label="12 条候选的当前状态">{DISCOVERY_ROWS.map(r=>{const kept=visible.some(v=>v.id===r.id);return <li key={r.id} data-kept={kept}><b>{r.id}</b><span>排序分 {r.score}</span><small>{!kept?'本步未保留':reveal?(r.hit?'通过本例测试':'未通过本例测试'):'候选 · 未验证'}</small></li>})}</ol>
}
function Funnel(){const states=discoveryStages(),steps=useTeachingSteps(states.length),current=states[steps.step];return <><StepControls steps={steps} count={states.length} label="筛选流程"/><div className="db-counts">{states.map((s,i)=><button key={s.title} aria-pressed={i===steps.step} onClick={()=>steps.jump(i)}><b>{s.rows.length}</b><span>{s.title}</span></button>)}</div><div className="db-two"><CandidateGrid visible={current.rows} reveal={steps.step===4}/><section className="db-card"><p className="db-eyebrow">步骤 {steps.step+1} / 5</p><h3>{current.title}</h3><p>{current.note}</p><ExactEquation source={`N_{\\mathrm{kept}}=${current.rows.length},\\quad N_{\\mathrm{not\\ kept}}=${12-current.rows.length}`}/><p className="db-note">灰色 ID 仍留在图中，方便追查。没有优先测 ≠ 已证明无效。</p>{steps.step===4&&<table><thead><tr><th>ID / 分数</th><th>构造结果</th></tr></thead><tbody>{current.rows.map(r=><tr key={r.id}><td>{r.id} / {r.score}</td><td>{r.hit?'通过本例测试':'未通过本例测试'}</td></tr>)}</tbody></table>}</section></div></>}
function Budget(){
 const [keep,setKeep]=useState(8),[tested,setTested]=useState<DiscoveryId[]>([]),[note,setNote]=useState('先缩小范围，再点一个候选花费一次预算。'),evidence=discoveryEvidence(tested,keep)
 const run=(id:DiscoveryId)=>{const next=testCandidate(tested,id,keep);setTested(next.tested);setNote(next.reason)}
 return <><div className="db-controls"><label>保留前 {keep} 个<input aria-label="保留候选数量" type="range" min="1" max="12" value={keep} onChange={e=>setKeep(Number(e.target.value))}/></label><strong>剩余预算 {evidence.remaining} / 5</strong><button onClick={()=>{setKeep(8);setTested([]);setNote('实验台已重置。')}}>重置实验台</button></div><div className="db-two"><section><h3>点击候选，揭晓一条教学记录</h3><div className="db-test-grid">{selection(keep).map(r=><button key={r.id} disabled={tested.includes(r.id)||tested.length===5} onClick={()=>run(r.id)}><b>{r.id}</b><span>排序分 {r.score}</span><small>{tested.includes(r.id)?(r.hit?'通过本例测试':'未通过本例测试'):'消耗 1 次 · 揭晓'}</small></button>)}</div><p className="db-note" role="status">{note}</p><p className="db-small">改变保留数量不会退还预算，也不会抹去已经得到的记录。分数低的候选也可能被漏掉。</p></section><section className="db-card"><h3>证据日志 · 已花 {evidence.spent} 次</h3><table><thead><tr><th>ID</th><th>分数</th><th>构造结果</th></tr></thead><tbody>{evidence.tested.length?evidence.tested.map(r=><tr key={r.id}><td>{r.id}</td><td>{r.score}</td><td>{r.result}</td></tr>):<tr><td colSpan={3}>尚未测试；所有结果保持未知。</td></tr>}</tbody></table><p>未测记录：{evidence.untested.length} 条，不能算作通过或失败。</p><button onClick={()=>downloadEvidence('M01-teaching-test-log.json',evidence)}>下载这次教学日志</button><p className="db-small">没有“猜中几个就算发现新药”的通关目标。评价的是记录是否诚实、预算是否守恒。</p></section></div></>
}
function BriefPreview({brief}:{brief:ProjectBrief}){return <dl className="db-fields"><dt>研究问题</dt><dd>{brief.question||'尚未填写'}</dd><dt>交付物</dt><dd>{brief.deliverable||'尚未填写'}</dd><dt>预测 / 检查</dt><dd>{brief.properties.join('；')||'尚未选择'}</dd><dt>诚实边界</dt><dd>{brief.honesty?'已确认：预测不替代实验，也不是医疗建议。':'尚未确认'}</dd></dl>}
function BriefEditor(){
 const [brief,setBrief]=useState<ProjectBrief>(EMPTY_BRIEF),[message,setMessage]=useState('修改字段后，下方卡片预览实时更新。'),[clearPending,setClearPending]=useState(false),problems=briefProblems(brief)
 useEffect(()=>{const timer=window.setTimeout(()=>{const saved=parseBrief(readSaved());if(saved){setBrief(saved);setMessage('已恢复本机保存的立项卡。')}},0);return()=>window.clearTimeout(timer)},[])
 const save=(download=false)=>{const gaps=briefProblems(brief);if(gaps.length){setMessage('尚需：'+gaps.join('；'));return}const data=briefArtifact(brief);try{window.localStorage.setItem(BRIEF_KEY,JSON.stringify(data));window.dispatchEvent(new Event('m01-brief-saved'));setMessage('已保存到当前浏览器；没有上传服务器。建议同时下载备份。')}catch{setMessage('浏览器不允许本地保存；请下载 JSON 备份。')}if(download)downloadEvidence('M01-my-project-brief.json',data)}
 const clear=()=>{if(!clearPending){setClearPending(true);setMessage('确定清除本机卡片吗？请先下载备份，再次点击确认。');return}try{window.localStorage.removeItem(BRIEF_KEY);window.dispatchEvent(new Event('m01-brief-saved'));setBrief(EMPTY_BRIEF);setClearPending(false);setMessage('本机卡片已清除；下载的备份不受影响。')}catch{setMessage('本机存储不可访问；未清除。')}}
 return <div className="db-two"><section className="db-form"><label>1 · 研究问题<textarea aria-label="研究问题" maxLength={200} value={brief.question} placeholder="例如：在给定数据集里，怎样优先找到值得继续研究的候选？" onChange={e=>setBrief({...brief,question:e.target.value})}/></label><label>2 · 最后交出什么<textarea aria-label="交付物" maxLength={200} value={brief.deliverable} placeholder="例如：输入 SMILES 的工作台 + 带理由与局限的候选报告" onChange={e=>setBrief({...brief,deliverable:e.target.value})}/></label><fieldset><legend>3 · 让电脑预测 / 检查什么？</legend>{BRIEF_PROPERTIES.map(x=><label key={x} className="db-check"><input type="checkbox" checked={brief.properties.includes(x)} onChange={e=>setBrief({...brief,properties:e.target.checked?[...brief.properties,x]:brief.properties.filter(v=>v!==x)})}/>{x}</label>)}</fieldset><label className="db-check"><input type="checkbox" checked={brief.honesty} onChange={e=>setBrief({...brief,honesty:e.target.checked})}/>我确认：预测不是实验事实，也不是医疗建议。</label></section><section className="db-card"><p className="db-eyebrow">我的第一件项目成果</p><h3>项目立项卡 · 实时预览</h3><BriefPreview brief={brief}/><p className="db-small">不填写个人健康经历、姓名或手机号。内容只保存在本机；换设备请使用下载备份。</p><div className="db-controls"><button onClick={()=>save()}>保存到本机</button><button onClick={()=>save(true)}>保存并下载立项卡</button><button onClick={clear}>{clearPending?"确认清除本机卡片":"清除本机卡片"}</button></div><p role="status">{message}</p><p className="db-small">{problems.length?`还缺 ${problems.length} 项`:'四项已齐，可保存交付'} · 本页不会自动替你完成整门课程。</p></section></div>
}
function Handoff(){const saved=useSavedBrief();return <div className="db-two"><section className="db-card"><h3>{saved?'已找到本机立项卡':'本机还没有保存立项卡'}</h3>{saved?<BriefPreview brief={saved}/>:<p>返回第 7 页填写并保存。这里不把默认示例当作你的成果。</p>}<p className="db-note">立项卡是目标，不是模型成绩。下一步拿它去核对工具和数据是否服务于同一个研究问题。</p></section><section><h3>下一站 M02 · 先验证工具可用</h3><ol className="db-route"><li><b>输入</b><span>这张立项卡：目标、输出与预测任务</span></li><li><b>操作</b><span>按照 M02 模板安装 / 导入 RDKit</span></li><li><b>留下证据</b><span>记录你实际运行得到的版本号和日志</span></li></ol><p className="db-note">这里没有执行安装，也没有伪造版本号。后面的结构图、特征表都需要这个工具基础。</p>{saved&&<button onClick={()=>downloadEvidence('M01-my-project-brief.json',briefArtifact(saved))}>再次下载已保存的卡片</button>}</section></div>}
export function DiscoveryBriefVisual({visual}:{visual:Extract<SlideTechnicalVisual,{renderer:'discovery-brief'}>}){
 const [role,setRole]=useState(0),[milestone,setMilestone]=useState(0),[revealed,setRevealed]=useState(false)
 let body:React.ReactNode=null
 switch(visual.scene){
 case 'overview':body=<><figure className="db-overview" data-medium="generated-raster"><Image src={DISCOVERY_IMAGE} alt="虚拟记录先在电脑中缩成候选短名单，再交由实验设备验证；示意图，不是真实实验记录" width={1600} height={900} loading="eager" unoptimized/><figcaption>生成教学插图 · 图中数量仅示意，不代表本节数据规模或已完成的实验。</figcaption></figure><div className="db-three">{[['01 · 电脑筛选','处理结构记录，比较和排序'],['02 · 候选报告','保留理由、局限和待查问题'],['03 · 后续验证','研究人员收集实验等证据']].map(([t,d])=><section key={t}><h3>{t}</h3><p>{d}</p></section>)}</div><p className="db-note">今天先交一张立项卡，不合成、不服用、不验证药物。课程最终产物是软件工作台和诚实报告。</p></>;break
 case 'roles':{const roles=[['研究问题 / 靶点','先定义想研究的过程或对象，而不是把某个蛋白天生叫成坏蛋。','交给后续：明确的任务和适用范围；不会仅靠外形判断好坏。'],['候选 / 输入','每个候选要有可追查的 ID 和结构写法。','右侧用乙醇演示表示方法，没有给它编造药效或毒性分。'],['模型 / 预测','在特定数据和任务上训练，输出该任务的预测。','它不是同时回答所有医学问题的万能打分器；还要检查数据和评估。']];body=<div className="db-two"><section><div className="db-controls">{roles.map((r,i)=><button key={r[0]} onClick={()=>setRole(i)} aria-pressed={role===i}>{r[0]}</button>)}</div><div className="db-card"><p className="db-eyebrow">当前角色 {role+1} / 3</p><h3>{roles[role][0]}</h3><p>{roles[role][1]}</p><p className="db-note">{roles[role][2]}</p></div></section><section><Structure/><dl className="db-fields"><dt>例子 ID</dt><dd>example-ethanol</dd><dt>结构输入</dt><dd>CCO</dd><dt>预测状态</dt><dd>本页没有调用训练模型</dd></dl></section></div>;break}
 case 'roadmap':{const m=DISCOVERY_MILESTONES[milestone];body=<div className="db-two"><nav className="db-milestones" aria-label="五件最终成果">{DISCOVERY_MILESTONES.map((x,i)=><button key={x.name} aria-pressed={i===milestone} onClick={()=>setMilestone(i)}><b>{String(i+1).padStart(2,'0')}</b><span>{x.name}</span><small>{i?'使用上一阶段的产物':'从立项卡定义的数据开始'}</small></button>)}</nav><section className="db-card"><p className="db-eyebrow">产物之间有接口，不是五次打勾</p><h3>{m.name}</h3><dl className="db-fields"><dt>接收</dt><dd>{m.input}</dd><dt>交出去</dt><dd>{m.output}</dd><dt>示例文件</dt><dd><code>{m.file}</code></dd></dl><p className="db-note">Top10 是最多十个候选，不需要为了凑数把不合格项塞进去。最终交的是可以复查的依据。</p></section></div>;break}
 case 'honesty':body=<><div className="db-controls"><button onClick={()=>setRevealed(v=>!v)}>{revealed?'收起教学结果':'揭晓教学结果'}</button><span>改变的是证据状态，不是模型原来的分数。</span></div><table><thead><tr><th>教学候选</th><th>原排序分（非概率）</th><th>构造验证结果</th><th>现在能说什么？</th></tr></thead><tbody>{[DISCOVERY_ROWS[0],DISCOVERY_ROWS[2],DISCOVERY_ROWS[8]].map(r=><tr key={r.id}><th>{r.id}</th><td><meter aria-label={`${r.id} 排序分`} min="0" max="100" value={r.score}/>{r.score}</td><td>{revealed?(r.hit?'通过本例测试':'未通过本例测试'):'未知 · 尚未揭晓'}</td><td>{!revealed?'安排优先级，不能宣称有效':r.hit?'只有本例测试记录，不是已证明成药':'高分也会失败，不能跳过验证'}</td></tr>)}</tbody></table><p className="db-note">{revealed?'A 得 92 分却失败；I 只有 51 分却通过构造测试。少测一些会减少成本，也可能漏掉候选。':'先作出判断：只看排序分，你知道这三个候选的验证结果吗？点击按钮，再核对你的判断。'} 这里没有把分数 92 解释成 92% 治疗成功率。</p></>;break
 case 'funnel':body=<Funnel/>;break
 case 'budget':body=<Budget/>;break
 case 'brief':body=<BriefEditor/>;break
 case 'handoff':body=<Handoff/>;break
 }
 return <div className="db" data-renderer="discovery-brief" data-scene={visual.scene}>{body}<footer>{DISCOVERY_NOTE} <a href="https://www.fda.gov/patients/drug-development-process/step-1-discovery-and-development" target="_blank" rel="noreferrer">进一步研究与实验依据：FDA</a></footer></div>
}
