"use client"

import { useState } from "react"
import type { SlideTechnicalVisual } from "@/lib/types/api"
import { DIVERSITY_POOL as P, DEFAULT_DIVERSITY, pickDiverse, similarity, diversitySummary, diversityEvidence, nextDiversityCandidates } from "@/lib/diversity-evidence"
import { RULES, REJECT_ROWS, DEFAULT_RULE_ORDER, rejectionTrace, rejectionEvidence } from "@/lib/rejection-evidence"
import { ExactEquation, EvidenceNote, StepControls, useTeachingSteps, downloadEvidence } from "./screening-common"
import "./diversity-rejection.css"

const f = (n: number) => n.toFixed(3)
function Panel({ title, children }: {title:string;children:React.ReactNode}) { return <section className="dr-panel"><h3>{title}</h3>{children}</section> }
function Structure({ id, scaffold = false, compact = false }: {id:string;scaffold?:boolean;compact?:boolean}) {
  const row = P.rows.find(r => r.id === id)!
  return <figure className={`dr-structure ${compact ? "compact" : ""}`}><div role="img" aria-label={`${row.name}的${scaffold ? "Murcko 骨架" : "二维结构"}`} dangerouslySetInnerHTML={{__html:scaffold ? row.scaffoldSvg : row.svg}} /><figcaption><strong>{row.id} · {row.name}</strong><span>{scaffold ? row.scaffold : row.smiles}</span></figcaption></figure>
}
function Structures({ids}:{ids:string[]}) { return <div className="dr-structures">{ids.map(id=><Structure key={id} id={id} compact />)}</div> }
function List({ids}:{ids:string[]}) { return <table><thead><tr><th>次序 / ID</th><th>结构示例</th><th>教学分</th><th>骨架 SMILES</th></tr></thead><tbody>{ids.map((id,i)=>{const r=P.rows.find(x=>x.id===id)!;return <tr key={id}><td>{i+1} · {id}</td><td>{r.name}</td><td>{r.score.toFixed(2)}</td><td><code>{r.scaffold}</code></td></tr>})}</tbody></table> }
function Stats({ids,label}:{ids:string[];label:string}) {const s=diversitySummary(ids);return <div className="dr-stats" aria-label={label}><span>{label}<strong>{s.count} 个</strong></span><span>不同骨架<strong>{s.scaffolds}</strong></span><span>平均教学分<strong>{f(s.meanScore)}</strong></span><span>最大两两 T<strong>{s.maxPairT===null ? "—" : f(s.maxPairT)}</strong></span></div>}
function PairInspector() {
  const [left,setLeft]=useState("D02"),[right,setRight]=useState("D03"),[scaffold,setScaffold]=useState(false)
  const a=P.rows.find(r=>r.id===left)!,b=P.rows.find(r=>r.id===right)!
  const common=a.bits.filter(x=>b.bits.includes(x)).length,union=new Set([...a.bits,...b.bits]).size
  return <><div className="se-controls"><label>结构 A <select aria-label="结构 A" value={left} onChange={e=>setLeft(e.target.value)}>{P.rows.map(r=><option key={r.id} value={r.id}>{r.id} {r.name}</option>)}</select></label><label>结构 B <select aria-label="结构 B" value={right} onChange={e=>setRight(e.target.value)}>{P.rows.map(r=><option key={r.id} value={r.id}>{r.id} {r.name}</option>)}</select></label><button type="button" onClick={()=>setScaffold(x=>!x)}>{scaffold ? "显示完整结构" : "提取骨架对比"}</button></div><div className="se-grid"><Structure id={left} scaffold={scaffold}/><Structure id={right} scaffold={scaffold}/></div><ExactEquation source={String.raw`T(A,B)=\frac{|A\cap B|}{|A\cup B|}=\frac{${common}}{${union}}\approx${f(similarity(left,right))}`} /><div className="dr-comparison"><span>A 开启位：{a.bits.length}</span><span>B 开启位：{b.bits.length}</span><strong>骨架 {a.scaffold===b.scaffold ? "相同" : "不同"}</strong></div><p>同骨架不等于相同指纹；指纹相似度也不是实验性质相同的保证。这里比较连接关系，不推断三维构象。</p></>
}
function Matrix() {
  const [pair,setPair]=useState<[string,string]>(["D02","D03"])
  const ids=P.rows.slice(0,10).map(r=>r.id)
  return <><div className="se-grid"><Panel title="Top10 的两两相似度"><table className="dr-matrix"><thead><tr><th>T</th>{ids.map(id=><th key={id}>{id.slice(1)}</th>)}</tr></thead><tbody>{ids.map(a=><tr key={a}><th>{a}</th>{ids.map(b=><td key={b}><button type="button" aria-label={`比较 ${a} 与 ${b}`} onClick={()=>setPair([a,b])} style={{background:`rgba(174,95,64,${.06+.55*similarity(a,b)})`}}>{similarity(a,b).toFixed(2)}</button></td>)}</tr>)}</tbody></table><p>横纵轴都是候选 ID。深色表示 T 较高；对角线是自己和自己。</p></Panel><Panel title={`${pair[0]} × ${pair[1]} · T = ${f(similarity(...pair))}`}><div className="se-grid"><Structure id={pair[0]}/><Structure id={pair[1]}/></div><p>点击矩阵格子，核对对应结构。这里只展示前十名，候选池实际有 16 个。</p></Panel></div></>
}
function DiversityTrace() {
  const result=pickDiverse(),steps=useTeachingSteps(result.trace.length)
  const trace=result.trace[steps.step],selected=result.selected.slice(0,steps.step+1)
  return <><StepControls steps={steps} count={result.trace.length} label="MaxMin 逐轮挑选"/><Stats ids={selected} label="本轮已选"/><div className="se-grid"><Panel title={`本轮加入 ${trace.chosen}`}><Structure id={trace.chosen}/><p>{trace.maxT===null ? "第一步保留教学分最高的 D01 作为种子。" : `与已有集合最像的是 ${trace.nearestId}，T=${f(trace.maxT)}，最近距离=${f(1-trace.maxT)}。`}</p></Panel><Panel title="本轮比较依据"><table><thead><tr><th>候选</th><th>最大 T</th><th>最小距离</th><th>决定</th></tr></thead><tbody>{trace.candidates.slice(0,6).map(r=><tr key={r.id}><td>{r.id}</td><td>{f(r.maxT)}</td><td>{f(r.minDistance)}</td><td>{r.id===trace.chosen ? "本轮加入" : "继续候选"}</td></tr>)}</tbody></table>{steps.step===0 && <p>还没有距离比较；下一步将对余下 15 个结构计算到种子的距离。</p>}<p>当前集合：{selected.join(" → ")}</p></Panel></div><EvidenceNote>每轮比较的是到全部已选者的最近距离，不只比较榜首。同距按教学分高者、再按 ID 升序；这是一种确定性的贪心策略。</EvidenceNote></>
}
function DiversityLab() {
  const [options,setOptions]=useState(DEFAULT_DIVERSITY),[note,setNote]=useState("")
  const r=pickDiverse(options),before=P.rows.slice(0,options.count).map(r=>r.id)
  return <><div className="se-grid"><Panel title="保持 16 个候选不变，改变选择约束"><label>目标数量：<output>{options.count}</output><input type="range" aria-label="目标数量" min="2" max="10" value={options.count} onChange={e=>setOptions({...options,count:Number(e.target.value)})}/></label><label>允许的最大相似度：<output>{options.maxSimilarity.toFixed(2)}</output><input type="range" aria-label="允许的最大相似度" min="0" max="1" step=".05" value={options.maxSimilarity} onChange={e=>setOptions({...options,maxSimilarity:Number(e.target.value)})}/></label><label className="dr-check"><input type="checkbox" checked={options.uniqueScaffold} onChange={e=>setOptions({...options,uniqueScaffold:e.target.checked})}/>额外要求每个骨架最多一个</label><button type="button" onClick={()=>setOptions(DEFAULT_DIVERSITY)}>重置默认条件</button><p>默认 T≤1、不限制骨架，就是普通 MaxMin。两个约束是本课程显式增加的规则。</p><label>我的选择理由<textarea aria-label="我的多样性选择理由" value={note} onChange={e=>setNote(e.target.value)} placeholder="记录你改变了哪个约束，实际得到几个候选。"/></label><button type="button" disabled={note.trim().length<5} onClick={()=>downloadEvidence("M45-my-diversity.json",diversityEvidence(options,note.trim()))}>下载我的多样性证据</button></Panel><Panel title={`实际选出 ${r.selected.length} / ${r.requested}`}><Stats ids={r.selected} label="新名单"/><List ids={r.selected}/><p role="status">{r.complete ? "已达到目标数量。" : "当前约束下不能继续补位，保留实际数量，不强行凑满。"}</p></Panel></div><Stats ids={before} label="同数量的分数基线"/><EvidenceNote>池中只有 9 个不同骨架，所以勾选骨架唯一时无法选满 10 个。结构覆盖增加不保证实验成功；分数是固定的教学构造值。</EvidenceNote></>
}
export function DiversityVisual({visual}:{visual:Extract<SlideTechnicalVisual,{renderer:"diversity-evidence"}>}) {
  const [mode,setMode]=useState(false),[note,setNote]=useState("")
  const baseline=P.rows.slice(0,10).map(r=>r.id),r=pickDiverse({...DEFAULT_DIVERSITY,uniqueScaffold:mode})
  let body:React.ReactNode
  switch(visual.scene) {
    case "overview": body=<><Stats ids={baseline} label="按分数取 Top10"/><div className="se-grid"><Panel title="分数靠前，不代表结构覆盖充分"><Structures ids={baseline.slice(0,4)}/><p>这是独立的 16 结构教学池，不把 M44 的合成 ID 当成真实分子。先验证 SMILES，再计算指纹与骨架。</p></Panel><Panel title="增加结构比较后"><Structures ids={r.selected.slice(0,4)}/><p>候选结构没有改变，改变的是名单的选择顺序。后面逐轮核对每次选择的依据。</p></Panel></div><Stats ids={r.selected} label="普通 MaxMin"/></>;break
    case "concentration": body=<><Panel title="看结构与骨架，不只看分数"><Structures ids={baseline}/></Panel><Stats ids={baseline} label="原始 Top10"/><EvidenceNote>前 8 个结构具有相同的苯环 Murcko 骨架。它们并不是同一个分子，侧基差异可能带来重要的性质差异，不能用一个实验替代全部实验。</EvidenceNote></>;break
    case "tradeoff": body=<><div className="se-controls"><button type="button" onClick={()=>setMode(x=>!x)}>{mode ? "取消骨架唯一限制" : "增加骨架唯一限制"}</button></div><div className="se-grid"><Panel title="分数基线"><List ids={baseline}/></Panel><Panel title="多样性选择"><List ids={r.selected}/></Panel></div><Stats ids={r.selected} label="当前结果"/><EvidenceNote>分数仍保持原值。换出不代表质量差；结构多样性与分数是两种评价角度，具体策略会产生取舍，不保证两者同时提升。</EvidenceNote></>;break
    case "fingerprint": body=<Matrix/>;break
    case "scaffold": body=<PairInspector/>;break
    case "maxmin": {const candidates=nextDiversityCandidates(["D01","D11"],DEFAULT_DIVERSITY);body=<><ExactEquation source={String.raw`d(x,s)=1-T(x,s),\qquad x^*=\arg\max_{x\notin S}\min_{s\in S}d(x,s)`}/><div className="se-grid"><Panel title="已选集合 S = {D01, D11}"><Structures ids={["D01","D11"]}/><p>先看每个候选离谁最近，再在这些最近距离中挑最大的一个。</p></Panel><Panel title="下一轮的可复核比较"><table><thead><tr><th>候选</th><th>T 对 D01</th><th>T 对 D11</th><th>最近距离</th></tr></thead><tbody>{candidates.slice(0,7).map(x=><tr key={x.id}><td>{x.id}</td><td>{f(similarity(x.id,"D01"))}</td><td>{f(similarity(x.id,"D11"))}</td><td>{f(x.minDistance)}</td></tr>)}</tbody></table><p>按同距规则，本例下一位：<strong>{candidates[0].id}</strong>。</p></Panel></div><EvidenceNote>公式解释贪心选择，不是全局最优证明。只从 10 个候选中选 10 个，不可能换入新的结构，补位必须提供更大候选池。</EvidenceNote></>};break
    case "trace": body=<DiversityTrace/>;break
    case "lab": body=<DiversityLab/>;break
    case "code": body=<><div className="se-grid"><Panel title="Python / RDKit 可复现方法"><pre>{`from rdkit import Chem\nfrom rdkit.Chem import rdFingerprintGenerator\nfrom rdkit.SimDivFilters.rdSimDivPickers import MaxMinPicker\n\nmols = [Chem.MolFromSmiles(s) for s in smiles_list]\nassert all(m is not None for m in mols)\ng = rdFingerprintGenerator.GetMorganGenerator(\n    radius=2, fpSize=2048)\nfps = [g.GetFingerprint(m) for m in mols]\n# 输入已按教学分降序；显式固定榜首\nidx = list(MaxMinPicker().LazyBitVectorPick(\n    fps, len(fps), 10, firstPicks=[0], seed=88))`}</pre></Panel><Panel title="三个必须明确的约定"><table><tbody><tr><th>候选池</th><td>16 个，不是只给 10 个再选 10 个</td></tr><tr><th>种子</th><td>firstPicks=[0]；不依赖随机首选</td></tr><tr><th>指纹</th><td>Morgan 半径 2，2048 位，不使用手绘指纹</td></tr><tr><th>阈值</th><td>普通接口没有相似度阈值参数；带阈值接口使用距离</td></tr></tbody></table><ExactEquation source={String.raw`d_{\min}=1-T_{\max}`}/><p>这是可在安装 RDKit 的 Python 环境运行的模板。当前页面由 TypeScript 重算；等距离的选法可能与 RDKit 内部次序不同。</p></Panel></div></>;break
    case "report": body=<><div className="se-grid"><Panel title="原分数榜单"><List ids={baseline}/></Panel><Panel title="默认 MaxMin 结果"><List ids={r.selected}/></Panel></div><label>我的对比结论<textarea aria-label="我的榜单对比结论" value={note} onChange={e=>setNote(e.target.value)} placeholder="选一个换出的 ID，说明排名分没变，为什么名单选择改变。"/></label><button type="button" disabled={note.trim().length<5} onClick={()=>downloadEvidence("M45-default-comparison.json",diversityEvidence(DEFAULT_DIVERSITY,note.trim()))}>下载本页对比记录</button><p>个性化参数结果在第 8 页导出；本页明确为默认条件。</p></>;break
    case "handoff": body=<><Stats ids={r.selected} label="候选选择证据"/><div className="se-grid"><Panel title="M45 交付的四层记录"><table><tbody><tr><th>身份</th><td>SMILES、候选 ID、教学分</td></tr><tr><th>结构证据</th><td>指纹设置、骨架、两两 T</td></tr><tr><th>选择政策</th><td>种子、数量、阈值、同距与补位策略</td></tr><tr><th>实际输出</th><td>选中 ID、每轮理由、未凑满时的实际数量</td></tr></tbody></table></Panel><Panel title="接续 M46：解释未进入名单的原因"><Structures ids={r.selected.slice(0,2)}/><p>区分三种情况：没有通过硬规则、通过但排名靠后、因结构覆盖策略未选中。不要把它们都叫作“分子不好”。</p></Panel></div><EvidenceNote>当前教学流程帮助理解候选选择，不能据此决定真实药物安全、疗效或实验执行。</EvidenceNote></>;break
  }
  return <div className="se dr" data-renderer="diversity-evidence" data-scene={visual.scene}>{body}<footer>{P.provenance} · RDKit {P.rdkit} · Morgan r=2 / 2048 bit；结构与矩阵为本地计算，非生成图片。</footer></div>
}

function RejectTable({index,order=DEFAULT_RULE_ORDER,visible=4,audit=false}:{index:number;order?:typeof DEFAULT_RULE_ORDER;visible?:number;audit?:boolean}) {
  const r=rejectionTrace(REJECT_ROWS[index],order,audit)
  return <table><thead><tr><th>顺序 / 规则</th><th>输入值</th><th>通过条件</th><th>本次执行状态</th></tr></thead><tbody>{r.checks.map((c,i)=><tr key={c.key} className={i<visible ? `dr-${c.status}` : ""}><td>{i+1} · {c.label}</td><td>{c.value??"缺失"} {c.unit}</td><td>≤ {c.limit} {c.unit}</td><td>{i>=visible ? "尚未执行" : ({pass:"通过",fail:audit ? "未通过 · 继续诊断" : "未通过 · 停止",missing:"缺数据 · 暂缓","not-evaluated":"短路后未执行"}[c.status])}</td></tr>)}</tbody></table>
}
function RowPicker({index,setIndex}:{index:number;setIndex:(n:number)=>void}) {return <div className="se-controls">{REJECT_ROWS.map((r,i)=><button type="button" className="secondary" key={r.id} aria-pressed={i===index} onClick={()=>setIndex(i)}>候选 {r.id}</button>)}</div>}
function RejectWalk({lab=false}:{lab?:boolean}) {
  const [index,setIndex]=useState(1),steps=useTeachingSteps(5),[note,setNote]=useState("")
  const trace=rejectionTrace(REJECT_ROWS[index]),reached=trace.checks.findIndex(c=>c.status==="fail"||c.status==="missing")
  const complete=steps.step >= (reached<0 ? 4 : reached+1)
  return <><RowPicker index={index} setIndex={n=>{setIndex(n);steps.reset();setNote("")}}/><StepControls steps={steps} count={5} label="顺序检查"/><RejectTable index={index} visible={steps.step}/><div className="dr-output" role="status"><strong>候选 {trace.id} 的执行记录</strong><p>{complete ? trace.reason : "按照规则顺序检查；还不能提前生成拒绝理由。"}</p></div>{lab && <><label>我为什么只报告这一步？<textarea aria-label="我的拒绝理由解释" value={note} onChange={e=>setNote(e.target.value)}/></label><button type="button" disabled={!complete||note.trim().length<5} onClick={()=>downloadEvidence("M46-my-trace.json",{row:REJECT_ROWS[index],...trace,learnerExplanation:note.trim()})}>下载我的检查记录</button></>}<EvidenceNote>A 有多项越界；B 先通过分子量再卡在 logP；E 正好等于四个上限，按本例 ≤ 条件全部通过；F 缺少 logP，结果是暂缓，不伪装成通过或实验失败。</EvidenceNote></>
}
export function RejectionVisual({visual}:{visual:Extract<SlideTechnicalVisual,{renderer:"rejection-evidence"}>}) {
  const [index,setIndex]=useState(0),[reverse,setReverse]=useState(false),[audit,setAudit]=useState(false),[note,setNote]=useState("")
  const order=reverse ? ["logp","mw","hbd","hba"] as typeof DEFAULT_RULE_ORDER : DEFAULT_RULE_ORDER
  const trace=rejectionTrace(REJECT_ROWS[index],order,audit),steps=useTeachingSteps(4)
  const results=REJECT_ROWS.map(row=>rejectionTrace(row,order))
  let body:React.ReactNode
  switch(visual.scene) {
    case "overview": body=<><div className="se-grid"><Panel title="输入：候选字段和本次政策"><RejectTable index={0}/></Panel><Panel title="输出：可以复核的结构化理由"><div className="dr-output"><strong>A · 未通过</strong><p>{trace.reason}</p></div><table><tbody><tr><th>规则版本</th><td>rejection-v1 / MW→logP→HBD→HBA</td></tr><tr><th>数值比较</th><td>612 &gt; 500 g/mol</td></tr><tr><th>超出</th><td>112 g/mol</td></tr><tr><th>后续</th><td>未执行，不等于通过</td></tr></tbody></table></Panel></div><EvidenceNote>解释的是本次规则执行，不是证明分子天生“不好”。本节扩展原文六行示例；不冒用 M43 的候选身份。</EvidenceNote></>;break
    case "transparent": body=<><div className="se-grid"><Panel title="只有结论时，证据丢在哪里？"><table><thead><tr><th>ID</th><th>结果</th><th>可复核？</th></tr></thead><tbody>{results.slice(0,4).map(r=><tr key={r.id}><td>{r.id}</td><td>未通过</td><td>缺规则、值和阈值</td></tr>)}</tbody></table></Panel><Panel title="补上同一批的执行证据"><table><thead><tr><th>ID</th><th>第一处失败</th><th>具体比较</th></tr></thead><tbody>{results.slice(0,4).map(r=>{const c=r.checks.find(c=>c.status==="fail")!;return <tr key={r.id}><td>{r.id}</td><td>{c.label}</td><td>{c.value} &gt; {c.limit} {c.unit}</td></tr>})}</tbody></table></Panel></div><EvidenceNote>“黑箱”在这里指结果对读者缺少解释；这些固定规则本身并不神秘，关键是把实际执行依据保留下来。</EvidenceNote></>;break
    case "audit": body=<><div className="se-controls"><button type="button" onClick={()=>setReverse(v=>!v)}>切换为{reverse ? "分子量优先" : "logP 优先"}</button></div><div className="se-grid"><Panel title="同一批数据，第一失败理由分布"><table><thead><tr><th>类别</th><th>数量</th></tr></thead><tbody>{RULES.map(rule=><tr key={rule.key}><td>{rule.label}</td><td>{results.filter(r=>r.decision==="reject"&&r.firstRule===rule.key).length}</td></tr>)}<tr><td>通过 / 暂缓</td><td>{results.filter(r=>r.decision==="pass").length} / {results.filter(r=>r.decision==="needs-data").length}</td></tr></tbody></table></Panel><Panel title="先核查，再考虑改变规则"><RejectTable index={0} order={order}/><p>顺序改变后，A 的首个失败理由变了，但仍被拒绝。统计首先反映数据组成、顺序和规则。</p><p>某类拒绝多，不能单凭这个比例就调松阈值；还要检查目的、数据分布和验证结果。</p></Panel></div></>;break
    case "reason": body=<><StepControls steps={steps} count={4} label="理由构造"/><div className="se-grid"><Panel title="逐步加入可核查的信息"><ol className="dr-steps">{["规则：分子量上限","比较：612 > 500 g/mol","差值：612 − 500 = 112 g/mol","范围：未通过本次教学政策；不推断真实药效"].map((s,i)=><li key={s} data-active={i<=steps.step}>{i<=steps.step?s:"待加入下一项"}</li>)}</ol></Panel><Panel title="数值证据"><ExactEquation source={String.raw`612\;\mathrm{g/mol}>500\;\mathrm{g/mol}`}/><ExactEquation source={String.raw`\Delta=612-500=112\;\mathrm{g/mol}`}/><p>数据来源必须另行注明：此处是构造数例，不应写成实测结果。</p><div className="dr-output">{steps.step===3 ? rejectionTrace(REJECT_ROWS[0]).reason : "完成步骤后组合成完整记录。"}</div></Panel></div></>;break
    case "short-circuit": body=<><div className="se-controls"><button type="button" onClick={()=>setReverse(v=>!v)}>交换前两道规则</button></div><RejectTable index={0} order={order}/><ExactEquation source={String.raw`k^*=\min\{k:\operatorname{pass}_k(x)=\mathrm{false}\}`}/><div className="dr-output">{rejectionTrace(REJECT_ROWS[0],order).reason}</div><p>“第一失败”不是“最严重失败”。顺序是报告政策的一部分，应当一同保存。</p></>;break
    case "all-checks": body=<><div className="se-controls"><button type="button" onClick={()=>setAudit(v=>!v)}>{audit ? "返回顺序短路模式" : "另外执行完整诊断"}</button></div><RejectTable index={0} audit={audit}/><div className="dr-output">当前：{audit ? "完整诊断实际执行了四条规则，可以报告四项结果。" : "原始短路轨迹只执行第一条；后面三个字段虽在输入中，但没有执行规则判断。"}</div><EvidenceNote>完整诊断不是错误。错误是没有执行却声称已经检查；必须区分原始短路证据与后来另行完成的诊断。</EvidenceNote></>;break
    case "pipeline": body=<><StepControls steps={steps} count={4} label="理由流水线"/><div className="se-grid"><Panel title="执行流程"><ol className="dr-steps">{["读取输入与规则版本","按顺序比较，失败或缺数据即返回","写出规则、值、阈值、状态","批量汇总，保存原始输入和顺序"].map((x,i)=><li key={x} data-active={i<=steps.step}>{x}</li>)}</ol><pre>{`for rule in ordered_rules:\n    value = row[rule.key]\n    if value is None:\n        return needs_data(rule)\n    if value > rule.limit:\n        return rejected(rule, value)\nreturn passed_this_policy()`}</pre></Panel><Panel title="本轮输出"><RejectTable index={1} visible={steps.step<2 ? steps.step : 4}/><div className="dr-output">{steps.step>=2 ? rejectionTrace(REJECT_ROWS[1]).reason : "正在执行，尚未返回"}</div><p>左侧是对应的 Python 风格流程说明，页面由 TypeScript 计算。</p></Panel></div></>;break
    case "trace": body=<RejectWalk/>;break
    case "lab": body=<RejectWalk lab/>;break
    case "batch": body=<><div className="se-controls"><button type="button" onClick={()=>setReverse(v=>!v)}>切换理由顺序</button></div><table><thead><tr><th>ID</th><th>结果</th><th>可复核理由</th></tr></thead><tbody>{results.map(r=><tr key={r.id}><td>{r.id}</td><td>{{reject:"未通过",pass:"通过本次规则","needs-data":"暂缓"}[r.decision]}</td><td>{r.reason}</td></tr>)}</tbody></table><label>我的解释<textarea aria-label="我的批量理由解释" value={note} onChange={e=>setNote(e.target.value)} placeholder="说明顺序如何影响第一失败理由，以及未执行与通过的区别。"/></label><button type="button" disabled={note.trim().length<5} onClick={()=>downloadEvidence("M46-my-rejection-report.json",rejectionEvidence(order,note.trim()))}>下载整批理由报告</button></>;break
    case "handoff": body=<><RowPicker index={index} setIndex={setIndex}/><div className="se-grid"><Panel title={`候选 ${trace.id} 的报告附件`}><RejectTable index={index}/><div className="dr-output">{rejectionTrace(REJECT_ROWS[index]).reason}</div></Panel><Panel title="最终工作台必须区分的状态"><table><tbody><tr><th>硬规则失败</th><td>指明首个失败和数值证据</td></tr><tr><th>缺少数据</th><td>暂缓，不伪装成通过或拒绝</td></tr><tr><th>排名靠后</th><td>说明评分与权重，不等于违反规则</td></tr><tr><th>多样性未选中</th><td>说明选择策略，不等于结构无效</td></tr></tbody></table><p>M47 再把输入、筛选、排名、多样性与理由合并。教学 go/no-go 不能代替真实实验或医疗判断。</p></Panel></div></>;break
  }
  return <div className="se dr" data-renderer="rejection-evidence" data-scene={visual.scene}>{body}<footer>数据：原文数值扩展的六行教学示例；不是实测数据，也不是 M43 的原始名单。本例要求四项均不超过上限，是教学政策；不代表完整的 Lipinski 经验判据或临床安全结论。</footer></div>
}
