'use client'
import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { useLearningRecord, useLearningIdentity } from '@/lib/hooks/use-learning-record'
import { learningRecords, type LearningBody, type LearningScope } from '@/lib/api/learning-records'
import { learningCacheKey } from '@/lib/learning-record-session'
import type { GuidedCourse, GuidedModule } from '@/lib/project-lines/guided-course'
import { ENERGY_VERSION, SCENE_NAMES, FIT_PROBES, newEnergy, runEnergy, rememberFit, energyChecks, physicalEnergyChecks, validEnergyWorkspace, printKey, energyKey, gearRatio, type EnergyWorkspace as Workspace, type EnergyConfig, type EnergyRun, type PrintEvidence } from '@/lib/project-lines/energy-model'
import { generatorCAD, energyDimensions } from '@/lib/project-lines/energy-geometry'
import { EnergyMachineView } from './energy-machine-view'
import { LearningRecordStatus } from './learning-record-status'
import { CheckQuestion } from './biomed-understanding-check'
import guides from '@/lib/project-lines/energy-guides.json'
import styles from './energy-workspace.module.css'

const guideMap:Record<string,Record<string,typeof guides['compare-energy-settings']['M01']>>=guides
const artifact=(a:Workspace)=>a as unknown as Record<string,unknown>
const lastNode=(id:string)=>id==='build-a-printed-generator'?'M06':'M04'
export const energyScope=(id:string,mode='work'):LearningScope=>({library_slug:id,module_id:mode==='work'?'WORK':lastNode(id),activity_id:mode==='work'?'generator-workbench':mode==='prototype'?'digital-prototype':'final-deliverable',kind:mode==='work'?'classroom':'assignment',content_version:'1.0'})
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function Checks({checks}:{checks:{title:string;passed:boolean}[]}){return <ul className={styles.checks}>{checks.map(c=><li key={c.title} data-pass={c.passed}>{c.passed?'已具备':'待补充'} · {c.title}</li>)}</ul>}
function Result({run}:{run:EnergyRun}){
  const r=run.result,max=Math.max(.01,...r.points.map(p=>p.power)),pts=r.points.map(p=>`${45+p.t*7.5},${170-p.power/max*135}`).join(' ')
  return <><div className={styles.stats}><div><strong>{r.meanPower.toFixed(2)}</strong><small>平均负载功率 / mW</small></div><div><strong>{r.energy.toFixed(3)}</strong><small>60 秒负载能量 / J</small></div><div><strong>{r.meanVoltage.toFixed(3)}</strong><small>真实模型电压均值 / V</small></div></div><svg className={styles.plot} viewBox="0 0 530 215" role="img" aria-label="60 秒输出功率曲线，原始数值见下表"><title>负载功率随时间变化</title>{[0,.5,1].map(v=><g key={v}><path d={`M45 ${170-v*135}H495`} stroke="#dadfd3"/><text x="39" y={174-v*135} textAnchor="end" fontSize="10" fill="#6a7564">{(max*v).toFixed(1)}</text></g>)}<polyline points={pts} fill="none" stroke="#547b5c" strokeWidth="2.5"/><text x="12" y="17" fontSize="11" fill="#6a7564">mW</text>{[0,15,30,45,60].map(t=><text key={t} x={45+t*7.5} y="190" textAnchor="middle" fontSize="10" fill="#6a7564">{t}s</text>)}</svg><p className={styles.muted}>能量账本：输入 {r.inputEnergy.toFixed(3)} J = 负载 {r.energy.toFixed(3)} + 损耗 {r.lossEnergy.toFixed(3)} + 剩余转动能 {r.storedEnergy.toFixed(3)} J。教学参数，不能预测某款电机实测输出。</p>{!r.unitAligned&&<p className={styles.notice}>接口读数异常：原始 mV 数值被接收侧当作 V 显示。下表保留这个错误，功率账本来自真实模型量；请检查并修复接口。</p>}<details><summary>检查每秒原始数值</summary><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>秒</th><th>摇柄 rpm</th><th>电机 rpm</th><th>接口显示 V</th><th>负载 mW</th><th>输入 mW</th></tr></thead><tbody>{r.points.map(p=><tr key={p.t}><td>{p.t}</td><td>{p.crank.toFixed(1)}</td><td>{p.shaft.toFixed(1)}</td><td>{p.voltage.toFixed(3)}</td><td>{p.power.toFixed(3)}</td><td>{p.input.toFixed(2)}</td></tr>)}</tbody></table></div></details></>
}
function Report({a,physical=false}:{a:Workspace;physical?:boolean}){return <article className={styles.report} data-energy-report><h4>{physical?'我的打印发电装置与实测档案':'我的传动与发电设计档案'}</h4><p>模型版本：{ENERGY_VERSION}。两级 {a.config.teeth}:18，增速 {gearRatio(a.config).toFixed(2)} 倍；孔径补偿 {a.config.clearance} mm；中心距补偿 {a.config.meshGap} mm。</p><p><strong>我的选择：</strong>{a.reason}</p><p><strong>尚不能说明：</strong>{a.limitation}</p>{a.sources.length>0&&<p>接入自己的正式作品：{a.sources.map(s=>`${s.project} / ${s.submission}`).join('；')}</p>}<details><summary>这次交付保存的可编辑 CAD</summary><pre style={{whiteSpace:'pre-wrap',fontSize:11}}>{a.cadSource}</pre><button onClick={()=>download('submitted-generator.scad',a.cadSource)}>下载这版 CAD</button></details><p>保留打印版本：{a.fitVersions.map(c=>`${c.teeth} 齿 / 孔补偿 ${c.clearance} / 中心距补偿 ${c.meshGap} mm`).join('；')}</p>{a.hypothesis&&<p>诊断：{a.hypothesis}。检查 {a.probes.join('、')}；修复依据：{a.repair}。</p>}{a.runs.map((r,i)=><details key={i}><summary>实验 {i+1} · {SCENE_NAMES[r.scene]} · {r.config.teeth} 齿 / {r.config.rpm} rpm / {r.config.load} Ω</summary><Result run={r}/></details>)}{physical&&<><p>材料 {a.physical.material}；电机 {a.physical.motor}；孔径实测 {a.physical.measuredBore} mm。</p><p>试配前：{a.physical.before}；修改：{a.physical.change}；试配后：{a.physical.after}。</p><p>接线：{a.physical.wiring}</p><details><summary>本人保存的 CAD 源</summary><pre style={{whiteSpace:'pre-wrap',fontSize:11}}>{a.physical.source}</pre></details>{a.physical.tests.map(t=><p key={t.id}>{t.turns} 圈 / {t.seconds} 秒 · {t.resistance} Ω · {t.voltage} V；记录：{t.observation}</p>)}{a.physical.photos.map(p=><figure key={p.id}><img className={styles.photo} src={p.data} alt={p.caption}/><figcaption>{p.caption}</figcaption></figure>)}<p>实物资料由学习者提供，等待人工评阅；系统未核验照片真实性或制造安全。</p></>}</article>}
function Delivery({id,a,ready,prototype=false}:{id:string;a:Workspace;ready:boolean;prototype?:boolean}){
  const physical=id==='build-a-printed-generator'&&!prototype,record=useLearningRecord(energyScope(id,prototype?'prototype':'final'),{answers:[]})
  const checks=[...energyChecks(id,a),...(physical?physicalEnergyChecks(a):[])],complete=ready&&validEnergyWorkspace(a)&&checks.every(c=>c.passed)
  const body:LearningBody={answers:[{question_id:'design',question:'设计选择与边界',answer:`${a.reason}\n${a.limitation}`}],artifact:artifact(structuredClone(a)),client_context:{schema:'energy-delivery/1',assessment:'ungraded',physical,prototype}}
  const same=!!record.submittedAt&&JSON.stringify(body)===JSON.stringify(record.body)
  async function submit(){if(record.pending){await record.session.submit();return}if(!complete)return;record.session.update(body);await record.session.submit()}
  const snapshots=record.history.length?record.history:record.submittedAt?[{id:'local',created_at:record.submittedAt,body:record.body}]:[]
  return <section className={styles.delivery} id={prototype?'digital-delivery':'project-delivery'} data-energy-delivery><p className={styles.eyebrow}>{prototype?'阶段交付 / 数字原型':'最终交付 / 我的作品'}</p><h3>{prototype?'先保存我的数字原型':physical?'交付我的打印发电装置':'交付我的设计与检验记录'}</h3><Checks checks={checks}/>{prototype&&<p>完成这一步可以暂停，等打印条件准备好再回来。正式完成 03 级仍需实物。</p>}<button className={styles.primary} onClick={submit} disabled={!record.ready||record.busy||record.conflict||(!record.pending&&(!complete||same))}>{record.pending?'重试保存':same?'已保存 · 待评阅':prototype?'保存数字原型':'提交我的作品'}</button><LearningRecordStatus record={record}/>{snapshots.map(s=><details key={s.id}><summary>查看已交付版本 · {new Date(s.created_at).toLocaleString()}</summary>{validEnergyWorkspace(s.body.artifact)?<Report a={s.body.artifact} physical={physical}/>:<p>旧版本不兼容，请使用记录备份。</p>}</details>)}</section>
}
async function compressPhoto(file:File){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>12_000_000)throw Error('请选择小于 12 MB 的 JPG、PNG 或 WebP。');const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,640/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);for(const q of [.65,.5,.35,.2]){const data=canvas.toDataURL('image/jpeg',q);if(data.length<=60000)return data}throw Error('图片细节太多，请裁剪后重试。')}finally{bitmap.close()}}
function Physical({a,update,locked}:{a:Workspace;update:(a:Workspace)=>void;locked:boolean}){
  const [message,setMessage]=useState(''),[loading,setLoading]=useState(false),live=useRef(a),enabled=useRef(!locked)
  useEffect(()=>{live.current=a;enabled.current=!locked},[a,locked]);useEffect(()=>()=>{enabled.current=false},[])
  const p=a.physical,change=(patch:Partial<PrintEvidence>)=>update({...a,physical:{...p,...patch}})
  return <div><h4>我的打印与实测证据</h4><p className={styles.notice}>先下载 CAD 与装配说明，打印试配片，再打印整套。这里上传本人装配照片，不能用封面或模拟截图代替。打印与等待不计入 150 分钟目标。</p><button type="button" onClick={()=>change({frozenKey:printKey(a.config)})}>将当前设计登记为本次实物版本</button><p className={styles.muted}>{p.frozenKey===printKey(a.config)?'已登记当前版本。':'当前参数未登记，旧实物证据不能验证新设计。'}</p><div className={styles.grid}>{[['material','实际打印材料与设置','例：PLA，层高 0.2 mm，实际切片用时'],['measuredBore','试配片孔径实测 / mm','例：用卡尺测得 3.28；请填自己的数字'],['before','第一次试配发生了什么','例：转动某一周会卡住，指出位置'],['change','我改了哪个结构或尺寸','例：增加孔径补偿，保持齿数不变'],['after','修改后的试配结果','例：仍有摩擦，记录原因而非填成功'],['motor','实购电机及外形、轴径','记录实际型号和测量值，不照抄图中外形'],['wiring','接线与电表档位','例：电阻跨接输出，电压表并联；直流 V 档']].map(([key,label,placeholder])=><label className={styles.field} key={key}>{label}<input maxLength={800} value={String(p[key as keyof PrintEvidence])} placeholder={placeholder} onChange={e=>change({[key]:e.target.value})}/></label>)}</div><label className={styles.field}>本人最终 CAD 源（含实际装配修改）<textarea rows={5} maxLength={16000} value={p.source} placeholder="在 OpenSCAD 修改后，把最终源码粘贴在这里；不是只写文件名。" onChange={e=>change({source:e.target.value})}/></label><label className={styles.field}><span><input type="checkbox" checked={p.inspected} onChange={e=>change({inspected:e.target.checked})}/> 我和成人检查了空载转动、紧固与护罩；只手摇，不接外部电源。</span></label>
  <h4>同一电阻，两种实际摇速</h4><p className={styles.muted}>数圈与计时得到平均 rpm = 圈数 ÷ 秒数 × 60。电压读数波动时记录范围和估读方式。0 V 和失败原因也是真实结果。</p>{p.tests.map((t,i)=><div key={t.id}><strong>测量 {i+1} {t.revision!==p.frozenKey?'· 旧版本':''}</strong><div className={styles.grid}>{[['turns','圈数'],['seconds','用时 / s'],['resistance','负载 / Ω'],['voltage','电压 / V'],['observation','观察与测量方式']].map(([k,label])=><label className={styles.field} key={k}>{label}<input maxLength={500} value={t[k as keyof typeof t]} onChange={e=>change({tests:p.tests.map(x=>x.id===t.id?{...x,[k]:e.target.value}:x)})}/></label>)}</div><button onClick={()=>change({tests:p.tests.filter(x=>x.id!==t.id)})}>移除此测量</button></div>)}<button disabled={p.tests.length>=8||p.frozenKey!==printKey(a.config)} onClick={()=>change({tests:[...p.tests,{id:crypto.randomUUID(),revision:p.frozenKey,turns:'',seconds:'',resistance:'220',voltage:'',observation:''}]})}>添加实测记录</button>
  <label className={styles.field}>两张现场照片：整体装配、接线与测量<input type="file" accept="image/jpeg,image/png,image/webp" disabled={loading||p.photos.length>=2} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setLoading(true);try{const data=await compressPhoto(file);if(enabled.current&&live.current.physical.photos.length<2)update({...live.current,physical:{...live.current.physical,photos:[...live.current.physical.photos,{id:crypto.randomUUID(),data,caption:''}]}});setMessage('已压缩照片，填写它展示的证据。')}catch(e){setMessage(String(e))}finally{setLoading(false)}}}/></label>{p.photos.map(f=><figure key={f.id}><img src={f.data} alt={f.caption||'待说明的本人实物照片'} className={styles.photo}/><label className={styles.field}>照片说明<input maxLength={300} value={f.caption} placeholder="指出这张图中的打印部件、修改或电表读数" onChange={e=>change({photos:p.photos.map(x=>x.id===f.id?{...x,caption:e.target.value}:x)})}/></label><button onClick={()=>change({photos:p.photos.filter(x=>x.id!==f.id)})}>移除照片</button></figure>)}{message&&<p role="status">{message}</p>}</div>
}
export function EnergyWorkspace({id,node='M01',micro=false}:{id:string;node?:string;micro?:boolean}){
  const record=useLearningRecord(energyScope(id),{answers:[],artifact:artifact(newEnergy())}),valid=validEnergyWorkspace(record.body.artifact),a=valid?record.body.artifact as unknown as Workspace:newEnergy()
  const [time,setTime]=useState(0),[playing,setPlaying]=useState(false),[message,setMessage]=useState(''),[importing,setImporting]=useState(false)
  const identity=useRef(record.identity);useEffect(()=>{identity.current=record.identity},[record.identity])
  const stage=Number(node.slice(1)),system=id==='build-a-printed-generator',design=id==='design-a-printed-transmission',last=!micro&&node===lastNode(id),locked=!record.ready||record.busy||!!record.pending||record.conflict||!valid||importing
  const recent=a.runs.at(-1),same=recent&&energyKey(recent.config)===energyKey(a.config)
  function update(next:Workspace){next={...next,cadSource:generatorCAD(next.config)};if(locked||!validEnergyWorkspace(next))return;record.session.update({answers:micro?[{question_id:'observation',question:'我的操作',answer:`保留 ${next.runs.length} 次实验`}]:[],artifact:artifact(next)})}
  function change<K extends keyof EnergyConfig>(k:K,v:EnergyConfig[K]){setPlaying(false);setTime(0);update({...a,config:{...a.config,[k]:v}})}
  useEffect(()=>{if(!playing)return;const timer=setInterval(()=>{if(document.hidden)return;setTime(t=>{if(t>=60){setPlaying(false);return 60}return t+1})},100);return()=>clearInterval(timer)},[playing])
  const run=(scene:keyof typeof SCENE_NAMES)=>{update(runEnergy(a,scene));setTime(0);setPlaying(!matchMedia('(prefers-reduced-motion: reduce)').matches)}
  async function importOwn(){setImporting(true);const owner=record.identity;try{let next={...a},found:Workspace['sources']=[];for(const project of ['compare-energy-settings','design-a-printed-transmission']){const scope=energyScope(project,'final');let body:LearningBody|undefined,submission='';if(owner.token){const remote=await learningRecords.read(owner.token,scope);body=remote.submissions[0]?.body;submission=remote.submissions[0]?.id||''}else{const raw=localStorage.getItem(learningCacheKey(owner.owner,scope));if(raw){const cached=JSON.parse(raw);if(cached.submittedAt){body=cached.body;submission=cached.submittedAt}}}if(validEnergyWorkspace(body?.artifact)){const source=body!.artifact as unknown as Workspace;next={...next,config:project==='compare-energy-settings'?{...next.config,rpm:source.config.rpm,load:source.config.load}:{...next.config,teeth:source.config.teeth,clearance:source.config.clearance,meshGap:source.config.meshGap},fitVersions:project==='design-a-printed-transmission'?source.fitVersions:next.fitVersions};found.push({project,submission})}}if(identity.current.owner!==owner.owner)return;record.session.update({answers:[],artifact:artifact({...next,cadSource:generatorCAD(next.config),sources:found})});setMessage(found.length?`已接入 ${found.length} 份自己的正式作品；组合后需要重新测试。`:'还没有找到正式交付，可以直接在本课制作自己的版本。')}catch{setMessage('读取未成功，当前作品未改变。')}finally{setImporting(false)}}
  const d=energyDimensions(a.config)
  return <><section className={styles.workspace} data-energy-workspace><p className={styles.eyebrow}>{micro?'3 分钟探索':'我的制作台'} / {design?'打印与配合':'传动与电输出'}</p><h3>{micro?(id==='spin-a-flywheel'?'换一组齿轮，看看转动发生什么':'摇快一点，电表会怎样变化？'):'把想法变成可以检查的版本'}</h3>{micro&&<p>先按“运行”，再改变一个设置重试。保存两次结果，留下你的比较。无需购买器材。</p>}
  {!valid&&record.ready&&<p className={styles.notice}>旧记录暂时无法核验，已停止编辑以保留原始数据。请从记录选项备份。</p>}
  <EnergyMachineView config={a.config} result={same?recent?.result:undefined} time={time}/>
  <fieldset disabled={locked}>
  {system&&stage===1&&<><button onClick={importOwn}>接入我在 02 级交付的作品</button><p className={styles.muted}>{a.sources.length?`已接入 ${a.sources.length} 份作品。`:'没有前作也可以从本课开始。下方起始参数由平台提供，需要自己修改、比较和解释。'}</p></>}
  <div className={styles.grid}><label className={styles.field}>每级大齿轮齿数<select aria-label="大齿轮齿数" value={a.config.teeth} onChange={e=>change('teeth',Number(e.target.value) as EnergyConfig['teeth'])}>{[60,72,90].map(n=><option key={n} value={n}>{n} 齿 × 18 齿</option>)}</select><small>两级增速 {gearRatio(a.config).toFixed(2)} 倍；增加转速需要付出输入功，不会凭空增加能量。</small></label><label className={styles.field}>目标摇速：{a.config.rpm} rpm<input aria-label="目标摇速" type="range" min="20" max="100" step="10" value={a.config.rpm} onChange={e=>change('rpm',Number(e.target.value))}/><small>每分钟转数。驱动力受限，实际速度见曲线数据。</small></label>{id!=='spin-a-flywheel'&&<label className={styles.field}>负载电阻<select aria-label="负载电阻" value={a.config.load} onChange={e=>change('load',Number(e.target.value))}>{[47,100,220,470,1000].map(n=><option key={n} value={n}>{n} Ω</option>)}</select></label>}{(design||system)&&<><label className={styles.field}>孔径补偿：{a.config.clearance.toFixed(2)} mm<input aria-label="孔径补偿" type="range" min="0" max=".8" step=".05" value={a.config.clearance} onChange={e=>change('clearance',Number(e.target.value))}/><small>M3 转动孔设计直径 {d.bore.toFixed(2)} mm；补偿不等于打印后实测间隙。</small></label><label className={styles.field}>中心距补偿：{a.config.meshGap.toFixed(2)} mm<input aria-label="中心距补偿" type="range" min="0" max=".5" step=".05" value={a.config.meshGap} onChange={e=>change('meshGap',Number(e.target.value))}/><small>当前每级中心距 {d.center.toFixed(2)} mm。</small></label></>}</div>
  {system&&stage>=3&&<><label className={styles.field}>我的故障假设<input value={a.hypothesis} maxLength={800} placeholder="例：突然变大的读数来自机械变化，还是传输格式？我先检查什么？" onChange={e=>update({...a,hypothesis:e.target.value})}/></label><div className={styles.actions}>{[['source','查原始字段与单位'],['identity','查运行编号'],['circuit','查电路条件']].map(([p,label])=><button key={p} disabled={!a.hypothesis.trim()} onClick={()=>update({...a,probes:Array.from(new Set([...a.probes,p]))})}>{label}</button>)}</div>{a.probes.map(p=><p className={styles.notice} key={p}>{FIT_PROBES[p]}</p>)}<label className={styles.field}>接收端单位处理<select aria-label="接收端单位处理" value={a.config.wiring} onChange={e=>change('wiring',e.target.value as EnergyConfig['wiring'])}><option value="raw">直接使用原始数字</option><option value="converted">从 mV 换算成 V</option></select></label><label className={styles.field}>我的修复依据<input maxLength={800} value={a.repair} placeholder="引用两项检查；说明为什么换算，再用同一配置复测。" onChange={e=>update({...a,repair:e.target.value})}/></label></>}
  <div className={styles.actions}><button className={styles.primary} onClick={()=>run('steady')}>运行 60 秒模拟</button>{(micro||!design)&&<button onClick={()=>run('coast')}>30 秒后停止摇动</button>}{!micro&&!design&&stage>=3&&<button onClick={()=>run('load-change')}>30 秒后换成 47 Ω</button>}{system&&stage>=3&&<button onClick={()=>run('interface')}>运行接口检查</button>}{system&&stage>=4&&<button onClick={()=>run('tight-fit')}>挑战：装配偏紧</button>}</div>
  {(design||system)&&<><div className={styles.actions}><button onClick={()=>update(rememberFit(a))}>保留这版打印设计</button><button onClick={()=>download(`generator-${a.config.teeth}t.scad`,generatorCAD(a.config))}>下载当前可编辑 CAD</button></div><div className={styles.links}><a href="/project-lines/energy-motion/hardware/assembly.md" target="_blank" rel="noreferrer">打印、采购与装配说明</a><a href="/project-lines/energy-motion/hardware/parts.zip">起始 STL 零件包</a></div><p className={styles.muted}>起始 STL 固定为 72 齿 / 0.30 mm 孔补偿 / 0.15 mm 中心距补偿。改参数后用自己的 CAD 导出新 STL；不能把旧文件当作新设计。板尺寸 {d.width.toFixed(1)} × {d.depth} mm。</p><p>已保留 {a.fitVersions.length} 版设计：{a.fitVersions.map(c=>`${c.teeth} 齿 / ${c.clearance} / ${c.meshGap} mm`).join('；')}</p></>}
  {(last||system&&stage>=4)&&<div className={styles.grid}><label className={styles.field}>我为什么选择这一版<input maxLength={800} value={a.reason} placeholder="例：指出比较中的两个数值、一个代价，以及我选的方案。" onChange={e=>update({...a,reason:e.target.value})}/></label><label className={styles.field}>我的记录还不能证明什么<input maxLength={800} value={a.limitation} placeholder="例：模型没有标定实际电机；试配片结果只适用于本次材料和打印设置。" onChange={e=>update({...a,limitation:e.target.value})}/></label></div>}
  {system&&stage>=5&&<Physical key={record.identity.owner} a={a} update={update} locked={locked}/>}
  </fieldset>{message&&<p role="status">{message}</p>}
  {recent&&<><h4>{same?'本次结果':'旧配置结果 · 当前配置需重新运行'} / {SCENE_NAMES[recent.scene]}</h4><div className={styles.actions}><button onClick={()=>{setTime(0);setPlaying(true)}} disabled={!same}>播放过程</button><button onClick={()=>setPlaying(false)}>暂停</button><label>回放 {time} / 60 s（10 倍速） <input type="range" min="0" max="60" value={time} onChange={e=>{setPlaying(false);setTime(Number(e.target.value))}}/></label></div><Result run={recent}/></>}
  {a.runs.length>0&&<details><summary>比较最近 {a.runs.length} 次实验（最多保留 10 次）</summary><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>实验</th><th>齿数</th><th>目标 rpm</th><th>Ω</th><th>情境</th><th>平均 mW</th><th>负载 J</th></tr></thead><tbody>{a.runs.map((r,i)=><tr key={i}><td>{i+1}</td><td>{r.config.teeth}</td><td>{r.config.rpm}</td><td>{r.config.load}</td><td>{SCENE_NAMES[r.scene]}</td><td>{r.result.meanPower.toFixed(3)}</td><td>{r.result.energy.toFixed(3)}</td></tr>)}</tbody></table></div></details>}
  {micro&&<div className={styles.actions}><button className={styles.primary} disabled={locked||a.runs.length<2} onClick={()=>record.session.submit()}>保存我的两次实验</button><Link href={`/explore/energy-motion/${id==='spin-a-flywheel'?'design-a-printed-transmission':'compare-energy-settings'}`}>继续制作自己的方案</Link></div>}
  <LearningRecordStatus record={record}/><p className={styles.muted}>模型版本 {ENERGY_VERSION}，参数为教学设定；没有连接真实电机。模拟记录不能代替打印试配或电表测量。光照与透视用于观察，不表示零件已经制造完成。</p></section>
  {!micro&&guideMap[id]?.[node]&&<CheckQuestion key={`${id}/${node}`} project={id} node={node} guide={guideMap[id][node]}/>}
  {system&&stage>=4&&<Delivery id={id} a={a} ready={!locked} prototype/>}{last&&<Delivery id={id} a={a} ready={!locked}/>}</>
}
export function EnergyCourseWorkspace({course,node}:{course:GuidedCourse;node:GuidedModule}){return <EnergyWorkspace id={course.id} node={node.module_id}/>}
export function EnergyMicroProject({id,title}:{id:string;title:string}){const identity=useLearningIdentity();return <main className={styles.page}><Link href="/library?view=lines&line=energy-motion">返回动力发明家</Link><p className={styles.eyebrow}>01 / 从一个动作开始</p><h1>{title}</h1><p className={styles.intro}>从桌上的一个小机构开始，发现转速、力量与电之间的联系。你的每次改动，都会留下不同的实验结果。</p><EnergyWorkspace key={`${id}:${identity.owner}`} id={id} micro/></main>}
