"use client"
import {useState} from 'react'
import Link from 'next/link'
import {Check,Circle} from 'lucide-react'
import type {GuidedCourse,GuidedModule} from '@/lib/project-lines/guided-course'
import {learningRecords,type LearningBody,type LearningScope} from '@/lib/api/learning-records'
import {learningCacheKey} from '@/lib/learning-record-session'
import {useLearningRecord} from '@/lib/hooks/use-learning-record'
import {isPhysicalRover,EMPTY_PHYSICAL} from '@/lib/project-lines/rover-system'
import {newExpedition,isExpedition,missionKey,runMission,expeditionChecks,type ExpeditionSystem,type MissionPlan} from '@/lib/project-lines/expedition-system'
import {PhysicalEvidenceFields} from './physical-evidence-fields'
import {RoverBuildView} from './rover-build-view'
import {LearningRecordStatus,downloadLearningRecord} from './learning-record-status'
import styles from './rover-system-workspace.module.css'
const scope:LearningScope={library_slug:'run-an-expedition',module_id:'WORK',activity_id:'field-mission',kind:'classroom',content_version:'2.0'}
const questions=['这次任务的关键取舍','两次现场尝试如何改变方案','实测与数字预算有什么差别']
const initial:LearningBody={answers:questions.map((question,i)=>({question_id:`explain-${i}`,question,answer:''})),artifact:newExpedition() as unknown as Record<string,unknown>}
function Delivery({body,ready}:{body:LearningBody;ready:boolean}){
  const r=useLearningRecord({...scope,module_id:'M05',activity_id:'final-deliverable',kind:'assignment'},{answers:[]}),a=isExpedition(body.artifact)?body.artifact:null
  const prepared:LearningBody={...body,client_context:{assessment:'ungraded',evidence_status:'learner_reported',schema_version:'physical-expedition-delivery/2'}}
  const complete=ready&&!!a&&expeditionChecks(a).every(c=>c.passed)&&body.answers.length===3&&body.answers.every(x=>x.answer.trim()),submitted=!!r.submittedAt&&JSON.stringify(r.body)===JSON.stringify(prepared),saved=r.history[0]??(r.submittedAt?{body:r.body,created_at:r.submittedAt}:null)
  return <section id="project-delivery" className={styles.delivery} data-expedition-delivery><h3>我的实地远征证据包</h3><ul className={styles.checks}>{(a?expeditionChecks(a):[]).map(c=><li key={c.title} data-passed={c.passed}>{c.passed?<Check size={17}/>:<Circle size={17}/>}<span>{c.title}</span></li>)}</ul><p>保存方案与学生报告的现场材料，提交后待评阅。数字预算与照片齐备不能自动证明真实任务已完成。</p><button type="button" className={styles.primary} disabled={!r.ready||r.busy||r.conflict||(!r.pending&&(!complete||submitted))} onClick={async()=>{if(!r.pending){if(!complete)return;r.session.update(structuredClone(prepared))}await r.session.submit()}}>{r.pending?'重试上次交付':submitted?'远征作品已保存 · 待评阅':r.identity.token?'提交远征作品':'保存远征作品到本机'}</button>{saved&&<details data-expedition-submission><summary>查看已交付版本 · {new Date(saved.created_at).toLocaleString()}</summary>{isExpedition(saved.body.artifact)&&<><p>{saved.body.artifact.plan.goal} · {saved.body.artifact.trials.length} 次现场尝试</p><p>{saved.body.artifact.change}</p><button type="button" onClick={()=>downloadLearningRecord(saved.body,'my-field-expedition.json')}>导出完整远征作品</button></>}{saved.body.answers.map(q=><p key={q.question_id}>{q.question}：{q.answer}</p>)}</details>}<LearningRecordStatus record={r}/><Link href="/library/mars-analog-rover">进入完整火星车工程</Link></section>
}
export function ExpeditionSystemWorkspace({course,node}:{course:GuidedCourse;node:GuidedModule}){
  const r=useLearningRecord(scope,initial),a=isExpedition(r.body.artifact)?r.body.artifact:newExpedition(),stage=Number(node.module_id.slice(1))
  const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),locked=!r.ready||r.pending||r.conflict||busy
  function update(next:ExpeditionSystem){r.session.update({...r.session.snapshot().body,artifact:next as unknown as Record<string,unknown>})}
  const field=(key:'routeNotes'|'measuredWidth'|'gateWidth'|'change',label:string,placeholder:string)=><label className={styles.field}>{label}<input aria-label={label} value={a[key]} maxLength={600} placeholder={placeholder} onChange={e=>update({...a,[key]:e.target.value})}/></label>
  async function importRover(){setBusy(true);try{const sourceScope:LearningScope={library_slug:'assemble-a-rover',module_id:'M08',activity_id:'final-deliverable',kind:'assignment',content_version:'2.0'};const remote=r.identity.token?(await learningRecords.read(r.identity.token,sourceScope)).submissions[0]:null;const local=!r.identity.token?JSON.parse(localStorage.getItem(learningCacheKey(r.identity.owner,sourceScope))||'null'):null;const raw=remote?.body.artifact??(local?.submittedAt?local.body?.artifact:null);if(!isPhysicalRover(raw)){setMessage('尚未找到 2.0 实物交付。先完成探测车的实物测试与正式提交，再来读取。');return}const source={id:remote?.id??`local:${local.submittedAt}`,createdAt:remote?.created_at??local.submittedAt,design:raw.design,codeChange:raw.physical.codeChange,reportedWidth:raw.physical.width};if(JSON.stringify(source)!==JSON.stringify(a.source))update({...a,source,runs:[],fieldKey:''});setMessage('已读取实际提交版本的设计参数与制作摘要。原始实物照片和完整证据保留在探测车作品中；远征需要另做现场记录。')}catch{setMessage('读取未完成，当前草稿保留，请重试。')}finally{setBusy(false)}}
  const select=(key:keyof MissionPlan,label:string,options:[string,string][])=> <label className={styles.field}>{label}<select aria-label={label} value={a.plan[key]} onChange={e=>update({...a,plan:{...a.plan,[key]:e.target.value}})}>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>
  return <><section className={styles.workshop} data-expedition-workshop><header className={styles.heading}><p>03 实地任务 / {course.title}</p><h3>{node.title}</h3><p>把一辆能做独立动作的车，变成能完成观察任务的系统。</p></header><fieldset disabled={locked} className={styles.panel}>
    {stage===1&&<><p>先选一个家中或课堂的地面观察目标，例如比较两块不同纹理的地垫。布置起点、观察区、返回区和软障碍；观察可由孩子在车辆停稳后拍摄，不宣称车辆已具备自主视觉。</p><label className={styles.field}>我的观察任务<input aria-label="我的观察任务" value={a.plan.goal} maxLength={600} placeholder="我要到哪里，观察什么，怎样带回一个结果？" onChange={e=>update({...a,plan:{...a.plan,goal:e.target.value}})}/></label><button type="button" onClick={importRover}>读取我的实物探测车</button><Link href="/explore/space-exploration/assemble-a-rover?node=M08#project-delivery">查看探测车实物交付</Link>{a.source&&<><p>已载入 {new Date(a.source.createdAt).toLocaleString()} 的提交版本 · 底板实测 {a.source.reportedWidth} mm。整车外宽仍需重新测量。</p><RoverBuildView design={a.source.design}/></>}</>}
    {stage===2&&<><p>先检查方案，不把耗能点当作真实电池容量。当前车的轮子、电池和结构会影响预算；捷径更短但有额外地形代价。至少比较两种任务方案。</p><div className={styles.threeCols}>{select('route','任务路线',[['short','捷径 / 凸起与额外消耗'],['wide','宽缓路线 / 多两个路段']])}{select('distance','往返路段',[['6','6 段'],['10','10 段']])}{select('reserve','任务预留能量',[['4','保留 4 点'],['10','保留 10 点']])}</div><button type="button" className={styles.primary} onClick={()=>update(runMission(a))}>运行任务预算</button>{a.runs.map((run,i)=><article key={i} className={styles.result}><h4>方案 {i+1} · {run.result.passed?'预算通过':'需要修改'}{run.key!==missionKey(a)?' · 非当前版':''}</h4><ol>{run.result.steps.map(s=><li key={s}>{s}</li>)}</ol></article>)}</>}
    {stage===3&&<><p>数字方案通过后冻结现场任务。换任务或载入新版车会使旧现场记录失效；重新冻结将清空旧草稿现场测量与照片，先备份旧版。</p><button type="button" disabled={!a.runs.some(run=>run.key===missionKey(a)&&run.result.passed)} onClick={()=>{if(a.fieldKey!==missionKey(a))update({...a,fieldKey:missionKey(a),routeNotes:'',measuredWidth:'',gateWidth:'',change:'',trials:[],photos:[]});setMessage('现场任务已冻结，接下来采集本次场地与实测。')}}>冻结现场任务</button><div className={styles.twoCols}>{field('measuredWidth','整车实测外宽（mm）','包含轮子、轴和外伸部件')}{field('gateWidth','现场最窄通道（mm）','实际测量，留出转弯余量')}{field('routeNotes','我的现场布置','起点、观察点、返回点、软障碍和成人站位')}</div></>}
    {stage===4&&<><p>先低速逐段操作，到达观察点后停车、记录一项真实观察，再沿计划返回。每次尝试写真实结果；程序没有相机，就由孩子停车后拍照。改动后重复，至少保留两次尝试。</p><button type="button" disabled={a.trials.length>=8||a.fieldKey!==missionKey(a)} onClick={()=>update({...a,trials:[...a.trials,{id:crypto.randomUUID(),distance:'',seconds:'',surface:'',observation:'',reached:'',returned:'',revision:''}]})}>记录一次现场任务</button>{a.trials.map((t,i)=><article key={t.id} className={styles.testRow}><h4>现场尝试 {i+1}</h4><div className={styles.twoCols}>{([['distance','实际累计路程（cm）'],['seconds','用时（秒）'],['surface','地面与障碍'],['revision','结构与程序版本'],['observation','实际观察或受阻情况']] as const).map(([key,label])=><label key={key} className={styles.field}>{label}<input aria-label={`现场 ${i+1} ${label}`} maxLength={600} value={t[key]} onChange={e=>update({...a,trials:a.trials.map((x,j)=>i===j?{...x,[key]:e.target.value}:x)})}/></label>)}{(['reached','returned'] as const).map(key=><label className={styles.field} key={key}>{key==='reached'?'是否到达观察点':'是否返回基地'}<select aria-label={`现场 ${i+1} ${key==='reached'?'是否到达观察点':'是否返回基地'}`} value={t[key]} onChange={e=>update({...a,trials:a.trials.map((x,j)=>i===j?{...x,[key]:e.target.value}:x)})}><option value="">按真实结果选择</option><option value="yes">是</option><option value="no">否</option></select></label>)}</div></article>)}{field('change','我在两次任务之间做了什么调整','如按实测缩短转向脉冲，仍保留原始第一次结果')}</>}
    {stage===5&&<><PhysicalEvidenceFields value={{...EMPTY_PHYSICAL,photos:a.photos}} onChange={p=>update({...a,photos:p.photos})} part="photos" disabled={locked}/>{r.body.answers.map((q,i)=><label className={styles.field} key={q.question_id}>{q.question}<input aria-label={q.question} maxLength={600} value={q.answer} placeholder="引用本次方案或实测，不用写长报告。" onChange={e=>r.session.update({...r.body,answers:r.body.answers.map((x,j)=>i===j?{...x,answer:e.target.value}:x)})}/></label>)}</>}
  </fieldset>{message&&<p role="status" className={styles.notice}>{message}</p>}<LearningRecordStatus record={r}/></section>{stage===5&&<Delivery body={r.body} ready={r.ready}/>}</>
}
