"use client"
import {useEffect,useState,useSyncExternalStore} from 'react'
import Image from 'next/image'
import type {SlideTechnicalVisual} from '@/lib/types/api'
import {getRDKitModule} from '@/lib/rdkit'
import {MOLECULES} from '@/lib/molecule-skeleton'
import {SKELETON_RUN_KEY,restoreSkeletonRun} from '@/lib/skeleton-evidence'
import {COMPARISON_KEY,GROUP_CHOICES,GROUP_SCRIPT,comparisonScope,traceResults,makeComparisonRecord,restoreComparison,type ComputedRow} from '@/lib/functional-group'
import {MolecularObject3D,MoleculeDiagram} from './molecular-object-3d'
import {downloadEvidence,ExactEquation,StepControls,useTeachingSteps} from './screening-common'
import './molecular-funnel.css'
import './skeleton-evidence.css'
import './functional-group.css'
type Spec=Extract<SlideTechnicalVisual,{renderer:'functional-group'}>
function useSaved(key:string){return useSyncExternalStore(cb=>{window.addEventListener('storage',cb);window.addEventListener('m04-comparison-saved',cb);return()=>{window.removeEventListener('storage',cb);window.removeEventListener('m04-comparison-saved',cb)}},()=>{try{return localStorage.getItem(key)}catch{return null}},()=>null)}
function useCalculation(smiles='CCO'){
 const [result,setResult]=useState<{key:string;rows:ComputedRow[];version:string;error:string}|null>(null)
 useEffect(()=>{let live=true;getRDKitModule().then(rdkit=>{try{const rows=['CC',smiles].map(s=>{const mol=rdkit.get_mol(s);if(!mol)throw Error('无法解析结构');try{const d=JSON.parse(mol.get_descriptors());if(!Number.isFinite(d.CrippenClogP)||!Number.isFinite(d.amw))throw Error('描述符缺失');return {smiles:s,logP:d.CrippenClogP,mw:d.amw}}finally{mol.delete()}});if(live)setResult({key:smiles,rows,version:rdkit.version(),error:''})}catch{if(live)setResult({key:smiles,rows:[],version:rdkit.version(),error:'结构或描述符计算失败；不填入默认成功值。'})}}).catch(()=>{if(live)setResult({key:smiles,rows:[],version:'',error:'RDKit 加载失败，可使用本节 Python 模板。'})});return()=>{live=false}},[smiles])
 return result?.key===smiles?result:null
}
function Note({children}:{children:React.ReactNode}){return <aside className="fg-note">{children}</aside>}
function Pair({target='CCO',explicit=false}:{target?:string;explicit?:boolean}){return <div className="fg-pair">{[['CC','基线 · 乙烷'],[target,GROUP_CHOICES.find(r=>r.smiles===target)?.name||target]].map(([s,label])=><section key={s}><h3>{label}</h3><MoleculeDiagram smiles={s} highlight={s==='CC'?[]:[s.length-1]} explicitHydrogens={explicit}/><code>{s}</code></section>)}</div>}
function Values({rows,delta=false}:{rows:ComputedRow[];delta?:boolean}){return <><table><thead><tr><th>输入</th><th>cLogP（计算值）</th><th>平均摩尔质量</th></tr></thead><tbody>{rows.map(r=><tr key={r.smiles}><th><code>{r.smiles}</code></th><td>{r.logP.toFixed(4)}</td><td>{r.mw.toFixed(3)} g/mol</td></tr>)}</tbody></table>{delta&&rows.length===2&&<div className="fg-delta"><span>Δ cLogP = 后 − 前</span><strong>{(rows[1].logP-rows[0].logP).toFixed(4)}</strong><span>无量纲；不是 g/L</span></div>}</>}
function Overview(){const prior=restoreSkeletonRun(useSaved(SKELETON_RUN_KEY));return <><p className="fg-kicker">M03 结构识读 → M04 同方法计算比较</p><Note>{prior?`已找到 M03 本人提供的四分子报告（RDKit ${prior.rdkit}）；来源仍为自报。`:'本机未找到 M03 运行报告。可先看结构对照，再补齐上一节的个人证据。'}</Note><Pair explicit/><div className="fg-two"><section className="fg-panel"><h3>保留什么？</h3><p>保留两个碳之间的连接。结构式中把一个 C–H 位点改为 C–O–H。</p><ExactEquation source={String.raw`\ce{C2H6}\quad\text{vs.}\quad\ce{C2H6O}`}/></section><section className="fg-panel"><h3>本节只下一个有限结论</h3><p>同一算法接收不同结构，返回不同的 cLogP。记录差异，再区分计算结果和需要实验验证的性质。</p></section></div></>}
function EvidenceRoute(){return <><Pair/><div className="fg-route">{[['01 输入','CC / CCO','先保留结构写法与变化位置'],['02 方法','Crippen cLogP','两次使用同一 RDKit 方法'],['03 输出','前值、后值、差值','数值来自实际计算'],['04 边界','尚未实测','没有溶解度、毒性或药效结论']].map(([n,v,t])=><section key={n}><span>{n}</span><h3>{v}</h3><p>{t}</p></section>)}</div><Note>“只改一处”帮助构造可解释比较；一次模型输出不构成对真实世界因果的独立证明。</Note></>}
function GroupObject(){const m=MOLECULES.find(r=>r.id==='ethanol')!,[showH,setShowH]=useState(true),[selected,setSelected]=useState(m.atoms.find(a=>a.element==='O')!.id);const atom=m.atoms[selected],neighbors=m.bonds.filter(b=>b.a===selected||b.b===selected).map(b=>m.atoms[b.a===selected?b.b:b.a]);return <div className="fg-two"><section><MolecularObject3D molecule={m} showH={showH} selected={selected} onSelect={setSelected}/><label className="fg-inline"><input type="checkbox" checked={showH} onChange={e=>setShowH(e.target.checked)}/>显示氢原子</label><label className="fg-inline">定位原子<select name="m04-atom" aria-label="M04 定位原子" value={selected} onChange={e=>setSelected(Number(e.target.value))}>{m.atoms.map(a=><option key={a.id} value={a.id}>{a.element}{a.id+1}</option>)}</select></label><p role="status">当前 {atom.element}{atom.id+1}；相邻：{neighbors.map(a=>a.element+(a.id+1)).join('、')}。</p></section><section><h3>局部原子组，必须连在具体结构上</h3><MoleculeDiagram smiles="CCO" highlight={[2]} explicitHydrogens/><ExactEquation source={String.raw`\ce{R-OH}\qquad\ce{R-NH2}`}/><MoleculeDiagram smiles="CCN" highlight={[2]}/><p>乙醇的氧连接一个碳和一个氢。乙胺含氮，不是羟基；酸碱与电离状态也会影响性质。</p><Note>3D 为 PubChem CID 702 的计算构象。氢显隐不改变连接；旋转用于观察遮挡，不是分子反应。</Note></section></div>}
function Controls(){const [target,setTarget]=useState('CCO'),scope=comparisonScope(target);return <><div className="fg-controls">{GROUP_CHOICES.filter(c=>c.smiles!=='CCN').map(c=><button key={c.smiles} aria-pressed={target===c.smiles} onClick={()=>setTarget(c.smiles)}>对比 {c.name}</button>)}</div><Pair target={target}/><table><thead><tr><th>变量</th><th>基线</th><th>比较项</th></tr></thead><tbody><tr><th>碳数</th><td>2</td><td>{target==='CCO'?2:3}</td></tr><tr><th>羟基</th><td>无</td><td>有</td></tr><tr><th>方法</th><td>Crippen cLogP</td><td>Crippen cLogP</td></tr></tbody></table><Note><strong>{scope.matched?'局部替换比较':'混入了第二个变化'}</strong>：{scope.reason} 物态、温度和溶液条件不是这个结构算法自动模拟的变量。</Note></>}
function Phases(){return <><div className="fg-two fg-head"><section><h3>乙烷：常温常压是气体</h3><p>上方是气相，不是浮在水上的液态油层。</p></section><section><h3>乙醇与水：可形成均一液体</h3><p>互溶不等于每个含 OH 的分子都无限溶于水。</p></section></div><Image unoptimized className="fg-phase" src="/slide-assets/molecule-monster-hunter/M04/phase-comparison-v1.webp" width={1440} height={810} alt="示意对照：左侧水面上方的稀疏气相，右侧均一液体中的混合组分；不是乙烷油珠"/><Note>AI 生成相态示意，不是实验照片。放大圆中的点只示意稀疏/混合，不表示精确分子、数量或浓度。气相可与空气混合，图中不模拟扩散；不要照图进行化学实验。</Note><p className="fg-small">物态与互溶性来源：NIST / NIOSH。cLogP 描述分配倾向的计算估计，不给出水中溶解度。</p></>}
function Trace(){const result=useCalculation(),steps=useTeachingSteps(4),labels=['固定两个输入','计算 CC','计算 CCO','取差值'];return <><StepControls steps={steps} count={4} label="结构计算轨迹"/><div className="fg-two"><ol className="fg-trace">{labels.map((l,i)=><li key={l} data-active={steps.step===i}><button onClick={()=>steps.jump(i)} aria-current={steps.step===i?'step':undefined}>{i+1} · {l}</button><code>{['inputs = ["CC", "CCO"]','MolLogP(MolFromSmiles("CC"))','MolLogP(MolFromSmiles("CCO"))','delta = after - before'][i]}</code></li>)}</ol><section className="fg-panel"><h3>逐步揭示实际库的计算结果</h3>{result?.rows.length?<Values rows={traceResults(steps.step,result.rows)} delta={steps.step===3}/>:<p role="status">{result?.error||'正在加载 RDKit…'}</p>}<p role="status">{steps.step===0?'结果暂未揭示。':steps.step===1?'已展示基线；不能拿它单独当差值。':steps.step===2?'两次输出都在了，下一步计算差值。':'在这一计算方法中，CCO 的 cLogP 比 CC 低。'}</p><p className="fg-small">浏览器已计算完整结果，播放控制教学揭示顺序，不伪装后台 Python 执行速度。</p></section></div><Note>没有把乙烷分子在水中“变成”乙醇，也没有求解溶解动力学。</Note></>}
function Lab(){const [target,setTarget]=useState('CCO'),result=useCalculation(target),scope=comparisonScope(target);return <><div className="fg-controls">{GROUP_CHOICES.map(c=><button key={c.smiles} aria-pressed={target===c.smiles} onClick={()=>setTarget(c.smiles)}>{c.name}</button>)}</div><Pair target={target}/><div className="fg-two"><section>{result?.rows.length?<Values rows={result.rows} delta/>:<p role="status">{result?.error||'正在计算…'}</p>}</section><section className="fg-panel"><h3>{scope.matched?'同一两碳骨架':'碳链也变了'}</h3><p>{scope.reason}</p><p>运行时版本：{result?.version||'待加载'}</p><p>返回字段 <code>CrippenClogP</code>；方法相同，输入改变时实际重新计算。</p></section></div><Note>这里没有“溶解度及格线”。中性结构的 cLogP 不能替代指定 pH 下的分布系数、溶解度或毒性。</Note></>}
function Record(){const result=useCalculation(),[note,setNote]=useState(''),[checked,setChecked]=useState(false),[message,setMessage]=useState('先写出计算支持的结论，并明确还不知道什么。');const save=()=>{const r=makeComparisonRecord(result?.rows||[],result?.version||'',note,checked);if(!r.record){setMessage(r.problem);return}try{localStorage.setItem(COMPARISON_KEY,JSON.stringify(r.record));window.dispatchEvent(new Event('m04-comparison-saved'));setMessage('已保存到本机并下载；来源为浏览器 RDKit 计算，不是本人 Python 输出。')}catch{setMessage('本机存储不可用，已下载备份。')}downloadEvidence('M04-my-comparison.json',r.record)};return <div className="fg-two"><section><h3>用相同输入在 Python 中复算</h3><pre className="fg-code">{GROUP_SCRIPT}</pre><button onClick={()=>{const u=URL.createObjectURL(new Blob([GROUP_SCRIPT],{type:'text/x-python'})),a=document.createElement('a');a.href=u;a.download='m04_compare.py';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}}>下载 Python 模板</button><p className="fg-small">模板输出可自行保存。本页不把浏览器结果标成你已运行过 Python。</p></section><section className="fg-panel"><h3>保存自己的计算对照记录</h3>{result?.rows.length?<Values rows={result.rows} delta/>:<p>{result?.error||'正在计算…'}</p>}<label className="fg-label">我的有限结论<textarea name="m04-conclusion" aria-label="我的 M04 对照结论" value={note} maxLength={240} onChange={e=>setNote(e.target.value)} placeholder="描述两个值的差异，再说明尚不能证明什么。"/></label><label className="fg-inline"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>我理解：这是计算比较，不是实测溶解度或药效。</label><button onClick={save}>保存并下载对照记录</button><p role="status">{message}</p></section></div>}
function Handoff(){const record=restoreComparison(useSaved(COMPARISON_KEY)),[clearing,setClearing]=useState(false);return <div className="fg-two"><section className="fg-panel"><h3>你实际留下的证据</h3>{record?<><Values rows={record.rows} delta/><blockquote>{record.conclusion}</blockquote><p>浏览器 RDKit {record.version} · 非实测</p><button onClick={()=>downloadEvidence('M04-my-comparison.json',record)}>下载已保存记录</button><button onClick={()=>{if(!clearing){setClearing(true);return}try{localStorage.removeItem(COMPARISON_KEY);window.dispatchEvent(new Event('m04-comparison-saved'));setClearing(false)}catch{}}}>{clearing?'确认清除 M04 记录':'清除 M04 本机记录'}</button></>:<p>尚未保存个人对照记录。请回第 8 页完成结论，不能把页面示例算作你的成果。</p>}</section><section><h3>从结构识读到可复算比较</h3><ol className="fg-trace"><li>M03：谁与谁相连，原子和环怎样计数。</li><li>M04：固定比较问题，保留输入、方法、结果与边界。</li><li>后续：用明确的结构写法组织数据，再比较和筛选更多分子。</li></ol><Note>待验证的问题仍包括真实溶解度、指定条件下的行为以及模型适用性。没有药物安全性或疗效结论。</Note></section></div>}
export function FunctionalGroupVisual({visual}:{visual:Spec}){let body:React.ReactNode;switch(visual.scene){case 'overview':body=<Overview/>;break;case 'route':body=<EvidenceRoute/>;break;case 'groups':body=<GroupObject/>;break;case 'controls':body=<Controls/>;break;case 'phases':body=<Phases/>;break;case 'trace':body=<Trace/>;break;case 'lab':body=<Lab/>;break;case 'record':body=<Record/>;break;case 'handoff':body=<Handoff/>;break}return <div className="fg m03-v2" data-renderer="functional-group" data-scene={visual.scene}>{body}<footer><a href="https://www.rdkit.org/docs/source/rdkit.Chem.Crippen.html">RDKit 计算方法</a> · <a href="https://webbook.nist.gov/cgi/cbook.cgi?ID=C74840&Mask=4">NIST 乙烷</a> · <a href="https://www.cdc.gov/niosh/npg/npgd0262.html">NIOSH 乙醇</a> · 软件教学，不做真实化学实验。</footer></div>}
