"use client"
import { useMemo, useState } from "react"
import type { SlideTechnicalVisual } from "@/lib/types/api"
import { GATES, DEFAULT_ORDER, FUNNEL_SEED, makeCandidates, runFunnel, rankedOrders, passesGate, rejectStage, type GateId, type Candidate } from "@/lib/funnel-evidence"
import { ExactEquation, EvidenceNote, StepControls, useTeachingSteps, downloadEvidence } from "./screening-common"
import "./molecular-funnel.css"

type Spec=Extract<SlideTechnicalVisual,{renderer:"funnel-evidence"}>
type Run=ReturnType<typeof runFunnel>
const names:Record<GateId,string>={lip:"性质",sol:"溶解度",sim:"相似度",tox:"风险分数"}
function FunnelChart({run,completed=4,waterfall=false}:{run:Run;completed?:number;waterfall?:boolean}) {
  const max=Math.max(run.initial,1),base=260,top=40,h=220,ys=(n:number)=>base-n/max*h
  const entries=[{name:"输入",n:run.initial,input:0,remaining:run.initial},...run.stages.slice(0,completed).map(s=>({name:names[s.gate],n:waterfall?s.rejected:s.remaining,input:s.input,remaining:s.remaining})),...(waterfall&&completed===4?[{name:"幸存",n:run.survivors.length,input:0,remaining:run.survivors.length}]:[])]
  const spacing=500/(waterfall?6:5)
  return <figure className="se-panel"><h3>{waterfall?"浮动减量瀑布图":"每层剩余数量"}</h3><svg className="mf-chart" viewBox="0 0 600 315" role="img" aria-label={`${waterfall?"筛除减量瀑布图":"剩余数量柱状图"}，${run.stages.slice(0,completed).map(s=>names[s.gate]+"后剩"+s.remaining).join("，")}`}><text x="14" y="19">候选数量 / 个</text>{[0,1,2,3,4].map(i=>{const n=max*i/4;return <g key={i}><line className="grid" x1="67" x2="578" y1={ys(n)} y2={ys(n)}/><text x="57" y={ys(n)+4} textAnchor="end">{Math.round(n)}</text></g>})}<line className="axis" x1="67" x2="578" y1={base} y2={base}/>{entries.map((e,i)=>{const decrease=waterfall&&i>0&&i<=completed,x=78+i*spacing,width=spacing*.58,y=decrease?ys(e.input):ys(e.n),height=e.n/max*h;return <g key={i}><rect x={x} y={y} width={width} height={height} rx="2" fill={decrease?"#c68057":i===0?"#90aebd":"#3e8b77"}/>{decrease&&<line x1={x} x2={x+spacing} y1={ys(e.remaining)} y2={ys(e.remaining)} stroke="#95b0ba" strokeDasharray="3 3"/>}<text className="number" x={x+width/2} y={Math.max(top-9,y-8)} textAnchor="middle">{decrease?"−":""}{e.n}</text><text x={x+width/2} y="284" textAnchor="middle">{e.name}</text></g>})}</svg><p className="ms-caption">{waterfall?"橙色浮动柱 = 本层拒绝数量；从输入高度减去这部分，落到剩余高度。绿色末柱 = 最后保留。":"每根柱子从 0 起算，柱高表示剩余数量；这不是用浮动柱表示增减量的瀑布图。"}</p></figure>
}
function GateCards({run,completed=4}:{run:Run;completed?:number}) {return <div className="mf-gates">{run.stages.map((s,i)=><div className="mf-gate" key={s.gate} data-active={completed===i+1}><small>第 {i+1} 层 · 成本 {GATES[s.gate].cost} 单位/行</small><strong>{GATES[s.gate].name}</strong><div className="mf-rule">{s.gate==="tox"?`教学风险分数 ≤ ${run.toxLimit.toFixed(2)}`:GATES[s.gate].rule}</div><div className="mf-count">{i<completed?s.remaining:"—"}</div><small>{i<completed?`输入 ${s.input} − 拒绝 ${s.rejected} = 剩余` : "等待上一层输出"}</small></div>)}</div>}
function CountTable({run}:{run:Run}) {return <div className="se-table-wrap"><table><thead><tr><th>关卡</th><th>输入</th><th>拒绝</th><th>剩余</th><th>本层保留率</th><th>累计成本</th></tr></thead><tbody>{run.stages.map(s=><tr key={s.gate}><td>{GATES[s.gate].name}</td><td>{s.input}</td><td>{s.rejected}</td><td>{s.remaining}</td><td>{s.input?(s.remaining/s.input*100).toFixed(1)+"%":"不适用"}</td><td>{s.cumulativeCost}</td></tr>)}</tbody></table></div>}
function RowTrace({rows,run,completed}:{rows:Candidate[];run:Run;completed:number}) {return <div className="se-table-wrap mf-rows"><table><thead><tr><th>ID</th>{run.order.map(g=><th key={g}>{names[g]}</th>)}<th>当前状态</th></tr></thead><tbody>{rows.slice(0,12).map(r=>{const failed=rejectStage(r,run.order,run.toxLimit);return <tr key={r.id}><td>{r.id}</td>{run.order.map((g,i)=><td key={g}>{i>=completed?"待执行":failed>=0&&i>failed?"未调用":<span className={passesGate(r,g,run.toxLimit)?"pass se-chip":"fail se-chip"}>{passesGate(r,g,run.toxLimit)?"通过":"拒绝"}</span>}</td>)}<td>{failed>=0&&failed<completed?`第 ${failed+1} 层退出`:completed===4?"幸存":"待后续"}</td></tr>})}</tbody></table><p className="ms-caption">预览前 12 行；完整 5000 行参与计算。退出后不再调用后续关卡。</p></div>}
export function FunnelEvidenceVisual({visual}:{visual:Spec}) {
  const {scene}=visual,rows=useMemo(()=>makeCandidates(),[])
  const [order,setOrder]=useState<GateId[]>(DEFAULT_ORDER),[tox,setTox]=useState(.3)
  const run=useMemo(()=>runFunnel(rows,order,tox),[rows,order,tox]),ranking=useMemo(()=>rankedOrders(rows,tox),[rows,tox])
  const steps=useTeachingSteps(5),[chosen,setChosen]=useState(0),[style,setStyle]=useState(false)
  const [answers,setAnswers]=useState(["","",""]),[checked,setChecked]=useState(false)
  const stage=run.stages[chosen],baseline=useMemo(()=>runFunnel(rows,DEFAULT_ORDER,tox),[rows,tox]),reverse=useMemo(()=>runFunnel(rows,[...DEFAULT_ORDER].reverse(),tox),[rows,tox])
  const evidence={module:"M43",dataset:{kind:"synthetic-teaching-data-not-real-compounds",seed:FUNNEL_SEED,rows:rows.length,generator:"m86-lcg-v1"},gates:GATES,...run,boundary:"No real toxicity model, docking, or experimental measurement. Costs are assumed operation units. Fixed independent predicates only."}
  const move=(i:number,d:number)=>{if(i+d<0||i+d>=order.length)return;const next=[...order];[next[i],next[i+d]]=[next[i+d],next[i]];setOrder(next);steps.reset()}
  const ordering=<div className="mf-order" aria-label="筛选关卡顺序">{order.map((g,i)=><div key={g}><span>{i+1}</span><strong>{GATES[g].name}</strong><span><button className="secondary" disabled={i===0} aria-label={`${GATES[g].name}上移`} onClick={()=>move(i,-1)}>↑</button> <button className="secondary" disabled={i===3} aria-label={`${GATES[g].name}下移`} onClick={()=>move(i,1)}>↓</button></span></div>)}</div>
  let body:React.ReactNode
  if(scene==="overview")body=<><div className="se-process"><div><strong>输入库</strong><small>5000 行固定合成数据</small></div><div><strong>四层规则</strong><small>上一层输出 = 下一层输入</small></div><div><strong>审计记录</strong><small>名单 + 计数 + 成本</small></div><div><strong>下一节点</strong><small>M44 再打分排序</small></div></div><GateCards run={run}/><div className="se-grid"><FunnelChart run={run}/><section className="se-panel"><h3>真正跑过每一行的结果</h3><ExactEquation source={`5000 \\longrightarrow ${run.stages.map(s=>s.remaining).join("\\longrightarrow ")}`}/><p>只有前一层的幸存行，才进入后一层。合成数据用于检验程序逻辑，不是发现新药的结果。</p><CountTable run={run}/></section></div></>
  else if(scene==="rules")body=<><div className="se-grid"><section className="se-panel"><h3>一行要满足四个条件</h3><ExactEquation source={String.raw`\mathrm{keep}(x)=L(x)\land S(x)\land R(x)\land T(x)`}/><p>“且”不是“任意一关通过就行”。用一组明确标注的构造反例检查：</p><table><thead><tr><th>教学行</th><th>L</th><th>S</th><th>R</th><th>T</th><th>AND</th><th>OR</th></tr></thead><tbody>{[[1,1,1,1],[1,0,1,1],[0,0,0,1],[0,0,0,0]].map((values,i)=><tr key={i}><td>示例 {i+1}</td>{values.map((v,j)=><td key={j}>{v?"✓":"×"}</td>)}<td className={values.every(Boolean)?"pass":"fail"}>{values.every(Boolean)?"保留":"拒绝"}</td><td>{values.some(Boolean)?"保留":"拒绝"}</td></tr>)}</tbody></table></section><section className="se-panel"><h3>图里的每个关卡都有具体定义</h3>{DEFAULT_ORDER.map(g=><p key={g}><strong>{GATES[g].name}</strong><br/>{g==="tox"?"教学风险分数 ≤ 0.30":GATES[g].rule}</p>)}<p className="ms-caption">相似度是相对于固定参考集合的预先给定分数，不是边筛边更新的去重算法。</p></section></div><EvidenceNote>四条全过，只能说明满足这组规则；不能推出安全、有效或一定能进入细胞。logP 也不等于溶解度。</EvidenceNote></>
  else if(scene==="pipeline"||scene==="run")body=<><StepControls steps={steps} count={5} label="逐层筛选"/><GateCards run={run} completed={steps.step}/><div className="se-grid"><section className="se-panel"><h3>{steps.step===0?"尚未执行任何关卡":`刚完成第 ${steps.step} 层：${GATES[run.order[steps.step-1]].name}`}</h3>{scene==="pipeline"?<><pre className="mf-code">{`alive = candidate_rows  # 5000 行\nfor gate in ordered_gates:\n    before = len(alive)\n    alive = [row for row in alive if gate(row)]\n    record(before, len(alive))\n# 只有 alive 被传到下一层`}</pre><div className="se-metrics"><div className="se-metric"><span>本步输入</span><strong>{steps.step?run.stages[steps.step-1].input:5000}</strong></div><div className="se-metric"><span>本步输出</span><strong>{steps.step?run.stages[steps.step-1].remaining:5000}</strong></div><div className="se-metric"><span>已花成本单位</span><strong>{steps.step?run.stages[steps.step-1].cumulativeCost:0}</strong></div></div><p>代码是对应流程说明；页面由 TypeScript 对全部合成行实际执行同样的规则。</p></>:<FunnelChart run={run} completed={steps.step}/>}</section><section className="se-panel"><h3>逐行调用轨迹</h3><RowTrace rows={rows} run={run} completed={steps.step}/></section></div><EvidenceNote>暂停时表格、数量和当前层停在同一步。不是预先写好几个剩余数字再播放：顺序或门槛改变后会重新运行全部行。</EvidenceNote></>
  else if(scene==="order")body=<><div className="se-grid"><section className="se-panel"><h3>两种顺序，末尾名单相同吗？</h3><div className="se-table-wrap"><table><thead><tr><th>执行顺序</th><th>最终剩余</th><th>总成本 / 单位</th></tr></thead><tbody>{[baseline,reverse].map((r,i)=><tr key={i}><td>{r.order.map(g=>names[g]).join(" → ")}</td><td>{r.survivors.length}</td><td>{r.cost}</td></tr>)}</tbody></table></div><ExactEquation source={String.raw`C_{\mathrm{total}}=\sum_i n_{i,\mathrm{input}}\,c_i`}/><p>这批数据的 24 种顺序全部重算，成本最低的是：</p><div className="ms-phase">{ranking[0].order.map(g=>names[g]).join(" → ")}<br/>{ranking[0].cost} 教学成本单位</div><p>便宜的先做不一定最优，还要看它能先筛掉多少，以及规则是否依赖其他计算。</p></section><section className="se-panel"><h3>亲自重排，检查计算成本</h3>{ordering}<CountTable run={run}/><p>当前顺序成本 <strong>{run.cost}</strong>；最终幸存 <strong>{run.survivors.length}</strong>，同一组固定规则的最终 ID 集合不变。</p></section></div><EvidenceNote>顺序无关有前提：固定、独立、无副作用的逐行判定。若中间训练模型、更新去重参考、截取 TopK 或处理缺失值方式不同，结论不一定成立。成本是为教学设定的每行 1/2/3/4 单位，不是实际模型耗时。</EvidenceNote></>
  else if(scene==="counts")body=<><GateCards run={run}/><div className="ms-choice">{run.stages.map((s,i)=><button className="secondary" aria-pressed={chosen===i} key={s.gate} onClick={()=>setChosen(i)}>检查第 {i+1} 层</button>)}</div><div className="se-grid"><section className="se-panel"><h3>{GATES[stage.gate].name}：三个数量必须守恒</h3><ExactEquation source={`${stage.input}-${stage.rejected}=${stage.remaining}`}/><ExactEquation source={`p_{\\mathrm{stage}}=\\frac{${stage.remaining}}{${stage.input}}=${(stage.remaining/stage.input*100).toFixed(1)}\\%`}/><ExactEquation source={`p_{\\mathrm{total}}=\\frac{${stage.remaining}}{5000}=${(stage.remaining/5000*100).toFixed(1)}\\%`}/><p>本层保留率用“本层输入”作分母；累计保留率用“初始 5000”作分母，不能混用。</p></section><section className="se-panel"><h3>计数背后有具体 ID</h3><p><strong>本层拒绝（前 12 个）</strong><br/>{stage.rejectedIds.slice(0,12).join(" · ")}</p><p><strong>本层幸存（前 12 个）</strong><br/>{stage.ids.slice(0,12).join(" · ")}</p><CountTable run={run}/></section></div></>
  else if(scene==="waterfall")body=<><div className="se-controls"><button className="secondary" aria-pressed={!style} onClick={()=>setStyle(false)}>剩余数量柱状图</button><button className="secondary" aria-pressed={style} onClick={()=>setStyle(true)}>浮动减量瀑布图</button></div><div className="se-grid"><FunnelChart run={run} waterfall={style}/><section className="se-panel"><h3>同一组计数，两种不同的图义</h3><CountTable run={run}/><div className="ms-phase">拒绝最多的层：{GATES[[...run.stages].sort((a,b)=>b.rejected-a.rejected)[0].gate].name}，拒绝 {[...run.stages].sort((a,b)=>b.rejected-a.rejected)[0].rejected} 行。</div><p>“拒绝人数最多”和“本层拒绝比例最高”是两种问题。图表也不能直接告诉你被拒绝的是不是好分子。</p></section></div><div className="mf-audit"><div><strong>掉得很多 → 检查证据</strong>先查数据质量、规则目标与验证集；不能仅因数量减少就自动放宽门槛。</div><div><strong>掉得很少 → 不等于没用</strong>少量但关键的风险排除仍可能必要。是否保留，要结合规则意义与成本。</div></div></>
  else if(scene==="lab")body=<><div className="se-grid"><section className="se-panel"><h3>控制变量：换顺序，或改单一门槛</h3>{ordering}<label>教学风险分数上限：<output>{tox.toFixed(2)}</output><input type="range" aria-label="教学风险分数上限" min="0.1" max="0.9" step="0.1" value={tox} onChange={e=>{setTox(Number(e.target.value));steps.reset()}}/></label><p>其余三条规则与 5000 行数据保持不变。</p><StepControls steps={steps} count={5} label="当前方案"/><button className="secondary" disabled={steps.step!==4} onClick={()=>downloadEvidence("M43-my-funnel.json",evidence)}>下载这次执行记录</button></section><section className="se-panel"><h3>当前方案的逐层结果</h3><FunnelChart run={run} completed={steps.step}/><p>已执行 {steps.step} / 4 层 · 累计成本 {steps.step?run.stages[steps.step-1].cumulativeCost:0} 单位</p>{steps.step===4&&<p className="ms-phase">当前保留 {run.survivors.length} 行；相同门槛下 24 种顺序的最少成本为 {ranking[0].cost} 单位。</p>}</section></div><EvidenceNote>降低风险分数上限会收紧这一规则，幸存集合不增加；这只是构造分数的筛选逻辑，不是在评估这些候选的真实毒性。</EvidenceNote></>
  else if(scene==="report") {
    const correct=answers.every((s,i)=>s!==""&&Number(s)===[3200,1200,50][i])
    body=<><div className="se-grid"><section className="se-panel"><h3>先完成原作业中的独立数例</h3><p>这不是右侧合成数据的运行结果。</p><ExactEquation source={String.raw`5000\rightarrow1800\rightarrow600\rightarrow550`}/>{["第一层拒绝数","第二层拒绝数","第三层拒绝数"].map((label,i)=><label className="se-check" key={label}>{label}<input type="number" min="0" step="1" aria-label={label} value={answers[i]} onChange={e=>{setAnswers(a=>a.map((v,j)=>i===j?e.target.value:v));setChecked(false)}}/></label>)}<div className="se-controls"><button onClick={()=>setChecked(true)}>检查数量守恒</button><button className="secondary" disabled={!checked||!correct} onClick={()=>downloadEvidence("M43-my-evidence.json",{...evidence,assignment:{counts:[5000,1800,600,550],learnerRejections:answers.map(Number)}})}>下载我的成果</button></div>{checked&&<p className="se-feedback" role="status">{correct?"三个相邻差值都正确。可以导出个人练习和示范漏斗记录。":"每层拒绝数 = 上一层剩余 − 这一层剩余，请逐层检查。"}</p>}</section><section className="se-report"><h3>一份完整的漏斗成果包</h3><ol><li>输入数据身份：合成数据、固定种子、5000 行。</li><li>关卡顺序、阈值和成本假设。</li><li>逐层输入 / 拒绝 / 幸存 ID 与计数。</li><li>剩余图或减量图，以及最多拒绝发生在哪里。</li><li>适用范围：程序逻辑验证，不是药物安全结论。</li></ol><CountTable run={run}/></section></div></>
  } else body=<><div className="se-process"><div><strong>M42 性质初筛</strong><small>从结构算描述符</small></div><div><strong>M43 多层过滤</strong><small>硬规则决定保留集合</small></div><div><strong>M44 候选排序</strong><small>再讨论归一化与权重</small></div><div><strong>进一步验证</strong><small>模型与实验的额外证据</small></div></div><div className="se-grid"><section className="se-panel"><h3>传给下一阶段的是候选记录，不是一个勾</h3><p>以下为幸存行的前 8 条。当前顺序是 ID 顺序，<strong>没有计算 Top10</strong>。</p><div className="se-table-wrap"><table><thead><tr><th>ID</th><th>MW</th><th>logP</th><th>logS</th><th>风险分数</th></tr></thead><tbody>{run.survivors.slice(0,8).map(r=><tr key={r.id}><td>{r.id}</td><td>{r.mw}</td><td>{r.logp}</td><td>{r.logS}</td><td>{r.toxScore}</td></tr>)}</tbody></table></div></section><section className="se-report"><h3>{run.survivors.length} 个教学候选，等待比较</h3><p>本阶段回答：哪些行满足全部硬规则？</p><p>下阶段回答：在幸存集合中，按照明确目标和权重，谁更值得优先研究？</p><button onClick={()=>downloadEvidence("M43-to-M44-candidates.json",evidence)}>导出候选和筛选来路</button><p>排序不能给违反必要硬约束的分子“加分复活”。</p></section></div></>
  return <section className="se" data-renderer="funnel-evidence" data-scene={scene} aria-label={visual.aria_label||"多层筛选教学视觉"}>{body}<div className="se-source">来源：分子猎人 M43 课文、作业与关卡游戏的流程语义。本页运行 <strong>5000 行固定种子的合成教学数据</strong>（seed {FUNNEL_SEED}），所有字段均为构造值；没有真实分子结构、真实预测或实验测量。页面本地逐行计算，成本单位为教学假设。</div></section>
}
