"use client"

import { useEffect, useState } from "react"
import type { SlideTechnicalVisual } from "@/lib/types/api"
import { drawSmilesSvg } from "@/lib/rdkit"
import { DEFAULT_LIMITS, DESCRIPTOR_KEYS, screenLibrary, screenMolecule, type DescriptorKey, type LipinskiLimits, type LipinskiRow } from "@/lib/lipinski-evidence"
import { ExactEquation, EvidenceNote, StepControls, downloadEvidence, useTeachingSteps } from "./screening-common"

type Spec = Extract<SlideTechnicalVisual, { renderer: "lipinski-evidence" }>
const names: Record<DescriptorKey, string> = { mw: "MW", logp: "cLogP", hbd: "HBD", hba: "HBA" }
const precise = (n: number, k: DescriptorKey) => ["hbd", "hba"].includes(k) ? String(n) : n.toFixed(2)

function MoleculeDrawing({ row }: { row: LipinskiRow }) {
  const [drawing, setDrawing] = useState({ smiles: "", svg: "", failed: false })
  useEffect(() => { let cancelled = false; if (row.smiles) drawSmilesSvg(row.smiles, { width: 430, height: 270 }).then(svg => { if (!cancelled) setDrawing({ smiles: row.smiles!, svg, failed: false }) }).catch(() => { if (!cancelled) setDrawing({ smiles: row.smiles!, svg: "", failed: true }) }); return () => { cancelled = true } }, [row.smiles])
  return <><div className="se-rdkit" aria-label={`${row.name} 的 RDKit 二维分子结构`}>{drawing.smiles === row.smiles && drawing.svg ? <div dangerouslySetInnerHTML={{ __html: drawing.svg }} /> : <p>{drawing.failed ? "结构绘图不可用；下方保留 SMILES 与数据。" : "正在用 RDKit 排布结构…"}</p>}</div><details><summary>结构与计算口径</summary><p className="break-all">SMILES：{row.smiles || "本行是数值反例，不对应真实结构"}</p><p>MW = amw；cLogP = CrippenClogP；HBD = NumHBD；HBA = NumHBA。RDKit 2025.03.4；不同算法 / 质子化形式可能得到不同值。</p>{row.source_url && <a href={row.source_url} target="_blank" rel="noreferrer" className="underline">PubChem 原结构</a>}</details></>
}
function RuleCells({ row, limits }: { row: LipinskiRow; limits: LipinskiLimits }) {
  return <div className="se-rule-cells">{DESCRIPTOR_KEYS.map(k => <div key={k} className={row[k] <= limits[k] ? "pass" : "fail"}><small>{names[k]}{k === "mw" ? " / Da" : ""}</small><strong>{precise(row[k], k)}</strong><span>{row[k] <= limits[k] ? "≤" : ">"} {limits[k]} · {row[k] <= limits[k] ? "达标" : "违反"}</span></div>)}</div>
}
function LibraryTable({ rows, limits, allowed, current, onSelect, revealed = rows.length }: { rows: LipinskiRow[]; limits: LipinskiLimits; allowed: number; current?: string; onSelect?: (id: string) => void; revealed?: number }) {
  const result = screenLibrary(rows, limits, allowed)
  return <div className="se-table-wrap"><table><thead><tr><th>分子 / 编号</th>{DESCRIPTOR_KEYS.map(k => <th key={k}>{names[k]} ≤ {limits[k]}</th>)}<th>违反</th><th>初筛</th></tr></thead><tbody>{result.results.map((r, i) => <tr key={r.id} data-active={r.id === current}><td>{onSelect ? <button type="button" onClick={() => onSelect(r.id)}>{r.name}</button> : r.name}</td>{DESCRIPTOR_KEYS.map(k => <td key={k} className={i < revealed ? r.failures.includes(k) ? "fail" : "pass" : ""}>{precise(r[k], k)}{i < revealed ? r.failures.includes(k) ? " ×" : " ✓" : ""}</td>)}<td>{i < revealed ? r.violations : "—"}</td><td>{i < revealed ? r.pass ? "保留" : "未通过" : "待判定"}</td></tr>)}</tbody></table></div>
}
function Rates({ rows, limits, allowed }: { rows: LipinskiRow[]; limits: LipinskiLimits; allowed: number }) {
  const r = screenLibrary(rows, limits, allowed)
  return <><h3>同一个库，分开统计</h3>{DESCRIPTOR_KEYS.map(k => <div className="se-rate" key={k}><strong>{names[k]}</strong><div className="se-rate-track"><div style={{ width: `${r.singleCounts[k] / r.total * 100}%` }} /></div><output>{r.singleCounts[k]}/{r.total}</output></div>)}<ExactEquation source={String.raw`\text{本次联合通过率}=\frac{${r.passed}}{${r.total}}\times100\%=${(100 * r.rate).toFixed(0)}\%`} /><p>联合策略：{allowed === 0 ? "四条全部达标" : "最多违反一条"}。这是对本批分子的统计，不是单个分子的“成药概率”。</p></>
}

export function LipinskiEvidenceVisual({ visual }: { visual: Spec }) {
  const { scene, rows, source_note } = visual
  const [selected, setSelected] = useState(rows[0].id), [allowed, setAllowed] = useState(1), [answers, setAnswers] = useState(["", "", ""]), [checked, setChecked] = useState(false), [saved, setSaved] = useState<Array<{ mw: number; allowed: number; single: number; joint: number }>>([])
  const steps = useTeachingSteps(scene === "sweep" ? 11 : rows.length + 1)
  const activeMw = scene === "sweep" ? 500 - steps.step * 5 : 500
  const limits = { ...DEFAULT_LIMITS, mw: activeMw }, result = screenLibrary(rows, limits, allowed), row = rows.find(r => r.id === selected)!, assessment = screenMolecule(row, limits, allowed)
  const record = { node: "M42-w0-lipinski", source: source_note, calculation: "RDKit 2025.03.4 / amw, CrippenClogP, NumHBD, NumHBA", limits, allowed_violations: allowed, rows: result.results, single_counts: result.singleCounts, retained: result.passed, total: result.total, pass_rate: result.rate, observations: saved, limitation: "经验初筛不是安全、有效、吸收或可上市的证明。" }
  const policy = <div className="se-controls"><span>联合策略</span><button type="button" className="secondary" aria-pressed={allowed === 0} onClick={() => setAllowed(0)}>四条全过</button><button type="button" className="secondary" aria-pressed={allowed === 1} onClick={() => setAllowed(1)}>允许 1 条违反</button></div>
  const tabs = <div className="se-molecule-tabs">{rows.map(r => <button type="button" key={r.id} className="secondary" aria-pressed={selected === r.id} onClick={() => setSelected(r.id)}>{r.name}</button>)}</div>
  const cards = <><p className="se-kicker">结构 → 计算描述符 → 比较阈值</p><h3>{row.name}</h3><MoleculeDrawing row={row} /><RuleCells row={row} limits={limits} /><p>违反 <output>{assessment.violations}</output> 条 · 当前策略：<strong>{assessment.pass ? "保留进入后续研究" : "未通过本次初筛"}</strong></p></>
  let content: React.ReactNode
  if (["meaning", "rules", "descriptors"].includes(scene)) {
    content = <>{tabs}<div className="se-grid"><div className="se-panel">{cards}</div><div className="se-panel tint"><h3>{scene === "meaning" ? "这四个数能回答到哪一步？" : scene === "rules" ? "四个条件，不是五个条件" : "定义、算法、数值，要一一对应"}</h3>{scene === "meaning" ? <><p>结构 → 计算性质 → 检查经验门槛，是早期候选筛选的一步。</p><div className="se-process" style={{ gridTemplateColumns: "1fr 1fr" }}><div><strong>溶解与渗透</strong><small>门槛提示相关风险</small></div><div><strong>靶点与效力</strong><small>本规则没有检验</small></div><div><strong>安全性</strong><small>本规则没有检验</small></div><div><strong>真实吸收</strong><small>仍需专门证据</small></div></div><p>分子“通过”只表示满足当前数值策略，不能理解为“能吃”或“可以给人用”。</p></> : <><ExactEquation source={String.raw`\mathrm{MW}\le500\,\mathrm{Da},\quad\mathrm{cLogP}\le5`} /><ExactEquation source={String.raw`\mathrm{HBD}\le5,\quad\mathrm{HBA}\le10`} /><p>MW：平均分子质量；cLogP：分配性质的计算估计；HBD / HBA：按明确规则识别氢键供体 / 受体。</p><p>氢键受体不是“所有 N / O 原子数量”。本页统一使用 RDKit NumHBA，不混用简单原子计数。</p></>}{policy}<ExactEquation source={String.raw`v=\sum_{j=1}^{4}\mathbf{1}[d_j>L_j],\quad\text{保留}\iff v\le${allowed}`} /><EvidenceNote>{scene === "rules" ? "边界值恰好等于门槛不违反。名称中的 Five 是阈值数字的记忆方式；“允许一条违反”是本课程明示的筛选策略。" : "点击咖啡因：这里由可核查结构重新计算 HBA = 6，已纠正旧课表中的 3。结构图由 RDKit 排布，不是图片模型猜画。"}</EvidenceNote></div></div></>
  } else if (scene === "sets") {
    const counter: LipinskiRow[] = [{ id: "A", name: "反例 A", mw: 520, logp: 2, hbd: 1, hba: 2 }, { id: "B", name: "反例 B", mw: 300, logp: 6, hbd: 1, hba: 2 }, { id: "C", name: "反例 C", mw: 300, logp: 2, hbd: 6, hba: 2 }, { id: "D", name: "反例 D", mw: 300, logp: 2, hbd: 1, hba: 11 }]
    content = <><EvidenceNote>专门构造的四张描述符卡，用于检验集合逻辑；不对应四种真实药物，也不混入十分子课程库。</EvidenceNote>{policy}<LibraryTable rows={counter} limits={DEFAULT_LIMITS} allowed={allowed} /><div className="se-grid"><div className="se-panel"><Rates rows={counter} limits={DEFAULT_LIMITS} allowed={allowed} /></div><div className="se-panel tint"><h3>“条件更多”之前，先看逻辑运算</h3><ExactEquation source={String.raw`\text{全过}=A\cap B\cap C\cap D`} /><p>四条全过：交集包含在每一个单规则集合内，比例不高于任何单条。</p><ExactEquation source={String.raw`\text{允许一条违反}=\{m:v(m)\le1\}`} /><p>每张反例卡都只违反一条，所以允许一条时全部保留；但每条单规则各自只保留三张。</p><p><strong>联合 100% &gt; 单条 75%</strong>，这足以否定“一定更低”。</p></div></div></>
  } else if (scene === "sweep") {
    const original = screenLibrary(rows, DEFAULT_LIMITS, 1), tightened = screenLibrary(rows, { ...DEFAULT_LIMITS, mw: 450 }, 1)
    content = <><div className="se-grid"><div className="se-panel"><h3>只改变 MW 上限，其余三条不动</h3><StepControls steps={steps} count={11} label="门槛收紧" /><label>分子质量上限：<output>{activeMw} Da</output><input aria-label="MW 上限" type="range" min="450" max="500" step="5" value={activeMw} onChange={e => steps.jump((500 - Number(e.target.value)) / 5)} /></label><div className="se-scale">{rows.map(r => <div className="se-scale-row" key={r.id}><span>{r.name}</span><div className="se-scale-lane"><div className="se-scale-bar" style={{ width: `${r.mw / 850 * 100}%`, background: r.mw > activeMw ? "#c28a71" : "#569a88" }} /><div className="se-threshold-line" style={{ left: `${activeMw / 850 * 100}%` }} /></div><output>{r.mw.toFixed(1)}</output></div>)}</div><p className="se-kicker">共用比例尺：0–850 Da · 橙线：当前上限</p></div><div className="se-panel"><Rates rows={rows} limits={limits} allowed={allowed} />{policy}<button type="button" onClick={() => setSaved(s => [...s, { mw: activeMw, allowed, single: result.singleCounts.mw, joint: result.passed }])}>记录当前读数</button><div className="se-table-wrap"><table><thead><tr><th>MW 上限</th><th>允许违反</th><th>MW 单条</th><th>联合保留</th></tr></thead><tbody>{saved.map((s, i) => <tr key={i}><td>{s.mw}</td><td>{s.allowed}</td><td>{s.single}/10</td><td>{s.joint}/10</td></tr>)}</tbody></table></div><p>{saved.length ? "记录可随完整证据 JSON 下载。" : "先点击记录，再改变上限进行对照。"}</p><button type="button" className="secondary" disabled={!saved.length} onClick={() => downloadEvidence("M42-threshold-observations.json", record)}>下载我的观察记录</button><EvidenceNote>默认允许 1 条：MW 从 500 到 450 时，单条 {original.singleCounts.mw}/10 → {tightened.singleCounts.mw}/10；联合 {original.passed}/10 → {tightened.passed}/10。收紧只能使保留数不增，也可能暂时不变。</EvidenceNote></div></div></>
  } else if (scene === "workshop") {
    const standard = screenLibrary(rows, DEFAULT_LIMITS, 1), tight = screenLibrary(rows, { ...DEFAULT_LIMITS, mw: 450 }, 1)
    const correct = answers.every((s, i) => s.trim() !== "" && Number(s) === [standard.singleCounts.mw, standard.passed, tight.passed][i])
    content = <><LibraryTable rows={rows} limits={DEFAULT_LIMITS} allowed={1} revealed={0} /><div className="se-grid"><div className="se-panel"><h3>你来完成三个保留计数</h3>{["MW ≤ 500 的分子数", "默认策略的联合保留数", "MW ≤ 450 后的联合保留数"].map((label, i) => <label className="se-check" key={label}>{label}<input aria-label={label} type="number" min="0" max="10" step="1" value={answers[i]} onChange={e => { setChecked(false); setAnswers(a => a.map((v, j) => i === j ? e.target.value : v)) }} /></label>)}<button type="button" onClick={() => setChecked(true)}>检查筛选结果</button>{checked && <p className="se-feedback" role="status">{correct ? "三个计数都正确。可下载包含结构、描述符、规则和保留名单的证据卡。" : "还需要核对。联合策略允许一条违反；不要把 MW 超标的一行直接等同于联合未通过。"}</p>}</div><div className="se-panel tint"><h3>产出物不是一个百分数，而是一份可核查筛选记录</h3><p>① 结构与数值表 → ② 写明门槛 → ③ 逐行违反数 → ④ 保留名单和比例。</p><p>用未四舍五入的计算值判断门槛；表格只为阅读保留小数位。</p><button type="button" disabled={!checked || !correct} onClick={() => downloadEvidence("M42-my-screening-evidence.json", { ...record, limits: DEFAULT_LIMITS, allowed_violations: 1, learner_answers: answers.map(Number), checked: true, tightened: tight })}>下载我的筛选证据卡</button></div></div></>
  } else if (scene === "limits") {
    content = <><div className="se-grid"><div className="se-panel"><h3>把筛选结论写成可证实的句子</h3><div className="se-report"><p><strong>可以说</strong>：在这 10 个指定结构、当前计算方法和四个门槛下，有 {result.passed} 个结构通过“最多违反 1 条”的初筛。</p></div><EvidenceNote>不能说：保留的分子都安全、有效、一定能口服。没有通过也不意味着它一定不能成为药物。</EvidenceNote><p>吸收和渗透还受结构形式、制剂、转运等因素影响。课程页面不提供用药判断。</p></div><div className="se-panel"><h3>交给下一阶段的材料</h3><LibraryTable rows={rows.slice(7)} limits={limits} allowed={1} /><p>未通过行仍保留在报告中，并明确违反哪条；不能把它们从原始数据里删除后假装没有出现。</p><p>下一层再引入活性、毒性预测、可合成性和结构多样性等独立证据，不能让同一条规则替代所有判断。</p></div></div></>
  } else if (scene === "protocol") {
    content = <><div className="se-process"><div><strong>① 固定数据</strong><small>10 个结构 + 来源</small></div><div><strong>② 明示策略</strong><small>阈值 + 允许违反数</small></div><div><strong>③ 逐行检查</strong><small>违反数 + 保留标志</small></div><div><strong>④ 汇总留证</strong><small>计数 / 分母 / 名单</small></div></div><StepControls steps={steps} count={rows.length + 1} label="逐行筛选" /><LibraryTable rows={rows} limits={limits} allowed={allowed} revealed={steps.step} /><p aria-live="polite">已检查 {steps.step}/10 行；目前已检查行中保留 {result.results.slice(0, steps.step).filter(r => r.pass).length} 行。</p><EvidenceNote>没有扫描完全部 10 行之前，不能把当前已保留数当作全库最终通过数。</EvidenceNote></>
  } else {
    content = <>{scene === "overview" && <div className="se-process"><div><strong>结构证据</strong><small>PubChem SMILES</small></div><div><strong>四个描述符</strong><small>RDKit 统一计算</small></div><div><strong>同一套规则</strong><small>逐行比较与计数</small></div><div><strong>筛选证据卡</strong><small>名单 + 比例 + 边界</small></div></div>}{policy}<div className="se-grid wide"><div className="se-panel"><h3>{scene === "report" ? "参考报告：十个结构的完整证据" : "全库 10 行，每一行都能回查"}</h3><LibraryTable rows={rows} limits={limits} allowed={allowed} current={selected} onSelect={setSelected} /></div><div className="se-panel"><Rates rows={rows} limits={limits} allowed={allowed} />{scene === "report" ? <><p>保留名单：{result.results.filter(r => r.pass).map(r => r.name).join("、")}。</p><button type="button" onClick={() => downloadEvidence("M42-reference-screening-report.json", record)}>下载完整参考报告</button></> : <><h3>点选任一行，核查结构</h3><MoleculeDrawing row={row} /><p><strong>{row.name}</strong> · HBA {row.hba} · 违反 {assessment.violations} 条</p></>}</div></div><EvidenceNote>{scene === "report" ? "递进关系：前序描述符计算 → M42 形成初筛证据与名单 → M43 多层筛选 → M44 候选排序。分子猎人整体替换尚未完成，此页不代表整项目已上线。" : "保留判断只使用公开结构重新计算的数值。百分比描述这一小库，不是每个分子的成药概率。"}</EvidenceNote></>
  }
  return <section className="se" aria-label={visual.aria_label} data-renderer="lipinski-evidence" data-scene={scene}>{content}<p className="se-source">{scene === "sets" ? "本页四张卡为明确构造的数值反例，不是 PubChem 结构或实测结果；其余页面使用原课程十个化合物的重算值。" : source_note} <a href="https://pubmed.ncbi.nlm.nih.gov/11259830/" target="_blank" rel="noreferrer">规则的研究背景</a> · <a href="https://www.rdkit.org/docs/source/rdkit.Chem.Lipinski.html" target="_blank" rel="noreferrer">RDKit 描述符</a></p></section>
}
