"use client"
import { useEffect, useState } from 'react'
import Image from 'next/image'
import type { SlideTechnicalVisual } from '@/lib/types/api'
import { drawSmilesSvg } from '@/lib/rdkit'
import { LOGP_SAMPLES, LOGP_DATA_NOTE, logpEvidence, logpHistogram, partitionState } from '@/lib/logp-lab'
import { ExactEquation, StepControls, useTeachingSteps, downloadEvidence } from './screening-common'
import { PartitionObject3D } from './partition-object-3d'
import './logp-lab.css'

export const LOGP_IMAGE = '/slide-assets/molecule-monster-hunter/M38/oil-water-comparison-v1.webp'
function OilPhoto() {
  return <figure data-medium="generated-raster"><Image className="lp-photo" src={LOGP_IMAGE} alt="生成的教学对比图：左杯中金色油滴分散于水中，右杯静置后油聚成上层，水留在下层" width={1600} height={900} unoptimized/><figcaption className="lp-photo-caption"><div><strong>搅拌后：油滴分散</strong><span>分散不等于溶解</span></div><div><strong>静置后：重新分层</strong><span>界面和物态变化可见</span></div></figcaption><p className="lp-small">AI 生成的定性教学示意，不是实拍实验记录。图中没有浓度或时间测量。</p></figure>
}
function Molecule({ index }: { index: number }) {
  const [drawing,setDrawing]=useState({smiles:'',svg:'',error:false})
  const row=LOGP_SAMPLES[index]
  const svg=drawing.smiles===row.smiles?drawing.svg:'',error=drawing.smiles===row.smiles&&drawing.error
  useEffect(()=>{let live=true;drawSmilesSvg(row.smiles,{width:440,height:180}).then(svg=>{if(live)setDrawing({smiles:row.smiles,svg,error:false})}).catch(()=>{if(live)setDrawing({smiles:row.smiles,svg:'',error:true})});return()=>{live=false}},[row.smiles])
  return <figure className="lp-molecule"><div aria-label={`${row.name}的 RDKit 二维结构`} role="img" dangerouslySetInnerHTML={{__html:svg}}/>{!svg&&<p>{error?'结构暂不可用；保留精确 SMILES：':'正在绘制结构…'}</p>}<figcaption>{row.name}<br/><code>{row.smiles}</code></figcaption></figure>
}
function SampleTable({visible=3}: {visible?:number}) {return <table><thead><tr><th>结构示例</th><th>cLogP</th><th>来源</th></tr></thead><tbody>{LOGP_SAMPLES.slice(0,visible).map(r=><tr key={r.id}><td>{r.name}</td><td>{r.logP.toFixed(4)}</td><td>RDKit 计算</td></tr>)}</tbody></table>}
function Scale({visible=3}: {visible?:number}) {return <><div className="lp-scale" aria-label="cLogP 数轴，范围负4到正4"><div className="lp-axis"/>{[-4,-2,0,2,4].map(v=><div className="lp-scale-mark" key={v} style={{left:`${(v+4)*12.5}%`}}><span>{v}</span></div>)}{LOGP_SAMPLES.slice(0,visible).map((r,i)=><div className="lp-scale-dot" key={r.id} style={{left:`${(r.logP+4)*12.5}%`,bottom:20+(i%2)*55}}>{r.id==='glucose'?'葡萄糖':r.name}<i/><strong>{r.logP.toFixed(4)}</strong></div>)}</div><div className="lp-scale-legend"><span>负值：偏向水相</span><span>正值：偏向正辛醇相</span></div></>}
function OrderingExercise() {
  const [order,setOrder]=useState(['ethanol','glucose','octane']),[checked,setChecked]=useState(false)
  const good=order.join(',')==='octane,ethanol,glucose'
  return <div className="lp-two"><section className="lp-card"><h3>从最偏油，到最偏水</h3><SampleTable/><p>只使用本表的计算值，不把分子的大小或图中的位置当作答案。</p></section><section><div className="lp-rank">{order.map((id,i)=><label key={i}>第 {i+1} 位<select aria-label={`排序第${i+1}位`} value={id} onChange={e=>{setOrder(order.map((v,j)=>j===i?e.target.value:v));setChecked(false)}}>{LOGP_SAMPLES.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>)}</div><div className="lp-controls"><button onClick={()=>setChecked(true)}>检查排序</button><button onClick={()=>{setOrder(['ethanol','glucose','octane']);setChecked(false)}}>重新尝试</button></div>{checked&&<p className="lp-result" role="status">{good?'正确：3.3668 > −0.0014 > −3.2214。排序依据是同一种方法计算的 cLogP。':new Set(order).size<3?'每个分子只能出现一次，请先消除重复。':'还不对。比较数值大小：正数最大，接近零的小负数居中，更负的数最小。'}</p>}</section></div>
}
export function LogpLabVisual({visual}:{visual:Extract<SlideTechnicalVisual,{renderer:'logp-lab'}>}) {
  const steps=useTeachingSteps(4),[index,setIndex]=useState(0),[example,setExample]=useState(1)
  const scene=visual.scene, p=partitionState(example), bins=logpHistogram(LOGP_SAMPLES.map(r=>r.logP))
  let body:React.ReactNode
  switch(scene){
    case 'overview': body=<><OilPhoto/><div className="lp-flow"><div><strong>01 看见现象</strong><small>油滴分散，静置后分层</small></div><div><strong>02 明确比较对象</strong><small>同一种溶质在两相中的浓度</small></div><div><strong>03 交出可计算字段</strong><small>用 RDKit 得到 cLogP，并标注“计算值”</small></div></div><p className="lp-callout">厨房食用油与水只用来建立直觉；正式的 LogP 定义使用正辛醇／水体系，不是由这张图片读出的数。</p></>;break
    case 'phases': body=<PartitionObject3D inspect/>;break
    case 'partition': body=<PartitionObject3D/>;break
    case 'scale': body=<div className="lp-two"><section className="lp-card"><p className="lp-kicker">KATEX · 从比例到对数</p><h3>logP 每增加 1，浓度比乘 10</h3><ExactEquation source={String.raw`\log P=\log_{10}\!\left(\frac{c_o}{c_w}\right)`}/><div className="lp-controls">{[-1,0,1].map(v=><button key={v} aria-pressed={example===v} onClick={()=>setExample(v)}>logP = {v}</button>)}</div><p className="lp-stat">P = {p.p.toFixed(1)}</p><p>正辛醇相浓度是水相的 {p.p.toFixed(1)} 倍。</p><table><thead><tr><th>logP</th><th>P</th><th>浓度关系</th></tr></thead><tbody>{[-1,0,1].map(v=><tr className={v===example?'lp-row-active':''} key={v}><td>{v}</td><td>{10**v}</td><td>{v<0?'水相浓度更高':v>0?'正辛醇相浓度更高':'两相浓度相等'}</td></tr>)}</tbody></table></section><section><h3>读数不等于用途结论</h3><Scale/><p className="lp-callout">这是“在两相间如何分配”的指标，不等于直接测得的水溶解度，也不能单独证明安全性或药效。</p><p className="lp-small">数轴为下页将比较的三个 RDKit 示例；左侧比例是独立设定的教学模型。</p></section></div>;break
    case 'ordering': body=<><StepControls steps={steps} count={4} label="逐个加入分子"/><div className="lp-two"><section><h3>同一条数轴，按数值落点</h3><Scale visible={steps.step}/><SampleTable visible={steps.step}/></section><section className="lp-card"><p className="lp-kicker">RDKIT · 精确结构</p><Molecule index={Math.max(0,steps.step-1)}/><p>当前已放入 {steps.step} / 3 个分子。落点由计算值决定，不由分子图片的尺寸决定。</p></section></div></>;break
    case 'code': body=<><StepControls steps={steps} count={4} label="计算记录"/><div className="lp-two"><section><p className="lp-kicker">输入 → 解析 → 计算 → 新列</p><pre className="lp-code"><span>from rdkit import Chem</span><span>from rdkit.Chem import Descriptors</span><span>rows = []</span><span data-active={steps.step>0}>for smiles in smiles_list:</span><span data-active={steps.step>0}>    mol = Chem.MolFromSmiles(smiles)</span><span>    if mol is None: raise ValueError(smiles)</span><span data-active={steps.step>0}>    value = Descriptors.MolLogP(mol)</span><span data-active={steps.step>0}>    rows.append((smiles, value))</span></pre><p className="lp-small">Python 模板供课后运行。演示逐行显示本地 RDKit 已核对的结果，不声称在网页内运行 Python。</p></section><section className="lp-card"><h3>已完成的结果：{steps.step} / 3</h3><SampleTable visible={steps.step}/><p className="lp-callout">输入结构并未变成“新分子”，只增加了一个描述符字段。cLogP 是 Wildman–Crippen 方法计算值，不是实测。</p></section></div></>;break
    case 'exercise': body=<OrderingExercise/>;break
    case 'distribution': body=<div className="lp-two"><section className="lp-card"><h3>先核对每一行，再数每一个区间</h3><SampleTable/><table><thead><tr><th>区间</th><th>计数</th></tr></thead><tbody>{bins.map((b,i)=><tr key={b.min}><td>[{b.min}, {b.max}{i===3?']':')'}</td><td>{b.count}</td></tr>)}</tbody></table><p className="lp-small">接近零的乙醇是 −0.0014，仍落入 [−2, 0)，不能先四舍五入为 0 再分组。</p></section><section><h3>三个教学示例的 cLogP 分布</h3><div className="lp-bars" role="img" aria-label="四个区间的计数分别为1、1、0、1"><div className="lp-small">数量</div>{bins.map(b=><div className="lp-bin" key={b.min}><strong>{b.count}</strong><div style={{height:b.count*120}}/><span>{b.min} 至 {b.max}</span></div>)}</div><p className="lp-callout">总计 3 行；这不是全库分布。扩展到你的库时，应记录真实有效行数、失败数、计算方法与版本，不能拿这三行代表所有分子。</p></section></div>;break
    case 'evidence': body=<div className="lp-two"><section className="lp-card"><p className="lp-kicker">计算证据</p><h3>RDKit 给的是 cLogP</h3><div className="lp-controls">{LOGP_SAMPLES.map((r,i)=><button key={r.id} aria-pressed={i===index} onClick={()=>setIndex(i)}>{r.id==='glucose'?'葡萄糖':r.name}</button>)}</div><Molecule index={index}/><p className="lp-stat">{LOGP_SAMPLES[index].logP.toFixed(4)}</p><p>已知结构 → 计算方法 → 估计值。没有测量两相浓度。</p></section><section><p className="lp-kicker">物态示意 ≠ 测量证据</p><div className="lp-mini-photo"><OilPhoto/></div><table><tbody><tr><th>图片能说明</th><td>分散油滴与静置分层的定性差异</td></tr><tr><th>图片不能提供</th><td>未知溶质的 LogP、两相浓度、达到平衡的时间</td></tr><tr><th>实测需要</th><td>规定条件下两相平衡，再测同一种溶质的浓度并求比值</td></tr></tbody></table></section></div>;break
    case 'handoff': body=<><div className="lp-flow"><div><strong>已有：分子量</strong><small>描述分子整体质量</small></div><div><strong>新增：cLogP</strong><small>计算的两相分配偏好</small></div><div><strong>下一步：特征矩阵</strong><small>每行同一分子，每列一个描述符</small></div></div><table><thead><tr><th>分子</th><th>SMILES</th><th>MW / g·mol⁻¹</th><th>cLogP</th><th>证据类型</th></tr></thead><tbody>{LOGP_SAMPLES.map(r=><tr key={r.id}><td>{r.name}</td><td><code>{r.smiles}</code></td><td>{r.mw.toFixed(3)}</td><td>{r.logP.toFixed(4)}</td><td>RDKit 计算</td></tr>)}</tbody></table><div className="lp-controls"><button onClick={()=>downloadEvidence('M18-logp-teaching-evidence.json',logpEvidence())}>下载三行教学证据</button><span className="lp-small">包含输入、方法、数值和直方图区间；不冒充学生的全库作业。</span></div><p className="lp-callout">本节完成时，你应能解释正负值、按值排序、运行课文模板，并在自己的结果上写清“计算值，不是实测”。</p></>;break
  }
  return <div className="lp" data-renderer="logp-lab" data-scene={scene}>{body}<footer>{LOGP_DATA_NOTE} 定义依据：<a href="https://www.oecd.org/en/publications/test-no-107-partition-coefficient-n-octanol-water-shake-flask-method_9789264069626-en.html" target="_blank" rel="noreferrer">OECD 107</a>。3D 为平衡分配教学模型，生成图片为定性示意；两者都不是实验记录。</footer></div>
}
