"use client"
import { useState } from 'react'
import type { SlideEntry } from '@/lib/types/api'
import { LessonSlidesProvider, LessonSlideCarousel, LessonSlideshowButton } from './lesson-slides'
const media=['生成图片','Three.js 3D','Three.js + 公式','精确公式','结构与动态','计算过程','排序练习','分布图','图片与证据','成果表']
export function LogpLabPreview({slides}:{slides:SlideEntry[]}) {
  const [index,setIndex]=useState(1),[width,setWidth]=useState('1152')
  return <main className="min-h-screen bg-[var(--paper)] p-5 text-[var(--ink)]"><div className="mx-auto" style={{maxWidth:Number(width)}}><p className="text-xs font-semibold text-[var(--primary-ink)]">分子猎人 · M38 新版 · 本地预览 · 已于 2026-09-09 部署</p><h1 className="my-3 text-2xl font-semibold">同一节课，明确分工的三种媒介</h1><p className="mb-4 text-sm text-[var(--sub)]">第 2、3 页是真正的 Three.js 物体；第 1、9 页使用生成图片（1 张资产复用，约 65 KB）；公式和结构保持精确渲染。点击下方页签切换。</p><label className="mb-4 flex items-center gap-3 text-sm">预览宽度<select aria-label="预览内容宽度" value={width} onChange={e=>setWidth(e.target.value)} className="rounded border bg-[var(--paper)] p-2">{[480,720,960,1152].map(w=><option key={w} value={w}>{w}px</option>)}</select></label><LessonSlidesProvider projectName="molecule-monster-hunter" moduleId="M38" knodeDir="knodes/M38-w0-rdkit-logp" title="M38 · LogP 多媒介讲课" slides={slides} currentIndex={index} onIndexChange={setIndex}><div className="mb-4 flex flex-wrap gap-2"><nav aria-label="M38 新版页码" className="flex flex-1 flex-wrap gap-2">{slides.map((s,i)=><button type="button" key={s.slide_id} aria-label={`第 ${i+1} 页：${media[i]}`} aria-current={index===i?'page':undefined} onClick={()=>setIndex(i)} className={`rounded-lg border px-3 py-2 text-xs ${index===i?'bg-[var(--primary)] text-[var(--primary-foreground)]':'bg-[var(--paper-2)]'}`}>{String(i+1).padStart(2,'0')} · {media[i]}</button>)}</nav><LessonSlideshowButton/></div><LessonSlideCarousel/><p className="mt-4 text-xs text-[var(--sub)]">当前：第 {index+1} 页 · {media[index]}。新版讲稿尚未配音，未沿用旧音频。3D 不可用时会明确显示备用剖面。</p></LessonSlidesProvider></div></main>
}
