"use client"
import { useState } from "react"
import type { SlideEntry } from "@/lib/types/api"
import { SlideBody } from "./teacher-scene-view"
const types=["HTML 证据链","HTML 对照","生成图片 + HTML","Three.js 真 3D + KaTeX","KaTeX + 对照","KaTeX + 预算表","KaTeX + 规格","可记录的动态实验","交互判断","可下载 PNG 成果","工程取舍表","阶段成果递进"]
export function M42SlidePreview({slides}:{slides:SlideEntry[]}) {
  const [index,setIndex]=useState(2)
  const slide=slides[index]
  return <main className="min-h-screen bg-[#edf2f4] px-5 py-8 text-[#203f54] sm:px-10"><div className="mx-auto max-w-[1240px]"><header className="mb-6 flex flex-wrap justify-between gap-4 border-b border-[#c6d6df] pb-5"><div><p className="mb-2 text-xs font-semibold tracking-widest text-[#748d9b]">不同学科 · 多模态教学验证</p><h1 className="text-3xl font-bold">肌电仿生机械手 · M42</h1><p className="mt-3 text-sm text-[#607d8e]">一个舵机，怎样预算五指负载？12 页全部重做，图片／3D／公式各有职责。</p></div><span className="h-fit rounded-full bg-[#fff0de] px-4 py-2 text-xs text-[#a46b36]">本地待审核 · 未部署 · v1</span></header><div className="mb-5 flex flex-wrap gap-2">{[[2,"03 新图片"],[3,"04 转动 3D"],[5,"06 精确公式"],[7,"08 动态实验"],[9,"10 下载成果"]].map(([i,t])=><button key={String(i)} onClick={()=>setIndex(Number(i))} className="rounded-lg border border-[#c5d6df] bg-white px-4 py-2 text-sm">{t}</button>)}</div><nav className="mb-5 flex flex-wrap gap-2" aria-label="M42 slide 页码">{slides.map((s,i)=><button key={s.slide_id} aria-label={`第 ${i+1} 页：${s.title}`} aria-current={index===i?"page":undefined} onClick={()=>setIndex(i)} className={`min-w-11 rounded-lg border px-3 py-2 text-sm ${index===i?"border-[#254e66] bg-[#254e66] text-white":"border-[#c5d6df] bg-white"}`}>{String(i+1).padStart(2,"0")}</button>)}</nav><article className="rounded-2xl border border-[#cbd9e1] bg-[#fffefa] p-5 shadow-sm sm:p-8"><div className="mb-4 flex justify-between gap-3 text-xs font-semibold text-[#75909f]"><span>本次新增 · M42 / {String(index+1).padStart(2,"0")}</span><span className="rounded bg-[#e8f2f4] px-3 py-1 text-[#33758b]">{types[index]}</span></div><h2 className="text-2xl font-bold">{slide.title}</h2><SlideBody key={slide.slide_id} slide={slide} ideaMap={new Map()} renderedSections={{}} projectName="emg-prosthetic-hand" knodeDir="knodes/M42-w0-module" previewImageSources={{"images/finger-states-v1.webp":"/slide-demo/emg-m42-v1/finger-states.webp"}}/><details className="mt-6 border-t border-[#d3dfe5] pt-4 text-sm text-[#647e8c]"><summary>查看本页修订讲稿（暂未配音）</summary><p className="mt-3 leading-7">{slide.audio_script}</p></details></article><footer className="mt-5 flex justify-between"><button disabled={index===0} onClick={()=>setIndex(i=>i-1)} className="rounded-lg border border-[#c4d5df] bg-white px-5 py-3 text-sm disabled:opacity-30">← 上一页</button><span className="py-3 text-sm text-[#6e8797]">{index+1} / 12</span><button disabled={index===11} onClick={()=>setIndex(i=>i+1)} className="rounded-lg bg-[#244e66] px-5 py-3 text-sm text-white disabled:opacity-30">下一页 →</button></footer><p className="mt-5 text-xs leading-6 text-[#7c929e]">模型：理想准静态，绳张力为教学假定，图片不是实测，3D 为程序化装配示意。没有把堵转规格当成持续安全能力。此节点仍在本地审核，尚未替换线上内容。</p></div></main>
}
