"use client"
import {useEffect,useState,useSyncExternalStore} from 'react'
import type {RDKitModule} from '@rdkit/rdkit'
import type {SlideTechnicalVisual} from '@/lib/types/api'
import {getRDKitModule} from '@/lib/rdkit'
import {SMILES_KEY,restoreSmilesRecord} from '@/lib/smiles-reading'
import {REPORT_KEY,READING_TARGETS,GROUPS,readMolecule,groupSvg,makeReadingCard,restoreReadingCards,reportHtml,READING_PYTHON,type ReadingResult,type ReadingCard} from '@/lib/molecule-reading'
import {ExactEquation,StepControls,useTeachingSteps,downloadEvidence} from './screening-common'
import './molecular-funnel.css'
import './skeleton-evidence.css'
import './functional-group.css'
import './molecule-reading.css'
type Spec=Extract<SlideTechnicalVisual,{renderer:'molecule-reading'}>
function useSaved(key:string){return useSyncExternalStore(cb=>{window.addEventListener('storage',cb);window.addEventListener('m06-saved',cb);return()=>{window.removeEventListener('storage',cb);window.removeEventListener('m06-saved',cb)}},()=>{try{return localStorage.getItem(key)}catch{return null}},()=>null)}
function Note({children}:{children:React.ReactNode}){return <aside className="fg-note">{children}</aside>}
function Drawing({svg}:{svg:string}){return <div className="mr-drawing" role="img" aria-label="RDKit 精确分子连接图" dangerouslySetInnerHTML={{__html:svg}}/>}
function Numbers({r}:{r:ReadingResult}){return <div className="mr-numbers">{[['碳 C',r.counts.C],['氮 N',r.counts.N],['氧 O',r.counts.O],['氢 H',r.hydrogens],['重原子间键',r.bonds],['环',r.rings]].map(([k,v])=><div key={k}><strong>{v}</strong><span>{k}</span></div>)}</div>}
function TargetButtons({target,onChange}:{target:string;onChange:(id:string)=>void}){return <div className="fg-controls">{READING_TARGETS.map(t=><button key={t.id} aria-pressed={target===t.id} onClick={()=>onChange(t.id)}>{t.name}</button>)}</div>}
function Source({id}:{id:string}){const t=READING_TARGETS.find(t=>t.id===id)!;return <a href={`https://pubchem.ncbi.nlm.nih.gov/compound/${t.cid}`} target="_blank" rel="noreferrer">PubChem · CID {t.cid} · {t.name}</a>}
function Overview({rdkit}:{rdkit:RDKitModule}){const prior=restoreSmilesRecord(rdkit,useSaved(SMILES_KEY)),cards=restoreReadingCards(rdkit,useSaved(REPORT_KEY));return <><p className="fg-kicker">S1 收官 · 从一条输入到两份可复核的分子档案</p><Note>{prior?`已找到你在 M05 保存的结构输入：${prior.target}。本节增加字段与来源证据。`:'尚未找到本机 M05 记录。示例不自动计入个人成果。'} 本节已保存 {cards.length} / 2 张卡。</Note><div className="fg-two">{READING_TARGETS.map(t=><section className="fg-panel" key={t.id}><h3>{t.name}</h3><Drawing svg={readMolecule(rdkit,t.smiles).svg}/><ExactEquation source={`\\ce{${t.formula}}`}/><p className="fg-small"><Source id={t.id}/> · 参考结构</p></section>)}</div><div className="mr-path"><span>来源与输入</span><b>→</b><span>结构与计数</span><b>→</b><span>官能团依据</span><b>→</b><span>双分子报告</span></div><Note>第 6 页亲自识读、保存；第 7 页下载含精确结构图的独立 HTML 报告。成品就是可以复核的数据作品。</Note></>}
function Dataflow({rdkit}:{rdkit:RDKitModule}){const [branch,setBranch]=useState('drawing'),r=readMolecule(rdkit,READING_TARGETS[0].smiles);return <><div className="mr-path"><span>公开记录 · CID 2244</span><b>→</b><span>SMILES 输入</span><b>→</b><span>RDKit Mol · 连接图对象</span></div><div className="fg-two"><section className="fg-panel"><h3>同一个 Mol，提供三种证据</h3><p className="mr-code">{r.canonical}</p><div className="mr-branches">{[['drawing','绘制结构图'],['counts','读取原子与键'],['groups','匹配官能团']].map(([id,label])=><button key={id} aria-pressed={branch===id} onClick={()=>setBranch(id)}>{label} →</button>)}</div><Note>三路都读取连接对象。计数不依赖“先生成图片”；图片不是计算的原始数据。</Note></section><section className="fg-panel"><h3>当前分支的真实输出</h3>{branch==='drawing'?<Drawing svg={r.svg}/>:branch==='counts'?<><Numbers r={r}/><p>键数按图的边计，双键连接同一对原子，不按两条边计。</p></>:<><ExactEquation source="\\ce{R-C(=O)-OH}"/><p>{r.groups.map(g=>`${g.name} ${g.matches.length} 处`).join('；')}</p><p className="mr-code">{GROUPS[0].smarts}</p></>}<p className="fg-small">输出与输入、来源、版本一起写入报告。</p></section></div></>}
function Groups({rdkit}:{rdkit:RDKitModule}){const [target,setTarget]=useState('aspirin'),[selected,setSelected]=useState('acid'),t=READING_TARGETS.find(t=>t.id===target)!,r=readMolecule(rdkit,t.smiles),g=r.groups.find(g=>g.id===selected)!;return <><TargetButtons target={target} onChange={setTarget}/><div className="fg-controls">{GROUPS.map(g=><button key={g.id} aria-pressed={selected===g.id} onClick={()=>setSelected(g.id)}>{g.name}</button>)}</div><div className="fg-two"><section className="fg-panel"><Drawing svg={groupSvg(rdkit,t.smiles,selected)}/><p>{g.matches.length?`匹配 ${g.matches.length} 处；高亮表示局部连接。`:'未匹配，不显示伪造高亮。'}</p><p className="fg-small">数字是当前原子索引，不是元素个数。高亮包含识别所需邻接原子。</p></section><section className="fg-panel"><h3>{g.name} · 看连接，不只看元素</h3><ExactEquation source={`\\ce{${g.formula}}`}/><p>{g.clue}</p><p className="mr-code">SMARTS：{g.smarts}</p><p>匹配索引：{g.matches.map(m=>m.atoms.join('、')).join('；')||'无'}</p><p className="fg-small">R 是相邻有机基团，两侧不必相同；Ar 表示芳香环。式子仅示意局部连接。</p></section></div><Note>规则针对本节两个例子。对乙酰氨基酚含酚羟基和酰胺，不因出现 N 就叫普通氨基；官能团识别不等于药效预测。</Note></>}
const faults=[['source','缺少来源'],['parse','环没有闭合'],['identity','合法但非目标'],['counts','计数填写错误']] as const
function Audit({rdkit}:{rdkit:RDKitModule}){const [fault,setFault]=useState('source'),[fixed,setFixed]=useState(false),input=!fixed&&fault==='parse'?'C1CC':!fixed&&fault==='identity'?'CCO':READING_TARGETS[0].smiles;let r:ReadingResult|null=null;try{r=readMolecule(rdkit,input)}catch{}const source=fixed||fault!=='source',identity=!!r&&r.canonical===readMolecule(rdkit,READING_TARGETS[0].smiles).canonical,count=!!r&&identity&&(fixed||fault!=='counts');return <><div className="fg-controls">{faults.map(([id,label])=><button key={id} aria-pressed={fault===id} onClick={()=>{setFault(id);setFixed(false)}}>{label}</button>)}</div><div className="fg-two"><section className="fg-panel"><h3>待验样本 · 目标阿司匹林</h3><p className="mr-code">输入：{input}</p>{r?<Drawing svg={r.svg}/>:<div className="mr-empty">解析失败：环标记 1 未闭合。下游结构与计数保持为空。</div>}<button onClick={()=>setFixed(v=>!v)}>{fixed?'查看修复前':'修复当前样本'}</button></section><section><table><thead><tr><th>证据检查</th><th>当前结论</th></tr></thead><tbody>{[['公开记录',source?'CID 2244，可回查':'缺失，药名不能代替来源'],['有效结构',r?'解析通过':'未通过'],['目标身份',!r?'未执行':identity?'规范结构一致':'不一致：乙醇不是目标'],['本人计数',!identity?'未执行':count?'C9 / N0 / O4':'碳误填 8；实际为 9']].map(([a,b])=><tr key={a}><td>{a}</td><td>{b}</td></tr>)}</tbody></table><Note>{source&&identity&&count?'机器可检查项已通过，仍需本人说明与老师复核。':'证据链有缺口，不得标为完整报告。'} 此页演示不写入个人作品。</Note></section></div></>}
const stages=['确认来源','提交输入','解析连接','读取原子与键','匹配官能团','组装报告字段']
function Trace({rdkit}:{rdkit:RDKitModule}){const [target,setTarget]=useState('aspirin'),steps=useTeachingSteps(6),t=READING_TARGETS.find(t=>t.id===target),input=t?.smiles||'C1CC';let r:ReadingResult|null=null;try{r=readMolecule(rdkit,input)}catch{}return <><TargetButtons target={target} onChange={v=>{setTarget(v);steps.reset()}}/><button onClick={()=>{setTarget('invalid');steps.reset()}}>无效环输入</button><StepControls steps={steps} count={6} label="证据流程"/><div className="fg-two"><ol className="fg-trace">{stages.map((label,i)=><li key={label} data-active={steps.step===i}><strong>{i+1} · {label}</strong><span className="fg-small">　{steps.step<i?'待执行':!r&&i>2?'阻断：解析失败':steps.step===i?'当前步骤':'已展示'}</span></li>)}</ol><section className="fg-panel" aria-live="polite"><h3>{stages[steps.step]}</h3><p>{t?<Source id={t.id}/>:'故障示例，没有目标记录'}</p>{steps.step>=1&&<p className="mr-code">{input}</p>}{steps.step>=2&&(r?<Drawing svg={r.svg}/>:<Note>解析失败，后续无原子表、无官能团、无报告。</Note>)}{steps.step>=3&&r&&<Numbers r={r}/>} {steps.step>=4&&r&&<p>匹配：{r.groups.filter(g=>g.matches.length).map(g=>g.name).join('、')}</p>}{steps.step===5&&r&&<p>机器字段齐全，还需第 6 页的本人核对和解释。</p>}</section></div><Note>RDKit {rdkit.version()} 实际计算；动画逐步揭示结果，不代表内部耗时、Python 后端或化学反应。</Note></>}
function downloadText(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function Workbench({rdkit}:{rdkit:RDKitModule}){const raw=useSaved(REPORT_KEY),saved=restoreReadingCards(rdkit,raw),[target,setTarget]=useState('aspirin'),[page,setPage]=useState(0),[input,setInput]=useState(''),[result,setResult]=useState<ReadingResult|null>(null),[counts,setCounts]=useState<Record<string,string>>({}),[groups,setGroups]=useState<string[]>([]),[source,setSource]=useState(false),[scope,setScope]=useState(false),[explanation,setExplanation]=useState(''),[hint,setHint]=useState(false),[message,setMessage]=useState('请输入结构后运行，参考写法不自动计为完成。'),t=READING_TARGETS.find(t=>t.id===target)!;
 const clear=(value:string)=>{setInput(value);setResult(null);setPage(0);setMessage('输入已改变，请重新运行。')}
 const run=()=>{setResult(null);try{const r=readMolecule(rdkit,input);if(r.canonical!==readMolecule(rdkit,t.smiles).canonical)throw Error('解析成功，但不是当前目标的结构。');setResult(r);setMessage('当前输入与目标一致。请进入第 2 步自行识读。')}catch(e){setMessage((e as Error).message)}}
 const save=()=>{try{if(!result||result.input!==input)throw Error('请先运行当前输入。');const values=Object.fromEntries(['C','N','O','bonds','rings'].map(k=>[k,counts[k]?.trim()?Number(counts[k]):NaN])) as ReadingCard['counts'];const card=makeReadingCard(rdkit,{target,input,runInput:result.input,counts:values,groups,sourceConfirmed:source,scopeConfirmed:scope,explanation});const next=[...saved.filter(c=>c.target!==target),card];try{localStorage.setItem(REPORT_KEY,JSON.stringify(next));window.dispatchEvent(new Event('m06-saved'));setMessage(`已保存 ${t.name}。当前 ${next.length} / 2 张卡；第 7 页导出报告。`)}catch{downloadEvidence('M06-record-backup.json',next);setMessage('存储不可用；已下载记录备份。')}}catch(e){setMessage((e as Error).message)}}
 return <><TargetButtons target={target} onChange={v=>{setTarget(v);clear('');setCounts({});setGroups([]);setSource(false);setScope(false);setExplanation('');setHint(false)}}/><div className="mr-wizard">{['输入与运行','计数与定位','说明与保存'].map((s,i)=><button key={s} aria-current={page===i?'step':undefined} disabled={i>0&&!result} onClick={()=>setPage(i)}>{i+1} · {s}</button>)}</div><p role="status" className="mr-message">{message}</p>{page===0?<div className="fg-two"><section className="fg-panel"><h3>1 · 从公开记录获取结构</h3><Source id={target}/><label className="fg-label">本次 SMILES<input aria-label="M06 我的 SMILES" value={input} maxLength={180} onChange={e=>clear(e.target.value)}/></label><div className="fg-controls"><button onClick={run}>运行并核对目标</button><button onClick={()=>clear(t.smiles)}>填入参考写法</button></div><p className="fg-small">不由药名猜结构。改动输入会清空上次运行态。</p></section><section>{result?<><Drawing svg={result.svg}/><p className="mr-code">规范写法：{result.canonical}</p></>:<div className="mr-empty">尚无已核对的当前结构</div>}</section></div>:page===1?<div className="fg-two"><section><Drawing svg={result!.svg}/><button onClick={()=>setHint(v=>!v)}>{hint?'收起计数提示':'查看计数提示'}</button>{hint&&<Numbers r={result!}/>}<Note>重原子不含氢；一对原子之间的双键仍算一条连接边。</Note></section><section className="fg-panel"><h3>2 · 读出可检查的字段</h3><div className="mr-inputs">{[['C','碳数'],['N','氮数'],['O','氧数'],['bonds','重原子间键数'],['rings','环数']].map(([key,label])=><label key={key}>{label}<input aria-label={label} type="number" min="0" max="100" value={counts[key]||''} onChange={e=>setCounts(v=>({...v,[key]:e.target.value}))}/></label>)}</div><p>选择实际存在的官能团（第 3 页可看高亮）：</p><div className="mr-checks">{GROUPS.map(g=><label key={g.id}><input type="checkbox" checked={groups.includes(g.id)} onChange={e=>setGroups(v=>e.target.checked?[...v,g.id]:v.filter(id=>id!==g.id))}/>{g.name}</label>)}</div></section></div>:<div className="fg-two"><section className="fg-panel"><h3>3 · 说明你的识读依据</h3><label className="fg-label">我的结构说明<textarea aria-label="M06 我的结构说明" value={explanation} maxLength={300} onChange={e=>setExplanation(e.target.value)} placeholder="指出连接依据，并说明它不能证明什么。至少 15 字。"/></label><label className="fg-inline"><input type="checkbox" checked={source} onChange={e=>setSource(e.target.checked)}/>已核对本页所列 PubChem 目标来源</label><label className="fg-inline"><input type="checkbox" checked={scope} onChange={e=>setScope(e.target.checked)}/>结构识读不能证明药效、安全性或实测溶解度</label><button onClick={save}>核验并保存分子卡</button></section><section><h3>个人进度：{saved.length} / 2</h3>{READING_TARGETS.map(t=><p key={t.id}>{t.name}：{saved.some(c=>c.target===t.id)?'已保存，可重新核验':'待完成'}</p>)}<Note>机器核验输入、计数与官能团。本人说明需老师复核，不以字数通过代替科学理解。</Note><button onClick={()=>downloadText('m06_read.py',READING_PYTHON,'text/x-python')}>下载完整 Python 模板</button><p className="fg-small">下载不代表已经运行 Python。</p></section></div>}</>
}
function Handoff({rdkit}:{rdkit:RDKitModule}){const raw=useSaved(REPORT_KEY),cards=restoreReadingCards(rdkit,raw),[confirm,setConfirm]=useState(false);return <><div className="mr-banner"><strong>{cards.length} / 2</strong><div><h3>{cards.length===2?'双分子结构记录已核验':'报告仍是草稿'}</h3><p>只读取本人记录；RDKit {rdkit.version()} 重新计算。解释需老师复核。</p></div></div>{cards.length?<><table><thead><tr><th>目标 / 来源</th><th>C / N / O</th><th>键 / 环</th><th>官能团</th></tr></thead><tbody>{cards.map(c=><tr key={c.target}><td><Source id={c.target}/></td><td>{c.counts.C} / {c.counts.N} / {c.counts.O}</td><td>{c.counts.bonds} / {c.counts.rings}</td><td>{c.groups.map(id=>GROUPS.find(g=>g.id===id)!.name).join('、')}</td></tr>)}</tbody></table><div className="fg-two">{cards.map(c=><section className="fg-panel" key={c.target}><Drawing svg={readMolecule(rdkit,c.input).svg}/><blockquote>{c.explanation}</blockquote></section>)}</div></>:<Note>{raw?'记录未通过重新核验，请回第 6 页修正。':'没有个人分子卡，请到第 6 页完成。示例不会自动计入报告。'}</Note>}<div className="fg-controls"><button onClick={()=>downloadText('M06-molecule-report.html',reportHtml(rdkit,cards),'text/html')}>下载{cards.length===2?'完整':'草稿'} HTML 报告</button><button onClick={()=>downloadEvidence('M06-molecule-records.json',cards)}>下载 JSON 记录</button><button onClick={()=>{if(!confirm){setConfirm(true);return}try{localStorage.removeItem(REPORT_KEY);window.dispatchEvent(new Event('m06-saved'));setConfirm(false)}catch{}}}>{confirm?'确认清除 M06 记录':'清除 M06 本机记录'}</button></div><Note>HTML 报告离线可打开，含结构图、来源和本人说明。下一阶段把同样字段排成数据表，再批量计算。只做软件，不制备或服用示例物质。</Note></>}
export function MoleculeReadingVisual({visual}:{visual:Spec}){const [rdkit,setRDKit]=useState<RDKitModule|null>(null),[error,setError]=useState('');useEffect(()=>{let live=true;getRDKitModule().then(r=>{if(live)setRDKit(r)}).catch(()=>{if(live)setError('RDKit 加载失败，请刷新重试；未生成替代成功数据。')});return()=>{live=false}},[]);const views={overview:Overview,dataflow:Dataflow,groups:Groups,audit:Audit,trace:Trace,workbench:Workbench,handoff:Handoff},View=views[visual.scene];return <div className="fg m03-v2 mr" data-renderer="molecule-reading" data-scene={visual.scene}>{rdkit?<View rdkit={rdkit}/>:<p role="status">{error||'正在加载精确结构引擎…'}</p>}<footer>RDKit 精确连接图、SMARTS 匹配、KaTeX 化学式与可操作证据流程。仅做软件识读，不由局部结构推断药效与安全。</footer></div>}
