"use client"
import { useState } from "react"
import type { SlideEntry } from "@/lib/types/api"
import { SlideBody } from "./teacher-scene-view"

export function MoleculeBatchPreview({ m78, m85 }: { m78: SlideEntry[]; m85: SlideEntry[] }) {
  const [node, setNode] = useState<"M78" | "M85">("M78"), [index, setIndex] = useState(0)
  const slides = node === "M78" ? m78 : m85, slide = slides[index]
  const jump = (which: "M78" | "M85", page: number) => { setNode(which); setIndex(page) }
  return <main className="min-h-screen bg-[#EDF3F5] px-4 py-7 text-[#234759] sm:px-8"><div className="mx-auto max-w-[1240px]"><header className="mb-6 border-b border-[#C7D9E0] pb-5"><p className="text-xs font-semibold tracking-widest text-[#628393]">分子怪兽猎人 / 本次新增 2 个完整节点</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-bold sm:text-3xl">从评估模型，到筛选候选分子</h1><span className="rounded-full border border-[#CFB997] bg-[#FFF5E8] px-3 py-1.5 text-xs text-[#916C3C]">22 页全部重做 · 本地待审 · 未部署</span></div><p className="mt-3 text-sm text-[#6B8290]">实际可操作的阈值扫描、精确公式、专业分子结构与可下载证据。全项目 47 个节点仍在推进。</p></header>
    <nav className="mb-4 flex flex-wrap gap-3" aria-label="节点切换">{(["M78", "M85"] as const).map(n => <button key={n} type="button" aria-pressed={node === n} onClick={() => jump(n, 0)} className={`rounded-lg border px-5 py-3 text-sm font-semibold ${node === n ? "border-[#27566D] bg-[#27566D] text-white" : "border-[#BFD3DD] bg-white"}`}>{n === "M78" ? "M78 · ROC / AUC（11 页）" : "M85 · Lipinski 筛选（11 页）"}</button>)}</nav>
    <div className="mb-5 flex flex-wrap gap-2 text-xs">{(node === "M78" ? [[3, "04 动态扫描"], [5, "06 同分与排序反例"], [8, "09 亲手计算"]] : [[3, "04 RDKit 结构与数值"], [5, "06 集合逻辑反例"], [6, "07 动态门槛与记录"], [9, "10 证据边界"]]).map(([page, label]) => <button key={String(page)} type="button" onClick={() => setIndex(Number(page))} className="rounded-md border border-[#C3D6DF] bg-white px-3 py-2">{label}</button>)}</div>
    <nav aria-label="新版 slide 页码" className="mb-4 flex flex-wrap gap-2">{slides.map((s, i) => <button type="button" key={s.slide_id} aria-label={`第 ${i + 1} 页：${s.title}`} aria-current={index === i ? "page" : undefined} onClick={() => setIndex(i)} className={`min-w-10 rounded-md border px-3 py-2 text-sm ${index === i ? "border-[#377D69] bg-[#377D69] text-white" : "border-[#C6D8DF] bg-white"}`}>{String(i + 1).padStart(2, "0")}</button>)}</nav>
    <article className="rounded-xl border border-[#C6D8DF] bg-[#FFFEFB] p-5 sm:p-7"><div className="mb-3 flex flex-wrap justify-between gap-2 text-xs font-semibold text-[#6A8A98]"><span>{node} / {String(index + 1).padStart(2, "0")} · 本批新生成</span><span>evidence-v2 · 精确内容 + 有意义的交互</span></div><h2 className="mb-4 text-xl font-bold sm:text-2xl">{slide.title}</h2><SlideBody key={node + slide.slide_id} slide={slide} ideaMap={new Map()} renderedSections={{}} projectName="molecule-monster-hunter" knodeDir={node === "M78" ? "knodes/M78-w0-roc" : "knodes/M85-w0-lipinski"} /><details className="mt-5 border-t border-[#D5E1E6] pt-3 text-sm text-[#6B818E]"><summary className="cursor-pointer">查看同步更新的讲稿（暂未配音）</summary><p className="mt-3 leading-7">{slide.audio_script}</p></details></article>
    <footer className="mt-4 flex justify-between gap-3"><button type="button" disabled={index === 0} onClick={() => setIndex(i => i - 1)} className="rounded-lg border border-[#C4D6DF] bg-white px-5 py-2.5 text-sm disabled:opacity-30">← 上一页</button><span className="self-center text-sm text-[#6D8793]">{node} · {index + 1} / {slides.length}</span><button type="button" disabled={index === slides.length - 1} onClick={() => setIndex(i => i + 1)} className="rounded-lg bg-[#27566D] px-5 py-2.5 text-sm text-white disabled:opacity-30">下一页 →</button></footer><p className="mt-6 text-xs leading-6 text-[#6C8794]">这是独立版本化预览，没有替换线上课程或旧音频。M78 / M85 的交互不调用外部模型。<a href="/slide-preview/emg-m42" className="ml-2 underline">查看上一轮机械手多媒介样例</a> · <a href="/slide-preview/m81" className="underline">M81 已部署版本</a></p>
  </div></main>
}
