"use client"
import {useEffect,useState,useSyncExternalStore} from 'react'
import type {SlideTechnicalVisual} from '@/lib/types/api'
import {getRDKitModule} from '@/lib/rdkit'
import {BRIEF_KEY,parseBrief} from '@/lib/discovery-brief'
import {CHECK_SCRIPT,EVIDENCE_KEY,initialRuntime,parseRuntimeOutput,restoreRuntimeEvidence,runRuntime,runtimeTrace,type RuntimeAction,type RuntimeState} from '@/lib/rdkit-runtime'
import {downloadEvidence,StepControls,useTeachingSteps} from './screening-common'
import './rdkit-runtime.css'

function useLocalRecord(key:string,event:string){return useSyncExternalStore(cb=>{window.addEventListener('storage',cb);window.addEventListener(event,cb);return()=>{window.removeEventListener('storage',cb);window.removeEventListener(event,cb)}},()=>{try{return window.localStorage.getItem(key)}catch{return null}},()=>null)}
function Code({children}:{children:string}){return <pre className="rr-code"><code>{children}</code></pre>}
function Note({children}:{children:React.ReactNode}){return <aside className="rr-note">{children}</aside>}
function DownloadScript(){return <button onClick={()=>{const url=URL.createObjectURL(new Blob([CHECK_SCRIPT+'\n'],{type:'text/x-python'}));const a=document.createElement('a');a.href=url;a.download='check_rdkit.py';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>下载检查脚本 .py</button>}
function Goal(){const brief=parseBrief(useLocalRecord(BRIEF_KEY,'m01-brief-saved'));return <><div className="rr-path"><section><span>01 · 来自上一节</span><h3>研究目标</h3><p>{brief?.question||'本机未找到 M01 立项卡；可回 M01 填写。'}</p></section><section><span>02 · 今天接通</span><h3>指定 Python 环境</h3><p>安装包 → 当前会话导入 → 读取版本</p></section><section><span>03 · 交给下一节</span><h3>可复查的运行记录</h3><p>Python 版本、解释器位置、RDKit 版本</p></section></div><div className="rr-two"><section className="rr-panel"><h3>不是“点亮一个成功图标”</h3><dl><dt>今天的输入</dt><dd>你的研究目标 + 准备用来学习的电脑环境</dd><dt>今天的输出</dt><dd>自己运行得到的 JSON / 截图</dd><dt>下一步用途</dt><dd>在同一个环境中画结构、算特征</dd></dl></section><section><h3>分清两种运行位置</h3><p>本网页能运行浏览器版 RDKit，帮你理解库的功能。</p><Note>它不能检查或安装你电脑上的 Python 包。网页里看见结构图，不等于本机 Python 已配置好。</Note><p className="rr-small">安装软件时请家长协助。先完成基础导入检查，不代表后续每一个功能都已测试。</p></section></div></>}
function Places(){const [where,setWhere]=useState<'terminal'|'notebook'>('notebook');return <><div className="rr-controls"><button aria-pressed={where==='notebook'} onClick={()=>setWhere('notebook')}>Jupyter / IPython 单元格</button><button aria-pressed={where==='terminal'} onClick={()=>setWhere('terminal')}>终端 / Anaconda Prompt</button></div><div className="rr-two"><section><p className="rr-kicker">第一步 · 安装到要使用的环境</p><h3>{where==='notebook'?'让当前 kernel 使用的 Python 安装包':'先进入老师指定的 Python 环境'}</h3><Code>{where==='notebook'?'%pip install rdkit':'python -m pip install rdkit'}</Code><p>{where==='notebook'?'这是 IPython 的 magic 指令，不是普通 Python 语法。安装后按提示重启 kernel，再运行下面的导入。':'python 必须指向你打算使用的解释器；有些电脑命令叫 python3。不要在 Python 的 >>> 提示符后粘贴安装命令。'}</p><Note>网络、Python 版本与平台会影响安装。失败时保存完整错误信息，请家长一起查看官方安装说明。</Note></section><section className="rr-panel"><p className="rr-kicker">第二步 · Python 代码</p><h3>导入与打印，是另一件事</h3><Code>{where==='notebook'?'import rdkit\nprint(rdkit.__version__)':'python -c "import rdkit; print(rdkit.__version__)"'}</Code><dl><dt>成功时</dt><dd>显示实际版本号，不要求和课件示例一致。</dd><dt>失败时</dt><dd>先看报错类型，再检查解释器 / kernel。</dd></dl><p className="rr-small">此页仅提供指令，不会替你执行或安装。</p></section></div></>}
type LibraryResult={svg:string;version:string;mass:number|null;error:string}
function Library(){const [smiles,setSmiles]=useState('CCO'),[result,setResult]=useState<LibraryResult|null>(null)
 useEffect(()=>{let live=true;getRDKitModule().then(rdkit=>{let mol=null;try{mol=rdkit.get_mol(smiles);if(!mol){if(live)setResult({svg:'',version:rdkit.version(),mass:null,error:'无法解析这个 SMILES：环标记 1 没有闭合。'});return}const descriptors=JSON.parse(mol.get_descriptors());const svg=mol.get_svg_with_highlights(JSON.stringify({width:460,height:210,explicitMethyl:true}));if(live)setResult({svg,version:rdkit.version(),mass:descriptors.amw,error:''})}catch{if(live)setResult({svg:'',version:rdkit.version(),mass:null,error:'RDKit 无法生成这条结构，请核对输入。'})}finally{mol?.delete()}}).catch(()=>{if(live)setResult({svg:'',version:'不可用',mass:null,error:'浏览器 RDKit 加载失败；仍可阅读下面的 Python 对应代码。'})});return()=>{live=false}},[smiles])
 return <><div className="rr-controls">{[['CCO','乙醇 CCO'],['O','水 O'],['C1CC','无效写法 C1CC']].map(([s,label])=><button key={s} aria-pressed={smiles===s} onClick={()=>{setResult(null);setSmiles(s)}}>{label}</button>)}</div><div className="rr-two"><section><p className="rr-kicker">输入 → 解析 → 绘制 / 计算</p><h3>不是手工画几个圆圈</h3><Code>{`from rdkit import Chem\nfrom rdkit.Chem import Descriptors\n\nmol = Chem.MolFromSmiles("${smiles}")\nif mol is not None:\n    print(Descriptors.MolWt(mol))`}</Code><p>左侧是可在 Python 中使用的对应代码；右侧通过本网页的 RDKit.js 实际调用结构解析、绘图和描述符计算。</p><Note>先检查解析是否成功，再调用后续功能；无效输入没有分子量结果。</Note></section><section className="rr-panel"><p className="rr-kicker">真实浏览器库输出 · 不是本机 Python 检查</p><h3>RDKit.js <span data-runtime-version>{result?.version||'加载中'}</span></h3><div className="rr-molecule" role="img" aria-label={`${smiles} 的 RDKit 结构输出`}>{result?.svg?<div dangerouslySetInnerHTML={{__html:result.svg}}/>:<p role="status">{result?.error||'正在载入实际结构库…'}</p>}</div><dl><dt>结构写法</dt><dd><code>{smiles}</code></dd><dt>平均摩尔质量</dt><dd data-molecular-mass>{result?.mass!==null&&result?.mass!==undefined?`${result.mass.toFixed(3)} g/mol`:'未计算'}</dd></dl></section></div></>
}
function StateView({state}:{state:RuntimeState}){return <div className="rr-runtime" aria-label="教学环境与会话状态"><div className="rr-environments">{(['A','B'] as const).map(e=><section key={e} data-active={state.active===e}><span>环境 {e}{state.active===e?' · 当前':''}</span><h3>{state.installed[e]?'RDKit 已安装':'尚无 RDKit'}</h3><p>{state.installed[e]?'包文件保留在此环境':'别的环境装好，不代表这里有'}</p></section>)}</div><section className="rr-session"><span>会话 #{state.session} · 使用环境 {state.active}</span><h3>当前名称：{state.bound?<code>rdkit → 模块对象</code>:'还没有 rdkit 这个名字'}</h3><p>重启会清空当前名称绑定，不会卸载环境中的包。</p></section></div>}
function Binding(){const [state,setState]=useState(initialRuntime),[message,setMessage]=useState('先安装到 A，再导入；最后试试重启。');const act=(a:RuntimeAction)=>{const r=runRuntime(state,a);setState(r.state);setMessage(r.output)};return <><div className="rr-controls"><button onClick={()=>act('install-A')}>1 · 安装到 A</button><button onClick={()=>act('import')}>2 · import rdkit</button><button onClick={()=>act('restart')}>3 · 重启会话</button><button onClick={()=>{setState(initialRuntime());setMessage('已重置教学状态。')}}>重置对照</button></div><StateView state={state}/><p className="rr-log" role="status">{message}</p><Note>在同一个会话里，后面的单元格可以继续使用已有名字；不是每一格都必须重新导入。<code>import rdkit</code> 也不等于加载全部子模块，使用 Chem 时要显式导入。</Note></>}
const ACTION_CODE:Record<RuntimeAction,string>={'install-A':'环境 A: python -m pip install rdkit','install-B':'环境 B: python -m pip install rdkit','use-A':'选择环境 A，启动新会话','use-B':'选择环境 B，启动新会话',import:'import rdkit',print:'print(rdkit.__version__)',restart:'Restart kernel / 重新启动解释器'}
function Trace(){const trace=runtimeTrace(),steps=useTeachingSteps(trace.length),row=trace[steps.step];return <><StepControls steps={steps} count={trace.length} label="安装与导入流程"/><div className="rr-two"><ol className="rr-trace" aria-label="执行步骤">{trace.map((t,i)=><li key={i} data-current={i===steps.step}><button aria-current={i===steps.step?'step':undefined} onClick={()=>steps.jump(i)}><b>{i+1}</b><code>{t.action?ACTION_CODE[t.action]:'开始：环境 A / 会话 #1'}</code></button></li>)}</ol><section><StateView state={row.state}/><p className="rr-log" role="status">{row.output}</p></section></div><Note>播放的是教学状态机，不是后台执行 Python。打印的版本是固定教学值；第 5 步重启后，先重新导入才能继续读取版本。</Note></>}
function Terminal(){const [state,setState]=useState(initialRuntime),[log,setLog]=useState<ReturnType<typeof runRuntime>[]>([]),[last,setLast]=useState('挑战：先直接打印，再判断错误发生在哪一层。');const act=(a:RuntimeAction)=>{const r=runRuntime(state,a);setState(r.state);setLog(v=>[...v.slice(-19),r]);setLast(r.output)};return <><div className="rr-controls"><button onClick={()=>act('install-A')}>安装到 A</button><button onClick={()=>act('install-B')}>安装到 B</button><button onClick={()=>act('use-A')}>用 A 开新会话</button><button onClick={()=>act('use-B')}>用 B 开新会话</button></div><div className="rr-two"><section><StateView state={state}/><div className="rr-controls"><button onClick={()=>act('import')}>运行 import</button><button onClick={()=>act('print')}>运行 print</button><button onClick={()=>act('restart')}>重启会话</button></div></section><section className="rr-panel"><p className="rr-kicker">有限指令练习 · 非 Python 解释器</p><h3>因果日志</h3><div className="rr-log" role="status" data-runtime-log>{last}</div><ol className="rr-recent">{log.slice(-3).map((r,i)=><li key={`${log.length}-${i}`}><code>{ACTION_CODE[r.action]}</code><span data-error={r.error}>{r.error?'错误':'状态更新'} · 环境 {r.state.active} / 会话 {r.state.session}</span></li>)}</ol><div className="rr-controls"><button onClick={()=>{setState(initialRuntime());setLog([]);setLast('教学状态与日志已重置。')}}>重置练习</button><button onClick={()=>downloadEvidence('M02-teaching-runtime-trace.json',{teachingOnly:true,notPythonExecution:true,versionIsFixedExample:true,log,retained:'仅最近 20 次动作'})}>下载教学过程</button></div></section></div><Note><b>NameError：</b>当前会话未绑定名字 → 先导入。<b> ModuleNotFoundError：</b>当前环境找不到包 → 核对环境和安装。日志只保留最近 20 次动作。</Note></>}
function EvidenceFields({raw}:{raw:string|null}){const e=restoreRuntimeEvidence(raw);return e?<dl><dt>来源</dt><dd>本人粘贴的 Python 输出 · 未独立核验</dd><dt>Python</dt><dd>{e.python}</dd><dt>RDKit</dt><dd>{e.rdkit}</dd><dt>解释器</dt><dd><code>{e.executable}</code></dd></dl>:<p>本机未找到有效 M02 记录。不会把网页 RDKit 版本或教学值填成你的成果。</p>}
function Evidence(){const saved=useLocalRecord(EVIDENCE_KEY,'m02-runtime-saved'),[raw,setRaw]=useState(''),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState('粘贴你自己的实际运行输出；此页仅做格式检查，不远程核验。'),[clearing,setClearing]=useState(false)
 const check=parseRuntimeOutput(raw,confirmed)
 const save=()=>{if(!check.evidence){setMessage(check.problem);return}try{localStorage.setItem(EVIDENCE_KEY,JSON.stringify(check.evidence));window.dispatchEvent(new Event('m02-runtime-saved'));setMessage('自报记录已保存到本机，并已下载。没有上传服务器。')}catch{setMessage('本机存储不可用；已下载备份。')}downloadEvidence('M02-my-runtime-evidence.json',check.evidence)}
 const restore=()=>{const e=restoreRuntimeEvidence(saved);if(e){setRaw(JSON.stringify({python:e.python,executable:e.executable,rdkit:e.rdkit},null,2));setConfirmed(false);setMessage('已恢复字段；请重新核对来源后再保存。')}}
 const clear=()=>{if(!clearing){setClearing(true);setMessage('请先下载备份；再次点击才清除本机记录。');return}try{localStorage.removeItem(EVIDENCE_KEY);window.dispatchEvent(new Event('m02-runtime-saved'));setRaw('');setConfirmed(false);setClearing(false);setMessage('已清除本机 M02 记录。')}catch{setMessage('本机存储不可用，未清除。')}}
 return <div className="rr-two"><section><h3>1 · 在自己的 Python 里运行</h3><Code>{CHECK_SCRIPT}</Code><DownloadScript/><p className="rr-small">终端可运行 <code>python check_rdkit.py</code>；Jupyter 可直接粘贴代码运行。不要把文件名保存成 rdkit.py，避免遮住库。</p><Note>解释器路径可能含用户名，可自行遮去用户名部分。不要粘贴密码、手机号或完整终端历史。</Note></section><section className="rr-panel rr-form"><h3>2 · 粘贴实际输出，留下证据</h3><label>检查脚本输出的 JSON<textarea aria-label="自己的 Python 运行输出" value={raw} maxLength={5000} onChange={e=>setRaw(e.target.value)} placeholder={'粘贴自己的输出；此处没有默认成功示例。'}/></label><label className="rr-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>这是我自己运行得到的输出，不是课件示例。</label><div className="rr-controls"><button onClick={save}>检查、保存并下载</button>{saved&&<button onClick={restore}>恢复已保存字段</button>}<button onClick={clear}>{clearing?'确认清除本机记录':'清除本机记录'}</button></div><p className="rr-small" role="status">{message}</p><EvidenceFields raw={saved}/></section></div>
}
function Next(){const saved=useLocalRecord(EVIDENCE_KEY,'m02-runtime-saved');return <div className="rr-two"><section className="rr-panel"><p className="rr-kicker">输入证据 · 不拿默认值充数</p><h3>你保存的 M02 运行记录</h3><EvidenceFields raw={saved}/><Note>格式完整不等于远程验收通过。基础版本检查也不能证明所有化学算法与后续模型都正确。</Note></section><section><h3>下一站 M03 · 从结构开始认识分子</h3><ol className="rr-deliverables"><li><b>带走</b><span>自己的环境记录、Python 脚本和截图备份</span></li><li><b>继续</b><span>在同一环境使用工具，核对原子与分子结构</span></li><li><b>再留下</b><span>输入的结构写法、输出图与可解释的观察</span></li></ol><p>如果换了环境或重启会话，先重新核对环境与导入，再继续。未保存记录时，回第 7 页补齐自己的证据。</p></section></div>}
export function RdkitRuntimeVisual({visual}:{visual:Extract<SlideTechnicalVisual,{renderer:'rdkit-runtime'}>}){let body:React.ReactNode;switch(visual.scene){case 'goal':body=<Goal/>;break;case 'places':body=<Places/>;break;case 'library':body=<Library/>;break;case 'binding':body=<Binding/>;break;case 'trace':body=<Trace/>;break;case 'terminal':body=<Terminal/>;break;case 'evidence':body=<Evidence/>;break;case 'next':body=<Next/>;break}return <div className="rr" data-renderer="rdkit-runtime" data-scene={visual.scene}>{body}<footer>讲清运行环境，保留真实证据。<a href="https://www.rdkit.org/docs/Install.html" target="_blank" rel="noreferrer">RDKit 安装</a> · <a href="https://docs.python.org/3/tutorial/modules.html" target="_blank" rel="noreferrer">Python 模块</a> · <a href="https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-pip" target="_blank" rel="noreferrer">Notebook %pip</a></footer></div>}
