'use client'
import { useEffect, useRef, useState } from 'react'
import { useLearningRecord } from '@/lib/hooks/use-learning-record'
import type { LearningBody, LearningScope } from '@/lib/api/learning-records'
import { CASES, FORECAST, HISTORY, fresh, key, stableJSON, validWorkspace, checks, physicalChecks, csvRows, forecastRows, mae, simulate, program, type Workspace, type Run, type Physical } from '@/lib/project-lines/renewable-model'
import { LearningRecordStatus } from './learning-record-status'
import styles from './renewable-workspace.module.css'

export const finalNode:Record<string,string>={'build-a-solar-tracker':'M05','design-a-wind-rotor':'M05','store-energy-for-later':'M04','write-energy-dispatch-rules':'M04','build-a-wind-solar-station':'M06','run-an-energy-mission':'M05'}
export const renewableScope=(id:string,phase='work'):LearningScope=>({library_slug:id,module_id:phase==='work'?'WORK':finalNode[id]||'M01',activity_id:`renewable-${phase}`,kind:phase==='work'?'classroom':'assignment',content_version:'1.0'})
export const energyBody=(a:Workspace):LearningBody=>({answers:[{question_id:'design',question:'我的设计与比较',answer:a.decision||'已保留 '+a.runs.length+' 次能源实验，参数与结果见作品。'}],artifact:structuredClone(a) as unknown as Record<string,unknown>,client_context:{schema:'renewable-energy/1',model:'wind-solar/1',data_origin:'simulated-and-learner-evidence'}})
export function download(name:string,text:string){const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function CheckList({items}:{items:{title:string;passed:boolean}[]}){return <ul className={styles.checks}>{items.map(x=><li key={x.title} data-pass={x.passed}><span>{x.passed?'已具备':'待补充'}</span>{x.title}</li>)}</ul>}
export function EnergyPlot({run:r}:{run:Run}){
 const generation=['solar','wind'].includes(r.mode),max=Math.max(1,...r.points.map(p=>p.input),...r.points.map(p=>p.load)),poly=(field:'input'|'load')=>r.points.map(p=>`${40+p.t/120*570},${180-p[field]/max*140}`).join(' ')
 return <><div className={styles.stats}><div><strong>{r.meanPower.toFixed(2)}<small> mW</small></strong><span>平均采集前输入</span></div><div><strong>{generation?r.inputJ.toFixed(3):r.alive}<small>{generation?' J':' / 120 s'}</small></strong><span>{generation?'两分钟采集前输入能量':'关键服务时间'}</span></div><div><strong>{generation?Math.max(...r.points.map(p=>p.input)).toFixed(2):Math.sqrt(2*r.endJ/r.config.capacitance).toFixed(2)}<small>{generation?' mW':' V'}</small></strong><span>{generation?'峰值采集前输入':'结束时电容电压'}</span></div></div><svg className={styles.plot} viewBox="0 0 660 220" role="img" aria-label="输入功率与负载功率曲线，原始数据在下方"><title>功率随时间变化 · 教学模拟</title>{[0,.5,1].map(v=><g key={v}><path d={`M40 ${180-v*140}H610`} stroke="#dce0d5"/><text x="32" y={184-v*140} textAnchor="end" fontSize="11" fill="#657164">{(max*v).toFixed(1)}</text></g>)}<polyline points={poly('input')} fill="none" stroke="#b56b4d" strokeWidth="3"/>{!generation&&<polyline points={poly('load')} fill="none" stroke="#47776f" strokeWidth="2.5"/>}{[0,30,60,90,120].map(t=><text key={t} x={40+t/120*570} y="199" fontSize="11" textAnchor="middle" fill="#657164">{t}s</text>)}<text x="40" y="20" fill="#b56b4d" fontSize="12">输入 mW</text>{!generation&&<text x="150" y="20" fill="#47776f" fontSize="12">实际供给负载 mW</text>}</svg><p className={styles.caption}>能量账本：起始 {r.startJ.toFixed(3)} J ＋ 输入 {r.inputJ.toFixed(3)} J ＝ 负载 {r.loadJ.toFixed(3)} ＋ 损耗 {r.lossJ.toFixed(3)} ＋ 满电溢出 {r.spillJ.toFixed(3)} ＋ 结束储能 {r.endJ.toFixed(3)} J。</p><details><summary>查看原始模拟数值</summary><div className={styles.tableScroll}><table><thead><tr><th>结束秒</th><th>输入 mW</th><th>负载 mW</th><th>电容 V</th><th>采样 V</th><th>可选任务</th></tr></thead><tbody>{r.points.map(p=><tr key={p.t}><td>{p.t}</td><td>{p.input.toFixed(3)}</td><td>{p.load.toFixed(3)}</td><td>{p.voltage.toFixed(3)}</td><td>{p.sensed===null?'缺测':p.sensed.toFixed(3)}</td><td>{p.optional?'开启':'暂停'}</td></tr>)}</tbody></table></div></details></>
}
function Report({a}:{a:Workspace}){return <article className={styles.report} data-renewable-report><h4>我的能源作品档案</h4><p>教学模型 wind-solar/1；模拟与实测分别列出。</p><p><strong>设计选择：</strong>{a.decision||'短体验的操作结果见两版对照。'}</p><p><strong>证据边界：</strong>{a.limit||'计算数据，尚未验证实际装置。'}</p><details><summary>这版参数与规则</summary><pre>{JSON.stringify(a.config,null,2)}</pre><pre>{program(a.config)}</pre></details>{a.sources.length>0&&<p>接入本人作品：{a.sources.map(s=>`${s.project} / ${s.submission}`).join('；')}</p>}{a.runs.map((r,i)=><details key={r.id}><summary>实验 {i+1} · {CASES[r.scenario]} · {r.config.tilt}° / {r.config.pitch}° / {r.config.control}</summary><EnergyPlot run={r}/></details>)}{a.hypothesis&&<p>诊断假设：{a.hypothesis}；探查：{a.probes.join('、')}；依据与修复：{a.repair}</p>}{a.frozen&&<div className={styles.notice}><h4>固定的第一次任务记录</h4><p>{a.frozen.question}；目标 {a.frozen.target} 秒；冻结于 {a.frozen.at}。</p>{a.frozen.first&&<><p>第一次数字服务 {a.frozen.first.alive} 秒：{a.frozen.first.alive>=a.frozen.target?'达到':'未达到'}原目标。后续为事后探索。</p><EnergyPlot run={a.frozen.first}/></>}{a.frozen.prediction&&<p>新数据 MAE：基线 {mae(a.frozen.prediction,'baseline').toFixed(3)} / 学习模型 {mae(a.frozen.prediction,'predicted').toFixed(3)} mW。</p>}{a.frozen.realFirst&&<details><summary>首次实物原始记录（不改写）</summary><pre>{a.frozen.realFirst}</pre></details>}</div>}{a.physical.revision&&<><h4>本人实物证据</h4><p>{a.physical.material}；{a.physical.part}；接线：{a.physical.wiring}</p><p>试配前：{a.physical.before}；改动：{a.physical.change}；复测：{a.physical.after}</p><details><summary>本人源文件与原始 CSV</summary><pre>{a.physical.source}</pre><pre>{a.physical.csv}</pre></details>{a.physical.photos.map(p=><figure key={p.id}><img src={p.data} alt={p.caption} className={styles.photo}/><figcaption>{p.caption}</figcaption></figure>)}<p>材料由学习者提供，等待人工评阅。平台未自动确认照片真实性与实际性能。</p></>}</article>}
export function EnergyDelivery({id,a,ready,micro=false,prototype=false}:{id:string;a:Workspace;ready:boolean;micro?:boolean;prototype?:boolean}){
 const record=useLearningRecord(renewableScope(id,prototype?'prototype':'final'),{answers:[]}),physical=!micro&&!prototype&&id!=='write-energy-dispatch-rules'
 const all=micro?checks(id,a).slice(0,2):[...checks(id,a),...(physical?physicalChecks(a):[]),...(physical&&id==='run-an-energy-mission'?[{title:'保留冻结方案对应的第一次实物记录',passed:!!a.frozen?.realFirst}]:[])],complete=ready&&all.every(c=>c.passed),payload=energyBody(a),same=!!record.submittedAt&&stableJSON(record.body)===stableJSON(payload)
 const snapshots=record.history.length?record.history:record.submittedAt?[{id:'local',created_at:record.submittedAt,body:record.body}]:[]
 async function submit(){if(record.pending){await record.session.submit();return}if(!complete)return;record.session.update(payload);await record.session.submit()}
 return <section className={styles.delivery} id={prototype?'digital-prototype':'project-delivery'}><p className={styles.eyebrow}>{micro?'带走我的发现':prototype?'阶段作品':'最终交付'}</p><h3>{micro?'我的两版能源实验':prototype?'先保存数字原型':'把自己的作品交给证据'}</h3><CheckList items={all}/>{prototype&&<p>可以先保存这一阶段，等打印和器材准备好再回来。正式实物作品还需自己的制作与测量。</p>}<button className={styles.primary} disabled={!record.ready||record.busy||record.conflict||(!record.pending&&(!complete||same))} onClick={submit}>{record.pending?'重试提交':same?'已保存 · 可在下方回看':micro?'保存我的发现':prototype?'保存数字原型':'提交最终作品'}</button><LearningRecordStatus record={record}/>{snapshots.map(s=><details key={s.id}><summary>已交付版本 · {new Date(s.created_at).toLocaleString()}</summary>{validWorkspace(s.body.artifact)?<Report a={s.body.artifact}/>:<p>记录版本不同，无法在当前工作台打开。</p>}</details>)}</section>
}
async function photoData(file:File){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>12_000_000)throw Error('请选择小于 12 MB 的 JPG、PNG 或 WebP。');const bmp=await createImageBitmap(file);try{const scale=Math.min(1,600/Math.max(bmp.width,bmp.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bmp.width*scale);canvas.height=Math.round(bmp.height*scale);const ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bmp,0,0,canvas.width,canvas.height);for(const quality of [.65,.45,.25]){const data=canvas.toDataURL('image/jpeg',quality);if(data.length<=52000)return data}throw Error('图片细节过多，请裁剪后再上传。')}finally{bmp.close()}}
export function PhysicalEvidence({a,update,disabled}:{a:Workspace;update:(a:Workspace)=>void;disabled:boolean}){
 const p=a.physical,[message,setMessage]=useState(''),[busy,setBusy]=useState(false),live=useRef({a,disabled})
 useEffect(()=>{live.current={a,disabled}},[a,disabled]);useEffect(()=>()=>{live.current.disabled=true},[])
 const edit=(patch:Partial<Physical>)=>update({...a,physical:{...p,...patch}}),registered=p.revision===key(a.config)
 async function upload(file:File,kind:'photo'|'source'){setBusy(true);const revision=p.revision;try{if(kind==='source'&&file.size>16000)throw Error('源文件限 16 KB。');const data=kind==='photo'?await photoData(file):await file.text();const current=live.current;if(current.disabled||current.a.physical.revision!==revision)return;if(kind==='source'){update({...current.a,physical:{...current.a.physical,source:data}})}else if(current.a.physical.photos.length<2){update({...current.a,physical:{...current.a.physical,photos:[...current.a.physical.photos,{id:crypto.randomUUID(),data,caption:'',revision}]}})}setMessage('已读入，请补上证据说明。')}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 return <section className={styles.section}><h4>自己的打印与实测</h4><p>登记后再填写证据。设计改变后需建立新证据组；先保存旧版作品，旧照片不能验证新版。</p><button disabled={disabled||registered} onClick={()=>update({...a,physical:{...fresh().physical,revision:key(a.config)}})}>{registered?'已登记当前版本':'登记当前版本并开始一组新证据'}</button><fieldset disabled={disabled||!registered||busy} className={styles.fieldset}><div className={styles.fields}>{([['material','打印材料与设置','例如：PLA，0.2 mm 层高；写实际切片设置'],['part','实购部件与尺寸','型号、轴径、面板与模块尺寸'],['before','试配前观察','哪一处卡住、晃动或无法装配？'],['change','自己的结构改动','改变了哪个孔、止挡、楔块或安装座？'],['after','修改后观察','同样的检查方法，结果有何变化？'],['wiring','实际接线与测量端口','输入极性、输出端、负载、电表、外部供电']] as const).map(([field,label,hint])=><label key={field}>{label}<input value={p[field]} maxLength={500} placeholder={hint} onChange={e=>edit({[field]:e.target.value})}/></label>)}</div><label>本人 CAD / 控制程序源（SCAD、INO、TXT，16 KB 以内）<input type="file" accept=".scad,.ino,.txt" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void upload(f,'source')}}/></label>{p.source&&<details><summary>查看已保存源文件</summary><pre>{p.source}</pre></details>}<label>本人实测 CSV（最多 6 KB）<textarea rows={6} maxLength={6000} value={p.csv} placeholder="首行：seconds,voltage,load_ohms,note；每行填写时间、电压、电阻、观察" onChange={e=>edit({csv:e.target.value})}/></label><details><summary>查看格式示例，不可当作本人实测</summary><pre>{['seconds,voltage,load_ohms,note','0,1.7,470,示例负载端','20,1.6,470,示例遮光开始','40,1.4,470,示例继续观察'].join(String.fromCharCode(10))}</pre></details><p className={styles.caption}>单位 s、V、Ω，至少三个递增时间点；说明测的是电容还是负载端。</p>{p.csv&&<p role="status">{(()=>{try{return `已识别 ${csvRows(p.csv).length} 个点；仅检查格式，未判断真实性。`}catch(e){return String(e)}})()}</p>}<label>本人装配、接线与测量照片（两张）<input type="file" accept="image/png,image/jpeg,image/webp" disabled={p.photos.length>=2} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void upload(f,'photo')}}/></label><div className={styles.photoGrid}>{p.photos.map(f=><figure key={f.id}><img src={f.data} alt={f.caption||'待说明的本人照片'} className={styles.photo}/><label>这张图证明什么<input value={f.caption} maxLength={240} placeholder="指出打印改动、测量位置或读数" onChange={e=>edit({photos:p.photos.map(x=>x.id===f.id?{...x,caption:e.target.value}:x)})}/></label><button onClick={()=>edit({photos:p.photos.filter(x=>x.id!==f.id)})}>移除</button></figure>)}</div></fieldset>{message&&<p role="status">{message}</p>}</section>
}
export function ForecastEvidence({a,update,disabled}:{a:Workspace;update:(a:Workspace)=>void;disabled:boolean}){
 const rows=forecastRows(48,72),[error,setError]=useState('')
 return <section className={styles.section}><p className={styles.eyebrow}>04 / 研究记录</p><h4>先写标准，再打开第一次结果</h4><p>合成历史：前 48 点训练、接着 24 点验证、最后 24 点首次检查。拟合模型：下一点 = {FORECAST.a.toFixed(3)} × 上一点 + {FORECAST.b.toFixed(3)}。</p><div className={styles.stats}><div><strong>{mae(rows,'baseline').toFixed(3)}</strong><span>验证 MAE · 持续性 / mW</span></div><div><strong>{mae(rows,'predicted').toFixed(3)}</strong><span>验证 MAE · 拟合 / mW</span></div></div><details><summary>检查训练与验证数据</summary><pre>{HISTORY.slice(0,48).map((v,i)=>`${i},${v.toFixed(3)}`).join(String.fromCharCode(10))}</pre><div className={styles.tableScroll}><table><thead><tr><th>序号</th><th>实际</th><th>基线</th><th>预测</th></tr></thead><tbody>{rows.map(r=><tr key={r.i}><td>{r.i}</td><td>{r.actual.toFixed(3)}</td><td>{r.baseline.toFixed(3)}</td><td>{r.predicted.toFixed(3)}</td></tr>)}</tbody></table></div></details><fieldset disabled={disabled||!!a.frozen} className={styles.fields}><label>事前任务、条件与停止标准<input maxLength={500} value={a.question} placeholder="120 秒内关键服务维持多久？另写实际器材、环境与停止条件" onChange={e=>update({...a,question:e.target.value})}/></label><label>关键服务目标 / 秒<input type="number" min={1} max={120} value={a.target} onChange={e=>update({...a,target:Math.max(1,Math.min(120,Number(e.target.value)||1))})}/></label><button disabled={a.question.trim().length<15} onClick={()=>update({...a,frozen:{at:new Date().toISOString(),question:a.question,target:a.target,config:{...a.config},first:null,realFirst:null,prediction:null}})}>冻结当前方案</button></fieldset>{a.frozen&&<><p>事前标准：{a.frozen.question}；目标 {a.frozen.target} 秒。第一次不能重抽或覆盖。</p><button disabled={disabled||!!a.frozen.first} onClick={()=>update({...a,frozen:{...a.frozen!,first:simulate(a.frozen!.config,'mission','front',crypto.randomUUID(),new Date().toISOString()),prediction:forecastRows(72,96)}})}>{a.frozen.first?'第一次数字结果已固定':'打开新工况，保存第一次数字结果'}</button>{a.frozen.first&&<><p>首次关键服务 {a.frozen.first.alive} 秒，{a.frozen.first.alive>=a.frozen.target?'达到':'未达到'}事前标准。目标失败也可完成交付。</p><EnergyPlot run={a.frozen.first}/><p>新数据 MAE：基线 {mae(a.frozen.prediction!,'baseline').toFixed(3)} / 拟合 {mae(a.frozen.prediction!,'predicted').toFixed(3)} mW。</p></>}<button disabled={disabled||!!a.frozen.realFirst||!a.frozen.first||!a.physical.csv||key(a.config)!==key(a.frozen.config)||a.physical.revision!==key(a.frozen.config)} onClick={()=>{try{if(csvRows(a.physical.csv).length<3)throw Error('先在实物记录填写至少三个点。');update({...a,frozen:{...a.frozen!,realFirst:a.physical.csv}})}catch(e){setError(String(e))}}}>{a.frozen.realFirst?'第一次实物记录已固定':'固定下方实测表为第一次结果'}</button><p className={styles.caption}>先按冻结版本完成实物首轮并固定，再修改。平台保留记录顺序，不替代独立监考或人工评阅。</p></>}{error&&<p role="status">{error}</p>}</section>
}
