"use client"
import {useState} from 'react'
import Link from 'next/link'
import {ArrowRight,Check,Circle,Package,Play,Wrench} from 'lucide-react'
import type {GuidedCourse,GuidedModule} from '@/lib/project-lines/guided-course'
import type {LearningBody,LearningScope} from '@/lib/api/learning-records'
import {learningRecords} from '@/lib/api/learning-records'
import {learningCacheKey} from '@/lib/learning-record-session'
import {useLearningRecord} from '@/lib/hooks/use-learning-record'
import {checkedArtifact,artifactChecks} from '@/lib/project-lines/space-models'
import {verifiedDrivingArtifact} from '@/lib/project-lines/guided-progress'
import {newRoverSystem,isRoverSystem,prototypeChecks,physicalChecks,designBudget,runSystem,probeResult,PROBE_NAMES,REPAIR_NAMES,roverCAD,EMPTY_PHYSICAL,type RoverSystem,type RoverDesign,type RunMode,type Probe} from '@/lib/project-lines/rover-system'
import {LearningRecordStatus,downloadLearningRecord} from './learning-record-status'
import {PhysicalEvidenceFields} from './physical-evidence-fields'
import {RoverBuildView} from './rover-build-view'
import styles from './rover-system-workspace.module.css'

export const roverScope:LearningScope={library_slug:'assemble-a-rover',module_id:'WORK',activity_id:'system-build',kind:'classroom',content_version:'2.0'}
const questions=['我的两项设计取舍','故障证据怎样改变了我的判断','实物结果与数字原型有什么差别']
const initial:LearningBody={answers:questions.map((question,i)=>({question_id:`explain-${i}`,question,answer:''})),artifact:newRoverSystem() as unknown as Record<string,unknown>}
function downloadText(body:string,name:string){const url=URL.createObjectURL(new Blob([body],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const materialRoot='/project-lines/space-exploration/assemble-a-rover/hardware'
function CheckList({checks}:{checks:{title:string;passed:boolean}[]}){return <ul className={styles.checks}>{checks.map(c=><li key={c.title} data-passed={c.passed}>{c.passed?<Check size={17}/>:<Circle size={17}/>}<span>{c.title}</span></li>)}</ul>}

function SystemDelivery({course,body,ready}:{course:GuidedCourse;body:LearningBody;ready:boolean}){
  const record=useLearningRecord({library_slug:course.id,module_id:'M08',activity_id:'final-deliverable',kind:'assignment',content_version:course.version},{answers:[]})
  const artifact=isRoverSystem(body.artifact)?body.artifact:null,checks=artifact?[...prototypeChecks(artifact),...physicalChecks(artifact.physical,artifact.design)]:[]
  const complete=ready&&!!artifact&&checks.every(c=>c.passed)&&body.answers.length===3&&body.answers.every(a=>a.answer.trim())
  const prepared={...body,client_context:{delivery:{schema_version:'physical-rover-delivery/2',assessment:'ungraded',evidence_status:'learner_reported'}}}
  const submitted=!!record.submittedAt&&JSON.stringify(prepared)===JSON.stringify(record.body),saved=record.history[0]??(record.submittedAt?{body:record.body,created_at:record.submittedAt}:null)
  async function submit(){if(record.pending){await record.session.submit();return}if(!complete)return;record.session.update(structuredClone(prepared));await record.session.submit()}
  return <section id="project-delivery" data-system-delivery className={styles.delivery}><header><Package size={22}/><div><p>03 正式交付 / 实物必需</p><h3>我的实物探测车与测试档案</h3></div></header><CheckList checks={checks}/><p>数字测试齐备后还需制作实物。这里核对作品材料与学生自测记录，提交状态是“待评阅”，不会自动认定实物已验证或知识已掌握。</p><button type="button" className={styles.primary} disabled={!record.ready||record.busy||record.conflict||(!record.pending&&(!complete||submitted))} onClick={submit}>{record.pending?'重试上次交付':submitted?'已保存实物作品 · 待评阅':record.identity.token?'提交实物作品':'保存实物作品到本机'}</button>
    {saved&&<details className={styles.saved} data-system-submission><summary>查看已交付版本 · {new Date(saved.created_at).toLocaleString()}</summary>{isRoverSystem(saved.body.artifact)&&<><details><summary>查看交付的 CAD 与程序</summary><pre className={styles.sourceCode}>{saved.body.artifact.physical.cadSource}</pre><pre className={styles.sourceCode}>{saved.body.artifact.physical.controlSource}</pre></details><p>结构宽 {saved.body.artifact.design.width} mm · {saved.body.artifact.physical.tests.length} 条实测 · {saved.body.artifact.physical.photos.length} 张照片</p><div className={styles.twoCols}>{saved.body.artifact.physical.photos.map(photo=><figure key={photo.id} className={styles.photo}>{/* eslint-disable-next-line @next/next/no-img-element */}
<img src={photo.data} alt={photo.caption}/><figcaption>{photo.caption}</figcaption></figure>)}</div><button type="button" onClick={()=>downloadLearningRecord(saved.body,'my-physical-rover.json')}>导出这版完整作品</button></>}{saved.body.answers.map(a=><p key={a.question_id}><strong>{a.question}：</strong>{a.answer}</p>)}</details>}
    <LearningRecordStatus record={record}/><Link className={styles.next} href="/explore/space-exploration/run-an-expedition">下一站：带着实物探测车完成远征<ArrowRight size={16}/></Link>
  </section>
}

export function RoverSystemWorkspace({course,node}:{course:GuidedCourse;node:GuidedModule}){
  const record=useLearningRecord(roverScope,initial),a=isRoverSystem(record.body.artifact)?record.body.artifact:newRoverSystem(),d=a.design,b=designBudget(d)
  const [message,setMessage]=useState(''),[loading,setLoading]=useState(false),[hint,setHint]=useState(0)
  const locked=!record.ready||record.pending||record.conflict||loading,stage=Number(node.module_id.slice(1)),prototype=prototypeChecks(a),frozen=a.physical.designKey===JSON.stringify(d)
  function update(next:RoverSystem){const body={...record.session.snapshot().body,artifact:next as unknown as Record<string,unknown>};if(new TextEncoder().encode(JSON.stringify(body)).length>225000){setMessage('作品接近保存上限，请先导出旧版，再减少重复运行或重新选择照片。');return}record.session.update(body)}
  function set(key:keyof RoverDesign,value:string){update({...a,design:{...d,[key]:value}})}
  function run(mode:RunMode){update(runSystem(a,mode));setMessage(mode==='transfer'?'新路线结果已保存。调整设计后，原来的测试不会自动算作新版结果。':'本次记录已保存，可展开查看每一层的实际结果。')}
  const select=(key:keyof RoverDesign,label:string,options:[string,string][])=> <label className={styles.field}>{label}<select aria-label={label} value={d[key]} onChange={e=>set(key,e.target.value)}>{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
  async function importPart(id:'tune-a-chassis'|'write-driving-rules'){
    setLoading(true);try{
      const scope:LearningScope={library_slug:id,module_id:id==='tune-a-chassis'?'M03':'M04',activity_id:'final-deliverable',kind:'assignment',content_version:'1.0'}
      const remote=record.identity.token?(await learningRecords.read(record.identity.token,scope)).submissions[0]?.body:JSON.parse(localStorage.getItem(learningCacheKey(record.identity.owner,scope))||'null')
      const raw=record.identity.token?remote?.artifact:remote?.submittedAt?remote.body?.artifact:null
      if(id==='tune-a-chassis'&&checkedArtifact(raw,id)&&artifactChecks(raw).every(c=>c.passed)){update({...a,design:{...d,wheel:Number(raw.config.wheel)>=20?'large':'small',pace:raw.config.speed==='1'?'slow':'fast'},sources:{...a.sources,chassis:'02 越野底盘已交付配置：'+JSON.stringify(raw.config)}})}
      else if(id==='write-driving-rules'&&verifiedDrivingArtifact(raw)){const rules=(raw.program as {rules:Record<string,string>}).rules;update({...a,design:{...d,sand:rules.sand==='slow'?'slow':'forward',unknown:rules.unknown==='stop'?'stop':'forward'},sources:{...a.sources,rules:'02 驾驶规则已交付配置：'+JSON.stringify(rules)}})}
      else{setMessage('未找到兼容的已交付作品。你也可以直接在本课作出自己的设计。');return}
      setMessage('已读取为本课设计起点。虚拟参数已按本课选项映射，不能直接当作实物尺寸或电机代码。请重新测试。')
    }catch{setMessage('暂时无法读取作品，现有设计保留。')}finally{setLoading(false)}
  }
  const last=a.runs.at(-1),sameVersion=last&&JSON.stringify(last.design)===JSON.stringify(d)
  return <><section className={styles.workshop} data-rover-workshop data-stage={stage}>
    <header className={styles.heading}><p><Wrench size={17}/> 03 系统制作台</p><h3>{['接下你的制造任务','让信息真正流动','每个选择，都有代价','先找证据，再下判断','把方案带到陌生路线','从尺寸变成零件','接通电路，让程序落地','用实物结果完成交付'][stage-1]}</h3><p>数字原型 → 制造文件 → 实物装配 → 现场测试。每一步都会留在你的作品档案中。</p></header>
    <div className={styles.milestones}><span data-ready={prototype.every(c=>c.passed)}>数字原型 {prototype.filter(c=>c.passed).length} / {prototype.length}</span><span data-ready={frozen}>{frozen?'制作版本已冻结':'待冻结制作版本'}</span><span>实物照片 {a.physical.photos.length} / 2</span></div>
    <fieldset disabled={locked} className={styles.panel}>
      {stage===1&&<><div className={styles.mission}><span>任务委托 / 桌面地形观察</span><h4>造一辆属于你的探测车</h4><p>为一条有窄门、低矮障碍和停止区的测试路线设计车辆。先在数字模型中协调结构、控制和能源，再打印、接线、编程并测量真实表现。</p><ul><li>数字模型：同一版设计通过训练路线与新路线，并能修复一次异常。</li><li>实物：前进、转向、触碰障碍后停止，留下带单位的原始测量。</li><li>自己制作：至少修改一件打印件，以及一段控制程序。</li></ul></div><RoverBuildView design={d}/><div className={styles.prepare}><h4>家庭准备，先看清再开始</h4><p>浏览器可先完成前五节。实物阶段需要 FDM 打印机或代打服务、低压电子器件、尺或卡尺、螺丝刀和成人现场协助。打印与采购等待不计入学习时长。</p><a href={`${materialRoot}/build-guide.md`} target="_blank" rel="noreferrer">查看材料规格、接线和制造说明</a><p>参考结构与程序已做文件和逻辑检查，尚未完成首台实体样机试制；先用小试配片验证尺寸。</p></div></>}
      {stage===2&&<><div className={styles.interfaceDiagram}><div><b>相机</b><small>图像</small></div><ArrowRight/><div><b>感知</b><small>地形标签</small></div><ArrowRight/><div><b>判断</b><small>动作命令</small></div><ArrowRight/><div><b>驱动</b><small>运动反馈</small></div></div><p>为每个输入端选择正确来源。电源连接与信息连接各有作用；选择改变后，运行结果也会改变。</p><div className={styles.threeCols}>{select('perception','感知模块接收', [['','未连接'],['camera','相机图像'],['battery','电池电源']])}{select('controller','判断模块接收',[['','未连接'],['terrain','感知输出的地形'],['camera','未处理的相机图像']])}{select('actuator','驱动模块接收',[['','未连接'],['action','判断输出的动作'],['battery','电池电源']])}</div><p>这是信息链。后面的实物起步车使用触碰开关提供观察输入，需要自己重新接线；相机识别留给完整火星车课程。</p><button className={styles.primary} onClick={()=>run('training')}><Play size={15}/>检查连接并运行</button></>}
      {stage===3&&<><RoverBuildView design={d}/><div className={styles.metrics}><div><span>设计质量 / 结构限值</span><strong>{b.mass} / {b.limit} <small>g</small></strong><meter value={b.mass} max={Math.max(b.mass,b.limit)} high={b.limit} optimum={b.limit*.7}/></div><div><span>模拟电量</span><strong>{b.capacity} <small>点</small></strong><p>增加电池会同时增加质量和每段能耗。</p></div></div><div className={styles.threeCols}>{select('wheel','轮子',[['small','小轮 / 轻，遇凸起需绕路'],['large','大轮 / 重，可通过凸起']])}{select('battery','电池方案',[['compact','紧凑电池 / 42 点'],['extended','扩展电池 / 74 点']])}{select('deck','结构方案',[['light','轻量底板 / 330 g 教学限值'],['reinforced','加强底板 / 480 g 教学限值']])}{select('width','底板宽度',[['100','100 mm'],['120','120 mm']])}{select('thickness','底板厚度',[['3','3 mm'],['4','4 mm']])}{select('pace','运行速度',[['fast','快速'],['slow','低速']])}{select('route','通过障碍',[['direct','直接通过'],['detour','绕行，增加路程']])}{select('sand','遇到软沙',[['forward','正常前进'],['slow','慢行']])}{select('unknown','看不清时',[['forward','继续前进'],['stop','停止并确认']])}</div><div className={styles.actions}><button type="button" className={styles.primary} onClick={()=>run('training')}><Play size={15}/>测试这一版设计</button><button type="button" onClick={()=>importPart('tune-a-chassis')}>读取我的 02 底盘</button><button type="button" onClick={()=>importPart('write-driving-rules')}>读取我的 02 规则</button></div><p>先记录第一版，再改一项并比较。当前克数和能量是教学约束；实物质量、刚度和续航必须重新测量。</p></>}
      {stage===4&&<><div className={styles.mission}><span>测试站异常 / {a.diagnosis.caseId}</span><h4>车没有完成观察任务</h4><p>先运行复现，再选择要检查的位置。收集两项证据后提出判断；一次猜中不能替代检查过程。</p></div><button type="button" className={styles.primary} onClick={()=>run('diagnostic')}>复现异常 / 验证修复</button><div className={styles.probes}>{(['camera','decision','motor'] as Probe[]).map(p=><article key={p}><button type="button" onClick={()=>update({...a,diagnosis:{...a.diagnosis,probes:[...new Set([...a.diagnosis.probes,p])]}})}>{PROBE_NAMES[p]}</button>{a.diagnosis.probes.includes(p)&&<p>{probeResult(a.diagnosis,p)}</p>}</article>)}</div><div className={styles.twoCols}><label className={styles.field}>我的故障判断<select aria-label="我的故障判断" value={a.diagnosis.hypothesis} onChange={e=>update({...a,diagnosis:{...a.diagnosis,hypothesis:e.target.value}})}><option value="">先收集证据</option><option value="camera">相机输入链</option><option value="controller">判断规则</option><option value="motor">驱动执行</option></select></label><label className={styles.field}>我准备怎样修复<select aria-label="我准备怎样修复" value={a.diagnosis.repair} onChange={e=>update({...a,diagnosis:{...a.diagnosis,repair:e.target.value}})}><option value="">选择修复动作</option>{Object.entries(REPAIR_NAMES).map(([v,label])=><option value={v} key={v}>{label}</option>)}</select></label></div><button type="button" onClick={()=>setHint(Math.min(2,hint+1))}>需要一点提示</button>{hint>0&&<p>{hint===1?'按信息流的顺序检查：输入有没有更新，判断有没有依据，驱动有没有反馈。':'把两个检查结果放在一起：哪一层先出现了不符合预期的现象？修复后还要重新运行。'}</p>}</>}
      {stage===5&&<><h4>同一辆车，换一条路线</h4><p>先保留当前设计。新路线会增加路程，并包含窄门；实际限制会记录在测试结果里。发现问题后回到设计节点修改，再把训练、诊断和新路线一起复测。</p><button type="button" className={styles.primary} onClick={()=>run('transfer')}>开始新路线验收</button><CheckList checks={prototype}/><button type="button" disabled={!prototype.every(c=>c.passed)} onClick={()=>{update({...a,physical:frozen?a.physical:{...structuredClone(EMPTY_PHYSICAL),designKey:JSON.stringify(d)}});setMessage('制作版本已冻结。冻结不同设计会清空草稿里的旧实测与照片，请为新版重新采集；已经正式交付的历史版本保留。')}}>冻结这个版本，准备制造</button><p>再次冻结不同设计前，请先从记录选项备份旧草稿；新制造版本需要重新采集实测证据。</p><p>{frozen?'当前设计已冻结，可以进入打印与装配。':'制造之前先完成数字检查；旧设计的测试不能代替当前版本。'}</p></>}
      {stage===6&&<><RoverBuildView design={d}/><div className={styles.actions}><button type="button" onClick={()=>downloadText(roverCAD(d),'my-rover.scad')}>下载当前尺寸 CAD 源文件</button><a href={`${materialRoot}/reference-stl.zip`} download>下载参考 STL 与试配片</a><a href={`${materialRoot}/dimension-sheet.svg`} target="_blank" rel="noreferrer">查看尺寸与安装示意</a></div><p>参考 STL 为 100 × 150 × 3 mm 底板。自己的尺寸请用 CAD 源文件重新导出；实物不得把两者混为一版。模型使用通用固定孔和绑带槽，按手头电机支架、万向支撑轮和开关的实测位置调整。</p><PhysicalEvidenceFields value={a.physical} onChange={physical=>update({...a,physical})} part="fabrication" disabled={locked}/></>}
      {stage===7&&<><div className={styles.circuit}><span>USB 电源 → Pico 控制板 → 控制信号 → DRV8833</span><span>4 × AA 电池盒 → 独立开关 → 驱动板 → 左右电机</span><span>触碰开关 → GPIO 输入 · 各板 GND 共地</span></div><p>电机电源不经过 GPIO。起步版本使用常闭触碰开关：按下或断线时停止。先断开电机电源、核对端子，再架空调试，最后低速落地。打印热端与需要焊接的接头由成人操作。</p><div className={styles.actions}><a href={`${materialRoot}/build-guide.md`} target="_blank" rel="noreferrer">逐项接线说明</a><a href={`${materialRoot}/controller.py`} download>下载控制程序</a><a href={`${materialRoot}/wiring.svg`} target="_blank" rel="noreferrer">查看接线图</a></div><PhysicalEvidenceFields value={a.physical} onChange={physical=>update({...a,physical})} part="electronics" disabled={locked}/></>}
      {stage===8&&<><p className={styles.notice}>{frozen?'实测记录对应已冻结设计。请保留未达到目标的尝试。':'当前设计尚未冻结，或冻结后又有修改。先到第 5 节完成复测并冻结，再做这版实物测试。'}</p><PhysicalEvidenceFields value={a.physical} onChange={physical=>update({...a,physical})} disabled={locked}/><h4>为作品写三句说明</h4>{record.body.answers.map((answer,i)=><label className={styles.field} key={answer.question_id}>{answer.question}<input aria-label={answer.question} maxLength={600} value={answer.answer} placeholder={['例如：为什么用小轮绕行，而没有加大电池？写自己的选择。','引用两项检查结果，再说明你的修复。','引用真实尺寸或停止距离，说出模型没考虑的情况。'][i]} onChange={e=>record.session.update({...record.body,answers:record.body.answers.map((old,j)=>i===j?{...old,answer:e.target.value}:old)})}/></label>)}</>}
    </fieldset>
    {message&&<p className={styles.notice} role="status">{message}</p>}
    {last&&stage<=5&&<div className={styles.result} data-system-result><h4>{!sameVersion?'上次设计的结果 · 修改后需要重新运行':last.result.passed?'本次模型条件通过':'本次需要调整或检查'}</h4><div className={styles.threeCols}><span>质量 {last.result.mass} g</span><span>能耗 {last.result.spent} 点</span><span>余量 {last.result.remaining} 点</span></div><ol>{last.result.steps.map((s,i)=><li key={i}>{s}</li>)}</ol></div>}
    {a.runs.length>0&&<details className={styles.history}><summary>我的设计与运行历史 · {a.runs.length} 次</summary>{a.runs.map((r,i)=><details key={i}><summary>第 {i+1} 次 · {r.mode==='training'?'训练':r.mode==='transfer'?'新路线':'诊断'} · {r.result.passed?'模型通过':'保留的问题'}</summary><p>宽 {r.design.width} mm · {r.design.wheel==='small'?'小轮':'大轮'} · {r.design.battery==='compact'?'紧凑电池':'扩展电池'}</p><ol>{r.result.steps.map((s,j)=><li key={j}>{s}</li>)}</ol></details>)}</details>}
    <LearningRecordStatus record={record}/>
  </section>{stage===8&&<SystemDelivery course={course} body={record.body} ready={record.ready}/>}</>
}
