"use client"
import {useState} from 'react'
import type {SlideEntry} from '@/lib/types/api'
import {LessonSlidesProvider,LessonSlideCarousel,LessonSlideshowButton} from './lesson-slides'
const labels=['二维与空间 · 3D','定位与计数 · 3D','质量求和 · 公式','单/双/三键 · 2D','链/支链/环 · 2D','苯环共面 · 3D','逐原子读取 · 动态','个人观察 · 3D','实际输出 · Python','成果交接 · 报告']
export function SkeletonSlidePreview({slides}:{slides:SlideEntry[]}){
 const [index,setIndex]=useState(0),[width,setWidth]=useState('1152')
 return <main className="min-h-screen bg-[var(--paper)] p-5 text-[var(--ink)]"><div className="mx-auto" style={{maxWidth:Number(width)}}><p className="text-xs font-semibold text-[var(--primary-ink)]">分子猎人 · M03 · spatial-evidence-v2 · 本地预览，未部署</p><h1 className="my-3 text-2xl font-semibold">从看清分子空间，到交出自己的骨架报告</h1><p className="mb-4 text-sm text-[var(--sub)]">10 页新版播放器：第 1/2/6/7/8 页有真实可交互 Three.js；第 7 页逐原子播放；第 8–10 页保存个人证据。非生成图片。</p><label className="mb-4 flex items-center gap-3 text-sm">预览宽度<select aria-label="预览内容宽度" value={width} onChange={e=>setWidth(e.target.value)} className="rounded border bg-[var(--paper)] p-2">{[480,720,960,1152].map(w=><option key={w} value={w}>{w}px</option>)}</select></label><LessonSlidesProvider projectName="molecule-monster-hunter" moduleId="M03" knodeDir="knodes/M03-w0-module" title="M03 · 分子骨架与空间证据" slides={slides} currentIndex={index} onIndexChange={setIndex}><div className="mb-4 flex flex-wrap gap-2"><nav className="flex flex-1 flex-wrap gap-2" aria-label="M03 新版页码">{slides.map((s,i)=><button key={s.slide_id} aria-label={`第 ${i+1} 页：${labels[i]}`} aria-current={i===index?'page':undefined} onClick={()=>setIndex(i)} className={`rounded-lg border px-3 py-2 text-xs ${i===index?'bg-[var(--primary)] text-[var(--primary-foreground)]':'bg-[var(--paper-2)]'}`}>{String(i+1).padStart(2,'0')} · {labels[i]}</button>)}</nav><LessonSlideshowButton/></div><LessonSlideCarousel/><p className="mt-4 text-xs text-[var(--sub)]">当前第 {index+1} 页 · {labels[index]}。四组来源坐标共约 9 KB；新讲稿未配音。<a href="/slide-preview/m02-runtime" className="ml-2 underline">M02 运行证据</a></p></LessonSlidesProvider></div></main>
}
