"use client"
import {useEffect,useState} from 'react'
import type {SlideTechnicalVisual} from '@/lib/types/api'
import {MOLECULES} from '@/lib/molecule-skeleton'
import {EVIDENCE_KEY,restoreRuntimeEvidence,type RuntimeEvidence} from '@/lib/rdkit-runtime'
import {OBSERVATION_KEY,SKELETON_RUN_KEY,SKELETON_SCRIPT,checkObservation,observationEnvelope,restoreObservations,parseSkeletonOutput,restoreSkeletonRun,compareRuntime,type Observations,type CountAnswers,type SkeletonRun} from '@/lib/skeleton-evidence'
import {MoleculeSkeletonVisual} from './molecule-skeleton-visual'
import {MolecularObject3D,MoleculeDiagram} from './molecular-object-3d'
import {downloadEvidence,ExactEquation} from './screening-common'
import './skeleton-evidence.css'

type Spec=Extract<SlideTechnicalVisual,{renderer:'molecule-skeleton-evidence'}>
const empty=():CountAnswers=>({heavy:'',atoms:'',bonds:'',rings:''})
function downloadScript(){const url=URL.createObjectURL(new Blob([SKELETON_SCRIPT],{type:'text/x-python;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='m03_read_skeletons.py';a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function SkeletonEvidenceVisual({visual}:{visual:Spec}){
 const [rows,setRows]=useState<Observations>({}),[run,setRun]=useState<SkeletonRun|null>(null),[previous,setPrevious]=useState<RuntimeEvidence|null>(null)
 const [id,setId]=useState('ethanol'),[showH,setShowH]=useState(true),[selected,setSelected]=useState<number|null>(null)
 const [answers,setAnswers]=useState<CountAnswers>(empty),[note,setNote]=useState(''),[raw,setRaw]=useState(''),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState(''),[clearArmed,setClearArmed]=useState(false)
 useEffect(()=>{const restore=()=>{try{const saved=restoreObservations(localStorage.getItem(OBSERVATION_KEY));setRows(saved);setRun(restoreSkeletonRun(localStorage.getItem(SKELETON_RUN_KEY)));setPrevious(restoreRuntimeEvidence(localStorage.getItem(EVIDENCE_KEY)));if(saved.ethanol){setAnswers(saved.ethanol.answers);setNote(saved.ethanol.note)}}catch{setMessage('本机存储不可用；可以下载证据备份，但不会自动保存。')}};const timer=window.setTimeout(restore,0);return()=>window.clearTimeout(timer)},[])
 const m=MOLECULES.find(r=>r.id===id)!,count=Object.keys(rows).length
 const choose=(next:string)=>{setId(next);setSelected(null);setAnswers(rows[next]?.answers??empty());setNote(rows[next]?.note??'');setMessage('');setClearArmed(false)}
 const saveObservation=()=>{const result=checkObservation(id,answers,note);if(!result.row){setMessage(result.problem);return}const next={...rows,[id]:result.row};try{localStorage.setItem(OBSERVATION_KEY,JSON.stringify(observationEnvelope(next)));setRows(next);setMessage(`${m.name} 的个人观察已保存。可继续选择下一个分子。`)}catch{setMessage('保存失败：请检查浏览器存储设置；这次没有记为已保存。')}}
 const saveRun=()=>{const result=parseSkeletonOutput(raw,confirmed);if(!result.evidence){setMessage(result.problem);return}try{localStorage.setItem(SKELETON_RUN_KEY,JSON.stringify(result.evidence));setRun(result.evidence);setMessage('四条输出与本节参考口径一致，已保存。来源为本人粘贴，网页没有独立验证执行过程。')}catch{setMessage('存储失败，这次没有记为已保存。')}}
 const clear=()=>{if(!clearArmed){setClearArmed(true);setMessage('再次点击确认清除本机 M03 记录；可先下载备份。不会清除 M02。');return}try{localStorage.removeItem(OBSERVATION_KEY);localStorage.removeItem(SKELETON_RUN_KEY);setRows({});setRun(null);setRaw('');setConfirmed(false);setAnswers(empty());setNote('');setClearArmed(false);setMessage('已清除本机 M03 记录。')}catch{setMessage('未能清除，请检查存储权限。')}}
 const status=<div className="ske-status"><span>个人观察 <strong>{count} / 4</strong></span><span>Python 输出 <strong>{run?'已保存 · 本人提供':'未保存'}</strong></span><span>M02 环境 <strong>{previous?'已找到本机记录':'本机尚无记录'}</strong></span>{run&&<span>本次版本 <strong>Python {run.python} / RDKit {run.rdkit}</strong></span>}</div>
 const handoff=compareRuntime(previous,run)
 const progress=<>{status}<p className="ske-note">{handoff==='same'?'M02 与本次输出的版本和解释器位置一致；这只是元数据一致性，不证明整个环境都正常。':handoff==='different'?'本次输出与 M02 的版本或解释器位置不同。请确认是否切换或更新了环境；本页不会覆盖 M02。':'尚不能比较两次环境：请保留 M02 的运行记录和本页实际输出。'}</p></>
 let body:React.ReactNode
 if(visual.scene==='lab'){
  body=<>{status}<div className="ske-tabs">{MOLECULES.map(r=><button key={r.id} aria-pressed={id===r.id} onClick={()=>choose(r.id)}>{r.name} · {rows[r.id]?'已保存':'待观察'}</button>)}</div><div className="ske-grid"><section className="ske-object"><MolecularObject3D key={id} molecule={m} showH={showH} selected={selected} onSelect={setSelected}/><label className="ske-inline"><input type="checkbox" checked={showH} onChange={e=>{setShowH(e.target.checked);setSelected(null)}}/>显示氢（不会改动分子）</label><label className="ske-inline">定位原子<select aria-label="个人观察定位原子" value={selected??''} onChange={e=>setSelected(e.target.value===''?null:Number(e.target.value))}><option value="">未选择</option>{m.atoms.filter(a=>showH||a.element!=='H').map(a=><option value={a.id} key={a.id}>{a.element}{a.id+1}</option>)}</select></label><p className="ske-small">{selected===null?'选中一个原子，检查它与哪些原子相连。':`${m.atoms[selected].element}${selected+1} 相连：${m.bonds.filter(b=>b.a===selected||b.b===selected).map(b=>{const a=m.atoms[b.a===selected?b.b:b.a];return a.element+(a.id+1)}).join('、')}`}</p></section><section className="ske-panel"><p className="ske-kicker">自己的读图证据 · {m.name}</p><MoleculeDiagram smiles={m.smiles} explicitHydrogens={showH}/><div className="ske-fields">{([['heavy','重原子数'],['atoms','全部原子数（含氢）'],['bonds','全部连接数（含氢）'],['rings','环数']] as const).map(([key,label])=><label key={key}>{label}<input inputMode="numeric" aria-label={label} value={answers[key]} onChange={e=>{setAnswers(a=>({...a,[key]:e.target.value}));setMessage('')}}/></label>)}</div><label className="ske-label">一条自己的发现<textarea aria-label="自己的读图发现" maxLength={240} value={note} onChange={e=>{setNote(e.target.value);setMessage('')}} placeholder="例如：转动视角后，原先被遮住的氢出现了，但连接关系没变。"/></label><button onClick={saveObservation}>核对并保存这个分子</button><p className="ske-small">检查数值是否正确，不替你评判自由文字的科学质量。切换分子可恢复已经保存的记录。</p></section></div><p className="ske-note">球棍模型来自公开计算构象，不是实验观测。模型大小、颜色为辨识服务；旋转不是分子动力学。精确连接以结构数据为依据。</p></>
 }else if(visual.scene==='report'){
  body=<>{progress}<div className="ske-grid"><section className="ske-panel"><p className="ske-kicker">01 · 在 M02 的 Python 环境运行</p><h3>完整模板，不用从零写</h3><p>下载脚本，在它所在目录执行：</p><pre className="ske-code">python m03_read_skeletons.py</pre><button onClick={downloadScript}>下载完整 Python 模板</button><p>模板读入四个固定 SMILES，显式加氢后再计数，并输出解释器位置和 RDKit 版本。</p><details><summary>查看完整脚本</summary><pre className="ske-code">{SKELETON_SCRIPT}</pre></details><p className="ske-small">这里不执行本机 Python。安装和运行请家长协助；不需要开展化学实验。</p></section><section className="ske-panel"><p className="ske-kicker">02 · 保留你的真实输出</p><label className="ske-label">粘贴四条记录的完整 JSON<textarea aria-label="M03 实际 Python 输出" rows={7} value={raw} onChange={e=>{setRaw(e.target.value);setMessage('')}} placeholder="等待你运行模板后的真实输出，不自动填入示例。"/></label><label className="ske-inline"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我确认这是自己运行模板得到的输出</label><button onClick={saveRun}>核查并保存实际输出</button><p className="ske-small">检查结构、计数和质量是否与本节口径一致；无法独立验证是谁、在哪里执行。路径中的用户名可自行遮去，勿粘贴密码或终端历史。</p></section></div><div className="ske-saved"><h3>你的四份观察记录</h3><div className="ske-records">{MOLECULES.map(r=><section key={r.id}><strong>{r.name} · {rows[r.id]?'已保存':'待完成'}</strong><p>SMILES：<code>{r.smiles}</code></p>{rows[r.id]&&<p>个人计数：重原子 {rows[r.id].answers.heavy} · 全部原子 {rows[r.id].answers.atoms} · 连接 {rows[r.id].answers.bonds} · 环 {rows[r.id].answers.rings}</p>}{run&&<p>本人输出：{run.rows.find(x=>x.id===r.id)?.massDa.toFixed(3)} Da · 芳香环 {run.rows.find(x=>x.id===r.id)?.aromaticRings}</p>}<p>{rows[r.id]?.note??'去第 8 页观察并填写；不会拿参考答案代替。'}</p></section>)}</div></div></>
 }else if(visual.scene==='handoff'){
  body=<>{progress}<div className="ske-grid"><section className="ske-panel"><p className="ske-kicker">M03 产物 · 准备交给下一节</p><h3>{count===4&&run?'两类证据都已保存':'还有证据需要补齐'}</h3><ul><li>{count} / 4 份个人结构观察</li><li>{run?'4 / 4 条本人提供的 Python 输出已核对':'0 / 4 条已保存 Python 输出'}</li><li>来源、SMILES、含氢口径与运行版本</li></ul><button disabled={count!==4||!run} onClick={()=>downloadEvidence('M03-my-skeleton-evidence.json',{schema:'m03-evidence-bundle-v2',observations:observationEnvelope(rows),pythonRun:run,m02EnvironmentComparison:handoff,boundary:'Learner-provided output; field consistency checked, execution provenance not independently verified.'})}>下载我的完整骨架报告</button><p className="ske-small">数据仅存在当前浏览器，不自动上传或跨设备同步。</p><details><summary>备份或清除本机 M03 记录</summary><button disabled={!count&&!run} onClick={()=>downloadEvidence('M03-partial-backup.json',{observations:observationEnvelope(rows),pythonRun:run})}>下载当前备份</button><button onClick={clear}>{clearArmed?'确认清除 M03 记录':'清除本机 M03 记录'}</button></details></section><section className="ske-panel"><p className="ske-kicker">M04 新问题 · 从连接比较到官能团</p><div className="ske-pair"><div><MoleculeDiagram smiles="CC"/><ExactEquation source={String.raw`\ce{CH3-CH3}`}/><p>乙烷：只有碳和氢</p></div><div><MoleculeDiagram smiles="CCO" highlight={[2]}/><ExactEquation source={String.raw`\ce{CH3-CH2-OH}`}/><p>乙醇：找到含氧的 —OH</p></div></div><p>保持两个碳的骨架来比较：多出的官能团如何影响相互作用？</p><p className="ske-small">这是两种结构的对比，不是乙烷转化为乙醇的反应动画，也不据此直接断言药效。</p></section></div></>
 }else{
  body=<>{visual.scene==='overview'&&<div className="ske-prior">接续 M02：{previous?`已找到本人提供的 Python ${previous.python} / RDKit ${previous.rdkit} 记录。`:'本机尚未找到环境记录；可先学习空间观察，再回 M02 保存真实运行输出。'} 本页浏览器 3D 不等于本机 Python 已安装。</div>}<MoleculeSkeletonVisual visual={{...visual,renderer:'molecule-skeleton'}}/></>
 }
 return <section className="m03-v2" data-renderer="molecule-skeleton-evidence" data-scene={visual.scene} aria-label={visual.aria_label}>{body}{message&&<p role="status" className="ske-message">{message}</p>}{['lab','report','handoff'].includes(visual.scene)&&<footer className="ske-source">PubChem 计算坐标 / RDKit 结构数据 · <a href="https://www.rdkit.org/docs/GettingStartedInPython.html" target="_blank" rel="noreferrer">RDKit 计数说明</a> · 新版讲稿尚未配音。</footer>}</section>
}
