"use client"
import {useEffect,useState,useSyncExternalStore} from 'react'
import type {RDKitModule} from '@rdkit/rdkit'
import type {SlideTechnicalVisual} from '@/lib/types/api'
import {getRDKitModule} from '@/lib/rdkit'
import {MOLECULES} from '@/lib/molecule-skeleton'
import {COMPARISON_KEY,restoreComparison} from '@/lib/functional-group'
import {SMILES_KEY,TARGETS,analyzeSmiles,teachingTokens,phenolTrace,makeSmilesRecord,restoreSmilesRecord,smilesPython,type SmilesResult,type SmilesAttempt} from '@/lib/smiles-reading'
import {MolecularObject3D,MoleculeDiagram} from './molecular-object-3d'
import {downloadEvidence,ExactEquation,StepControls,useTeachingSteps} from './screening-common'
import './molecular-funnel.css'
import './skeleton-evidence.css'
import './functional-group.css'
import './smiles-reading.css'
type Spec=Extract<SlideTechnicalVisual,{renderer:'smiles-reading'}>
function useRDKit(){const [state,setState]=useState<{module:RDKitModule|null;error:string}>({module:null,error:''});useEffect(()=>{let live=true;getRDKitModule().then(module=>{if(live)setState({module,error:''})}).catch(()=>{if(live)setState({module:null,error:'RDKit 加载失败；不显示替代的成功结果。'})});return()=>{live=false}},[]);return state}
function useSaved(key:string){return useSyncExternalStore(cb=>{window.addEventListener('storage',cb);window.addEventListener('m05-saved',cb);return()=>{window.removeEventListener('storage',cb);window.removeEventListener('m05-saved',cb)}},()=>{try{return localStorage.getItem(key)}catch{return null}},()=>null)}
function Note({children}:{children:React.ReactNode}){return <aside className="fg-note">{children}</aside>}
function Stats({result}:{result:SmilesResult}){return <div className="sm-stats">{[['重原子',result.heavy],['氢',result.hydrogens],['重原子间键',result.bonds],['环',result.rings]].map(([k,v])=><div key={k}><strong>{v}</strong><span>{k}</span></div>)}</div>}
function Result({smiles}:{smiles:string}){const {module,error}=useRDKit();let result:SmilesResult|null=null,problem=error;try{if(module)result=analyzeSmiles(module,smiles)}catch(e){problem=(e as Error).message}return result?<><MoleculeDiagram smiles={smiles}/><Stats result={result}/><p className="sm-canonical">RDKit 规范写法：<code>{result.canonical}</code></p></>:<p role="status">{problem||'正在加载 RDKit…'}</p>}
function Overview(){const prior=restoreComparison(useSaved(COMPARISON_KEY));return <><p className="fg-kicker">M04 结构比较 → M05 自己写出可核对的结构输入</p><Note>{prior?'本机已有 M04 对照记录：现在把比较中的 CCO 变成自己可输入、可保存的结构。':'尚未找到本机 M04 对照记录。此处可以学习，上一节个人成果仍需补齐。'}</Note><div className="sm-flow"><section><span>01 · 输入字符</span><code className="sm-big">CCO</code><p>不是图片文件；不含三维坐标。</p></section><section><span>02 · 解析连接</span><p>C₁ — C₂ — O₃</p><p>3 个重原子，2 条重原子间的键。</p></section><section><span>03 · 生成结构图</span><MoleculeDiagram smiles="CCO"/><p>线段端点未写 C 时，按骨架式理解。</p></section></div><Note>RDKit 图表达连接关系，不是分子的照片。能解析也不证明你写对了目标；第 8 页要亲自输入并核对。</Note></>}
function Equivalence(){const [smiles,setSmiles]=useState('CCO'),{module,error}=useRDKit();const result=module?analyzeSmiles(module,smiles):null,match=module&&result?result.canonical===analyzeSmiles(module,'CCO').canonical:false;return <><div className="fg-controls">{['CCO','OCC','COC'].map(s=><button key={s} aria-pressed={s===smiles} onClick={()=>setSmiles(s)}>{s}</button>)}</div><div className="fg-two"><section className="fg-panel"><h3>目标：乙醇</h3><MoleculeDiagram smiles="CCO"/><code>CCO</code><p>氧位于两碳链的一端。</p></section><section className="fg-panel"><h3>当前输入：{smiles}</h3><MoleculeDiagram smiles={smiles}/><p role="status">{result?(match?'与目标连接相同':'合法结构，但连接不同：二甲醚'):error||'正在解析…'}</p><p className="sm-canonical">规范写法：<code>{result?.canonical||'等待库返回'}</code></p></section></div><Note>同一个分子可以有不同遍历写法。这里比较同一版本 RDKit 的规范 SMILES；不要把字符串原样相等当作唯一依据，也不声称所有软件都会输出同一个规范字符串。</Note></>}
function Tokens(){const [input,setInput]=useState('CCO'),{module,error}=useRDKit(),r=module?analyzeSmiles(module,input):null;return <><div className="fg-controls">{['CCO','ClC','[NH4+]'].map(s=><button key={s} aria-pressed={input===s} onClick={()=>setInput(s)}>{s}</button>)}</div><div className="fg-two"><section className="fg-panel"><h3>先按完整原子符号读</h3><div className="sm-tokens">{teachingTokens(input).map((s,i)=><span key={i}>{s}</span>)}</div><p>{input==='ClC'?'Cl 是氯的一个元素符号，不能拆成 C 与 l。':input==='[NH4+]'?'方括号把氮、所带的氢数和正电荷放在一起。不是五个重原子。':'三个大写符号分别表示两个碳和一个氧。'}</p><Note>这是限定例子的教学分词，不是完整 SMILES 解析器。</Note></section><section><MoleculeDiagram smiles={input} explicitHydrogens/><table><thead><tr><th>原子索引</th><th>元素</th><th>所带氢数</th><th>电荷</th></tr></thead><tbody>{r?.atoms.map((a,i)=><tr key={i}><td>{i}</td><td>{a.element}</td><td>{a.hydrogens}</td><td>{a.charge}</td></tr>)}</tbody></table><p role="status">{r?`RDKit：${r.heavy} 个重原子，${r.hydrogens} 个氢。`:error||'正在读取原子表…'}</p></section></div></>}
function ObjectView({id,showH}:{id:string;showH:boolean}){const m=MOLECULES.find(v=>v.id===id)!,[selected,setSelected]=useState(0);return <><MolecularObject3D molecule={m} showH={showH} selected={selected} onSelect={setSelected}/><p className="fg-small">PubChem 预先核验的计算构象（{m.name}），不是当前字符串即时预测的 3D 坐标。</p></>}
function Hydrogens(){const [input,setInput]=useState('CCO'),[showH,setShowH]=useState(true),{module,error}=useRDKit(),r=module?analyzeSmiles(module,input):null;const info:Record<string,{formula:string;id?:string}>={C:{formula:'CH4',id:'methane'},N:{formula:'NH3'},O:{formula:'H2O',id:'water'},CCO:{formula:'C2H6O',id:'ethanol'}},current=info[input];return <><div className="fg-controls">{['C','N','O','CCO'].map(s=><button key={s} aria-pressed={s===input} onClick={()=>setInput(s)}>{s}</button>)}<label className="fg-inline"><input type="checkbox" checked={showH} onChange={e=>setShowH(e.target.checked)}/>显示氢</label></div><div className="fg-two"><section>{current.id?<ObjectView key={current.id} id={current.id} showH={showH}/>:<><MoleculeDiagram smiles={input} explicitHydrogens={showH}/><Note>本批没有已核验的氨 3D 坐标，因此使用精确二维图。</Note></>}</section><section className="fg-panel"><h3>省略写法，不等于没有氢</h3><ExactEquation source={`\\ce{${current.formula}}`}/>{r?<><Stats result={r}/><table><thead><tr><th>原子</th><th>附带氢</th></tr></thead><tbody>{r.atoms.map((a,i)=><tr key={i}><td>{a.element} · 索引 {i}</td><td>{a.hydrogens}</td></tr>)}</tbody></table></>:<p>{error||'正在计算…'}</p>}<p>勾选只控制显示；不会改变 SMILES、分子式或氢总数。</p></section></div><Note>中性简单 C / N / O 例子可分别补足常见价态 4 / 3 / 2。带电、芳香及方括号写法必须按规则读取，不能无条件套用减法。</Note></>}
const syntax=[{label:'双键 =',s:'C=C',contrast:'CC',text:'两个碳仍是两个重原子。双键提高键级；乙烯含 4 个氢，乙烷含 6 个氢。'},{label:'支链 ( )',s:'CC(C)C',contrast:'CCCC',text:'括号表示从当前原子分支。两者都有 4 个碳，但连接方式不同。'},{label:'环标记 1',s:'C1CCCCC1',contrast:'CCCCCC',text:'两个相同数字配成一对，闭合一条键。数字不是新碳：环己烷是 6 个碳。'},{label:'芳香小写 c',s:'c1ccccc1',contrast:'C1CCCCC1',text:'小写 c 表示芳香碳。本例苯含 6 个氢，环己烷含 12 个氢；不以气味判断芳香性。'}]
function Syntax(){const [index,setIndex]=useState(0),row=syntax[index];return <><div className="fg-controls">{syntax.map((r,i)=><button key={r.label} aria-pressed={index===i} onClick={()=>setIndex(i)}>{r.label}</button>)}</div><div className="fg-two">{[row.contrast,row.s].map(s=><section className="fg-panel" key={s}><h3><code>{s}</code></h3><Result smiles={s}/></section>)}</div><Note>{row.text} 本页只覆盖入门子集；还有电荷、同位素、立体化学等规则，不能称作 SMILES 全套语法。</Note></>}
function Validation(){const [input,setInput]=useState('CCO'),{module,error}=useRDKit();let result:SmilesResult|null=null,problem=error;try{if(module)result=analyzeSmiles(module,input)}catch(e){problem=(e as Error).message}const matched=result&&module?result.canonical===analyzeSmiles(module,'CCO').canonical:false;return <><div className="fg-controls">{['CCO','COC','C1CC'].map(s=><button key={s} aria-pressed={input===s} onClick={()=>setInput(s)}>{s}</button>)}</div><div className="fg-two"><section className="fg-panel"><h3>当前输入：{input}</h3>{result?<><MoleculeDiagram smiles={input}/><Stats result={result}/></>:<div className="sm-empty" role="status">{problem||'正在加载…'}<p>解析失败时清空结构，不保留上一张成功图。</p></div>}</section><section><ol className="fg-trace"><li><strong>1 · 能解析吗？</strong><p>{result?'是，当前 RDKit 接受。':module?'否，先检查环标记、括号和价态。':'等待库。'}</p></li><li><strong>2 · 是目标乙醇吗？</strong><p>{result?(matched?'规范结构一致。':'不是；COC 是另一个合法结构。'):'解析失败，不进入目标判定。'}</p></li><li><strong>3 · 能证明什么？</strong><p>连接结构核对；不能证明药效、合成可行性或使用安全。</p></li></ol></section></div><Note>未配对的环标记是 C1CC 的问题。这里不伪造 RDKit 返回的具体字符错误位置，也不自动“猜着修复”。</Note></>}
function Trace(){const steps=useTeachingSteps(10),t=phenolTrace(steps.step);return <><StepControls steps={steps} count={10} label="SMILES 读取轨迹"/><div className="sm-tokens">{[...'Oc1ccccc1'].map((s,i)=><button key={i} data-read={i<steps.step} aria-current={i===steps.step-1?'step':undefined} onClick={()=>steps.jump(i+1)}>{s}<small>{i+1}</small></button>)}</div><div className="fg-two"><section className="fg-panel"><h3>完整结构预览 · 苯酚</h3><MoleculeDiagram smiles="Oc1ccccc1" highlight={t.highlight}/><p className="fg-small">始终由完整有效 SMILES 生成，黄色标记已读原子；不是把不完整芳香片段当成有效分子。</p></section><section><div className="sm-stats">{[['已读重原子',t.heavy],['已接重原子键',t.bonds],['已闭环',t.rings]].map(([k,v])=><div key={k}><strong>{v}</strong><span>{k}</span></div>)}</div><table><tbody><tr><th>当前字符</th><td><code>{t.token}</code></td></tr><tr><th>环表：标记 1</th><td>{t.ringOpen?'保存端点：原子索引 1':t.rings?'已配对并闭合':'尚未登记'}</td></tr></tbody></table><p role="status" className="sm-message">{t.message}</p></section></div><Note>这是解释字符串与分子图关系的教学轨迹，不是 RDKit 内部算法录像，更不是化学反应或分子形成过程。</Note></>}
function downloadText(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function Workbench(){const {module,error}=useRDKit(),[target,setTarget]=useState('ethanol'),[input,setInput]=useState(''),[result,setResult]=useState<SmilesResult|null>(null),[attempts,setAttempts]=useState<SmilesAttempt[]>([]),[observation,setObservation]=useState(''),[message,setMessage]=useState('输入后点击运行。填入参考写法也需要实际核对。');const current=TARGETS.find(t=>t.id===target)!;
 const clear=(value:string)=>{setInput(value);setResult(null);setMessage('输入已改变，请重新运行。')}
 const run=()=>{setResult(null);if(!module){setMessage(error||'等待 RDKit 加载。');return}try{const r=analyzeSmiles(module,input),matched=r.canonical===analyzeSmiles(module,current.smiles).canonical;setResult(r);setAttempts(a=>[...a,{input,target,parsed:true,matched,canonical:r.canonical}].slice(-12));setMessage(matched?'结构与当前目标一致。':'解析成功，但不是当前目标；请检查连接。')}catch(e){setAttempts(a=>[...a,{input,target,parsed:false,matched:false}].slice(-12));setMessage((e as Error).message)}}
 const save=()=>{if(!module)return;if(!result||result.input!==input){setMessage('请先运行当前输入并通过目标核对。');return}try{const record=makeSmilesRecord(module,target,input,attempts,observation);try{localStorage.setItem(SMILES_KEY,JSON.stringify(record));window.dispatchEvent(new Event('m05-saved'));setMessage('个人结构记录已保存并下载；下一页可复核。')}catch{setMessage('本机存储不可用，已下载备份。')}downloadEvidence('M05-my-molecule.json',record)}catch(e){setMessage((e as Error).message)}}
 return <><div className="fg-controls">{TARGETS.map(t=><button key={t.id} aria-pressed={t.id===target} onClick={()=>{setTarget(t.id);setResult(null);setMessage('目标已改变，请核对当前输入并重新运行。')}}>{t.name}</button>)}</div><div className="fg-two"><section className="fg-panel"><h3>目标：{current.name}</h3><p className="fg-small">参考：PubChem CID {current.cid}。本页只有软件操作，不进行制备或用药。</p><label className="fg-label">我的 SMILES<input aria-label="我的 SMILES" value={input} maxLength={180} onChange={e=>clear(e.target.value)}/></label><div className="fg-controls"><button onClick={run} disabled={!module}>运行并核对</button><button onClick={()=>clear(current.smiles)}>填入参考写法</button></div><p role="status" className="sm-message">{error||message}</p>{result?<><MoleculeDiagram smiles={result.input}/><p className="sm-canonical"><code>{result.canonical}</code></p><button onClick={()=>downloadText('M05-my-molecule.svg',result.svg,'image/svg+xml')}>下载当前 RDKit 结构图</button></>:<div className="sm-empty">尚无当前输入的有效结构</div>}</section><section><h3>把修正过程留下来</h3><p className="fg-small">保留最近 12 次实际尝试。完成一个药物结构目标、一条失败尝试和自己的说明。</p><table><thead><tr><th>输入</th><th>解析 / 目标</th></tr></thead><tbody>{attempts.slice(-4).map((a,i)=><tr key={i}><td><code>{a.input||'（空输入）'}</code></td><td>{!a.parsed?'未解析':a.matched?'与当时目标一致':'非当时目标'}</td></tr>)}</tbody></table><label className="fg-label">我的错误与修正<textarea aria-label="我的 SMILES 修正说明" value={observation} maxLength={280} onChange={e=>setObservation(e.target.value)}/></label><div className="fg-controls"><button onClick={save} disabled={!module}>保存个人结构记录</button><button onClick={()=>downloadText('m05_draw.py',smilesPython(input||current.smiles),'text/x-python')}>下载 Python 绘图模板</button></div><Note>这里实际执行的是浏览器 RDKit。下载 Python 模板不代表你已经在 Python 运行；后续须自行保存运行证据。</Note></section></div></>
}
function Handoff(){const {module,error}=useRDKit(),raw=useSaved(SMILES_KEY),record=module?restoreSmilesRecord(module,raw):null,[confirm,setConfirm]=useState(false);return <div className="fg-two"><section className="fg-panel"><h3>本人保存的结构成果</h3>{record?<><MoleculeDiagram smiles={record.input}/><p className="sm-canonical">输入：<code>{record.input}</code></p><p>{TARGETS.find(t=>t.id===record.target)?.name} · 当前 RDKit {record.version} 重新核对通过</p><blockquote>{record.observation}</blockquote><p>{record.attempts.length} 条尝试；至少一条解析或目标核对失败。</p><div className="fg-controls"><button onClick={()=>downloadEvidence('M05-my-molecule.json',record)}>下载已保存结构记录</button><button onClick={()=>{if(!confirm){setConfirm(true);return}try{localStorage.removeItem(SMILES_KEY);window.dispatchEvent(new Event('m05-saved'));setConfirm(false)}catch{}}}>{confirm?'确认清除 M05 记录':'清除 M05 本机记录'}</button></div></>:<p role="status">{error||(!module?'正在加载核验库…':raw?'保存内容未通过当前重新核验，请回第 8 页重做。':'还没有个人结构成果。请回第 8 页提交；示例图不会自动算作你的作品。')}</p>}</section><section><h3>下一步拿到的是数据，不是一句“完成了”</h3><ol className="fg-trace"><li>M04 · 比较：输入、算法、数值与有限结论。</li><li>M05 · 表达：自己选择目标，输入字符串，核对连接并保留修正记录。</li><li>后续 · 组织：把结构输入和属性放进同一份数据，继续计算、比较与筛选。</li></ol><Note>当前成果验证结构表达，不证明真实存在、可合成、药效或安全性。个人记录仅在本机保存；请下载备份。</Note></section></div>}
export function SmilesReadingVisual({visual}:{visual:Spec}){const views={overview:Overview,equivalence:Equivalence,tokens:Tokens,hydrogens:Hydrogens,syntax:Syntax,validation:Validation,trace:Trace,workbench:Workbench,handoff:Handoff},View=views[visual.scene];return <div className="fg m03-v2 sm" data-renderer="smiles-reading" data-scene={visual.scene}><View/><footer><a href="https://www.daylight.com/dayhtml/doc/theory/theory.smiles.html">SMILES 语法</a> · <a href="https://www.rdkitjs.com/">RDKit.js</a> · <a href="https://pubchem.ncbi.nlm.nih.gov/compound/2519">PubChem 咖啡因</a> · 精确连接图、教学轨迹与来源明确的 3D 各司其职。</footer></div>}
