"use client"

import { useEffect, useState, type ReactNode } from 'react'
import type { SlideTechnicalVisual } from '@/lib/types/api'
import { getRDKitModule } from '@/lib/rdkit'
import { TARGETS, teachingTokens, smilesPython } from '@/lib/smiles-reading'
import { SMILES_REFERENCE, SMILES_REFERENCE_VERSION, SMILES_TRACE, SYNTAX_PAIRS, computeSmilesEvidence, sameSmilesEvidence, validSmilesRow, type SmilesEvidence } from '@/lib/smiles-readonly'
import { MOLECULES, GEOMETRY_SOURCE } from '@/lib/molecule-skeleton'
import { MolecularObject3D, MoleculeDiagram } from './molecular-object-3d'
import { ExactEquation } from './screening-common'
import { useReadonlySteps } from './readonly-presentation'
import './molecular-funnel.css'
import './skeleton-evidence.css'
import './functional-group-readonly.css'
import './smiles-reading-readonly.css'

type Spec=Extract<SlideTechnicalVisual,{renderer:'smiles-reading'}>
type Calculation={rows:SmilesEvidence;verified:boolean;message:string}
type Props={calculation:Calculation}
function useEvidence():Calculation {
  const [state,setState]=useState<Calculation>({rows:SMILES_REFERENCE,verified:false,message:`独立核验参考 · RDKit ${SMILES_REFERENCE_VERSION}；正在核对当前浏览器`})
  useEffect(()=>{let live=true;getRDKitModule().then(rdkit=>{
    const rows=computeSmilesEvidence(rdkit)
    if(!sameSmilesEvidence(rows))throw Error('Reference mismatch')
    if(live)setState({rows,verified:true,message:`浏览器 RDKit ${rdkit.version()} 实际解析，已与固定参考核对`})
  }).catch(()=>{if(live)setState({rows:SMILES_REFERENCE,verified:false,message:'本页计算暂不可用；显示独立核验参考，不表示当前浏览器解析成功'})});return()=>{live=false}},[])
  return state
}
function Note({children}:{children:ReactNode}){return <aside className="fgr-note">{children}</aside>}
function Structure({input,title,explicit=false}:{input:string;title?:string;explicit?:boolean}){
  return <section className="fgr-structure"><header><h3>{title||input}</h3>{title&&<code>{input}</code>}</header><MoleculeDiagram smiles={input} explicitHydrogens={explicit}/></section>
}
function Stats({rows,input}:{rows:SmilesEvidence;input:string}){const r=validSmilesRow(rows,input);return <dl className="smro-stats">{[['重原子',r.heavy],['氢',r.hydrogens],['重原子间键',r.bonds],['环',r.rings]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}
function Overview(){return <><p className="fgr-kicker">M04 比较结构 → M05 明确写出输入</p><div className="smro-flow"><section className="fgr-panel"><h3>01 · 字符串</h3><code className="smro-input">CCO</code><p>按顺序写了三个重原子；不是三维坐标文件。</p><div className="smro-token-row">{teachingTokens('CCO').map((t,i)=><span key={i}>{t}<small>索引 {i}</small></span>)}</div></section><section className="fgr-panel"><h3>02 · 连接账本</h3><table><thead><tr><th>索引 / 元素</th><th>相邻重原子</th></tr></thead><tbody><tr><td>0 / C</td><td>1</td></tr><tr><td>1 / C</td><td>0、2</td></tr><tr><td>2 / O</td><td>1</td></tr></tbody></table><p>3 个重原子 · 2 条连接</p></section><Structure input="CCO" title="03 · RDKit 结构图"/></div><Note>解析与绘图把同一份连接数据变得可读。线端省略的 C 要按骨架式读；H 的省略规则在第 4 页核对。参考结构不算个人成果。</Note></>}
function Equivalence({calculation:{rows}}:Props){const target=validSmilesRow(rows,'CCO').canonical;return <><div className="fgr-three"><Structure input="CCO" title="乙醇 · 从碳端读"/><Structure input="OCC" title="乙醇 · 从氧端读"/><Structure input="COC" title="二甲醚 · 氧在中间"/></div><table><caption>同时比较字符串、规范写法和连接，不靠“解析成功”下结论</caption><thead><tr><th>输入</th><th>RDKit 规范写法</th><th>氧连接的重原子</th><th>与乙醇目标</th></tr></thead><tbody>{['CCO','OCC','COC'].map(s=><tr key={s} data-equivalence-row={s}><th><code>{s}</code></th><td><code>{validSmilesRow(rows,s).canonical}</code></td><td>{s==='COC'?'两个碳':'一个碳'}</td><td>{validSmilesRow(rows,s).canonical===target?'同一连接结构':'不是同一连接结构'}</td></tr>)}</tbody></table><ExactEquation source={String.raw`\ce{C2H6O}\quad\text{不唯一确定连接方式}`}/><Note>三个输入都合法，分子式也相同，但 COC 是异构体。这里只比较同一 RDKit 版本的规范写法，不承诺不同软件返回完全相同字符串。</Note></>}
function Tokens({calculation:{rows}}:Props){return <><div className="fgr-three">{['CCO','ClC','[NH4+]'].map(input=><section key={input} className="fgr-panel"><h3><code>{input}</code></h3><div className="smro-token-row">{teachingTokens(input).map((t,i)=><span key={i}>{t}</span>)}</div><MoleculeDiagram smiles={input} explicitHydrogens/><p>{input==='ClC'?'Cl 是完整元素符号，另一个 C 才是碳。':input==='[NH4+]'?'方括号声明 N、4 个 H 和 +1 电荷。':'C、C、O 是三个重原子。'}</p></section>)}</div><table><caption>RDKit 原子表 · 索引从 0 开始；氢附在对应原子上</caption><thead><tr><th>输入</th><th>原子索引</th><th>元素</th><th>所带 H</th><th>形式电荷</th></tr></thead><tbody>{['CCO','ClC','[NH4+]'].flatMap(input=>validSmilesRow(rows,input).atoms.map((a,i)=><tr key={input+i}><th><code>{input}</code></th><td>{i}</td><td>{a.element}</td><td>{a.hydrogens}</td><td>{a.charge>0?`+${a.charge}`:a.charge}</td></tr>))}</tbody></table><ExactEquation source={String.raw`\ce{NH4+}\qquad 1\text{ 个重原子}+4\text{ 个氢}`}/><Note>这里的分词只解释固定例子，不是完整 SMILES 解析器。“Cl”不能拆为 C 和 l；方括号中的数字也不等于新增重原子。</Note></>}
function Hydrogens({calculation:{rows}}:Props){const {root,step}=useReadonlySteps(3,4200),m=MOLECULES.find(r=>r.id==='ethanol')!;return <section ref={root} data-demo-step={step}><p className="fgr-state">{step+1} / 3 · {['只画重原子：H 被省略显示','显示全部 H：结构总数没有增加','斜向观察：看清连接，不把二维布局当空间形状'][step]}</p><div className="fgr-two smro-hydrogen"><section><MolecularObject3D molecule={m} showH={step>0} selected={null} readOnly presetView={step===2?'oblique':'face'} observationPlane={[1,0,8]}/><p className="fgr-source">PubChem CID702 计算构象，经 RDKit {GEOMETRY_SOURCE.rdkitVersion} 核验；不是当前字符串即时生成的坐标或分子动力学。</p></section><section className="fgr-panel"><h3>乙醇结构总原子数始终为 9</h3><ExactEquation source={String.raw`\ce{C2H6O}:\quad 2+6+1=9`}/><table><thead><tr><th>显示口径</th><th>可见球数</th><th>结构实际总数</th></tr></thead><tbody><tr className={step===0?'fgr-active':''}><th>只画重原子</th><td>3</td><td>9</td></tr><tr className={step>0?'fgr-active':''}><th>显示全部氢</th><td>9</td><td>9</td></tr></tbody></table><MoleculeDiagram smiles="CCO" explicitHydrogens/><p>省略的是写法与显示，不是把氢从分子里删除。</p></section></div><table><caption>四个简单中性例子的完整账本 · 不是所有情况的通用减法</caption><thead><tr><th>输入</th><th>分子式</th><th>重原子</th><th>H</th><th>总原子</th></tr></thead><tbody>{[['C','CH4'],['N','NH3'],['O','H2O'],['CCO','C2H6O']].map(([s,f])=>{const r=validSmilesRow(rows,s);return <tr key={s}><th><code>{s}</code></th><td><ExactEquation source={`\\ce{${f}}`}/></td><td>{r.heavy}</td><td>{r.hydrogens}</td><td>{r.heavy+r.hydrogens}</td></tr>})}</tbody></table><Note>带电、芳香和方括号写法有各自规则，不能无条件用 C 四价、N 三价、O 二价补氢。本页固定输入自动演示，无需旋转或选择。</Note></section>}
function Syntax({calculation:{rows}}:Props){return <><div className="smro-syntax">{SYNTAX_PAIRS.map(p=><section className="fgr-panel" key={p.label} data-syntax-pair={p.label}><h3>{p.label}</h3><div className="smro-pair">{[p.before,p.after].map(s=><section key={s}><code>{s}</code><MoleculeDiagram smiles={s}/><Stats rows={rows} input={s}/></section>)}</div><p>{p.claim}</p></section>)}</div><Note>键的数量与键级不是一回事：C=C 仍只有一对相邻碳。这里只覆盖入门子集；电荷、同位素和立体化学仍需相应规则，芳香性不按气味判断。</Note></>}
function Validation({calculation:{rows}}:Props){return <><div className="fgr-three"><section className="fgr-panel"><h3>① 无法解析</h3><code>C1CC</code><div className="smro-invalid">未配对的环标记 1<br/>没有有效分子图</div></section><Structure input="COC" title="② 合法，但不是乙醇"/><Structure input="CCO" title="③ 合法且连接匹配"/></div><table><caption>目标固定为乙醇 · 两道检查不能合并</caption><thead><tr><th>输入</th><th>RDKit 解析</th><th>规范结构</th><th>目标核对</th></tr></thead><tbody>{['C1CC','COC','CCO'].map(s=>{const r=rows[s];return <tr key={s} data-validation-row={s}><th><code>{s}</code></th><td>{r.parsed?'通过':'失败'}</td><td><code>{r.parsed?r.canonical:'— 无有效结构'}</code></td><td>{!r.parsed?'未执行，不等于通过':r.canonical===validSmilesRow(rows,'CCO').canonical?'与目标一致':'不是目标'}</td></tr>})}</tbody></table><Note>解析失败不能沿用上一张成功图，也不猜测具体字符报错位置。结构核对不证明药效、安全或合成可行性。</Note></>}
function Trace(){const {root,step}=useReadonlySteps(10,1700),t=SMILES_TRACE[step];return <section ref={root} data-demo-step={step}><div className="smro-token-row">{[...'Oc1ccccc1'].map((s,i)=><span key={i} data-read={i<step} aria-current={i===step-1?'step':undefined}>{s}<small>{i+1}</small></span>)}</div><div className="fgr-two"><section className="fgr-panel"><h3>完整苯酚图 · 已读原子高亮</h3><MoleculeDiagram smiles="Oc1ccccc1" highlight={t.highlight}/><p>图始终来自完整有效输入；不把片段当成有效分子。</p></section><section className="fgr-panel"><p className="fgr-kicker">自动读取 {step} / 9</p><h3>{t.message}</h3><dl className="fgr-fields"><dt>已读重原子</dt><dd>{t.heavy}</dd><dt>已登记连接</dt><dd>{t.bonds}</dd><dt>环表</dt><dd>{t.ringOpen?'标记 1 → 保存索引 1':t.rings?'1 配对闭合，环数 1':'尚未登记'}</dd></dl></section></div><table className="smro-trace"><caption>完整教学读取轨迹 · 暂停时仍可核对全部状态</caption><thead><tr><th>步 / 字符</th><th>重原子</th><th>连接</th><th>环表变化</th></tr></thead><tbody>{SMILES_TRACE.map(r=><tr key={r.step} data-smiles-trace={r.step} className={step===r.step?'fgr-active':''}><th>{r.step} / <code>{r.token}</code></th><td>{r.heavy}</td><td>{r.bonds}</td><td>{r.step===0?'未开始':r.step===3?'保存环端点；不添加原子':r.step===9?'配对闭环；只新增一条连接':r.ringOpen?'端点保持，继续读取原子':'读取原子及相邻连接'}</td></tr>)}</tbody></table><Note>最终 7 个重原子、7 条重原子间连接、1 个环。这是解释语法的教学轨迹，不是 RDKit 内部实现录像，也不是化学反应。</Note></section>}
function Workbench({calculation:{rows}}:Props){const targets=TARGETS.filter(t=>t.deliverable);return <><div className="fgr-two">{targets.map(t=><section className="fgr-panel" key={t.id}><h3>{t.name} · PubChem CID {t.cid}</h3><code className="smro-wrap">{t.smiles}</code><MoleculeDiagram smiles={t.smiles}/><Stats rows={rows} input={t.smiles}/><p className="fgr-source">规范写法：<code>{validSmilesRow(rows,t.smiles).canonical}</code></p></section>)}</div><div className="fgr-two"><section><h3>完整 Python 绘图模板 · 咖啡因</h3><pre className="fgr-code"><code>{smilesPython(targets[0].smiles)}</code></pre><p>代码供课后独立运行；本页不执行本机 Python，不保存或下载个人成果。</p></section><section className="fgr-panel"><h3>构造的纠错示例 · 目标固定为乙醇</h3><table><thead><tr><th>输入</th><th>证据与下一步</th></tr></thead><tbody><tr><th><code>C1CC</code></th><td>解析失败；重新对照目标连接，不猜着补字符。</td></tr><tr><th><code>COC</code></th><td>合法但氧连两个碳；目标应有末端 OH。</td></tr><tr><th><code>CCO</code></th><td>解析通过，规范结构与目标一致；保留输入与版本。</td></tr></tbody></table><Note>不是你的运行记录。药物目标的实际输入、SVG、运行输出和失败修正说明，应由本人课后产生，不能直接把这里的例子当作提交。</Note></section></div></>}
function Handoff(){return <><table><caption>从比较，到精确表达，再到阶段总装</caption><thead><tr><th>节点</th><th>证据产物</th><th>如何接到下一步</th></tr></thead><tbody><tr><th>M04 比较</th><td>两个结构、计算方法、数值与有限结论</td><td>明确结构变化，而不是只记一个分数</td></tr><tr className="fgr-active"><th>M05 表达</th><td>目标来源、SMILES、结构图、版本与纠错依据</td><td>输入可重复解析，连接可核对</td></tr><tr><th>M06 阶段总装</th><td>把结构识读与前面知识组成真药识读小工作台</td><td>同一输入连接结构、属性和来源</td></tr></tbody></table><div className="fgr-two"><section className="fgr-panel"><h3>参考记录要有的字段</h3><pre className="fgr-code"><code>{'目标及来源\n输入 SMILES\nRDKit 版本\n规范结构及 SVG\n实际运行输出\n失败输入 → 修正说明'}</code></pre></section><section className="fgr-panel"><h3>理解与个人成果分开</h3><p>本页不读取本机保存内容，也不会自动判定任务完成。个人证据仍须来自自己的运行和核对。</p><p>能解析、目标一致、具有药效或安全，是不同层次的问题。</p></section></div><Note>接下来按连续编号进入 M06。所有任务仅在软件中完成，不在现实中制备、服用或测试这些物质。</Note></>}

export function SmilesReadingReadonly({visual}:{visual:Spec}) {
  const calculation=useEvidence(),scenes={overview:Overview,equivalence:Equivalence,tokens:Tokens,hydrogens:Hydrogens,syntax:Syntax,validation:Validation,trace:Trace,workbench:Workbench,handoff:Handoff},Scene=scenes[visual.scene]
  return <section className="fgr smro" data-renderer="smiles-reading" data-scene={visual.scene} data-presentation="readonly" aria-label={visual.aria_label}><Scene calculation={calculation}/><p className="fgr-source" data-rdkit-check={calculation.verified?'verified':'reference'}>{calculation.message}</p><footer>只读讲解 · <a href="https://www.daylight.com/dayhtml/doc/theory/theory.smiles.html">SMILES 规则</a> · <a href="https://www.rdkitjs.com/">RDKit.js</a> · 结构与参考示例不是个人成果。</footer></section>
}
