"use client"
import { useEffect, useState } from 'react'
import type { SlideTechnicalVisual } from '@/lib/types/api'
import { drawSmilesSvg } from '@/lib/rdkit'
import { WB_DATA_NOTE, WB_FEATURES, WB_MOLECULES, WB_STAGES, auditEvaluation, checkFeatureContract, pipelineTrace, workbenchReport, type EvaluationMode, type RunScenario } from '@/lib/workbench-evidence'
import { ExactEquation, StepControls, useTeachingSteps, downloadEvidence } from './screening-common'
import './workbench-evidence.css'

const correctNames=WB_FEATURES.map(f=>f.key)
const swappedNames=[correctNames[1],correctNames[0],...correctNames.slice(2)]
function Structure({index}:{index:number}) {
  const row=WB_MOLECULES[index],[drawing,setDrawing]=useState({smiles:'',svg:'',error:false})
  useEffect(()=>{let live=true;drawSmilesSvg(row.smiles,{width:440,height:200}).then(svg=>{if(live)setDrawing({smiles:row.smiles,svg,error:false})}).catch(()=>{if(live)setDrawing({smiles:row.smiles,svg:'',error:true})});return()=>{live=false}},[row.smiles])
  const svg=drawing.smiles===row.smiles?drawing.svg:''
  return <figure className="wb-structure"><div role="img" aria-label={`${row.name}的 RDKit 二维结构`} dangerouslySetInnerHTML={{__html:svg}}/>{!svg&&<p>{drawing.error?'结构暂不可用，保留 SMILES':'正在绘制 RDKit 结构…'}</p>}<figcaption><strong>{row.id} · {row.name}</strong><code>{row.smiles}</code></figcaption></figure>
}
function CandidateSelect({index,setIndex}:{index:number;setIndex:(n:number)=>void}) {return <label className="wb-field">当前候选<select aria-label="当前候选" value={index} onChange={e=>setIndex(Number(e.target.value))}>{WB_MOLECULES.map((r,i)=><option key={r.id} value={i}>{r.id} · {r.name}</option>)}</select></label>}
function Contract({exercise=false}:{exercise?:boolean}) {
  const [names,setNames]=useState<readonly string[]>(swappedNames),[checked,setChecked]=useState(!exercise)
  const row=WB_MOLECULES[0],values=names.map(n=>row.values[correctNames.indexOf(n as typeof correctNames[number])]),result=checkFeatureContract(names,values)
  return <><div className="wb-prompt"><strong>同样是 8 个数，顺序错了也不能交给模型。</strong><span>练习对象：乙醇 CCO；真实描述符，按列名取值。训练契约版本：features-v1。</span></div><table aria-label="特征列顺序契约"><thead><tr><th>位置 / 训练时需要</th><th>实际送入列</th><th>实际值</th><th>核对</th></tr></thead><tbody>{WB_FEATURES.map((f,i)=><tr key={f.key} className={checked&&names[i]!==f.key?'wb-bad-row':''}><th>{i+1} · {f.key}<small>{f.unit}</small></th><td>{exercise?<select aria-label={`第${i+1}列特征`} value={names[i]||''} onChange={e=>{setNames(names.map((n,j)=>j===i?e.target.value:n));setChecked(false)}}>{correctNames.map(k=><option key={k}>{k}</option>)}</select>:<code>{names[i]??'缺失'}</code>}</td><td>{Number.isFinite(values[i])?values[i]:'—'}</td><td>{checked?(names[i]===f.key?'一致':'错位 / 缺失'):'待核对'}</td></tr>)}</tbody></table><div className="wb-controls">{exercise?<><button onClick={()=>setChecked(true)}>检查接口</button><button onClick={()=>{setNames(swappedNames);setChecked(false)}}>恢复初始错序</button></>:<><button onClick={()=>setNames(swappedNames)}>交换 MW 与 LogP</button><button onClick={()=>setNames(correctNames.slice(0,7))}>模拟缺少一列</button><button onClick={()=>setNames(correctNames)}>按训练顺序恢复</button></>}</div>{checked&&<div className={`wb-verdict ${result.ok?'wb-pass':'wb-fail'}`} role="status"><strong>{result.ok?'接口通过：可以进入下一道':'已阻断：不调用模型'}</strong><p>{result.ok?'名称、顺序、数量、单位和值都通过当前契约检查。方法和预处理配置也须与真实模型包一致。':result.errors.join('；')}</p></div>}</>
}
function ReportPanel({index,riskLimit}:{index:number;riskLimit:number}) {
  const report=workbenchReport(riskLimit),r=report.candidates[index],rank=report.top10.find(x=>x.id===r.id)?.rank
  return <div className="wb-report"><div className="wb-report-head"><span>候选 {r.id} · {r.name}</span><strong>{r.decision}</strong></div><table aria-label="候选证据报告"><tbody><tr><th>RDKit 描述符</th><td>MW {r.values[0].toFixed(3)} g/mol；cLogP {r.values[1].toFixed(4)}</td></tr><tr><th>模型接口测试值</th><td>risk {r.prediction.risk.toFixed(2)}；logS {r.prediction.logS.toFixed(1)}<small>编造值，仅用于测试数据怎样流入规则；不描述此分子的实际性质。</small></td></tr><tr><th>Lipinski 统计</th><td>{r.violations} 项违反；本例允许 ≤ 1 项</td></tr><tr><th>本轮理由</th><td>{r.reason}</td></tr><tr><th>教学优先级</th><td>{rank?`第 ${rank} / ${report.top10.length} 名；1 − risk = ${r.priority.toFixed(2)}`:'未进入排序，不用空名额补入'}</td></tr><tr><th>真实研究决定</th><td><strong>需要更多证据</strong><small>缺真实训练模型、适用范围与评估记录；Go 不等于安全或有效。</small></td></tr></tbody></table></div>
}
function EvaluationPanel() {
  const [mode,setMode]=useState<EvaluationMode>('disjoint'),a=auditEvaluation(mode)
  return <><div className="wb-controls">{([['disjoint','无重叠示例'],['leak','注入分组泄漏'],['missing','移除评估记录']] as const).map(([id,label])=><button key={id} aria-pressed={mode===id} onClick={()=>setMode(id)}>{label}</button>)}</div><div className="wb-two"><section><h3>分组清单先核对</h3><div className="wb-groups"><p>训练：{a.trainGroups.join('、')}</p><p>测试：{a.testGroups.join('、')||'未提供'}</p><strong>交集：{a.overlap.join('、')||(a.rows.length?'空集':'未知')}</strong></div><p className={a.groupCheck?'wb-pass wb-verdict':'wb-fail wb-verdict'}>{a.note}</p><p className="wb-small">A–D 是人工分组标签，不是现场计算的化学骨架。实际作业需保存真实 scaffold 划分；它也不能保证杜绝所有泄漏或未来预测准确。</p><h3>四行评估示例（全部为构造值）</h3><table><thead><tr><th>ID</th><th>分类标签 / 分数</th><th>回归目标 / 预测</th></tr></thead><tbody>{a.rows.map(r=><tr key={r.id}><td>{r.id}</td><td>{r.label} / {r.score}</td><td>{r.truth} / {r.prediction}</td></tr>)}</tbody></table></section><section className="wb-card"><h3>数字算得出 ≠ 评估可信</h3><ExactEquation source={String.raw`\mathrm{AUC}=\frac{\text{wins}+0.5\,\text{ties}}{N_+N_-}`}/><p className="wb-metric">{a.metrics?`${a.metrics.auc.toFixed(2)} = 3 / 4`:'AUC 未提供'}</p>{a.metrics&&<p className="wb-small">四个正负配对的得分：{a.metrics.pairs.map(p=>p.credit).join('、')}；不是从截图猜一个分数。</p>}<ExactEquation source={String.raw`\mathrm{MAE}=\frac{1}{n}\sum_{i=1}^{n}|\hat y_i-y_i|`}/><p className="wb-metric">{a.metrics?`${a.metrics.mae.toFixed(2)} = (0.5 + 0.5 + 1 + 0) / 4`:'MAE 未提供'}</p><p className="wb-callout">有分组重叠时，数字没有自动消失，但不能把它当作合格的组间测试成绩。没有记录时保持缺失，不能补 0。</p></section></div></>
}
function RunTrace({scenario}:{scenario:RunScenario}) {
  const trace=pipelineTrace(scenario),steps=useTeachingSteps(trace.length),current=trace[steps.step]
  return <><StepControls steps={steps} count={trace.length} label="总装过程"/><div className="wb-run"><ol>{WB_STAGES.map((s,i)=><li key={s.name} data-state={i<steps.step?'done':i===steps.step?current.status:'waiting'}><b>{String(i+1).padStart(2,'0')}</b><span>{s.name}</span><small>{i===steps.step?(current.status==='blocked'?'阻断':'已完成'):i<steps.step?'已完成':'未执行'}</small></li>)}</ol><section><p className="wb-kicker">当前接缝 · {steps.step+1}</p><h3>{current.name}</h3><dl className="wb-payload"><dt>接收</dt><dd>{current.from}</dd><dt>验证</dt><dd>{current.check}</dd><dt>产出 / 错误</dt><dd>{current.output}</dd></dl><div className={`wb-verdict ${current.status==='blocked'?'wb-fail':'wb-pass'}`} role="status">{current.status==='blocked'?'停止在这里。后续预测、排序和报告均不伪造。':steps.step===4?'教学流程已到报告；真实模型和真实评估仍待补齐。':'这道已交出具名结果，下一道才能继续。'}</div><div className="wb-log">{trace.slice(0,steps.step+1).map(s=><p key={s.stage}><code>{s.status==='pass'?'OK':'STOP'} · {s.stage+1}</code> {s.output}</p>)}</div></section></div></>
}
const tasks=[
  ['铺好骨架','已有：结构、特征、模型、漏斗、理由的版本信息','产出：入口到报告的接口清单'],
  ['接前半段','输入：SMILES 与已确定的特征契约','产出：能读通的结构 + 同列同序的特征表'],
  ['接后半段','输入：对齐特征 + 真实模型包 + 筛选政策','产出：预测、筛选轨迹、评分与名次'],
  ['熟分子走全程','输入：已知结构的乙醇或阿司匹林','产出：每个接缝的日志；不是“见过这个分子就证明模型准”'],
  ['出报告并验收','输入：候选证据 + 真实测试划分/标签/预测','产出：诚实报告 + 验收清单 + 观众的一条反馈'],
]
export function WorkbenchEvidenceVisual({visual}:{visual:Extract<SlideTechnicalVisual,{renderer:'workbench-evidence'}>}) {
  const [index,setIndex]=useState(0),[riskLimit,setRiskLimit]=useState(.4),[stage,setStage]=useState(0),[scenario,setScenario]=useState<RunScenario>('demo'),[hasEvaluation,setHasEvaluation]=useState(true)
  const steps=useTeachingSteps(5),report=workbenchReport(riskLimit,hasEvaluation?'disjoint':'missing'),scene=visual.scene
  let body:React.ReactNode=null
  switch(scene){
    case 'overview':body=<><div className="wb-flow">{WB_STAGES.map((s,i)=><div key={s.name}><b>{i+1}</b><strong>{s.name}</strong><small>{s.to}</small></div>)}</div><div className="wb-two"><section><CandidateSelect index={index} setIndex={setIndex}/><Structure index={index}/><p className="wb-callout">左侧换一个候选，右侧的 ID、结构证据、规则理由必须一起换，不能把不同分子的字段拼错行。</p></section><ReportPanel index={index} riskLimit={riskLimit}/></div></>;break
    case 'acceptance':body=<><div className="wb-two"><section><h3>每个要求，都指向可检查的产物</h3><table><thead><tr><th>要求</th><th>可查看的证据</th></tr></thead><tbody>{[['接通','一次运行的输入、阶段日志、报告'],['对齐','特征列名、顺序、单位和预处理版本'],['有理由','每个候选的规则、数值与比较结果'],['诚实','评估划分、测试标签、预测、局限']].map(([a,b])=><tr key={a}><th>{a}</th><td>{b}</td></tr>)}</tbody></table></section><section className="wb-card"><h3>演示通过 ≠ 真实作品已完成</h3><label className="wb-check"><input type="checkbox" checked={hasEvaluation} onChange={e=>setHasEvaluation(e.target.checked)}/>提供示例评估记录</label><p className={`wb-verdict ${hasEvaluation?'wb-pass':'wb-fail'}`}>{hasEvaluation?'教学报告字段可以核对；真实模型与真实评估仍未接入。':'评估记录缺失：保持“需要更多证据”，不填写虚构指标。'}</p><h3>最终交付还需要</h3><ul>{report.missingEvidence.map(x=><li key={x}>{x}</li>)}</ul><p>分数高低不是交付标准；记录完整、可复跑、如实说明局限才是。</p></section></div></>;break
    case 'assembly':body=<div className="wb-run"><nav aria-label="查看接口">{WB_STAGES.map((s,i)=><button key={s.name} aria-pressed={stage===i} onClick={()=>setStage(i)}>{i+1} · {s.name}</button>)}</nav><section className="wb-card"><p className="wb-kicker">不是再造一个零件，而是检查交接面</p><h3>{WB_STAGES[stage].name}</h3><dl className="wb-payload"><dt>上一道交来</dt><dd>{WB_STAGES[stage].from}</dd><dt>这道交出去</dt><dd>{WB_STAGES[stage].to}</dd><dt>如何验收</dt><dd>{WB_STAGES[stage].check}</dd></dl><pre>{JSON.stringify({candidate_id:'E',source_smiles:'CCO',stage:stage+1,contract_version:'features-v1',model:stage>=2?'mock-model-v1（教学替身）':'尚未调用'},null,2)}</pre><p className="wb-callout">candidate_id 从入口跟到报告。模型阶段的字段不是结构图，不能靠看图判断它的真伪。</p></section></div>;break
    case 'contract':body=<Contract/>;break
    case 'report':body=<><div className="wb-controls"><CandidateSelect index={index} setIndex={setIndex}/><label className="wb-field">教学 risk 上限 {riskLimit.toFixed(2)}<input aria-label="教学风险上限" type="range" min="0" max=".8" step=".02" value={riskLimit} onChange={e=>setRiskLimit(Number(e.target.value))}/></label></div><div className="wb-two"><ReportPanel index={index} riskLimit={riskLimit}/><section><h3>先过滤，再排本轮名单</h3><p className="wb-small">本例政策：Lipinski 违反 ≤ 1；mock risk ≤ 当前上限；mock logS ≥ −4。优先级只用 1 − mock risk，非 M44 完整多指标评分或 M45 多样性筛选。</p><table><thead><tr><th>顺序</th><th>候选</th><th>教学优先级</th></tr></thead><tbody>{report.top10.map(r=><tr key={r.id}><td>{r.rank}</td><td>{r.name}</td><td>{r.priority.toFixed(2)}</td></tr>)}</tbody></table><p className="wb-callout">通过者只有 {report.top10.length} 个就展示 {report.top10.length} 个。Top10 是上限，不是必须凑满的配额。</p><Structure index={index}/></section></div></>;break
    case 'evaluation':body=<EvaluationPanel/>;break
    case 'run':body=<><div className="wb-controls">{([['demo','正常教学流程'],['invalid','无效 SMILES'],['columns','特征错序'],['missing-model','模型缺失']] as const).map(([id,label])=><button key={id} aria-pressed={scenario===id} onClick={()=>setScenario(id)}>{label}</button>)}</div><RunTrace key={scenario} scenario={scenario}/></>;break
    case 'repair':body=<Contract exercise/>;break
    case 'tasks':body=<><StepControls steps={steps} count={5} label="五步交付"/><div className="wb-run"><ol>{tasks.map((t,i)=><li key={t[0]} data-state={i===steps.step?'pass':i<steps.step?'done':'waiting'}><b>{i+1}</b><span>{t[0]}</span></li>)}</ol><section className="wb-card"><h3>{tasks[steps.step][0]}</h3><p className="wb-prompt">{tasks[steps.step][1]}</p><p className="wb-verdict wb-pass">{tasks[steps.step][2]}</p><p>接好一道，就拿熟分子检查日志和字段。需要家长协助运行课文模板，不要求从零写整套系统。</p><p className="wb-callout">这一页演示任务递进，不会替你把真实作业自动打勾。</p></section></div></>;break
    case 'handoff':body=<><div className="wb-two"><section className="wb-card"><p className="wb-kicker">可以带走的教学报告</p><h3>一个文件，能查回每个决定</h3><table><tbody>{[['输入','3 个具名 SMILES 与 RDKit 描述符'],['规则','阈值、违反数、候选理由、排序'],['评估','4 行构造记录、分组清单、AUC/MAE 算法'],['局限','mock-model-v1；真实项目证据仍缺失']].map(([a,b])=><tr key={a}><th>{a}</th><td>{b}</td></tr>)}</tbody></table><button className="wb-download" onClick={()=>downloadEvidence('M47-workbench-teaching-report.json',report)}>下载教学报告 JSON</button><p className="wb-small">下载的是教学证据，不是你的全库结果；不替代真实模型训练或最终作业。</p></section><section><h3>从本页，走向你的真实成品</h3><ol>{report.missingEvidence.map(x=><li key={x}>{x}</li>)}<li>展示给同伴或老师，记下一个问题，再选一条可公开核对的证据继续研究。</li></ol><div className="wb-verdict wb-fail"><strong>真实研究结论：需要更多证据</strong><p>{report.limitation}</p></div><p>本节点是课程终点，但做完这份演示不等于已经完成自己的成品。</p></section></div></>;break
  }
  return <div className="wb" data-renderer="workbench-evidence" data-scene={scene}><p className="wb-disclosure">教学演示 · 精确结构 / 编造的模型接口测试值 / 非真实筛选结果</p>{body}<footer>{WB_DATA_NOTE} 所有表格、公式和状态均为确定性渲染；没有把工具名称当作已训练、已部署的能力。</footer></div>
}
