"use client"
import { useState } from 'react'
import type { SlideEntry } from '@/lib/types/api'
import { LessonSlidesProvider, LessonSlideCarousel, LessonSlideshowButton } from './lesson-slides'
const labels=['产品全景','验收证据','接口地图','故障注入','候选报告','公式与评估','动态执行','接口修复','五步交付','报告导出']
export function WorkbenchSlidePreview({slides}:{slides:SlideEntry[]}){
  const [index,setIndex]=useState(0),[width,setWidth]=useState('1152')
  return <main className="min-h-screen bg-[var(--paper)] p-5 text-[var(--ink)]"><div className="mx-auto" style={{maxWidth:Number(width)}}><p className="text-xs font-semibold text-[var(--primary-ink)]">分子猎人 · M90 · 10 页全部新版 · 本地预览 · 已于 2026-09-09 部署</p><h1 className="my-3 text-2xl font-semibold">从零散脚本，到可追溯的工作台</h1><p className="mb-4 text-sm text-[var(--sub)]">本节点讲软件总装：使用实际界面、RDKit、精确公式和动态执行，不虚构实体机器。第 4/8 页可修复错序，第 7 页可查看正常与故障分支。</p><label className="mb-4 flex items-center gap-3 text-sm">预览宽度<select aria-label="预览内容宽度" value={width} onChange={e=>setWidth(e.target.value)} className="rounded border bg-[var(--paper)] p-2">{[480,720,960,1152].map(w=><option key={w} value={w}>{w}px</option>)}</select></label><LessonSlidesProvider projectName="molecule-monster-hunter" moduleId="M90" knodeDir="knodes/M90-w0-workbench-go-no-go" title="M90 · 工作台总装与诚实报告" slides={slides} currentIndex={index} onIndexChange={setIndex}><div className="mb-4 flex flex-wrap gap-2"><nav aria-label="M90 新版页码" className="flex flex-1 flex-wrap gap-2">{slides.map((s,i)=><button key={s.slide_id} aria-label={`第 ${i+1} 页：${labels[i]}`} aria-current={i===index?'page':undefined} onClick={()=>setIndex(i)} className={`rounded-lg border px-3 py-2 text-xs ${i===index?'bg-[var(--primary)] text-[var(--primary-foreground)]':'bg-[var(--paper-2)]'}`}>{String(i+1).padStart(2,'0')} · {labels[i]}</button>)}</nav><LessonSlideshowButton/></div><LessonSlideCarousel/><p className="mt-4 text-xs text-[var(--sub)]">当前第 {index+1} 页 · {labels[index]}。新讲稿尚未配音；所有“模型值”均明确标为教学替身，不是已训练的真实模型。</p></LessonSlidesProvider></div></main>
}
