const fs=require('fs'),assert=require('assert');const {chromium}=require('/Users/xinghan/Dev/systemedu/node_modules/playwright-core');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:4000/preview/teachopencadd';const checks=[];
 for(const [mid,view] of [['M01','reading'],['M02','slides'],['M03','lab'],['M24','assignment'],['M26','lab']]){
  let r=await page.goto(`${base}/${mid}?view=${view}&mode=${view==='lab'?'game':'animation'}`,{waitUntil:'networkidle'});assert.equal(r.status(),200);await page.locator('[data-teachopencadd-preview]').waitFor();assert(!(await page.locator('body').innerText()).includes('Application error'));await page.screenshot({path:`/private/tmp/cadd-authoring/${mid}-${view}-preview.png`});checks.push(`${mid}/${view}: 200, visible`)
 }
 await page.goto(base+'/M03?view=lab&mode=game',{waitUntil:'networkidle'});
 const frame=page.frameLocator('[data-preview-lab] iframe');await frame.getByRole('button',{name:'保存本次证据'}).click();await page.getByRole('button',{name:'关联到本节作业',exact:true}).click();await page.locator('[data-teachopencadd-delivery]').waitFor();
 const section=page.locator('[data-teachopencadd-delivery]');await section.getByLabel('作品文件或共享链接',{exact:true}).fill('QA-local/M03/structure.json');await section.getByLabel('我用了什么输入，亲手做了哪一步',{exact:true}).fill('QA 验证：比较分子连接');await section.getByLabel('哪项证据支持我的结果',{exact:true}).fill('QA 验证：保留原子编号');await section.getByLabel('还不能确定什么',{exact:true}).fill('QA 验证：不推断疗效');await section.getByRole('button',{name:'保存本节作业到本机',exact:true}).click();await page.waitForTimeout(600);await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('[data-teachopencadd-delivery]').getByLabel('作品文件或共享链接',{exact:true}).inputValue(),'QA-local/M03/structure.json');assert(await page.getByText('已关联实验操作产物',{exact:true}).isVisible());checks.push('iframe artifact accepted, attached, guest assignment persisted after reload');
 await page.goto(base+'/M01?view=reading',{waitUntil:'networkidle'});const bridge=page.getByRole('group').filter({has:page.locator('summary',{hasText:'B02'})}).first();
 await page.locator('summary').filter({hasText:'B02'}).first().click();assert(!(await page.locator('body').innerText()).includes('<details>'));checks.push('foundation markdown visible without raw HTML');
 assert.deepEqual(errors,[]);fs.writeFileSync('/private/tmp/cadd-authoring/preview-check.json',JSON.stringify({checks,errors,scope:'isolated headless browser; guest records only; account server API not impersonated'},null,2));await browser.close();console.log(checks.join('\n'));
})().catch(e=>{console.error(e);process.exit(1)});
