const fs=require('fs'),assert=require('assert');const {chromium}=require('/Users/xinghan/Dev/systemedu/node_modules/playwright-core');
(async()=>{const b=await chromium.launch({headless:true});const p=await b.newPage({viewport:{width:1440,height:1100}});const base='http://127.0.0.1:4000/preview/teachopencadd/';const checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(base+'M05?view=assignment',{waitUntil:'networkidle'});
for(const kind of ['quiz','exam']){const s=p.locator(`[data-teachopencadd-assessment="${kind}"]`);const fields=s.locator('fieldset');assert.equal(await fields.count(),3);for(let i=0;i<3;i++)await fields.nth(i).locator('input').nth(i%3).check();await s.getByRole('button',{name:'保存本次尝试到本机'}).click();await p.waitForTimeout(350)}
await p.reload({waitUntil:'networkidle'});for(const kind of ['quiz','exam'])assert.equal(await p.locator(`[data-teachopencadd-assessment="${kind}"] input:checked`).count(),3);checks.push('quiz and stage exam stored separately and restored after reload');
await p.goto(base+'M02?view=slides',{waitUntil:'networkidle'});assert(await p.getByText('编号图＋连接表＋省略信息说明',{exact:true}).isVisible());await p.getByRole('button',{name:'下一张',exact:true}).click();const imgs=p.locator('[data-preview-slides] img');await imgs.first().waitFor({state:'visible'});await p.waitForFunction(()=>[...document.querySelectorAll('[data-preview-slides] img')].every(x=>x.complete&&x.naturalWidth>0));await p.screenshot({path:'/private/tmp/cadd-authoring/M02-slides-figure-preview.png'});checks.push('typed intro body visible; exact molecular figure loads through preview media route');
await p.goto(base+'M01?view=lab&mode=animation',{waitUntil:'networkidle'});assert.equal(await p.getByRole('button',{name:'关联到本节作业',exact:true}).count(),0);assert(await p.getByText('对照这张图解',{exact:false}).isVisible());checks.push('static diagram has correct instructions and no impossible evidence-save control');
await p.goto(base+'M26?view=lab&mode=game',{waitUntil:'networkidle'});const f=p.frameLocator('[data-preview-lab] iframe');await f.locator('#ctl-cut').fill('360');await f.locator('#ctl-cut').dispatchEvent('input');await f.getByRole('button',{name:'保存这次实验',exact:true}).click();await p.getByRole('button',{name:'关联到本节作业',exact:true}).click();assert(await p.getByText('已关联实验操作产物',{exact:true}).isVisible());checks.push('late game actual changed control artifact accepted by parent');
assert.deepEqual(errors,[]);fs.writeFileSync('/private/tmp/cadd-authoring/records-check.json',JSON.stringify({checks,errors,scope:'isolated guest browser; not a claim of logged-in server API test'},null,2));await b.close();console.log(checks.join('\n'))})().catch(e=>{console.error(e);process.exit(1)});
