"""RegistryPromoter: promote approved staging candidates to production objects.

Reads staging/*.json (status="approved", score>0.8) and:
1. Generates objects/{safe_key}.py with build() function
2. Updates objects/__init__.py imports and _REGISTRY dict
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_OBJECT_PY_TEMPLATE = '''"""Auto-generated object module: {object_key}.

DO NOT EDIT MANUALLY.
Generated by ObjectFactory. To regenerate, delete this file and run the factory again.
"""

from __future__ import annotations

from systemedu.agents.builtin.gameagent.object_spec import (
    AnyShape,
    EllipseShape,
    LabelAnchor,
    LineShape,
    PathShape,
    PolygonShape,
    RectShape,
    RenderSpec,
)

# ---------------------------------------------------------------------------
# Semantic layer (auto-generated from factory)
# ---------------------------------------------------------------------------

META = {meta_repr}

# ---------------------------------------------------------------------------
# Geometry layer (auto-generated from factory)
# ---------------------------------------------------------------------------

def build(view: str = "side", variant: str | None = None) -> RenderSpec:
    """Build RenderSpec for {object_key}."""
    if view != "side":
        raise ValueError(f"{object_key!r} only supports view=\'side\', got {{view!r}}")

    shapes = {shapes_repr}

    anchors = {anchors_repr}

    rendered_parts = list({{s.part_id for s in shapes if s.part_id}})

    return RenderSpec(
        object_key={object_key_repr},
        viewbox={viewbox_repr},
        shapes=shapes,
        anchors=anchors,
        rendered_parts=rendered_parts,
    )
'''


def _safe_key_to_module_name(object_key: str) -> str:
    """Convert 'submarine.basic' -> 'submarine_basic'."""
    return object_key.replace(".", "_").replace("-", "_")


def _dict_to_shape(shape_dict: dict):
    """Convert a shape dict from staging JSON to a Python shape object."""
    stype = shape_dict.get("type", "")
    if stype == "rect":
        from systemedu.agents.builtin.gameagent.object_spec import RectShape
        return RectShape(
            id=shape_dict["id"],
            part_id=shape_dict.get("part_id"),
            x=shape_dict.get("x", 0),
            y=shape_dict.get("y", 0),
            w=shape_dict.get("w", 0),
            h=shape_dict.get("h", 0),
            rx=shape_dict.get("rx", 0),
            fill=shape_dict.get("fill", "#cccccc"),
            stroke=shape_dict.get("stroke"),
            stroke_width=shape_dict.get("stroke_width", 1.0),
            opacity=shape_dict.get("opacity", 1.0),
        )
    if stype == "ellipse":
        from systemedu.agents.builtin.gameagent.object_spec import EllipseShape
        return EllipseShape(
            id=shape_dict["id"],
            part_id=shape_dict.get("part_id"),
            cx=shape_dict.get("cx", 0),
            cy=shape_dict.get("cy", 0),
            rx=shape_dict.get("rx", 10),
            ry=shape_dict.get("ry", 10),
            fill=shape_dict.get("fill", "#cccccc"),
            stroke=shape_dict.get("stroke"),
            stroke_width=shape_dict.get("stroke_width", 1.0),
            opacity=shape_dict.get("opacity", 1.0),
        )
    if stype == "polygon":
        from systemedu.agents.builtin.gameagent.object_spec import PolygonShape
        raw_pts = shape_dict.get("points", [])
        points = [tuple(p) for p in raw_pts]
        return PolygonShape(
            id=shape_dict["id"],
            part_id=shape_dict.get("part_id"),
            points=points,
            fill=shape_dict.get("fill", "#cccccc"),
            stroke=shape_dict.get("stroke"),
            stroke_width=shape_dict.get("stroke_width", 1.0),
            opacity=shape_dict.get("opacity", 1.0),
        )
    if stype == "path":
        from systemedu.agents.builtin.gameagent.object_spec import PathShape
        return PathShape(
            id=shape_dict["id"],
            part_id=shape_dict.get("part_id"),
            d=shape_dict.get("d", ""),
            fill=shape_dict.get("fill", "none"),
            stroke=shape_dict.get("stroke", "#cccccc"),
            stroke_width=shape_dict.get("stroke_width", 2.0),
            opacity=shape_dict.get("opacity", 1.0),
        )
    if stype == "line":
        from systemedu.agents.builtin.gameagent.object_spec import LineShape
        return LineShape(
            id=shape_dict["id"],
            part_id=shape_dict.get("part_id"),
            x1=shape_dict.get("x1", 0),
            y1=shape_dict.get("y1", 0),
            x2=shape_dict.get("x2", 0),
            y2=shape_dict.get("y2", 0),
            stroke=shape_dict.get("stroke", "#cccccc"),
            stroke_width=shape_dict.get("stroke_width", 2.0),
            opacity=shape_dict.get("opacity", 1.0),
        )
    raise ValueError(f"Unknown shape type: {stype!r}")


def _repr_shape(shape) -> str:
    """Produce Python constructor repr for a shape object."""
    from systemedu.agents.builtin.gameagent.object_spec import (
        EllipseShape, LineShape, PathShape, PolygonShape, RectShape,
    )
    if isinstance(shape, RectShape):
        parts = [
            f'id="{shape.id}"',
            f'part_id={shape.part_id!r}',
            f'x={shape.x}',
            f'y={shape.y}',
            f'w={shape.w}',
            f'h={shape.h}',
        ]
        if shape.rx:
            parts.append(f'rx={shape.rx}')
        parts += [f'fill="{shape.fill}"']
        if shape.stroke:
            parts += [f'stroke="{shape.stroke}"', f'stroke_width={shape.stroke_width}']
        if shape.opacity != 1.0:
            parts.append(f'opacity={shape.opacity}')
        return f'RectShape({", ".join(parts)})'
    if isinstance(shape, EllipseShape):
        parts = [
            f'id="{shape.id}"',
            f'part_id={shape.part_id!r}',
            f'cx={shape.cx}',
            f'cy={shape.cy}',
            f'rx={shape.rx}',
            f'ry={shape.ry}',
            f'fill="{shape.fill}"',
        ]
        if shape.stroke:
            parts += [f'stroke="{shape.stroke}"', f'stroke_width={shape.stroke_width}']
        if shape.opacity != 1.0:
            parts.append(f'opacity={shape.opacity}')
        return f'EllipseShape({", ".join(parts)})'
    if isinstance(shape, PolygonShape):
        pts = str(shape.points)
        parts = [
            f'id="{shape.id}"',
            f'part_id={shape.part_id!r}',
            f'points={pts}',
            f'fill="{shape.fill}"',
        ]
        if shape.stroke:
            parts += [f'stroke="{shape.stroke}"', f'stroke_width={shape.stroke_width}']
        if shape.opacity != 1.0:
            parts.append(f'opacity={shape.opacity}')
        return f'PolygonShape({", ".join(parts)})'
    if isinstance(shape, PathShape):
        parts = [
            f'id="{shape.id}"',
            f'part_id={shape.part_id!r}',
            f'd="{shape.d}"',
            f'fill="{shape.fill}"',
            f'stroke="{shape.stroke}"',
            f'stroke_width={shape.stroke_width}',
        ]
        if shape.opacity != 1.0:
            parts.append(f'opacity={shape.opacity}')
        return f'PathShape({", ".join(parts)})'
    if isinstance(shape, LineShape):
        parts = [
            f'id="{shape.id}"',
            f'part_id={shape.part_id!r}',
            f'x1={shape.x1}',
            f'y1={shape.y1}',
            f'x2={shape.x2}',
            f'y2={shape.y2}',
            f'stroke="{shape.stroke}"',
            f'stroke_width={shape.stroke_width}',
        ]
        if shape.opacity != 1.0:
            parts.append(f'opacity={shape.opacity}')
        return f'LineShape({", ".join(parts)})'
    raise TypeError(f"Unknown shape: {type(shape)}")


def _repr_shapes_list(shapes: list) -> str:
    if not shapes:
        return "[]"
    items = ",\n        ".join(_repr_shape(s) for s in shapes)
    return f"[\n        {items},\n    ]"


def _repr_anchors_list(anchors: list) -> str:
    if not anchors:
        return "[]"
    from systemedu.agents.builtin.gameagent.object_spec import LabelAnchor
    items = []
    for a in anchors:
        items.append(f'LabelAnchor(part_id="{a.part_id}", x={a.x}, y={a.y})')
    return "[\n        " + ",\n        ".join(items) + ",\n    ]"


class RegistryPromoter:
    """Promotes approved staging candidates to production objects."""

    def __init__(self, gameagent_dir: Path | None = None):
        if gameagent_dir is None:
            gameagent_dir = Path(__file__).parent.parent
        self._gameagent_dir = gameagent_dir
        self._objects_dir = gameagent_dir / "objects"
        self._staging_dir = self._objects_dir / "staging"
        self._init_path = self._objects_dir / "__init__.py"

    def promote(self, staging_path: Path) -> Path:
        """Promote a staging JSON to a production .py object.

        Args:
            staging_path: path to approved staging JSON

        Returns: path to the generated .py file
        Raises: ValueError if staging JSON is not approved or score too low
        """
        data = json.loads(staging_path.read_text(encoding="utf-8"))

        status = data.get("status", "candidate")
        score = data.get("validation_score", 0.0)

        if status != "approved":
            raise ValueError(f"Staging file status is {status!r}, must be 'approved'")
        if score < 0.8:
            raise ValueError(f"Staging file score {score} < 0.8 threshold")

        object_key = data["object_key"]
        module_name = _safe_key_to_module_name(object_key)
        target_path = self._objects_dir / f"{module_name}.py"

        py_content = self._generate_module(data)
        target_path.write_text(py_content, encoding="utf-8")
        logger.info(f"Generated object module: {target_path}")

        self._update_init(object_key, module_name)
        logger.info(f"Updated __init__.py for {object_key!r}")

        return target_path

    def _generate_module(self, data: dict) -> str:
        """Generate Python module content from staging dict."""
        from systemedu.agents.builtin.gameagent.object_spec import LabelAnchor

        object_key = data["object_key"]
        meta = data.get("meta", {})
        render_spec_dict = data.get("render_spec", {})
        viewbox = render_spec_dict.get("viewbox", "0 0 560 420")

        # Convert shape dicts to shape objects for repr
        shape_objs = []
        for sd in render_spec_dict.get("shapes", []):
            try:
                shape_objs.append(_dict_to_shape(sd))
            except Exception as e:
                logger.warning(f"Skipping shape {sd.get('id', '?')}: {e}")

        # Convert anchor dicts to LabelAnchor objects
        anchor_objs = []
        for ad in render_spec_dict.get("anchors", []):
            anchor_objs.append(
                LabelAnchor(part_id=ad["part_id"], x=ad["x"], y=ad["y"])
            )

        return _OBJECT_PY_TEMPLATE.format(
            object_key=object_key,
            object_key_repr=repr(object_key),
            viewbox_repr=repr(viewbox),
            meta_repr=repr(meta),
            shapes_repr=_repr_shapes_list(shape_objs),
            anchors_repr=_repr_anchors_list(anchor_objs),
        )

    def _update_init(self, object_key: str, module_name: str) -> None:
        """Add the new object to objects/__init__.py."""
        init_text = self._init_path.read_text(encoding="utf-8")

        # Check if already imported
        if f"from .{module_name} import" in init_text:
            logger.info(f"{module_name} already in __init__.py, skipping")
            return

        # Find import block end (last "from .xxx import" line)
        import_line = f"from .{module_name} import build as _build_{module_name}, META as _{module_name}_meta\n"

        # Insert import after last existing "from ." import line
        last_import_pos = 0
        for m in re.finditer(r"^from \.", init_text, re.MULTILINE):
            last_import_pos = m.end()
        # Find end of that line
        eol = init_text.find("\n", last_import_pos)
        if eol == -1:
            eol = len(init_text) - 1
        insert_pos = eol + 1

        init_text = init_text[:insert_pos] + import_line + init_text[insert_pos:]

        # Add to _REGISTRY dict
        registry_entry = f'    "{object_key}": {{"builder": _build_{module_name}, "meta": _{module_name}_meta}},\n'

        # Find the closing brace of _REGISTRY
        registry_close = init_text.rfind("\n}")
        if registry_close != -1:
            init_text = init_text[:registry_close] + "\n" + registry_entry + "}" + init_text[registry_close + 2:]

        self._init_path.write_text(init_text, encoding="utf-8")
