import {chromium,expect} from '@playwright/test';import fs from 'node:fs/promises';
const dir=new URL('./',import.meta.url).pathname,catalog=JSON.parse(await fs.readFile('packages/student-web/src/lib/project-lines/biomed-mission.json'));
const browser=await chromium.launch({headless:true}),report={passed:false,checks:[],errors:[]};
const seed=async context=>context.addInitScript(stations=>{for(const s of stations)localStorage.setItem(`systemedu:biomed-stage-film:v1:guest:${s}`,'seen')},catalog.stations.map(s=>s.id));
try{
 const c=await browser.newContext({viewport:{width:1440,height:1000}});await seed(c);const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));const imageRequests=[];p.on('request',r=>{if(r.url().includes('/mission/biomedicine/')&&r.resourceType()==='image')imageRequests.push(r.url())});
 for(const st of catalog.stations){const task=catalog.tasks.find(t=>t.station===st.id&&t.role!=='support');await p.goto('http://127.0.0.1:4000/mission/biomedicine/control?task='+encodeURIComponent(task.id));const arrival=p.locator('[data-room-arrival]');await expect(arrival).toHaveAttribute('data-phase','playing');await expect(arrival).toHaveAttribute('data-arrival-duration','5600');await expect.poll(()=>arrival.locator('img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);await expect(arrival.locator('img')).toHaveAttribute('src',new RegExp(st.id+'-v2-1536.webp'));
  await p.screenshot({path:dir+st.id+'-arrival.png'});await p.keyboard.press('Escape');await expect(arrival).toBeHidden();await expect(p.getByLabel('我的子任务状态',{exact:true})).toBeEnabled();await expect(p.locator('[data-room-background] img').last()).toHaveAttribute('src',new RegExp(st.id+'-v2-1536.webp'));if(st.id==='observation')await p.screenshot({path:dir+'observation-ready.png'});
 }
 expect(imageRequests.every(u=>!u.includes('-v1-'))).toBe(true);report.checks.push('All eight center stages load v2 lab scenes; neither arrival nor permanent backdrop requests any old portrait/room v1 image; 5.6s entrance, skip and forms work');await c.close();
 for(const width of [390,320]){const c=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true});await seed(c);const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:4000/mission/biomedicine/control?task=build-a-candidate-filter%3AM01');await expect(p.locator('[data-room-arrival]')).toHaveAttribute('data-phase','playing');await expect.poll(()=>p.locator('[data-room-arrival] img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);await p.screenshot({path:dir+`filter-arrival-${width}.png`});await p.keyboard.press('Escape');expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await p.screenshot({path:dir+`filter-ready-${width}.png`});await c.close()}
 report.checks.push('320px/390px arrival and normal task center fit viewport and load responsive v2 assets');
 const failure=await browser.newContext({reducedMotion:'reduce'});await seed(failure);await failure.route('**/stations/filter-v2-*.webp',r=>r.abort());const f=await failure.newPage();f.on('pageerror',e=>report.errors.push(e.message));await f.goto('http://127.0.0.1:4000/mission/biomedicine/control?task=build-a-candidate-filter%3AM01');const image=f.locator('[data-room-background] img').last();await expect(image).toHaveAttribute('src',/observation-v2-1536.webp/);await expect.poll(()=>image.evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);await f.screenshot({path:dir+'fallback-no-portrait.png'});await failure.close();report.checks.push('Failed stage image falls back to new unoccupied observation lab, not mentor image');
 const regression=await browser.newContext({reducedMotion:'reduce'}),r=await regression.newPage();r.on('pageerror',e=>report.errors.push(e.message));await r.goto('http://127.0.0.1:4000/mission/space/control?task=pick-an-observation-site%3AM01');await expect(r.locator('[data-room-background] img').last()).toHaveAttribute('src',/space\/stations\/mission-design-v1-1536.webp/);await expect(r.getByLabel('我的子任务状态',{exact:true})).toBeEnabled();await regression.close();report.checks.push('Space room skin still uses its original v1 assets');
 expect(report.errors).toEqual([]);report.passed=true;
}catch(e){report.failure=String(e);throw e}finally{await fs.writeFile(dir+'verification.json',JSON.stringify(report,null,2)+'\n');await browser.close()}
