const ts=require('../../packages/student-web/node_modules/typescript'), fs=require('fs'), cp=require('child_process'), path=require('path');
const root=path.resolve(__dirname,'../..'), conf=root+'/packages/student-web/tsconfig.json';
const base=process.argv[2]||'1c62963c';
const c=ts.readConfigFile(conf,ts.sys.readFile),parsed=ts.parseJsonConfigFileContent(c.config,ts.sys,path.dirname(conf));
const changed=cp.execFileSync('git',['diff',base,'--diff-filter=M','--name-only','--','packages/student-web/src'],{cwd:root,encoding:'utf8'}).trim().split('\n');
const added=[...cp.execFileSync('git',['diff',base,'--diff-filter=A','--name-only','--','packages/student-web/src'],{cwd:root,encoding:'utf8'}).trim().split('\n'),...cp.execFileSync('git',['ls-files','--others','--exclude-standard','--','packages/student-web/src'],{cwd:root,encoding:'utf8'}).trim().split('\n')].filter(Boolean).map(s=>root+'/'+s);
const snapshot=new Map(changed.filter(p=>/\.(tsx?|json)$/.test(p)).map(p=>[root+'/'+p,cp.execFileSync('git',['show',base+':'+p],{cwd:root,encoding:'utf8'})]));
function check(baseline){const host=ts.createCompilerHost(parsed.options),read=host.readFile;host.readFile=f=>baseline&&f.includes("/.next/")?"":baseline&&added.includes(f)?undefined:baseline&&snapshot.has(f)?snapshot.get(f):read(f);host.getSourceFile=(f,v)=>{const s=host.readFile(f);return s===undefined?undefined:ts.createSourceFile(f,s,v)};const program=ts.createProgram(parsed.fileNames.filter(f=>!baseline||!added.includes(f)),{...parsed.options,incremental:false},host);return ts.getPreEmitDiagnostics(program).map(d=>({file:d.file?.fileName.replace(root+'/',''),code:d.code,message:ts.flattenDiagnosticMessageText(d.messageText,'\n')}))}
const baseline=check(true),current=check(false),key=o=>JSON.stringify(o),addedErrors=current.filter(d=>!baseline.some(e=>key(e)===key(d)));
const result={passed:!addedErrors.length,baselineRef:base,baseline,current,addedErrors};fs.writeFileSync(root+'/artifacts/biomed-research-rooms-20261010/typecheck-baseline.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({baseline:baseline.length,current:current.length,addedErrors:addedErrors.length}));process.exitCode=addedErrors.length?1:0;
