import {chromium,expect} from '@playwright/test';import fs from 'node:fs/promises';
const dir=new URL('./space-regression/',import.meta.url).pathname;await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']}),report={passed:false,checks:[],errors:[]};
try{const c=await browser.newContext(),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));
// The October 10 curriculum maps films to stations, not the former level tabs.
for(const [station,n] of [['first-contact',1],['mission-design',2],['build',3],['expedition',4]]){
 await p.goto('http://127.0.0.1:4000/mission/space?station='+station);const film=p.locator(`[data-stage-film="${n}"]`);await expect(film).toBeVisible();await expect(film).toContainText('林岚');await expect(film.locator('video')).toHaveAttribute('poster','/mission/rover/engineer-1920.webp');await expect.poll(()=>film.locator('video').evaluate(v=>!v.paused&&v.currentTime>0),{timeout:15000}).toBe(true);await film.locator('video').evaluate(v=>v.currentTime=v.duration-.2);await expect(film).toHaveCount(0,{timeout:10000});
}
await p.reload();await expect(p.locator('[data-stage-replay]')).toBeVisible();await expect(p.locator('dialog')).toHaveCount(0);await p.locator('[data-stage-replay]').click();await expect(p.locator('[data-stage-film="4"]')).toBeVisible();await p.keyboard.press('Escape');await expect(p.locator('dialog')).toHaveCount(0);await c.close();
const m=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),q=await m.newPage();q.on('pageerror',e=>report.errors.push(e.message));await q.goto('http://127.0.0.1:4000/mission/space/control?task=pick-an-observation-site%3AM01');await expect(q.locator('[data-room-arrival]')).toBeHidden();await expect(q.getByLabel('我的子任务状态',{exact:true})).toBeEnabled();await q.getByLabel('我的证据摘要').fill('本地回归：已有任务表单保持可用');await q.reload();await expect(q.getByLabel('我的证据摘要')).toHaveValue('本地回归：已有任务表单保持可用');expect(await q.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await q.screenshot({path:dir+'space-center-mobile.png'});await m.close();
report.checks.push('Current space station mapping still plays four assigned films with Lin Lan and original poster; end/replay/Escape/dedup work','Space center reduced-motion arrival, form persistence and mobile layout remain intact');expect(report.errors).toEqual([]);report.passed=true;
}catch(e){report.failure=String(e);throw e}finally{await fs.writeFile(dir+'verification.json',JSON.stringify(report,null,2)+'\n');await browser.close()}
