const ts=require('../../packages/student-web/node_modules/typescript'),fs=require('fs'),assert=require('node:assert/strict'),path=require('path');
const root=path.resolve(__dirname,'../..'),dir=root+'/packages/student-web/src/lib/project-lines/';
const source=fs.readFileSync(dir+'mission-operations-core.ts','utf8'),compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const mod={exports:{}};new Function('module','exports',compiled)(mod,mod.exports);const core=mod.exports;
const bio=JSON.parse(fs.readFileSync(dir+'biomed-mission.json')),space=JSON.parse(fs.readFileSync(dir+'space-mission-tasks.json'));
const steps=bio.stations.flatMap(s=>s.steps),scope={library_slug:'biomedicine',module_id:'JOURNEY',activity_id:'mission-operations',kind:'classroom',content_version:'1.0'};
const engine=core.createMissionOperations(bio.tasks,scope,'biomed-mission-operations/1',steps),old=core.createMissionOperations(space,{...scope,library_slug:'space-exploration'},'space-mission-operations/1',space.filter(t=>t.role==='lesson').map(t=>t.id));
let ops=engine.operationsFrom(engine.INITIAL_OPERATIONS);assert(ops);assert.equal(old.operationsFrom(engine.INITIAL_OPERATIONS),null);assert.equal(engine.operationsFrom(old.INITIAL_OPERATIONS),null);assert(old.operationsFrom(old.INITIAL_OPERATIONS));
const task=bio.tasks.find(t=>t.id===steps[0]),at='2026-10-10T00:00:00Z';ops=engine.changeTask(ops,task.id,{status:'done'},at);assert.equal(core.taskState(ops,task.id).status,'review');ops=engine.changeTask(ops,task.id,{checks:task.checks.map((_,i)=>`check-${i}`),evidence:'Actual evidence',status:'done'},at);assert.equal(engine.mainProgress(ops).done,1);ops=engine.changeTask(ops,task.id,{evidence:''},at);assert.equal(engine.mainProgress(ops).done,0);assert.throws(()=>engine.changeTask(ops,task.id,{status:'blocked'},at));
const seg={id:'work-1',task:task.id,startedAt:at,endedAt:at,seconds:10,reason:'checkpoint'};ops=engine.recordWork(ops,seg,'2026-10-10');ops=engine.recordWork(ops,seg,'2026-10-10');assert.equal(ops.time.totals[task.id],10);ops=engine.recordWork(ops,{...seg,seconds:19},'2026-10-10');assert.equal(ops.time.totals[task.id],19);assert.equal(ops.time.days['2026-10-10'],19);assert.equal(engine.operationsFrom({answers:[],artifact:{...ops,schema:'wrong'}}),null);assert.throws(()=>engine.recordWork(ops,{...seg,task:'unknown'},'2026-10-10'));
assert.equal(new Set(bio.tasks.map(t=>t.id)).size,114);assert.equal(steps.length,65);assert.equal(new Set(steps).size,65);assert.equal(bio.modules.filter(n=>n.mode==='support').length,47);
for(const n of bio.modules){assert(bio.tasks.some(t=>t.id===n.ref));assert(bio.stations.some(s=>s.id===n.station));if(n.anchor)assert(steps.includes(n.anchor));const tree=JSON.parse(fs.readFileSync(n.kind==='guided'?root+`/packages/student-web/public/project-lines/biomedicine/${n.project}/course/tree/knowledge_tree.json`:root+`/../systemeduidea/projects_data/${n.project}/tree/knowledge_tree.json`));assert(tree.modules.some(m=>m.module_id===n.module&&m.title===n.title));}
for(const station of bio.stations){for(const id of station.dependsOn)assert(bio.stations.some(s=>s.id===id));for(const size of [640,960,1536])assert(fs.existsSync(root+`/packages/student-web/public/mission/biomedicine/stations/${station.id}-v1-${size}.webp`));}
const result={passed:true,checks:['114 unique task IDs resolve to existing lesson sources; all 65 main nodes ordered, 47 support anchors valid','Independent schemas reject cross-line records; old space schema remains readable','Self-check requires all checks and evidence; clearing evidence demotes done; blockers require explanation','Cumulative timer checkpoints are idempotent and unknown tasks rejected','Eight stage scenes have all responsive variants']};fs.writeFileSync(__dirname+'/core-verification.json',JSON.stringify(result,null,2)+'\n');console.log(result);
