import {chromium,expect} from '@playwright/test';import fs from 'node:fs/promises';
const dir=new URL('./',import.meta.url).pathname,browser=await chromium.launch({headless:true}),report={passed:false,checks:[],errors:[]};
const catalog=JSON.parse(await fs.readFile('packages/student-web/src/lib/project-lines/biomed-mission.json'));
try{const c=await browser.newContext({viewport:{width:1440,height:1000}}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));
for(const station of catalog.stations){const task=catalog.tasks.find(t=>t.station===station.id&&t.role!=='support');await p.goto('http://127.0.0.1:4000/mission/biomedicine/control?task='+encodeURIComponent(task.id));const arrival=p.locator('[data-room-arrival]');await expect(arrival).toHaveAttribute('data-phase','playing');await expect(arrival).toHaveAttribute('data-arrival-duration','5600');await expect(arrival.locator('h2')).toContainText(station.place);await expect(arrival.locator('img')).toHaveAttribute('src',new RegExp('/biomedicine/stations/'+station.id));await expect.poll(()=>arrival.locator('img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);if(station.id==='protocol'){await p.screenshot({path:dir+'arrival-protocol.png'});await expect(arrival).toBeHidden({timeout:8500});await p.screenshot({path:dir+'protocol-ready.png'});}else await p.keyboard.press('Escape');}
await p.goto('http://127.0.0.1:4000/library?view=lines');await expect(p.locator('a[href="/mission/biomedicine"]').first()).toBeAttached();
await p.goto('http://127.0.0.1:4000/explore/biomedicine/turn-a-molecule?mission=biomedicine');await expect(p.locator('[data-biomed-briefing]')).toBeVisible();await p.getByRole('button',{name:'关闭简报',exact:true}).click();await expect(p.getByRole('link',{name:'继续任务：做一个候选筛选器'})).toHaveAttribute('href',/M01&mission=biomedicine/);
report.checks.push('All eight distinct stage backgrounds decode; arrival lasts 5.6 seconds, Escape skips, research protocol scene reveals its task panels','Library line card enters mission homepage; micro experience continues to guided course with mission context');expect(report.errors).toEqual([]);report.passed=true;
}catch(e){report.failure=String(e);throw e}finally{await fs.writeFile(dir+'scene-verification.json',JSON.stringify(report,null,2)+'\n');await browser.close()}
