"use client"
import Link from "next/link"
import { ArrowLeft, ArrowRight, Map } from "lucide-react"
import { BIO_MODULES, BIO_STEPS, BIO_ENGINE, bioContext, bioLessonHref, bioMapHref, bioCenterHref, bioNode } from "@/lib/project-lines/biomed-mission"
import { useMissionOperations } from "@/lib/hooks/use-mission-operations"
import { useLearningIdentity } from "@/lib/hooks/use-learning-record"
import { LearningRecordStatus } from "@/components/learning/learning-record-status"
import { WorkClock } from "./mission-work-strip"
import { BiomedBriefing } from "./biomed-briefing"
import s from "./space-mission-curriculum.module.css"
import c from "./space-mission-control.module.css"
type Context=NonNullable<ReturnType<typeof bioContext>>
export function BiomedWorkStrip({taskId}:{taskId:string}){const {owner}=useLearningIdentity();return <Strip key={owner+taskId} taskId={taskId}/>}
function Strip({taskId}:{taskId:string}){const model=useMissionOperations(BIO_ENGINE);return <section className={c.workStrip}><Link href={bioCenterHref(taskId)}>任务中心 · {BIO_ENGINE.taskById(taskId)?.code} ↗</Link><WorkClock model={model} taskId={taskId}/><details><summary>保存与恢复</summary><LearningRecordStatus record={model.record}/>{model.message&&<p role="alert">{model.message}</p>}</details></section>}
export function BiomedLessonBrief({context}:{context:Context}){const {station,node}=context;return <section className={s.lessonBrief} data-biomed-context={station.id}><nav><Link href={bioMapHref(station.id)}><Map size={15}/>研究地图 / {station.code} {station.place}</Link><Link href={bioCenterHref(node.ref)}>本站任务中心</Link><Link href={bioCenterHref(BIO_STEPS.at(-1)!,"dossier")}>我的研究档案</Link></nav><p className={s.kicker}>候选分子研究 · {node.mode==="support"?"按需补给":"当前任务"}</p><h2>{station.message}</h2><div className={s.handoffPair}><p><small>带着什么来</small>{station.input}</p><p><small>这一站带走什么</small>{station.handoff}</p></div><BiomedWorkStrip taskId={node.ref}/><details className={s.mobileOutline}><summary>查看本站任务步骤</summary><BiomedLessonOutline context={context}/></details><BiomedBriefing stationId={station.id}/><details className={s.sourceDetails}><summary>来源与已有记录</summary><p>{node.project} / {node.module}。继续使用原课堂的正文、视频、实验、作业及资料下载；记录标识不变。</p>{node.mode==="support"&&<p>这是基础补给。原课实验可能使用不同数据，不能自动当作当前研究的验证结果。</p>}</details></section>}
export function BiomedLessonOutline({context}:{context:Context}){return <nav className={s.outline} aria-label="本站研究步骤" data-biomed-outline><p>{context.station.code} / {context.station.place}</p>{context.station.steps.map((id,i)=><Link key={id} href={bioLessonHref(id)} aria-current={id===context.primary?"step":undefined}><span>{String(i+1).padStart(2,"0")}</span><div><strong>{bioNode(id)!.title}</strong><small>{bioNode(id)!.module} · {bioNode(id)!.kind==="full"?"真实研究":"方法练习"}</small></div></Link>)}<Link href={bioMapHref(context.station.id)}>返回研究地图</Link></nav>}
export function BiomedLessonFooter({context}:{context:Context}){const support=BIO_MODULES.filter(n=>n.anchor===context.node.ref);return <>{support.length>0&&<details className={s.support}><summary>需要时补一小步 · {support.length} 个基础节点</summary>{support.map(n=><Link key={n.ref} href={bioLessonHref(n.ref)}>{n.title}<ArrowRight size={14}/></Link>)}</details>}<nav className={s.lessonFooter} data-biomed-footer><Link href={context.previous?bioLessonHref(context.previous):bioMapHref("observation")}><ArrowLeft size={16}/>上一步</Link>{context.node.mode==="support"?<Link href={bioLessonHref(context.primary)}>回到当前研究任务<ArrowRight size={16}/></Link>:context.next?<Link href={bioLessonHref(context.next)}>下一步：{bioNode(context.next)!.title}<ArrowRight size={16}/></Link>:<Link href={bioCenterHref(context.node.ref,"dossier")}>整理研究交付<ArrowRight size={16}/></Link>}</nav></>}
