"use client"
import Link from "next/link"
import { ArrowLeft, ArrowRight, Map } from "lucide-react"
import { ENERGY_MODULES, ENERGY_STEPS, ENERGY_ENGINE, energyContext, energyLessonHref, energyMapHref, energyCenterHref, energyNode } from "@/lib/project-lines/energy-mission"
import { useMissionOperations } from "@/lib/hooks/use-mission-operations"
import { useLearningIdentity } from "@/lib/hooks/use-learning-record"
import { LearningRecordStatus } from "@/components/learning/learning-record-status"
import { WorkClock } from "./mission-work-strip"
import { EnergyBriefing } from "./energy-briefing"
import s from "./space-mission-curriculum.module.css"
import c from "./space-mission-control.module.css"
type Context=NonNullable<ReturnType<typeof energyContext>>
export function EnergyWorkStrip({taskId}:{taskId:string}){const {owner}=useLearningIdentity();return <Strip key={owner+taskId} taskId={taskId}/>}
function Strip({taskId}:{taskId:string}){const model=useMissionOperations(ENERGY_ENGINE);return <section className={c.workStrip}><Link href={energyCenterHref(taskId)}>任务中心 · {ENERGY_ENGINE.taskById(taskId)?.code} ↗</Link><WorkClock model={model} taskId={taskId}/><details><summary>保存与恢复</summary><LearningRecordStatus record={model.record}/>{model.message&&<p role="alert">{model.message}</p>}</details></section>}
export function EnergyLessonBrief({context}:{context:Context}){const {station,node}=context;return <section className={s.lessonBrief} data-energy-context={station.id}><nav><Link href={energyMapHref(station.id)}><Map size={15}/>任务地图 / {station.code} {station.place}</Link><Link href={energyCenterHref(node.ref)}>本站任务中心</Link><Link href={energyCenterHref(ENERGY_STEPS.at(-1)!,"dossier")}>我的工程档案</Link></nav><p className={s.kicker}>能源工程任务 · {node.mode==="support"?"按需补给":"当前任务"}</p><h2>{station.message}</h2><div className={s.handoffPair}><p><small>带着什么来</small>{station.input}</p><p><small>这一站带走什么</small>{station.handoff}</p></div><EnergyWorkStrip taskId={node.ref}/><details className={s.mobileOutline}><summary>查看本站任务步骤</summary><EnergyLessonOutline context={context}/></details><EnergyBriefing stationId={station.id}/><details className={s.sourceDetails}><summary>来源与已有记录</summary><p>{node.project} / {node.module}。继续使用原课堂的正文、视频、实验、作业及资料下载；记录标识不变。</p>{node.mode==="support"&&<p>这是机构与测量补给。旧装置的参数不能自动代替新站校准，原课堂记录仍保留。</p>}</details></section>}
export function EnergyLessonOutline({context}:{context:Context}){return <nav className={s.outline} aria-label="本站研究步骤" data-energy-outline><p>{context.station.code} / {context.station.place}</p>{context.station.steps.map((id,i)=><Link key={id} href={energyLessonHref(id)} aria-current={id===context.primary?"step":undefined}><span>{String(i+1).padStart(2,"0")}</span><div><strong>{energyNode(id)!.title}</strong><small>{energyNode(id)!.module} · {energyNode(id)!.kind==="full"?"真实预报":"方法练习"}</small></div></Link>)}<Link href={energyMapHref(context.station.id)}>返回任务地图</Link></nav>}
export function EnergyLessonFooter({context}:{context:Context}){const support=ENERGY_MODULES.filter(n=>n.anchor===context.node.ref);return <>{support.length>0&&<details className={s.support}><summary>需要时补一小步 · {support.length} 个基础节点</summary>{support.map(n=><Link key={n.ref} href={energyLessonHref(n.ref)}>{n.title}<ArrowRight size={14}/></Link>)}</details>}<nav className={s.lessonFooter} data-energy-footer><Link href={context.previous?energyLessonHref(context.previous):energyMapHref("discovery")}><ArrowLeft size={16}/>上一步</Link>{context.node.mode==="support"?<Link href={energyLessonHref(context.primary)}>回到当前工程任务<ArrowRight size={16}/></Link>:context.next?<Link href={energyLessonHref(context.next)}>下一步：{energyNode(context.next)!.title}<ArrowRight size={16}/></Link>:<Link href={energyCenterHref(context.node.ref,"dossier")}>整理工程交付<ArrowRight size={16}/></Link>}</nav></>}
